force-app/main/default/src/objects/PJN_Log__c/PJN_Log__c.object-meta.xml
<CustomObject>
    <description>Logs errors and debug information for Patient Service Accelerator</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Log__c/fields/PJN_Exception_JSON__c.field-meta.xml
<CustomField>
    <fullName>PJN_Exception_JSON__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exception JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log__c/fields/PJN_Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Exception_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log__c/fields/PJN_Message__c.field-meta.xml
<CustomField>
    <fullName>PJN_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log__c/fields/PJN_SObject_JSON__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_JSON__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SObject JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log__c/fields/PJN_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log__c/fields/PJN_Source__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source__c</fullName>
    <description>The source of the error. Typically a class or feature name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Exception_JSON__c.field-meta.xml
<CustomField>
    <fullName>PJN_Exception_JSON__c</fullName>
    <label>Exception JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Message__c.field-meta.xml
<CustomField>
    <fullName>PJN_Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_SObject_JSON__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_JSON__c</fullName>
    <label>SObject JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Type__c</fullName>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Source__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source__c</fullName>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_LogEventSubscriber.cls
/**
 * @author      Mavens
 * @group       Log
 * @description handle log event and create PJN_Log__c records
 */
public without sharing class PJN_LogEventSubscriber implements PJN_TriggerDispatcher.HandlerInterface {
    /**
     * handle after insert trigger context
     */
    public void handle() {
        List<PJN_Log__c> logsToInsert = new List<PJN_Log__c>();
        for(PJN_Log_Event__e thisLogEvent : (List<PJN_Log_Event__e>) trigger.new) {
            logsToInsert.add(
                new PJN_Log__c(
                    PJN_Source__c = thisLogEvent.PJN_Source__c,
                    PJN_Message__c = thisLogEvent.PJN_Message__c,
                    PJN_Exception_Type__c = thisLogEvent.PJN_Exception_Type__c,
                    PJN_Exception_JSON__c = thisLogEvent.PJN_Exception_JSON__c,
                    PJN_SObject_Type__c = thisLogEvent.PJN_SObject_Type__c,
                    PJN_SObject_JSON__c = thisLogEvent.PJN_SObject_JSON__c
                )
            );
        }
        insert logsToInsert;
    }
}