force-app/main/default/src/objects/Relay_Network__mdt/Relay_Network__mdt.object-meta.xml
<CustomObject>
    <label>Relay Network Setting</label>
    <pluralLabel>Relay Network Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all Account trigger logic from running</description>
    <inlineHelpText>If checked (disabled), all Relay Account trigger logic will be disabled.</inlineHelpText>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableEventConsentTrigger__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableEventConsentTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Relay Event Trigger from updating Accounts when a Consent change event is received</description>
    <inlineHelpText>If checked (disabled), this trigger will not update TCPA consent data on Account or Contact objects.</inlineHelpText>
    <label>Disable TCPA Consent Processing Logic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableTaskEventing__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableTaskEventing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable events from being emitted when a call task is created.</description>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsAccountCCIDFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsAccountCCIDFieldName__c</fullName>
    <description>The filed name in the Account object that contains the Relay CCID</description>
    <inlineHelpText>The filed name in the Account object that contains the Relay CCID</inlineHelpText>
    <label>Account CCID Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsContactCCIDFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsContactCCIDFieldName__c</fullName>
    <description>The field name in the Contact object that contains the Relay CCID.</description>
    <inlineHelpText>The field name in the Contact object that contains the Relay CCID. If the Conact object does not need to contain the Relay CCID, then this can be left blank</inlineHelpText>
    <label>Contact CCID Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsDisableAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsDisableAccountLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the lookup of the Account reference object</description>
    <label>Disable Account Ref Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsDisableContactLookup__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsDisableContactLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the lookup of the Contact reference object</description>
    <label>Disable Contact Ref Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayMobilePhoneFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayMobilePhoneFieldName__c</fullName>
    <description>The Account field name that contains the mobile phone number</description>
    <inlineHelpText>The filed name in the Account object that contains the mobile number. If left blank, it defaults to MobilePhone</inlineHelpText>
    <label>Account Mobile Phone Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/RelayEvents__c.object-meta.xml
<CustomObject>
    <label>Relay Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relay Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/RelayEvents__c/fields/ClientMessageTag__c.field-meta.xml
<CustomField>
    <fullName>ClientMessageTag__c</fullName>
    <description>An optional, Client, value that was initially provided during a Messaging API call.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Message Tag</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventSubType__c.field-meta.xml
<CustomField>
    <fullName>EventSubType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventTimestamp__c.field-meta.xml
<CustomField>
    <fullName>EventTimestamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/TriggerID__c.field-meta.xml
<CustomField>
    <fullName>TriggerID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trigger ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/RelayCalloutTest.cls
@isTest
public class RelayCalloutTest {
    @isTest static void testGetJourneyList() {
        setupMetadata();
        Test.setMock(HttpCalloutMock.class, new RelayHttpMock('getJourney', 'GET', 200, '{}'));

        Object res = Relay.getJourneyList(0,3, 'sfdc');
        System.assert(res != null);
    }

    @isTest static void testTriggerJourneyList1() {
        setupMetadata();
        Test.setMock(HttpCalloutMock.class, new RelayHttpMock('trigggerJourney', 'POST', 200, '{}'));

        Object res = Relay.triggerJourney('welcome', '1001' , '{}', 'Welcome', 'Contact');
        System.assert(res != null);
    }

    @isTest static void testTriggerJourneyList2() {
        setupMetadata();
        Test.setMock(HttpCalloutMock.class, new RelayHttpMock('triggerJourney', 'POST', 200, '{}'));

        Object res = Relay.triggerJourney('welcome', '1001', null, 'Welcome', 'Contact' );
        System.assert(res != null);
    }

    @isTest(SeeAllData=true) static void testGetRelaySettings() {
        setupMetadata();
        Object json = Relay.getRelaySettings();

        System.assert(json != null);
    }

    @isTest static void testLastTriggerDate() {
        setupMetadata();

        Datetime dt = Datetime.now();

        RelayEvents__c re = new RelayEvents__c(
                Name='Experience Sent',
                RelayCCID__c = '1001',
                EventType__c = 'journey_trigger',
                EventTimestamp__c = dt,
                ClientMessageTag__c = '5003j00001bMJuMAAW',
                TriggerID__c = 'Welcome',
                TriggerNickname__c = 'Welcome Test'
        );
        insert re;
        re = new RelayEvents__c(
                Name='Opened SMS',
                RelayCCID__c = '1001',
                EventType__c = 'notification',
                EventSubType__c = 'auth_link_used',
                EventTimestamp__c = dt,
                ClientMessageTag__c = '5003j00001bMJuMAAW',
                TriggerID__c = 'Welcome',
                TriggerNickname__c = 'Welcome Test'
        );
        insert re;

        String jsonstr = Relay.getLastTriggerDate('1001','Welcome');
        Relay.EngagementDates edates = (Relay.EngagementDates)JSON.deserialize(jsonstr, Relay.EngagementDates.class);

        Long tm = dt.GetTime();
        System.debug(tm);
        System.debug(edates.sentDtm);
        System.assert(edates.sentDtm != 0);
        // System.assert(edates.openedDtm != 0);
    }

    static void setupMetadata() {
        Relay.testMetaData = new Relay_Network__mdt(
            RelayDisableEventConsentTrigger__c=false,
            RelayEventsAccountCCIDFieldName__c=null,
            RelayEventsContactCCIDFieldName__c=null,
            RelayEventsDisableContactLookup__c=false, 
            RelayEventsDisableAccountLookup__c=false, 
            RelayMobilePhoneFieldName__c=null, 
            RelayDisableAccountTrigger__c=false, 
            RelayDisableTaskEventing__c=false);
    }
    // @isTest static void testProcessHttpResponse() {
    //     List<String> labels;

    //     Relay.processHttpResponse(labels, state)
    // }
}