force-app/main/default/src/objects/Relay_Network__mdt/Relay_Network__mdt.object-meta.xml
<CustomObject>
    <label>Relay Network Setting</label>
    <pluralLabel>Relay Network Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Relay_Network__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>The API key used to access the Relay APIs</description>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayApiUrl__c.field-meta.xml
<CustomField>
    <fullName>RelayApiUrl__c</fullName>
    <description>The Relay REST API endpoint URL. Relay has different endpoints for our Staging and Production environments</description>
    <label>Relay API URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all Account trigger logic from running</description>
    <inlineHelpText>If checked (disabled), all Relay Account trigger logic will be disabled.</inlineHelpText>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableEventConsentTrigger__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableEventConsentTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Relay Event Trigger from updating Accounts when a Consent change event is received</description>
    <inlineHelpText>If checked (disabled), this trigger will not update TCPA consent data on Account or Contact objects.</inlineHelpText>
    <label>Disable TCPA Consent Processing Logic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableTaskEventing__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableTaskEventing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable events from being emitted when a call task is created.</description>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsAccountCCIDFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsAccountCCIDFieldName__c</fullName>
    <description>The filed name in the Account object that contains the Relay CCID</description>
    <inlineHelpText>The filed name in the Account object that contains the Relay CCID</inlineHelpText>
    <label>Account CCID Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsContactCCIDFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsContactCCIDFieldName__c</fullName>
    <description>The field name in the Contact object that contains the Relay CCID.</description>
    <inlineHelpText>The field name in the Contact object that contains the Relay CCID. If the Conact object does not need to contain the Relay CCID, then this can be left blank</inlineHelpText>
    <label>Contact CCID Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsDisableAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsDisableAccountLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the lookup of the Account reference object</description>
    <label>Disable Account Ref Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsDisableContactLookup__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsDisableContactLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the lookup of the Contact reference object</description>
    <label>Disable Contact Ref Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayMobilePhoneFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayMobilePhoneFieldName__c</fullName>
    <description>The Account field name that contains the mobile phone number</description>
    <inlineHelpText>The filed name in the Account object that contains the mobile number. If left blank, it defaults to MobilePhone</inlineHelpText>
    <label>Account Mobile Phone Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/RelayEvents__c.object-meta.xml
<CustomObject>
    <label>Relay Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relay Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/RelayEvents__c/fields/ActionValue__c.field-meta.xml
<CustomField>
    <fullName>ActionValue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ActionValue</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventSubType__c.field-meta.xml
<CustomField>
    <fullName>EventSubType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventTimestamp__c.field-meta.xml
<CustomField>
    <fullName>EventTimestamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/TriggerID__c.field-meta.xml
<CustomField>
    <fullName>TriggerID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trigger ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/TestRelayExperienceStatus.cls
@isTest
public class TestRelayExperienceStatus {    

    static void setupMetaData() {
        Relay.testMetaData = new Relay_Network__mdt(
            Client_ID__c='sf-unit=test', 
            API_Key__c='111-222-333', 
            RelayApiUrl__c='https://sf-unit-test.relayit.com',
            RelayDisableEventConsentTrigger__c=false,
            RelayEventsAccountCCIDFieldName__c=null,
            RelayEventsContactCCIDFieldName__c=null,
            RelayEventsDisableContactLookup__c=false, 
            RelayEventsDisableAccountLookup__c=false, 
            RelayMobilePhoneFieldName__c='Phone', 
            RelayDisableAccountTrigger__c=false, 
            RelayDisableTaskEventing__c=false);
    }

    static RelayExperienceStatus getTriggerStats(List<RelayExperienceStatus> stats, String triggerId) {
        for (RelayExperienceStatus stat: stats) {
            if (stat.triggerId == triggerId)
                return stat;
        }
        return null;
    }

    static testmethod void testHappyPath() {
        setupMetaData();

        String ccid = '1001';
        String triggerId1 = 'AAA-BBB-CCC';
        // Add some mock event records
        List<RelayEvents__c> events = new List<RelayEvents__c>();
        events.add(new RelayEvents__c(name='Sent Experience', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='journey_trigger', EventSubType__c='', ActionValue__c='',
                EventTimestamp__c=Datetime.now()
            ));
        events.add(new RelayEvents__c(name='Message: Added to wire', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='message', EventSubType__c='delivered', ActionValue__c='',
                EventTimestamp__c=Datetime.now().addSeconds(10)
            ));
        events.add(new RelayEvents__c(name='SMS: Delivered', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='notification', EventSubType__c='delivered', ActionValue__c='',
                EventTimestamp__c=Datetime.now().addSeconds(15)
            ));
        events.add(new RelayEvents__c(name='Message: Opened', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='notification', EventSubType__c='auth_link_used', ActionValue__c='',
                EventTimestamp__c=Datetime.now().addSeconds(20)
            ));
        insert events;
        
        List<String> triggerIds = new List<String>();
        triggerIds.add(triggerId1);
        triggerIds.add('DDD-EEE-FFFF');

        List<RelayExperienceStatus> res = RelayExperienceStatus.getExperienceStatus(ccid, triggerIds);
        
        System.assert(res != null);                

        RelayExperienceStatus stats1 = getTriggerStats(res, triggerId1);
        System.assert(stats1 != null);
        System.assert(stats1.requestSentDtm > 0, 'Request Sent DTM not set');
        System.assert(stats1.postedDtm > 0, 'Posted DTM not set');
        System.assert(stats1.deliveredDtm > 0, 'Notification delivered DTM not set');
        System.assert(stats1.openedDtm > 0, 'Opened DTM should be set');
    }

    static testmethod void testDeliveredBeforePosted() {
        setupMetaData();

        String ccid = '1001';
        String triggerId1 = 'AAA-BBB-CCC';
        // Add some mock event records
        List<RelayEvents__c> events = new List<RelayEvents__c>();
        events.add(new RelayEvents__c(name='SMS: Delivered', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='notification', EventSubType__c='delivered', ActionValue__c='',
                EventTimestamp__c=Datetime.now()
            ));
        events.add(new RelayEvents__c(name='Sent Experience', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='journey_trigger', EventSubType__c='', ActionValue__c='',
                EventTimestamp__c=Datetime.now().addSeconds(10)
            ));
        insert events;
        
        List<String> triggerIds = new List<String>();
        triggerIds.add(triggerId1);
        triggerIds.add('DDD-EEE-FFFF');

        List<RelayExperienceStatus> res = RelayExperienceStatus.getExperienceStatus(ccid, triggerIds);
        
        System.assert(res != null);                

        RelayExperienceStatus stats1 = getTriggerStats(res, triggerId1);
        System.assert(stats1 != null);
        System.assert(stats1.requestSentDtm > 0, 'Request Sent DTM not set');        
        System.assert(stats1.deliveredDtm == 0, 'Notification delivered DTM should be 0');
    }

    static testmethod void testNotPosted() {
        setupMetaData();

        String ccid = '1001';
        String triggerId1 = 'AAA-BBB-CCC';
        String reason = 'Message Suppression';
        // Add some mock event records
        List<RelayEvents__c> events = new List<RelayEvents__c>();
        events.add(new RelayEvents__c(name='Message: Undelivered', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='message', EventSubType__c='undelivered', ActionValue__c=reason,
                EventTimestamp__c=Datetime.now().addSeconds(10)
            ));
        insert events;
        
        List<String> triggerIds = new List<String>();
        triggerIds.add(triggerId1);

        List<RelayExperienceStatus> res = RelayExperienceStatus.getExperienceStatus(ccid, triggerIds);
        
        System.assert(res != null);                

        RelayExperienceStatus stats1 = getTriggerStats(res, triggerId1);
        System.assert(stats1 != null);
        System.assertEquals(stats1.postedDtm, 0, 'Posted DTM should NOT have been set');
        System.assert(stats1.notPostedDtm > 0, 'Not Posted DTM should have been set');
        System.assertEquals(stats1.notPostedReason, reason, 'Not Posted reason should have been set');
        System.assertEquals(stats1.deliveredDtm, 0, 'Notification delivered DTM should be 0');
    }

    static testmethod void testNotDelivered() {
        setupMetaData();
        
        String ccid = '1001';
        String triggerId1 = 'AAA-BBB-CCC';
        String reason = 'Carrier error';
        // Add some mock event records
        List<RelayEvents__c> events = new List<RelayEvents__c>();
        events.add(new RelayEvents__c(name='Sent Experience', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='journey_trigger', EventSubType__c='', ActionValue__c='',
                EventTimestamp__c=Datetime.now()
            ));
        events.add(new RelayEvents__c(name='Message: Added to wire', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='message', EventSubType__c='delivered', ActionValue__c='',
                EventTimestamp__c=Datetime.now().addSeconds(10)
            ));
        events.add(new RelayEvents__c(name='SMS: Not Delivered', RelayCCID__c=ccid, TriggerID__c=triggerId1, 
                EventType__c='notification', EventSubType__c='undelivered', ActionValue__c=reason,
                EventTimestamp__c=Datetime.now().addSeconds(15)
            ));
        insert events;
        
        List<String> triggerIds = new List<String>();
        triggerIds.add(triggerId1);

        List<RelayExperienceStatus> res = RelayExperienceStatus.getExperienceStatus(ccid, triggerIds);
        
        System.assert(res != null);                

        RelayExperienceStatus stats1 = getTriggerStats(res, triggerId1);
        System.assert(stats1 != null);
        System.assert(stats1.postedDtm > 0, 'Posted DTM should have been set');
        System.assert(stats1.undeliveredDtm > 0, 'Not Delivered DTM should have been set');
        System.assertEquals(stats1.undeliveredReason, reason, 'Not Delivered reason should have been set');
        System.assertEquals(stats1.deliveredDtm, 0, 'Notification delivered DTM should be 0');
    }
}