force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/PJN_Network_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Network Object Setting</label>
    <pluralLabel>Network Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_DCR_Record_Field_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Record_Field_Id__c</fullName>
    <description>Field API Name to link the record.</description>
    <inlineHelpText>Field API Name to link the record.</inlineHelpText>
    <label>DCR Record Field Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_DCR_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Record_Type_Name__c</fullName>
    <description>Record type associated to the DCR to be created.</description>
    <label>DCR Record Type Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_DCR_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Record_Types_Allowed__c</fullName>
    <description>Record type names which allows DCR creation. This names should be separate by comma. &apos;All&apos; will include every single record type.</description>
    <inlineHelpText>Record type names which allows DCR creation. This names should be separate by comma. &apos;All&apos; will include every single record type.</inlineHelpText>
    <label>SObject Record Types Allowed</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Parent_Account_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Account_Field_Name__c</fullName>
    <description>Parent Account field API name associated.</description>
    <label>Parent Account Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Search_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Search_Record_Types_Allowed__c</fullName>
    <description>Record types allowed to search in Network.</description>
    <label>Search Record Types Allowed</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Name__c</fullName>
    <description>SObject Name for the DCR.</description>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Sync_Delay__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Delay__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sync delay in minutes - No delay with value 0</description>
    <inlineHelpText>Sync delay in minutes - No delay with value 0</inlineHelpText>
    <label>Sync Delay</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Sync_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Record_Types_Allowed__c</fullName>
    <defaultValue>&quot;All&quot;</defaultValue>
    <label>Sync Record Types Allowed</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkObjectSettingsQuery.cls
/**
 * Query Network Object Settings metadata
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_NetworkObjectSettingsQuery {

    /**
     * Query all Network Object Settings metadatas
     * @returns `List<PJN_Network_Object_Setting__mdt>`
     */
    public List<PJN_Network_Object_Setting__mdt> queryAll() {
        return [
            SELECT
                Id,
                DeveloperName,
                MasterLabel,
                PJN_DCR_Record_Type_Name__c,
                PJN_DCR_Record_Field_Id__c,
                PJN_Parent_Account_Field_Name__c,
                PJN_SObject_Name__c,
                PJN_DCR_Record_Types_Allowed__c,
                PJN_Search_Record_Types_Allowed__c,
                PJN_Sync_Record_Types_Allowed__c,
                PJN_Sync_Delay__c
            FROM
                PJN_Network_Object_Setting__mdt
        ];
    }
}