force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/PJN_Network_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Network Object Setting</label>
    <pluralLabel>Network Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Name__c</fullName>
    <description>SObject Name for the DCR.</description>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/PJN_Network_Record_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Object record type to Veeva Network entity type mapping</description>
    <label>Network Record Type Mapping</label>
    <pluralLabel>Network Record Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Inbound__c.field-meta.xml
<CustomField>
    <fullName>PJN_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Veeva Network to Salesforce</description>
    <label>Inbound?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Network_Object_Setting__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Object_Setting__c</fullName>
    <label>Network Object Setting</label>
    <referenceTo>PJN_Network_Object_Setting__mdt</referenceTo>
    <relationshipLabel>Network Record Type Mappings</relationshipLabel>
    <relationshipName>PJN_Network_Record_Type_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Network_Record_SubType__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Record_SubType__c</fullName>
    <description>Network Record type described on HCP/HCO type.</description>
    <label>Network Record SubType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Network_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Record_Type__c</fullName>
    <description>Veeva Network entity type</description>
    <label>Network Record Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Outbound__c.field-meta.xml
<CustomField>
    <fullName>PJN_Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce to Veeva Network</description>
    <label>Outbound?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Type_Name__c</fullName>
    <description>Salesforce record type developer name</description>
    <label>Record Type Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkRecordTypeMappingsQuery.cls
/**
 * Query PJN_Network_Record_Type_Mapping__mdt custom metadatas
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_NetworkRecordTypeMappingsQuery {

    /**
     * Query all Network Record Type Mappings
     * @returns `List<PJN_Network_Record_Type_Mapping__mdt>`
     */
    public List<PJN_Network_Record_Type_Mapping__mdt> queryAll() {
        return [
            SELECT
                Id,
                DeveloperName,
                MasterLabel,
                PJN_Network_Object_Setting__c,
                PJN_Network_Object_Setting__r.PJN_SObject_Name__c,
                PJN_Network_Record_Type__c,
                PJN_Network_Record_SubType__c,
                PJN_Record_Type_Name__c,
                PJN_Inbound__c,
                PJN_Outbound__c
            FROM
                PJN_Network_Record_Type_Mapping__mdt
        ];
    }
}