force-app/main/default/src/objects/PJN_Care_Plan_Field__mdt/PJN_Care_Plan_Field__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder; Care Plan Path
Purpose: Define the field and icon to be displayed on the right-side boxes in the care plan path for a specific program problem.
Metadata Relationship(s): CarePlan Path Coaching Setting
Created by Mavens: Yes</description>
    <label>Care Plan Field</label>
    <pluralLabel>Care Plan Fields</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Care_Plan_Field__mdt/fields/PJN_CarePlan_Path_Coaching_Setting__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Path_Coaching_Setting__c</fullName>
    <inlineHelpText>Add CarePlan Path Coaching Setting value if Care Plan Field related to Stage. Leave blank if related to Program.</inlineHelpText>
    <label>CarePlan Path Coaching Setting</label>
    <referenceTo>PJN_CarePlan_Path_Coaching_Setting__mdt</referenceTo>
    <relationshipLabel>Care Plan Fields</relationshipLabel>
    <relationshipName>PJN_Care_Plan_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Field__mdt/fields/PJN_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_Label__c</fullName>
    <label>Field Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Field__mdt/fields/PJN_Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Icon_Name__c</fullName>
    <defaultValue>&apos;standard:default&apos;</defaultValue>
    <label>Icon Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Field__mdt/fields/PJN_Icon_Size__c.field-meta.xml
<CustomField>
    <fullName>PJN_Icon_Size__c</fullName>
    <defaultValue>&apos;small&apos;</defaultValue>
    <label>Icon Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>x-small</fullName>
                <default>true</default>
                <label>x-small</label>
            </value>
            <value>
                <fullName>small</fullName>
            </value>
            <value>
                <fullName>medium</fullName>
            </value>
            <value>
                <fullName>large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Field__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <inlineHelpText>The Program this field belongs to.</inlineHelpText>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Care Plan Fields</relationshipLabel>
    <relationshipName>PJN_Care_Plan_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_CarePlan_Path_Coaching_Setting__mdt/PJN_CarePlan_Path_Coaching_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder; Care Plan Path Coaching
Purpose: Define the guidance and key fields for each program problem/stage.
Metadata Relationship(s): Program Problem; CarePlan Path Keys Setting
Created by Mavens: Yes</description>
    <label>CarePlan Path Coaching Setting</label>
    <pluralLabel>CarePlan Path Coaching Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_CarePlanFieldQuery.cls
/**
 * @author      Mavens
 * @group       CarePlan-UI
 * @description class to query care plan field metadata
 */
public with sharing class PJN_CarePlanFieldQuery {
    /**
     * query by care plan path coaching setting developer name
     * @param   String        carePlanPathCoachingSettingDeveloperName
     * @returns  List<PJN_Care_Plan_Field__mdt>
     */
    public List<PJN_Care_Plan_Field__mdt> queryByCoachingSettingDeveloperName(String carePlanPathCoachingSettingDeveloperName) {
        return [
            SELECT
                Id,
                PJN_Field_API_Name__c,
                PJN_Field_Label__c,
                PJN_Icon_Name__c,
                PJN_Icon_Size__c,
                PJN_Order__c
            FROM
                PJN_Care_Plan_Field__mdt
            WHERE
                PJN_CarePlan_Path_Coaching_Setting__r.DeveloperName = :carePlanPathCoachingSettingDeveloperName
            ORDER BY
                PJN_Order__c ASC
        ];
    }

    /**
     * query by care plan program developer name
     * @param   String        carePlanProgramDeveloperName
     * @returns  List<PJN_Care_Plan_Field__mdt>
     */
    public List<PJN_Care_Plan_Field__mdt> queryByCarePlanProgramDeveloperName(String carePlanProgramDeveloperName) {
        return [
            SELECT
                Id,
                PJN_Field_API_Name__c,
                PJN_Field_Label__c,
                PJN_Icon_Name__c,
                PJN_Icon_Size__c,
                PJN_Order__c
            FROM
                PJN_Care_Plan_Field__mdt
            WHERE
                PJN_Program__r.DeveloperName = :carePlanProgramDeveloperName
            AND
                PJN_CarePlan_Path_Coaching_Setting__c = null
            ORDER BY
                PJN_Order__c ASC
        ];
    }
}