force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Primary_Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Primary_Coverage_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Coverage Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Primary_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Primary_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Secondary_Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Secondary_Coverage_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Coverage Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Secondary_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Secondary_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Primary_BIN__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_BIN__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary active member plan BIN (related to the primary active member plan stored on their care plan record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary BIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Primary_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Group_Number__c</fullName>
    <description>Group Number from Primary Coverage --&gt; PRIMARY_GROUP,</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Group Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Primary_Insurance_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Insurance_ID__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary active member plan insurance ID (related to the primary active member plan stored on their care plan record).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Primary Insurance ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Primary_Payer_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Payer_Name__c</fullName>
    <description>Text(255) field used to store Primary Payer Name.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Payer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Primary_PCN__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_PCN__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary active member plan PCN (related to the primary active member plan stored on their care plan record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary PCN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Primary_Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Plan_Name__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary active member plan name (related to the primary active member plan stored on their care plan record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Secondary_BIN__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_BIN__c</fullName>
    <description>Text field used to stamp a patient&apos;s secondary active member plan BIN (related to the secondary active member plan stored on their care plan record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary BIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Secondary_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_Group_Number__c</fullName>
    <description>Group Number from Secondary Coverage --&gt; SECONDARY_GROUP,</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Group Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Secondary_Insurance_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_Insurance_ID__c</fullName>
    <description>Text field used to stamp a patient&apos;s secondary active member plan insurance ID (related to the secondary active member plan stored on their care plan record).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Secondary Insurance ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Secondary_Payer_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_Payer_Name__c</fullName>
    <description>- Name from Secondary Coverage&apos;s Payer Plan --&gt; SECONDARY_PAYER_NAME.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Payer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Secondary_PCN__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_PCN__c</fullName>
    <description>Text field used to stamp a patient&apos;s secondary active member plan PCN (related to the secondary active member plan stored on their care plan record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary PCN</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Secondary_Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_Plan_Name__c</fullName>
    <description>Text field used to stamp a patient&apos;s secondary active member plan name (related to the secondary active member plan stored on their care plan record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_ConnectiveRxEnrollInsurance.cls
/**
 * @author      Mavens
 * @group       ConnectiveRx
 * @description Wrapper for the Insurance in the Enrollment Request
 */
public with sharing class MVN_ConnectiveRxEnrollInsurance {

    /**
     * JSON Parameters requesting into ConnectiveRx Insurance
     */
    public String groupNumber;
    public String memberId;
    public String payerName;
    public String insuranceTypeCode;
    public Date effectiveDate;
    public String payerPlanName;
    public String bin;
    public String pcn;
    public Integer ordinal;

    /**
     * Primary Insurance Type Code mapping from SFDC to ConnectiveRx
     */
    private static final Map<String, String> PRIMARY_INSURANCE_TYPE_CODE_MAPPING = new Map<String, String> {
        Label.MVN_CRX_Enroll_Insurance_Medical_Type => Label.MVN_CRX_Enroll_Insurance_Primary_Medical,
        Label.MVN_CRX_Enroll_Insurance_Pharmacy_Type => Label.MVN_CRX_Enroll_Ins_Primary_Prescription
	};

    /**
     * Secondary Insurance Type Code mapping from SFDC to ConnectiveRx
     */
    private static final Map<String, String> SECONDARY_INSURANCE_TYPE_CODE_MAPPING = new Map<String, String> {
        Label.MVN_CRX_Enroll_Insurance_Medical_Type => Label.MVN_CRX_Enroll_Insurance_Secondary_Medical,
        Label.MVN_CRX_Enroll_Insurance_Pharmacy_Type => Label.MVN_CRX_Enroll_Ins_Secondary_Prescription
    };

    /**
     * Constructor to populate the Insurance for ConnectiveRx
     * @param fulfillmentRequest    Fulfillment Request
     * @param isPrimary             Defines either primary or secundary insurance
     */
    public MVN_ConnectiveRxEnrollInsurance(PJN_Fulfillment_Request__c fulfillmentRequest, Boolean isPrimary) {
        if (isPrimary) {
            setPrimaryInsurance(fulfillmentRequest);
        } else {
            setSecondaryInsurance(fulfillmentRequest);
        }
    }

    /**
     * Set Primary Insurance record using fulfillment request record
     * @param fulfillmentRequest    Fulfillment Request record
     */
    private void setPrimaryInsurance(PJN_Fulfillment_Request__c fulfillmentRequest) {
        this.groupNumber = fulfillmentRequest.PJN_Primary_Group_Number__c;
        this.memberId = fulfillmentRequest.PJN_Primary_Insurance_ID__c;
        this.payerName = fulfillmentRequest.PJN_Primary_Payer_Name__c;
        this.insuranceTypeCode = PRIMARY_INSURANCE_TYPE_CODE_MAPPING.containsKey(fulfillmentRequest.MVN_Primary_Coverage_Type__c) ?
            PRIMARY_INSURANCE_TYPE_CODE_MAPPING.get(fulfillmentRequest.MVN_Primary_Coverage_Type__c) :
            null;
        this.effectiveDate = fulfillmentRequest.MVN_Primary_Effective_Date__c;
        this.payerPlanName = fulfillmentRequest.PJN_Primary_Plan_Name__c;
        this.bin = fulfillmentRequest.PJN_Primary_BIN__c;
        this.pcn = fulfillmentRequest.PJN_Primary_PCN__c;
    }

    /**
     * Set Secondary Insurance record using fulfillment request record
     * @param fulfillmentRequest    Fulfillment Request record
     */
    private void setSecondaryInsurance(PJN_Fulfillment_Request__c fulfillmentRequest) {
        this.groupNumber = fulfillmentRequest.PJN_Secondary_Group_Number__c;
        this.memberId = fulfillmentRequest.PJN_Secondary_Insurance_ID__c;
        this.payerName = fulfillmentRequest.PJN_Secondary_Payer_Name__c;
        this.insuranceTypeCode = SECONDARY_INSURANCE_TYPE_CODE_MAPPING.containsKey(fulfillmentRequest.MVN_Secondary_Coverage_Type__c) ?
            SECONDARY_INSURANCE_TYPE_CODE_MAPPING.get(fulfillmentRequest.MVN_Secondary_Coverage_Type__c) :
            null;
        this.effectiveDate = fulfillmentRequest.MVN_Secondary_Effective_Date__c;
        this.payerPlanName = fulfillmentRequest.PJN_Secondary_Plan_Name__c;
        this.bin = fulfillmentRequest.PJN_Secondary_BIN__c;
        this.pcn = fulfillmentRequest.PJN_Secondary_PCN__c;
    }
}