force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Group_Number__c</fullName>
    <description>The plan&apos;s pharmacy group number or the unique number a plan assigns to an employer group or another entity purchasing health coverage on behalf of its employees/members.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Group Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_ConnectiveRxEnrollRequest.cls
/**
 * @author      Mavens
 * @group       ConnectiveRx
 * @description Wrapper for the Enrollment Request
 */
public with sharing class MVN_ConnectiveRxEnrollRequest {

    /**
     * JSON Parameters from ConnectiveRx Request
     */
    public MVN_ConnectiveRxEnrollWorkflow workflow;
    public String groupNumber;
    public MVN_ConnectiveRxEnrollmentWrapper enrollment;

    /**
     * Constructor to populate the request for ConnectiveRx
     * @param fulfillmentRequest    Fulfillment Request record
     */
    public MVN_ConnectiveRxEnrollRequest(PJN_Fulfillment_Request__c fulfillmentRequest) {
        this.workflow = new MVN_ConnectiveRxEnrollWorkflow('Enrollment');
        this.groupNumber = fulfillmentRequest.MVN_Copay_Group_Number__c;
        this.enrollment = new MVN_ConnectiveRxEnrollmentWrapper(fulfillmentRequest);
    }
}