force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_ICD_10_CM_Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>MVN_ICD_10_CM_Diagnosis_Code__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>ICD-10-CM Diagnosis Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Patient_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_Diagnosis__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Diagnosis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Master-details relationship with Case object.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Fulfillment Requests</relationshipLabel>
    <relationshipName>Fulfillment_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Date_of_Rx__c.field-meta.xml
<CustomField>
    <fullName>PJN_Date_of_Rx__c</fullName>
    <description>Date field to store Date of Rx.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Rx</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>PJN_Date_Submitted__c</fullName>
    <description>Date/Time a fulfillment request was submitted.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Submitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Fulfillment_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Fulfillment_Request_Status__c</fullName>
    <description>Status of the fulfillment request.</description>
    <label>Fulfillment Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_NDC__c.field-meta.xml
<CustomField>
    <fullName>PJN_NDC__c</fullName>
    <description>NDC from Prescription&apos;s Product --&gt; NDC,</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NDC</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_Address_Line_1__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary address line 1 (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_City__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary address city (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_DOB__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_DOB__c</fullName>
    <description>Birthdate from Patient Account --&gt; PATIENT_DOB.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_First_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_First_Name__c</fullName>
    <description>Text field used to stamp the first name of the patient related to the care plan.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_Gender__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_Gender__c</fullName>
    <description>Text field used to stamp the gender of the patient related to the care plan.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Gender</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_Last_Name__c</fullName>
    <description>Text field used to stamp the last name of the patient related to the care plan.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_Phone__c</fullName>
    <description>Phone field used to stamp a patient&apos;s primary phone number (stored on their phone contact information record when that record is set as primary).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_Postal_Code__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary address postal code (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Patient_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient_State__c</fullName>
    <description>Text field used to stamp a patient&apos;s primary address state (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_Address_Line_1__c</fullName>
    <description>Text field used to stamp a physician&apos;s primary address line 1 (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_City__c</fullName>
    <description>Text field used to stamp a physician&apos;s primary address city (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_First_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_First_Name__c</fullName>
    <description>Text field used to stamp the first name of the physician related to a patient&apos;s care plan.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_Last_Name__c</fullName>
    <description>Text field used to stamp the last name of the physician related to a patient&apos;s care plan.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_NPI__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_NPI__c</fullName>
    <description>Text field used to stamp a physician&apos;s NPI (stored on their account record).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician NPI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_Postal_Code__c</fullName>
    <description>Text field used to stamp a physician&apos;s primary address postal code (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Physician_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician_State__c</fullName>
    <description>Text field used to stamp a physician&apos;s primary address state (stored on their address contact information record when that record is set as primary).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Physician State</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/recordTypes/MVN_SP_Triage_Submitted.recordType-meta.xml
<RecordType>
    <fullName>MVN_SP_Triage_Submitted</fullName>
    <active>true</active>
    <description>Defines a submitted request to triage an order to a patient&apos;s specialty pharmacy</description>
    <label>SP Triage - Submitted</label>
</RecordType>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/recordTypes/PJN_Materials_Order.recordType-meta.xml
<RecordType>
    <fullName>PJN_Materials_Order</fullName>
    <active>true</active>
    <description>Defines a request to send materials to a patient</description>
    <label>Materials Order</label>
</RecordType>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/recordTypes/PJN_SP_Triage.recordType-meta.xml
<RecordType>
    <fullName>PJN_SP_Triage</fullName>
    <active>true</active>
    <description>Defines a request to triage an order to a patient&apos;s specialty pharmacy</description>
    <label>SP Triage</label>
</RecordType>

force-app/main/default/src/classes/PJN_SubmitFulfillmentRequestCtrl.cls
/**
 * @author      Mavens
 * @date        April 2019
 * @description Used by quick action on the fulfillment request record to submit record
 * @group       Fulfillment
 */
public with sharing class PJN_SubmitFulfillmentRequestCtrl {

    private static final Map<String, String> FULFILLMENT_RECORD_TYPE_MAPPING = new Map<String, String> {
        'PJN_SP_Triage' => 'MVN_SP_Triage_Submitted',
        'MVN_Copay_Claim' => 'MVN_Copay_Claim_Submitted',
        'PJN_Materials_Order' => 'PJN_Materials_Order'
    };
    private static final Set<String> FULFILLMENT_REQUEST_STD_FIELDS = new Set<String> {
        'PJN_Fulfillment_Request_Status__c',
        'PJN_Date_Submitted__c',
        'RecordTypeId',
        'RecordType.DeveloperName'
    };
    private static final Map<String, Schema.SObjectField> FULFILLMENT_FIELDS = Schema.SObjectType.PJN_Fulfillment_Request__c.fields.getMap();
    private static final Set<String> SP_TRIAGE_REQUIRED_FIELDS = new Set<String> {
        'MVN_Patient_Id__c',
        'PJN_Patient_Last_Name__c',
        'PJN_Patient_First_Name__c',
        'PJN_Patient_DOB__c',
        'PJN_Patient_Gender__c',
        'PJN_Patient_Address_Line_1__c',
        'PJN_Patient_City__c',
        'PJN_Patient_State__c',
        'PJN_Patient_Postal_Code__c',
        'PJN_Patient_Phone__c',
        'MVN_ICD_10_CM_Diagnosis_Code__c',
        'PJN_Physician_Last_Name__c',
        'PJN_Physician_First_Name__c',
        'PJN_Physician_Address_Line_1__c',
        'PJN_Physician_City__c',
        'PJN_Physician_State__c',
        'PJN_Physician_Postal_Code__c',
        'PJN_Physician_NPI__c',
        'PJN_Date_of_Rx__c',
        'PJN_NDC__c',
        'PJN_Care_Plan__c',
        'MVN_Patient_Diagnosis__c',
        'MVN_Clinical_Trial_Transition_Patient__c'
    };
    private static Set<String> visitedFields = new Set<String>();

    @AuraEnabled
    public static Boolean submitFulfillmentRecord(Id recordId){
        PJN_Fulfillment_Request__c fulfillment = getFulfillmentRequest(recordId);
        if (fulfillment.PJN_Fulfillment_Request_Status__c == 'Submitted') {
            return false;
        }
        Set<String> noFilledRequiredFields = getNoFilledRequiredFields(fulfillment);
        if (!noFilledRequiredFields.isEmpty()) {
            String fields = '';
            System.debug('### Missing required fields:');
            for (String noFilledRequiredField : noFilledRequiredFields) {
                System.debug('' + noFilledRequiredField);
                fields += noFilledRequiredField + ', ';
            }
            String errorMessage = String.format(Label.MVN_Missing_Required_Fields_Submitting_Fulfillment_Error_Message, new List<String>{fields.substringBeforeLast(', ')});
            AuraHandledException auraException = new AuraHandledException(errorMessage);
            auraException.setMessage(errorMessage);
            throw auraException;
        }
        if (!fulfillment.RecordType.DeveloperName.equals('PJN_Materials_Order') && !getIfFilesAttached(fulfillment)) {
            AuraHandledException auraException = new AuraHandledException(Label.MVN_Missing_Files_Submitting_Fulfillment_Error_Message);
            auraException.setMessage(Label.MVN_Missing_Files_Submitting_Fulfillment_Error_Message);
            throw auraException;
        }
        fulfillment.PJN_Fulfillment_Request_Status__c = 'Submitted';
        fulfillment.PJN_Date_Submitted__c = Datetime.now();
        fulfillment.RecordTypeId = getNewFulfillmentRecordType(fulfillment);
        try {
            update fulfillment;
            return true;
        } catch (Exception exc) {
            throw new AuraHandledException(exc.getMessage());
        }
    }

    private static PJN_Fulfillment_Request__c getFulfillmentRequest(Id recordId) {
        String fields = getFulfillmentRequestFields(FULFILLMENT_REQUEST_STD_FIELDS);
        fields += getFulfillmentRequestFields(SP_TRIAGE_REQUIRED_FIELDS);
        String query = 'SELECT ' + fields.substringBeforeLast(',') + ' FROM PJN_Fulfillment_Request__c WHERE Id = :recordId';
        return (PJN_Fulfillment_Request__c) Database.query(query);
    }

    private static String getFulfillmentRequestFields(Set<String> frFields) {
        String fields = '';
        for (String frField : frFields) {
            if (!visitedFields.contains(frField)) {
                fields += frField + ',';
                visitedFields.add(frField);
            }
        }
        return fields;
    }

    private static Boolean getIfFilesAttached(PJN_Fulfillment_Request__c fulfillment) {
        List<ContentDocumentLink> cdls = [
            SELECT
                Id
            FROM
                ContentDocumentLink
            WHERE
                LinkedEntityId = :fulfillment.Id
            LIMIT 1
        ];
        return !cdls.isEmpty();
    }

    private static Set<String> getNoFilledRequiredFields(PJN_Fulfillment_Request__c fulfillmentRequest) {
        Set<String> noFilledRequiredFields = new Set<String>();
        if (fulfillmentRequest.RecordType.DeveloperName == 'PJN_SP_Triage') {
            noFilledRequiredFields.addAll(getNoFilledRequiredSPTriage(fulfillmentRequest));
        }
        return noFilledRequiredFields;
    }

    private static Set<String> getNoFilledRequiredSPTriage(PJN_Fulfillment_Request__c fulfillmentRequest) {
        Set<String> noFilledRequiredFields = new Set<String>();
        for (String spTriageField : SP_TRIAGE_REQUIRED_FIELDS) {
            if (!FULFILLMENT_FIELDS.containsKey(spTriageField)) {
                continue;
            }
            Boolean noFilled = fulfillmentRequest.get(spTriageField) == null || String.isBlank(String.valueOf(fulfillmentRequest.get(spTriageField)));
            if (noFilled) {
                noFilledRequiredFields.add(FULFILLMENT_FIELDS.get(spTriageField).getDescribe().getLabel());
            }
        }
        return noFilledRequiredFields;
    }

    private static Id getNewFulfillmentRecordType(PJN_Fulfillment_Request__c fulfillmentRequest) {
        if (!FULFILLMENT_RECORD_TYPE_MAPPING.containsKey(fulfillmentRequest.RecordType.DeveloperName)) {
            return fulfillmentRequest.RecordTypeId;
        }
        String newRecordTypeDevName = FULFILLMENT_RECORD_TYPE_MAPPING.get(fulfillmentRequest.RecordType.DeveloperName);
        return Schema.SObjectType.PJN_Fulfillment_Request__c.getRecordTypeInfosByDeveloperName().containsKey(newRecordTypeDevName) ?
            Schema.SObjectType.PJN_Fulfillment_Request__c.getRecordTypeInfosByDeveloperName().get(newRecordTypeDevName).getRecordTypeId() :
            fulfillmentRequest.RecordTypeId;
    }
}