force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Program_Consent_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Consent_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Consent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Program_Consent_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Consent_Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Consent Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_HIPPA_Consent_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_HIPPA_Consent_Date__c</fullName>
    <description>- Consent Date from Patient&apos;s HIPAA Consent --&gt; HIPAA_CONSENT_DATE.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>HIPAA Consent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_HIPPA_Consent_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_HIPPA_Consent_Expiration_Date__c</fullName>
    <description>- Expiration Date from Patient&apos;s HIPAA Consent --&gt; consent_expiration_date,</description>
    <encryptionScheme>None</encryptionScheme>
    <label>HIPAA Consent Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/classes/MVN_ConnectiveRxEnrollAssociation.cls
/**
 * @author      Mavens
 * @group       ConnectiveRx
 * @description Wrapper Connective Rx Enrollment Assosiations
 */
public with sharing class MVN_ConnectiveRxEnrollAssociation {

    /**
     * JSON Parameters requesting into ConnectiveRx Assosiation
     */
    public String associationType;
    public String type;
    public Datetime signedDate;
    public Datetime expiryDate;
    public String age;
    public String name;
    public String description;

    private static final Set<String> HIPAA_CONSENT_TYPES = new Set<String> {
        'hipaa-authorization',
        'third-party-disclosure'
    };

    private static final Set<String> PROGRAM_CONSENT_TYPES = new Set<String> {
        'phone-communication',
        'email-communication',
        'mail-communication',
        'market-research'
    };

    /**
     * Contructor to populate the Assosiations for ConnectiveRx
     * @param fulfillmentRequest    Fulfillment Request record
     * @param associationType       Current assosiation type
     */
    public MVN_ConnectiveRxEnrollAssociation(PJN_Fulfillment_Request__c fulfillmentRequest, String associationType) {
        if (HIPAA_CONSENT_TYPES.contains(associationType.toLowerCase())) {
            setHipaaAuthorization(fulfillmentRequest, associationType);
        } else if (PROGRAM_CONSENT_TYPES.contains(associationType.toLowerCase())) {
            setProgramAuthorization(fulfillmentRequest, associationType);
        }
    }

    /**
     * Set HIPAA Authorization using fulfillment request to the assosiation type
     * @param fulfillmentRequest    Fulfillment Request record
     * @param associationType       Current assosiation type
     */
    private void setHipaaAuthorization(PJN_Fulfillment_Request__c fulfillmentRequest, String associationType) {
        this.associationType = Label.MVN_CRX_Enroll_Default_Association_Type.toLowerCase();
        this.type = associationType;
        this.signedDate = fulfillmentRequest.PJN_HIPPA_Consent_Date__c;
        this.expiryDate = fulfillmentRequest.PJN_HIPPA_Consent_Expiration_Date__c;
    }

    /**
     * Set Program Authorization using fulfillment request to the assosiation type
     * @param fulfillmentRequest    Fulfillment Request record
     * @param associationType       Current assosiation type
     */
    private void setProgramAuthorization(PJN_Fulfillment_Request__c fulfillmentRequest, String associationType) {
        this.associationType = Label.MVN_CRX_Enroll_Default_Association_Type.toLowerCase();
        this.type = associationType;
        this.signedDate = fulfillmentRequest.MVN_Program_Consent_Date__c;
        this.expiryDate = fulfillmentRequest.MVN_Program_Consent_Expiration_Date__c;
    }
}