force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fulfillment Requests (Practice)</relationshipLabel>
    <relationshipName>Fulfillment_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Address_Line_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Address_Line_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_City__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Fax__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Fax__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_NPI__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_NPI__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice NPI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Phone__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Practice_State__c.field-meta.xml
<CustomField>
    <fullName>MVN_Practice_State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Practice State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_ConnectiveRxEnrollAccount.cls
/**
 * @author      Mavens
 * @group       ConnectiveRx
 * @description Wrapper Connective Rx Enrollment Business Account
 */
public with sharing class MVN_ConnectiveRxEnrollAccount {

    /**
     * JSON Parameters requesting into ConnectiveRx Enrollment
     */
    public String partnerId;
    public String name;
    public String address1;
    public String address2;
    public String city;
    public String state;
    public String postalCode;
    public String countryCode;
    public String phone;
    public String fax;
    public String email;
    public String taxId;
    public String npi;

    /**
     * Contructor to populate the Business Account for ConnectiveRx
     * @param fulfillmentRequest    Fulfillment Request record
     */
    public MVN_ConnectiveRxEnrollAccount(PJN_Fulfillment_Request__c fulfillmentRequest) {
        this.partnerId = fulfillmentRequest.MVN_Practice__c;
        this.name = fulfillmentRequest.MVN_Practice_Name__c;
        this.address1 = fulfillmentRequest.MVN_Practice_Address_Line_1__c;
        this.address2 = fulfillmentRequest.MVN_Practice_Address_Line_2__c;
        this.city = fulfillmentRequest.MVN_Practice_City__c;
        this.state = fulfillmentRequest.MVN_Practice_State__c;
        this.postalCode = fulfillmentRequest.MVN_Practice_Postal_Code__c;
        this.countryCode = Label.MVN_CRX_Enroll_Default_Country;
        this.phone = fulfillmentRequest.MVN_Practice_Phone__c;
        this.fax = fulfillmentRequest.MVN_Practice_Fax__c;
        this.email = fulfillmentRequest.MVN_Practice_Email__c;
        this.npi = fulfillmentRequest.MVN_Practice_NPI__c;
    }
}