force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Document_Key__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Document_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Status__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Status__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/Pending_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pending Consumer</label>
    <referenceTo>Pending_Lead_MVN__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_MVN__c/Pending_Lead_MVN__c.object-meta.xml
<CustomObject>
    <label>Pending Consumer</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Pending Consumer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Consumers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/classes/AgreementStatusCheckHdlrMVN.cls
/**
 * @author      Mavens
 * @description Calls out Adobe Sign to check the status of an agreement on insert. This is to catch if an agreement is signed in the window between receiving an agreement id and passing it to the WebHook.
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class AgreementStatusCheckHdlrMVN implements PJN_TriggerDispatcher.HandlerInterface {
    public void handle() {

        Boolean canCallFuture = !System.isFuture() && !System.isBatch() && !System.isQueueable() && !System.isScheduled();

        if (canCallFuture) {
            List<Id> agreementIds = new List<Id>();
            for (echosign_dev1__SIGN_Agreement__c agreement : (List<echosign_dev1__SIGN_Agreement__c>) trigger.new) {
                agreementIds.add(agreement.Id);
            }

            updateAgreementsAndPendingLeads(agreementIds);
        }
    }

    @future (callout=true)
    public static void updateAgreementsAndPendingLeads(List<Id> agreementIds) {
        List<echosign_dev1__SIGN_Agreement__c> agreements = [SELECT echosign_dev1__Document_Key__c, echosign_dev1__Status__c, Pending_Lead_MVN__c FROM echosign_dev1__SIGN_Agreement__c WHERE Id IN :agreementIds AND echosign_dev1__Document_Key__c != NULL];

        for (echosign_dev1__SIGN_Agreement__c agreement : agreements) {
            if (agreement.Pending_Lead_MVN__c != NULL && agreement.echosign_dev1__Status__c != 'Signed' && !Test.isRunningTest()) {
                Map<String, Object> agreementMap = AdobeSignAPIMVN.getAgreement(agreement.echosign_dev1__Document_Key__c);
                String status = (String) agreementMap.get('status');
                agreement.echosign_dev1__Status__c = status.replace('_', ' ');
            }
        }

        update agreements;
    }
}