force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/CustomConsumer__c.field-meta.xml
<CustomField>
    <fullName>CustomConsumer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field created by Adobe to allow re-labeled Lead records to be used as recipients.</description>
    <label>Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agreements (Consumer)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/Pending_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pending Consumer</label>
    <referenceTo>Pending_Lead_MVN__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/Agreement_Id_MVN__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Id_MVN__c</fullName>
    <description>Adobe Sign Agreement Id.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Agreement ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/Consumer_has_consented_to_the_prog_MVN__c.field-meta.xml
<CustomField>
    <fullName>Consumer_has_consented_to_the_prog_MVN__c</fullName>
    <description>Captures whether the consumer has provided their consent to enter the program.</description>
    <label>Consumer has consented to the program?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Lead/fields/HealthCloudGA__CarePlanRecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanRecordTypeName__c</fullName>
    <description>Record Type name to use for Care Plan when we convert this lead into a Patient.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Plan Record Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/HealthCloudGA__CarePlanRecordTypeNamespace__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanRecordTypeNamespace__c</fullName>
    <description>Record Type namespace to use for Care Plan when we convert this lead into a Patient.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Plan Record Type Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/HealthCloudGA__IsMarkedForPatientConversion__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__IsMarkedForPatientConversion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the Lead should be converted to Patient</description>
    <label>IsMarkedForPatientConversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/Pending_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Pending Consumer object.</description>
    <inlineHelpText>Lookup to Pending Consumer object.</inlineHelpText>
    <label>Pending Consumer</label>
    <referenceTo>Pending_Lead_MVN__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Consumers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Lead/recordTypes/Libtayo_Marketing_Consumer_MVN.recordType-meta.xml
<RecordType>
    <fullName>Libtayo_Marketing_Consumer_MVN</fullName>
    <active>true</active>
    <businessProcess>Libtayo Marketing</businessProcess>
    <label>Libtayo Marketing Consumer</label>
</RecordType>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt.object-meta.xml
<CustomObject>
    <description>Maps lead record types to the types of care plan record types that should be created on conversion</description>
    <label>Lead Convert Care Plan RT Mapping</label>
    <pluralLabel>Lead Convert Care Plan RT Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/Care_Plan_Record_Type_DeveloperName_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Record_Type_DeveloperName_MVN__c</fullName>
    <description>Care plan record type developer name to use when converting lead</description>
    <inlineHelpText>Developer name of the case record type</inlineHelpText>
    <label>Care Plan Record Type Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/CarePlan_RecordType_Namespace_Prefix_MVN__c.field-meta.xml
<CustomField>
    <fullName>CarePlan_RecordType_Namespace_Prefix_MVN__c</fullName>
    <description>Namespace of the care plan record type to use when converting lead</description>
    <label>Care Plan Record Type Namespace Prefix</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/Lead_Record_Type_DeveloperName_MVN__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Type_DeveloperName_MVN__c</fullName>
    <description>Lead record type to match against</description>
    <inlineHelpText>Developer name of the lead record type</inlineHelpText>
    <label>Lead Record Type Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/Lead_Record_Type_Namespace_Prefix_MVN__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Type_Namespace_Prefix_MVN__c</fullName>
    <description>Lead record type namespace prefix to match against</description>
    <label>Lead Record Type Namespace Prefix</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_Mapping_MVN__mdt/Pending_Lead_Mapping_MVN__mdt.object-meta.xml
<CustomObject>
    <description>When the Libtayo API call is received it creates a Pending Consumer which is later converted into a Lead. This contains mappings for that converstion.</description>
    <label>Pending Consumer API Mapping</label>
    <pluralLabel>Pending Consumer API Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Pending_Lead_Mapping_MVN__mdt/fields/Lead_Field_MVN__c.field-meta.xml
<CustomField>
    <fullName>Lead_Field_MVN__c</fullName>
    <label>Consumer Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_Mapping_MVN__mdt/fields/Pending_Consumer_Field_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Consumer_Field_MVN__c</fullName>
    <label>Pending Consumer Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_MVN__c/Pending_Lead_MVN__c.object-meta.xml
<CustomObject>
    <label>Pending Consumer</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Pending Consumer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Consumers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/Pending_Lead_MVN__c/fields/Agreement_Id_MVN__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Id_MVN__c</fullName>
    <description>Adobe Sign Agreement Id.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Agreement ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_MVN__c/fields/Agreement_Status_MVN__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Status_MVN__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_MVN__c/fields/Consumer_has_consented_to_the_prog_MVN__c.field-meta.xml
<CustomField>
    <fullName>Consumer_has_consented_to_the_prog_MVN__c</fullName>
    <description>Captures whether the consumer has provided their consent to enter the program.</description>
    <label>Consumer has consented to the program?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_MVN__c/fields/Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Pending Consumers</relationshipLabel>
    <relationshipName>Pending_Consumers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/classes/PendingLeadCheckStatusHndlrMVN.cls
/**
 * @author      Mavens
 * @description If Agreement Status turns to “Signed” then convert the record to a Lead and stamp the Lead to the lookup field. 
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class PendingLeadCheckStatusHndlrMVN implements PJN_TriggerDispatcher.HandlerInterface {
    public void handle() {
        List<Pending_Lead_MVN__c> pendingConsumersForProcess = new List<Pending_Lead_MVN__c>();
        for (Pending_Lead_MVN__c pendingConsumer : (List<Pending_Lead_MVN__c>) Trigger.new) {
            if (isPendingLeadEligibleForConversion(pendingConsumer)) {
                pendingConsumersForProcess.add(pendingConsumer);
            }
        }

        convertPendingLeadsIntoLeads(pendingConsumersForProcess);
    }

    public static void convertPendingLeadsIntoLeads(List<Pending_Lead_MVN__c> pendingConsumersForProcess) {
        List<Pending_Lead_Mapping_MVN__mdt> consumerMappings = [SELECT Pending_Consumer_Field_MVN__c, Lead_Field_MVN__c FROM Pending_Lead_Mapping_MVN__mdt WHERE Active_MVN__c = true];
        Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt rtMapping = [SELECT CarePlan_RecordType_Namespace_Prefix_MVN__c, Care_Plan_Record_Type_DeveloperName_MVN__c FROM Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt WHERE Lead_Record_Type_Namespace_Prefix_MVN__c = '' AND Lead_Record_Type_DeveloperName_MVN__c = 'Libtayo_Marketing_Consumer_MVN' LIMIT 1][0];
        List<LeadWrapper> wrappers = new List<LeadWrapper>();
        List<Lead> consumers = new List<Lead>();
        Map<Id, echosign_dev1__SIGN_Agreement__c> agreementMap = queryAgreementMap(pendingConsumersForProcess);
        System.debug('#### agreementMap: ' + agreementMap);
        Id recordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Lead' AND DeveloperName = 'Libtayo_Marketing_Consumer_MVN' LIMIT 1].Id;
        Id integrationUserId = [SELECT Id FROM User WHERE Name = 'Integration User' LIMIT 1].Id;

        for (Pending_Lead_MVN__c pendingConsumer : pendingConsumersForProcess) {
            Lead consumer = new Lead();

            for (Pending_Lead_Mapping_MVN__mdt consumerMapping : consumerMappings) {
                // make sure the field from the mapping actually exists and the pending consumer value isn't null
                if (pendingConsumer.get(consumerMapping.Pending_Consumer_Field_MVN__c) != NULL) {
                    System.debug('#### Setting ' + consumerMapping.Lead_Field_MVN__c + ' to ' + pendingConsumer.get(consumerMapping.Pending_Consumer_Field_MVN__c));
                    consumer.put(consumerMapping.Lead_Field_MVN__c, pendingConsumer.get(consumerMapping.Pending_Consumer_Field_MVN__c));
                }
            }

            consumer.HealthCloudGA__IsMarkedForPatientConversion__c = true;
            consumer.HealthCloudGA__CarePlanRecordTypeNamespace__c = rtMapping.CarePlan_RecordType_Namespace_Prefix_MVN__c;
            consumer.HealthCloudGA__CarePlanRecordTypeName__c = rtMapping.Care_Plan_Record_Type_DeveloperName_MVN__c;
            consumer.Consumer_has_consented_to_the_prog_MVN__c = 'Yes';
            consumer.LeadSource = 'Website';
            consumer.RecordTypeId = recordTypeId;
            consumer.OwnerId = integrationUserId;
            consumer.Pending_Lead_MVN__c = pendingConsumer.Id;
            consumer.Status = 'Enrolled';

            LeadWrapper wrapper = new LeadWrapper(consumer, agreementMap.get(pendingConsumer.Id), pendingConsumer.Id);
            System.debug('#### agreementMap.get(' + pendingConsumer.Id + '): ' + agreementMap.get(pendingConsumer.Id));
            System.debug('#### new wrapper: ' + wrapper);
            wrappers.add(wrapper);
            consumers.add(consumer);
        }

        // prevent flows from running when testing.
        if (Test.isRunningTest()) {
            for (Lead consumer : consumers) {
                consumer.Status = 'Interaction';
                consumer.Consumer_has_consented_to_the_prog_MVN__c = 'No';
                consumer.HealthCloudGA__IsMarkedForPatientConversion__c = false;
            }
        }

        System.debug('#### consumers: ' + consumers);
        insert consumers;

        List<Pending_Lead_MVN__c> pendingConsumers = new List<Pending_Lead_MVN__c>();
        List<echosign_dev1__SIGN_Agreement__c> agreements = new List<echosign_dev1__SIGN_Agreement__c>();
        for (LeadWrapper wrapper : wrappers) {
            System.debug('#### wrapper: ' + wrapper);

            System.debug('#### wrapper.consumer: ' + wrapper.consumer);
            wrapper.pendingConsumer.Lead_MVN__c = wrapper.consumer.Id;
            pendingConsumers.add(wrapper.pendingConsumer);

            System.debug('#### wrapper.agreement: ' + wrapper.agreement);
            if (wrapper.agreement != NULL) {
                wrapper.agreement.CustomConsumer__c = wrapper.consumer.Id;
                wrapper.agreement.echosign_dev1__Recipient_Lead__c = wrapper.consumer.Id;
                agreements.add(wrapper.agreement);
            }
        }

        update pendingConsumers;
        update agreements;
    }

    private static Boolean isPendingLeadEligibleForConversion(Pending_Lead_MVN__c pendingConsumer) {
        Boolean result = false;
        // if agreement status is signed or agreement id is null on insert
        if (Trigger.isInsert && (pendingConsumer.Agreement_Status_MVN__c == 'Signed' || pendingConsumer.Agreement_Id_MVN__c == NULL)) {
            result = true;
        // if agreement status switched to signed
        } else if (Trigger.isUpdate && pendingConsumer.Agreement_Status_MVN__c == 'Signed') {
            Pending_Lead_MVN__c oldPendingLead = (Pending_Lead_MVN__c) Trigger.oldMap.get(pendingConsumer.Id);
            if (pendingConsumer.Agreement_Status_MVN__c != oldPendingLead.Agreement_Status_MVN__c) {
                result = true;
            }
        // if agreement id has become null
        } else if (Trigger.isUpdate && pendingConsumer.Agreement_Id_MVN__c == NULL) {
            Pending_Lead_MVN__c oldPendingLead = (Pending_Lead_MVN__c) Trigger.oldMap.get(pendingConsumer.Id);
            if (pendingConsumer.Agreement_Id_MVN__c != oldPendingLead.Agreement_Id_MVN__c) {
                result = true;
            }
        }

        return result;
    }

    private static Map<Id, echosign_dev1__SIGN_Agreement__c> queryAgreementMap(List<Pending_Lead_MVN__c> pendingConsumers) {
        Map<Id, echosign_dev1__SIGN_Agreement__c> result = new Map<Id, echosign_dev1__SIGN_Agreement__c>();
        for (echosign_dev1__SIGN_Agreement__c agreement : [SELECT CustomConsumer__c, Pending_Lead_MVN__c FROM echosign_dev1__SIGN_Agreement__c WHERE Pending_Lead_MVN__c IN :pendingConsumers]) {
            result.put(agreement.Pending_Lead_MVN__c, agreement);
        }
        return result;
    }

    private class LeadWrapper {
        public Pending_Lead_MVN__c pendingConsumer;
        public Lead consumer;
        public echosign_dev1__SIGN_Agreement__c agreement;

        public LeadWrapper(Lead consumer, echosign_dev1__SIGN_Agreement__c agreement, Id pendingConsumerId) {
            this.consumer = consumer;
            this.pendingConsumer = new Pending_Lead_MVN__c(Id = pendingConsumerId);
            this.agreement = agreement;
        }
    }
}