force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Document_Key__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Document_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/Gender_MVN__c.field-meta.xml
<CustomField>
    <fullName>Gender_MVN__c</fullName>
    <description>Gender of the individual with whom the interaction took place.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Decline to Specify</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Lead/fields/HealthCloudGA__BirthDate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__BirthDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/Regeneron_Adobe_Sign_Settings_MVN__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the config for the Regeneron custom API connection to Adobe Sign</description>
    <label>Regeneron Adobe Sign Settings</label>
</CustomObject>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Authentication_Endpoint_MVN__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Endpoint_MVN__c</fullName>
    <description>The endpoint to call for authentication actions such as obtaining an access token</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The endpoint to call for authentication actions such as obtaining an access token</inlineHelpText>
    <label>Authentication Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Client_Id_MVN__c.field-meta.xml
<CustomField>
    <fullName>Client_Id_MVN__c</fullName>
    <description>The client id for the Adobe Sign App</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The client id for the Adobe Sign App</inlineHelpText>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Client_Secret_MVN__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret_MVN__c</fullName>
    <description>The client secret for the Adobe Sign App</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The client secret for the Adobe Sign App</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Refresh_Token_MVN__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token_MVN__c</fullName>
    <description>The refresh token for the Adobe Sign App</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The refresh token for the Adobe Sign App</inlineHelpText>
    <label>Refresh Token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/REST_API_Endpoint_MVN__c.field-meta.xml
<CustomField>
    <fullName>REST_API_Endpoint_MVN__c</fullName>
    <description>The base endpoint to send all rest API calls to</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The base endpoint to send all rest API calls to</inlineHelpText>
    <label>REST API Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Webhook_Public_Site_MVN__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Public_Site_MVN__c</fullName>
    <description>The url of the public site that the Adobe webhook can call</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The url of the public site that the Adobe webhook can call</inlineHelpText>
    <label>Webhook Public Site</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/src/classes/LeadConsentCtrlTestMVN.cls
@isTest
public class LeadConsentCtrlTestMVN {
    
    @TestSetup
    static void makeData(){
        AdobeSignAPITestMVN.createAdobeSignTemplate();

        insert new Regeneron_Adobe_Sign_Settings_MVN__c(
            Authentication_Endpoint_MVN__c  = 'https://auth.endpoint.adobe.com',
            Client_Id_MVN__c = 'A-client-id',
            Client_Secret_MVN__c = 'A-client-secret',
            Refresh_Token_MVN__c = 'A-refresh-token',
            REST_API_Endpoint_MVN__c = 'https://rest.endpoint.adobe.com',
            Webhook_Public_Site_MVN__c = 'https://public-site-regeneron.salesforce.com'
        );
    }

    @isTest
    private static void itShouldCreateAndSendAnAgreement() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        Lead consumer = new Lead(
            FirstName = 'Dean',
            LastName = 'Martin',
            Email= 'dean.martin@test.dedsi.com',
            HealthCloudGA__BirthDate__c = Date.today().addDays(-365 * 50),
            Gender_MVN__c  = 'Male'
        );

        insert consumer;

        Test.startTest();
        String agreementId = LeadConsentCtrlMVN.createAndSendAgreement(consumer.Id, 'DEDSI Consent', false);
        Test.stopTest();

        System.assertEquals('1234567890Id', agreementId);
        System.assertEquals(1, [
            SELECT COUNT()
            FROM echosign_dev1__SIGN_Agreement__c
        ]);
    }

    @isTest
    private static void itShouldGetSigningUrl() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        Test.startTest();
        String signingUrl = LeadConsentCtrlMVN.getSigningUrl('agreementId');
        Test.stopTest();

        System.assertEquals('https://signingurl.adobesign.com', signingUrl);
    }

    @isTest
    private static void itShouldGetAgreementDocId() {
        echosign_dev1__SIGN_Agreement__c agreement = new echosign_dev1__SIGN_Agreement__c (
            echosign_dev1__Document_Key__c = 'documentKey'
        );
        insert agreement;

        Test.startTest();
        String docKey = LeadConsentCtrlMVN.getAgreementDocId(agreement.Id);
        Test.stopTest();

        System.assertEquals('documentKey', docKey);
    }   
}