force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Status__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Status__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/Pending_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pending Consumer</label>
    <referenceTo>Pending_Lead_MVN__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/Pending_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Pending Consumer object.</description>
    <inlineHelpText>Lookup to Pending Consumer object.</inlineHelpText>
    <label>Pending Consumer</label>
    <referenceTo>Pending_Lead_MVN__c</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Consumers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Pending_Lead_MVN__c/Pending_Lead_MVN__c.object-meta.xml
<CustomObject>
    <label>Pending Consumer</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Pending Consumer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Consumers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/Pending_Lead_MVN__c/fields/Agreement_Status_MVN__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Status_MVN__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/AgreementUpdatePendingLeadHdlrMVN.cls
/**
 * @author      Mavens
 * @description If an Agreement is inserted or the status is updated on an update AND it’s associated to a Pending Lead it updates the Agreement Status on the Pending Lead. If the Pending Lead’s agreement status is changed to Signed it will kick off the Lead conversion process.
 */ 
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class AgreementUpdatePendingLeadHdlrMVN implements PJN_TriggerDispatcher.HandlerInterface {
    public void handle() {
        List<Pending_Lead_MVN__c> pendingLeads = new List<Pending_Lead_MVN__c>();
        for (echosign_dev1__SIGN_Agreement__c agreement : (List<echosign_dev1__SIGN_Agreement__c>) trigger.new) {
            System.debug('#### agreement: ' + agreement);
            System.debug('#### agreement.Pending_Lead_MVN__c: ' + agreement.Pending_Lead_MVN__c);
            if (Trigger.isInsert && agreement.Pending_Lead_MVN__c != NULL) {
                pendingLeads.add(buildPendingLead(agreement));
            } else if (Trigger.isUpdate && agreement.Pending_Lead_MVN__c != NULL) {
                echosign_dev1__SIGN_Agreement__c oldAgreement = (echosign_dev1__SIGN_Agreement__c) trigger.oldMap.get(agreement.Id);
                System.debug('#### oldAgreement.echosign_dev1__Status__c: ' + oldAgreement.echosign_dev1__Status__c);
                System.debug('#### agreement.echosign_dev1__Status__c: ' + agreement.echosign_dev1__Status__c);
                if (oldAgreement.echosign_dev1__Status__c != agreement.echosign_dev1__Status__c) {
                    pendingLeads.add(buildPendingLead(agreement));
                }
            }
        }

        System.debug('#### updating pendingLeads: ' + pendingLeads);
        update pendingLeads;
    }

    private static Pending_Lead_MVN__c buildPendingLead(echosign_dev1__SIGN_Agreement__c agreement) {
        return new Pending_Lead_MVN__c(
            Id = agreement.Pending_Lead_MVN__c,
            Agreement_Status_MVN__c = agreement.echosign_dev1__Status__c
        );
    }
}