force-app/main/default/src/objects/MVN_MDM_Object_Setting__mdt/MVN_MDM_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <description>MDM Object setting mapping</description>
    <label>MDM Object Setting</label>
    <pluralLabel>MDM Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/MVN_MDM_Object_Setting__mdt/fields/MVN_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>MVN_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/MVN_MDM_Object_Setting__mdt/fields/MVN_MDM_Connection__c.field-meta.xml
<CustomField>
    <fullName>MVN_MDM_Connection__c</fullName>
    <description>MDM Connect which uses the Object setting.</description>
    <label>MDM Connection</label>
    <referenceTo>MVN_MDM_Connection__mdt</referenceTo>
    <relationshipLabel>MDM Object Settings</relationshipLabel>
    <relationshipName>MVN_MDM_Object_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/MVN_MDM_Object_Setting__mdt/fields/MVN_MDM_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_MDM_Object_Name__c</fullName>
    <label>MDM Object Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_MDM_Object_Setting__mdt/fields/MVN_SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_SObject_API_Name__c</fullName>
    <description>Salesforce Object API Name</description>
    <label>SObject API Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_MDMObjectSettingQuery.cls
/**
 * @author      Mavens
 * @group       MDM
 * @description Query for MDM Object Settings metadata
 */
public with sharing class MVN_MDMObjectSettingQuery {

    /**
     * Retrieve all Active MDM Object Setting metadatas
     * @return  `List<MVN_MDM_Object_Setting__mdt>`
     */
    public List<MVN_MDM_Object_Setting__mdt> queryAll() {
        return [
            SELECT
                Id,
                DeveloperName,
                MasterLabel,
                MVN_MDM_Connection__c,
                MVN_SObject_API_Name__c,
                MVN_MDM_Object_Name__c
            FROM
                MVN_MDM_Object_Setting__mdt
            WHERE
                MVN_Is_Active__c = true
        ];
    }
}