force-app/main/default/src/objects/PJN_Global_Setting__mdt/PJN_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search
Purpose: Definition of handler class used for the Account Search and the number max of results to be displayed. Global setting for all Programs; change only the max results field.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Global Setting</label>
    <pluralLabel>Global Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Account_Search_Handler_Classes__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account_Search_Handler_Classes__c</fullName>
    <defaultValue>&quot;PJN_AccountSearchHdlr&quot;</defaultValue>
    <description>Comma separated list of classes used in the Account Search. Results from each class are merged.</description>
    <inlineHelpText>Comma separated list of classes used in the Account Search. Results from each class are merged. The win order is the order they are listed (eg: A,B,C means A&gt;B&gt;C with A being the winner).</inlineHelpText>
    <label>Account Search Handler Classes</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Account_Search_Max_Results__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account_Search_Max_Results__c</fullName>
    <defaultValue>50</defaultValue>
    <description>Max number of search results returned by account search.  Cannot exceed the SOSL limit of 200.</description>
    <label>Account Search Max Results</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Address_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Address_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info address record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info address record types.</inlineHelpText>
    <label>Contact Info Address Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Email_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Email_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info email record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info email record types.</inlineHelpText>
    <label>Contact Info Email Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Fax_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Fax_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info fax record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info fax record types.</inlineHelpText>
    <label>Contact Info Fax Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Phone_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Phone_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info phone record types.</description>
    <label>Contact Info Phone Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Create_DCR__c.field-meta.xml
<CustomField>
    <fullName>PJN_Create_DCR__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allow Data Change Request creation</description>
    <inlineHelpText>Allow Data Change Request creation</inlineHelpText>
    <label>Create DCR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Enable_Event_Automation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enable_Event_Automation__c</fullName>
    <defaultValue>true</defaultValue>
    <description>The Event Automation Handler can be disabled by turning this setting off.</description>
    <label>Enable Event Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_API_Version__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_API_Version__c</fullName>
    <defaultValue>&quot;v19.0&quot;</defaultValue>
    <description>Veeva Network API version.</description>
    <label>Network API Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Named_Credential__c</fullName>
    <defaultValue>&quot;PJN_Veeva_Network&quot;</defaultValue>
    <description>Named credential used to connect with Veeva Network.</description>
    <inlineHelpText>Named credential used to connect with Veeva Network.</inlineHelpText>
    <label>Network Named Credential</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_System__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_System__c</fullName>
    <defaultValue>&quot;PJN&quot;</defaultValue>
    <description>System used to identify in every connection with Veeva Network.</description>
    <inlineHelpText>System used to identify in every connection with Veeva Network.</inlineHelpText>
    <label>Network System</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Transaction_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>PJN_Transaction_Log_Level__c</fullName>
    <defaultValue>&quot;All&quot;</defaultValue>
    <description>Transaction log levels accepted - None, All, Errors</description>
    <inlineHelpText>Transaction log levels accepted - None, All, Errors</inlineHelpText>
    <label>Transaction Log Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Veeva_Network__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows Veeva Network connection (Send/Retrieve DCRs, Sync, Search...)</description>
    <inlineHelpText>Allows Veeva Network connection</inlineHelpText>
    <label>Veeva Network</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/classes/PJN_TestFactoryGlobalSetting.cls
/**
 * @author      Mavens
 * @date        March 2019
 * @description Class to provide factory methods to create test custom metadata for GlocalSettings
 * @group       TestFactory
 */
@isTest(isParallel=true) public class PJN_TestFactoryGlobalSetting {
    public static void setMock() {
        setMock(null);
    }

    public static void setMock(Map<String, Object> fieldValues) {
        PJN_Global_Setting__mdt setting = new PJN_Global_Setting__mdt(
            MasterLabel = 'Global Setting',
            DeveloperName = 'PJN_Global_Setting',
            PJN_Account_Search_Handler_Classes__c = 'PJN_AccountSearchHdlr',
            PJN_Account_Search_Max_Results__c = 200,
            PJN_Enable_Event_Automation__c = true,
            PJN_Create_DCR__c = true,
            PJN_Network_API_Version__c = PJN_NetworkConstants.NETWORK_API_VERSION,
            PJN_Network_Named_Credential__c = PJN_NetworkConstants.NETWORK_NAMED_CREDENTIAL,
            PJN_Network_System__c = PJN_NetworkConstants.NETWORK_SYSTEM,
            PJN_Transaction_Log_Level__c = 'All',
            PJN_Veeva_Network__c = true,
            PJN_Contact_Info_Address_Record_Types__c = 'PJN_Address',
            PJN_Contact_Info_Email_Record_Types__c = 'PJN_Email',
            PJN_Contact_Info_Phone_Record_Types__c = 'PJN_Phone',
            PJN_Contact_Info_Fax_Record_Types__c = 'PJN_Fax'
        );

        if(fieldValues != null) {
            for(String field : fieldValues.keySet()) {
                setting.put(field, fieldValues.get(field));
            }
        }

        PJN_Utilities.globalSettingMock = setting;
    }
}