force-app/main/default/src/objects/PJN_Global_Setting__mdt/PJN_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search
Purpose: Definition of handler class used for the Account Search and the number max of results to be displayed. Global setting for all Programs; change only the max results field.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Global Setting</label>
    <pluralLabel>Global Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_API_Version__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_API_Version__c</fullName>
    <defaultValue>&quot;v19.0&quot;</defaultValue>
    <description>Veeva Network API version.</description>
    <label>Network API Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Named_Credential__c</fullName>
    <defaultValue>&quot;PJN_Veeva_Network&quot;</defaultValue>
    <description>Named credential used to connect with Veeva Network.</description>
    <inlineHelpText>Named credential used to connect with Veeva Network.</inlineHelpText>
    <label>Network Named Credential</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkCalloutSettings.cls
/**
 * Settings to make a callout to Veeva Network
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_NetworkCalloutSettings {
    /**
     * Veeva Network method endpoint
     */
    private String endpoint;

    /**
     * HTTP Method for current endpoint
     */
    private String httpMethod;

    /**
     * Content type for method body
     */
    private String contentType;

    /**
     * Veeva Network callout settings constructor
     * @param endpoint      Method endpoint
     * @param httpMethod    HTTP method
     * @param contentType   Body content type
     */
    public PJN_NetworkCalloutSettings(String endpoint, String httpMethod, String contentType) {
        this.endpoint = endpoint;
        this.httpMethod = httpMethod;
        this.contentType = contentType;
    }

    /**
     * Get HTTP request with network settings and body
     * @param body  HTTP Request body to send into Veeva Network
     * @returns `HttpRequest`
     */
    public HttpRequest getRequest(String body) {
        HttpRequest req = new HttpRequest();
        if(String.isNotBlank(body)) {
            req.setBody(body);
        }
        PJN_Global_Setting__mdt pjnSetting = PJN_Utilities.globalSetting;
        String networkNamedCredential = pjnSetting != null ? pjnSetting.PJN_Network_Named_Credential__c : PJN_NetworkConstants.NETWORK_NAMED_CREDENTIAL;
        String networkAPIVersion = pjnSetting != null ? pjnSetting.PJN_Network_API_Version__c : PJN_NetworkConstants.NETWORK_API_VERSION;
        String thisEndpoint = 'callout:' + networkNamedCredential + '/api/' + networkAPIVersion + endpoint;
        req.setEndpoint(thisEndpoint);
        req.setMethod(httpMethod);
        req.setTimeout(5000);
        req.setHeader('Accept', 'application/json');

        if(String.IsNotBlank(contentType)) {
            req.setHeader('Content-Type', contentType);
        }

        return req;
    }
}