force-app/main/default/src/objects/PJN_Fulfillment_Request_Creation__mdt/PJN_Fulfillment_Request_Creation__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Fulfillment Request Creation
Purpose: Defines the fields that will be pre-populated when a fulfillment request is created.
Metadata Relationship(s): Program
Created by Mavens: Yes</description>
    <label>Fulfillment Request Creation</label>
    <pluralLabel>Fulfillment Requests Creation</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request_Creation__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Fulfillment Requests Creation</relationshipLabel>
    <relationshipName>PJN_Fulfillment_Requests_Creation</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request_Creation__mdt/fields/PJN_Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Type_Developer_Name__c</fullName>
    <label>Record Type Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_FulfillmentRequestCreateMock.cls
@isTest(isParallel=true) public with sharing class PJN_FulfillmentRequestCreateMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if(stubbedMethodName == 'queryByProgramDeveloperNameAndRecordTypeDeveloperName') {
            return this.queryByProgramDeveloperNameAndRecordTypeDeveloperName((String) listOfArgs[0], (String) listOfArgs[1]);
        } else {
            return null;
        }
    }

    private Object queryByProgramDeveloperNameAndRecordTypeDeveloperName(String programDeveloperName, String recordTypeDeveloperName) {
        if(programDeveloperName == 'PJN_NO_MAPPING') {
            return new List<PJN_Fulfillment_Request_Creation__mdt>();
        } else {
            return new List<PJN_Fulfillment_Request_Creation__mdt> {
                new PJN_Fulfillment_Request_Creation__mdt(
                    MasterLabel = 'Mocked Fulfillment Request Creation',
                    DeveloperName = 'PJN_Mocked_Fulfillment_Request_Creation',
                    PJN_Program__r = new PJN_Program__mdt(
                        MasterLabel = 'Mocked Program',
                        DeveloperName = programDeveloperName
                    ),
                    PJN_Care_Plan_Source_Field_API_Name__c = 'Id',
                    PJN_Request_Target_Field_API_Name__c = 'PJN_Care_Plan__c',
                    PJN_Record_Type_Developer_Name__c = recordTypeDeveloperName
                )
            };
        }
    }
}