force-app/main/default/src/objects/Activity/fields/PJN_Outcome__c.field-meta.xml
<CustomField>
    <fullName>PJN_Outcome__c</fullName>
    <description>Picklist to identify the outcome of the contact attempt.</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call Completed</fullName>
            </value>
            <value>
                <fullName>Call Started</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>Left Voicemail</fullName>
            </value>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>Not a good time</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Sent Email</fullName>
            </value>
            <value>
                <fullName>Sent Text</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>MVN_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>myRARE team member focused on all aspects of benefits investigation, verification, and support related to pharmacy, medical, and buy/bill claims.</description>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Copay_Member_ID__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Member_ID__c</fullName>
    <description>Used to store the Copay Member Id from the related Assistance Program</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Member ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Activity.recordType-meta.xml
<RecordType>
    <fullName>PJN_Activity</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities related to a patient&apos;s care plan</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Member_Id__c</fullName>
    <description>The unique number a plan assigns to a member.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Member Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Eligibility_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Eligibility_Type__c</fullName>
    <label>Eligibility Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Functionally Uninsured</fullName>
            </value>
            <value>
                <fullName>Insurance Status Change</fullName>
            </value>
            <value>
                <fullName>Insured - Commercial</fullName>
            </value>
            <value>
                <fullName>Insured - Government</fullName>
            </value>
            <value>
                <fullName>Medicare Part B</fullName>
            </value>
            <value>
                <fullName>PA/Appeal Processing</fullName>
            </value>
            <value>
                <fullName>Pending PA Appeal</fullName>
            </value>
            <value>
                <fullName>Product Acquisition Delay</fullName>
            </value>
            <value>
                <fullName>Unaffordable - Medicare Advantage</fullName>
            </value>
            <value>
                <fullName>Unaffordable - Part D</fullName>
            </value>
            <value>
                <fullName>Uninsured</fullName>
            </value>
            <value>
                <fullName>Uninsured - Alternate Coverage</fullName>
            </value>
            <value>
                <fullName>Uninsured - Income Above PAP</fullName>
            </value>
            <value>
                <fullName>Uninsured - Income Below PAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Date__c</fullName>
    <description>Date the Assistance Program is effective from.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Outcome__c.field-meta.xml
<CustomField>
    <fullName>PJN_Outcome__c</fullName>
    <description>The outcome of the application to enroll into an Assistance Program.</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/recordTypes/PJN_Patient_Assistance_Program.recordType-meta.xml
<RecordType>
    <fullName>PJN_Patient_Assistance_Program</fullName>
    <active>true</active>
    <description>An enrollment into the Patient Assistance Program.</description>
    <label>Patient Assistance Program</label>
</RecordType>

force-app/main/default/src/objects/PJN_Assistance_Program__c/recordTypes/PJN_Patient_Assistance_Program_Locked.recordType-meta.xml
<RecordType>
    <fullName>PJN_Patient_Assistance_Program_Locked</fullName>
    <active>true</active>
    <description>A Patient Assistance Program record with a read-only page layout.</description>
    <label>Patient Assistance Program Locked</label>
</RecordType>

force-app/main/default/src/classes/MVN_PapRenewalActivityBatchTest.cls
/**
 * @author      Mavens
 * @date        July 28, 2021
 * @description Unit tests for MVN_PapRenewalActivityBatch.
 */
@IsTest
private class MVN_PapRenewalActivityBatchTest {

    private static final String CRON_EXP = '0 0 0 3 9 ? ' + System.now().addYears(1).year();

    @TestSetup
    static void makeData() {
        createAssistancePrograms();
    }

    @IsTest
    static void testIfSchedulesCorrectly() {
        Test.startTest();
            // Schedule the test job
            String jobId = System.schedule('MVN_PapRenewalActivityBatch', CRON_EXP, new MVN_PapRenewalActivityBatch());

            // Get the information from the CronTrigger API object
            CronTrigger ct = [SELECT CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

            // Verify the expressions are the same
            System.assertEquals(CRON_EXP, ct.CronExpression, 'Expressions should be the same.');

            // Verify the job has not run
            System.assertEquals(0, ct.TimesTriggered, 'Times triggered should be 0. Job should not run.');

            // Verify the next time the job will run
            System.assertEquals(System.now().addYears(1).year() + '-09-03 00:00:00', String.valueOf(ct.NextFireTime), 'Dates should match.');
        Test.stopTest();
    }

    @IsTest
    static void testIfActivtiesCreated() {
        Test.startTest();
        Database.executeBatch(new MVN_PapRenewalActivityBatch());
        Test.stopTest();

        String activityRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId();
        System.assertEquals(2, [SELECT Id FROM Case WHERE RecordTypeId = :activityRecordTypeId].size(), 'Two activities should have been inserted.');

        Id userId = [SELECT Id FROM User WHERE Alias = 'Testy' LIMIT 1][0].Id;
        for (Case activity : [SELECT OwnerId FROM Case WHERE RecordTypeId = :activityRecordTypeId]) {
            System.assertEquals(userId, activity.OwnerId, 'OwnerId should match the test user.');
        }
    }


    @IsTest
    static void testShouldFailWithNonMatchingDates() {

        List<PJN_Assistance_Program__c> programs = new List<PJN_Assistance_Program__c>();
        for (PJN_Assistance_Program__c program : [SELECT PJN_Effective_Date__c FROM PJN_Assistance_Program__c]) {
            program.PJN_Effective_Date__c = Date.today();
            programs.add(program);
        }
        update programs;

        Test.startTest();
        Database.executeBatch(new MVN_PapRenewalActivityBatch());
        Test.stopTest();

        String activityRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId();
        System.assertEquals(0, [SELECT Id FROM Case WHERE RecordTypeId = :activityRecordTypeId].size(), 'No activities should have been created.');
    }

    private static void createAssistancePrograms() {

        // insert User that will be used as Owner
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1][0];
        User testUser = new User(
            LastName = 'Testerson',
            FirstName = 'Testy',
            Email = 'testerson@testcode.com',
            Username= 'testerson@testcode.com.test',
            ProfileId = adminProfile.id,
            Alias = 'testy',
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            LocalesIdKey='en_US',
            TimezonesIdKey='America/Los_Angeles',
            Street = 'Test Street',
            MobilePhone = '12345678',
            Phone = '12345678'
        );
        insert testUser;

        // insert Care Plan
        Case carePlan = new Case (
            OwnerId = testUser.Id,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Status = 'Open',
            MVN_Coordinator__c = testUser.Id
        );
        insert carePlan;

        // insert Assistance Programs
        Id recordTypeId = Schema.SObjectType.PJN_Assistance_Program__c.getRecordTypeInfosByDeveloperName().get('PJN_Patient_Assistance_Program').getRecordTypeId();
        Id lockedrecordTypeId = Schema.SObjectType.PJN_Assistance_Program__c.getRecordTypeInfosByDeveloperName().get('PJN_Patient_Assistance_Program_Locked').getRecordTypeId();
        Date effectiveDate = Date.today().addDays(-300);

        insert new List<PJN_Assistance_Program__c>{
            new PJN_Assistance_Program__c(
                MVN_Copay_Member_Id__c='9610834643', 
                MVN_Eligibility_Type__c = 'Exception',
                PJN_Care_Plan__c = carePlan.Id, 
                PJN_Effective_Date__c = effectiveDate,
                PJN_Outcome__c = 'Eligible',
                RecordTypeId = recordTypeId),
            new PJN_Assistance_Program__c(
                MVN_Copay_Member_Id__c='9137243527', 
                MVN_Eligibility_Type__c = 'Exception',
                PJN_Care_Plan__c = carePlan.Id, 
                PJN_Effective_Date__c = effectiveDate,
                PJN_Outcome__c = 'Eligible',
                RecordTypeId = lockedRecordTypeId)
        };
    }
}