force-app/main/default/src/objects/Activity/fields/PJN_Outcome__c.field-meta.xml
<CustomField>
    <fullName>PJN_Outcome__c</fullName>
    <description>Picklist to identify the outcome of the contact attempt.</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call Completed</fullName>
            </value>
            <value>
                <fullName>Call Started</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>Left Voicemail</fullName>
            </value>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>Not a good time</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Sent Email</fullName>
            </value>
            <value>
                <fullName>Sent Text</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>MVN_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>myRARE team member focused on all aspects of benefits investigation, verification, and support related to pharmacy, medical, and buy/bill claims.</description>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Status__c</fullName>
    <description>A patient&apos;s program treatment journey status. Utilizing Status Global Value Set.</description>
    <label>Therapy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Activity.recordType-meta.xml
<RecordType>
    <fullName>PJN_Activity</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities related to a patient&apos;s care plan</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Date__c</fullName>
    <description>Date insurance plan effective from.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Expiration_Date__c</fullName>
    <description>Date insurance plan effective to.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient who is a member of an insurance plan.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/PJN_Prior_Authorization__c.object-meta.xml
<CustomObject>
    <description>Custom object to track prior authorizations related to member plans.</description>
    <label>Prior Authorization</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Prior Authorization Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan the parent member plan belongs to.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Date__c</fullName>
    <description>Date the prior authorization goes into effect.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Expiration_Date__c</fullName>
    <description>Date the prior authorization expires.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <description>Master detail relationship with Member Plan.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Outcome__c.field-meta.xml
<CustomField>
    <fullName>PJN_Outcome__c</fullName>
    <description>Prior authorization outcome.</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Complete</fullName>
        <isActive>false</isActive>
        <label>Treatment Complete</label>
    </customValue>
    <customValue>
        <fullName>On Therapy</fullName>
        <isActive>false</isActive>
        <label>On Therapy</label>
    </customValue>
    <description>Status field picklist value set, used for Therapy Status fields. 

Pending: Status assigned to a patient&apos;s care plan confirming they are going through the program enrollment process (new or restart patient).

On Therapy: Status assigned to a patient&apos;s care plan confirming they are fully approved for dispense and awaiting/currently receiving shipments.

Treatment Complete: Status assigned to a patient&apos;s care plan confirming they have completed their treatment journey.

Discontinued: Status assigned to a patient&apos;s care plan confirming they have previously enrolled in a program, but have either chosen or have been deemed ineligible to continue. 

Cancelled: Status assigned to a patient&apos;s care plan confirming they have either chosen not to continue with enrollment, or have been deemed ineligible to continue.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/MVN_PaReauthActivityBatchTest.cls
/**
 * @author      Mavens
 * @date        July 28, 2021
 * @description Unit tests for MVN_PaReauthActivityBatch.
 */
@IsTest
private class MVN_PaReauthActivityBatchTest {

    private static final String CRON_EXP = '0 0 0 3 9 ? ' + System.now().addYears(1).year();

    @TestSetup
    static void makeData() {
        createData();
    }

    @IsTest
    static void testIfSchedulesCorrectly() {
        Test.startTest();
            // Schedule the test job
            String jobId = System.schedule('MVN_PaReauthActivityBatch', CRON_EXP, new MVN_PaReauthActivityBatch());

            // Get the information from the CronTrigger API object
            CronTrigger ct = [SELECT CronExpression, NextFireTime, TimesTriggered FROM CronTrigger WHERE id = :jobId];

            // Verify the expressions are the same
            System.assertEquals(CRON_EXP, ct.CronExpression, 'Expressions should be the same.');

            // Verify the job has not run
            System.assertEquals(0, ct.TimesTriggered, 'Times triggered should be 0');

            // Verify the next time the job will run
            System.assertEquals(System.now().addYears(1).year() + '-09-03 00:00:00', String.valueOf(ct.NextFireTime), 'Dates should match');
        Test.stopTest();
    }

    @IsTest
    static void testIfActivtiesCreated() {
        Test.startTest();
        Database.executeBatch(new MVN_PaReauthActivityBatch());
        Test.stopTest();

        String activityRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId();
        System.assertEquals(2, [SELECT Id FROM Case WHERE RecordTypeId = :activityRecordTypeId].size(), 'Two activities should have been inserted.');

        Id ownerId = [SELECT Id FROM User WHERE Alias = 'owner' LIMIT 1][0].Id;
        Id coordinatorId = [SELECT Id FROM User WHERE Alias = 'coord' LIMIT 1][0].Id;
        System.assertEquals(1, [SELECT Id FROM Case WHERE OwnerId = :ownerId AND RecordTypeId = :activityRecordTypeId].size(), 'One activity should have been inserted with OwnerId matching the OwnerId from CarePlans.');
        System.assertEquals(1, [SELECT Id FROM Case WHERE OwnerId = :coordinatorId AND RecordTypeId = :activityRecordTypeId].size(), 'One activity should have been inserted with OwnerId matching the MVN_Coordinator__c from CarePlans.');
    }

    @IsTest
    static void testShouldFailWithNonMatchingDates() {

        List<PJN_Prior_Authorization__c> priorAuths = new List<PJN_Prior_Authorization__c>();
        for (PJN_Prior_Authorization__c priorAuth : [SELECT PJN_Effective_Date__c FROM PJN_Prior_Authorization__c]) {
            priorAuth.PJN_Expiration_Date__c = Date.today();
            priorAuths.add(priorAuth);
        }
        update priorAuths;

        Test.startTest();
        Database.executeBatch(new MVN_PaReauthActivityBatch());
        Test.stopTest();

        String activityRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId();
        System.assertEquals(0, [SELECT Id FROM Case WHERE RecordTypeId = :activityRecordTypeId].size(), 'No activities should have been created.');
    }

    private static void createData() {

        // profile for our users, just using admin to avoid any unforeseen permission issues
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1][0];

        // build User that will be used as OwnerId
        User ownerUser = buildUser('Owner', adminProfile.Id);

        // build User that will be used as Coordinator
        User coordinatorUser = buildUser('Coordinator', adminProfile.Id);

        // insert users
        insert new List<User>{coordinatorUser, ownerUser};

        // insert test account
        Account acct = new Account(
            FirstName = 'Test',
            LastName = 'Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId()
        );
        insert acct;

        // create careplan with coordinator
        Case carePlan0 = new Case (
            AccountId = acct.Id,
            OwnerId = ownerUser.Id,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Status = 'Open',
            MVN_Coordinator__c = coordinatorUser.Id,
            PJN_Therapy_Status__c = 'Active'
        );

        // create careplan without coordinator
        Case carePlan1 = new Case (
            AccountId = acct.Id,
            OwnerId = ownerUser.Id,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Status = 'Open',
            PJN_Therapy_Status__c = 'Active'
        );

        // insert careplans
        insert new List<Case>{carePlan0,carePlan1};

        // create member plan that associates with carePlan0
        PJN_Member_Plan__c plan0 = new PJN_Member_Plan__c(
            PJN_Patient__c = acct.Id,
            PJN_Care_Plan__c = carePlan0.Id
        );

        // create member plan that associates with carePlan1
        PJN_Member_Plan__c plan1 = new PJN_Member_Plan__c(
            PJN_Patient__c = acct.Id,
            PJN_Care_Plan__c = carePlan1.Id
        );

        // insert member plans
        insert new List<PJN_Member_Plan__c>{plan0, plan1};

        // create dates
        Date effectiveDate = Date.today().addDays(-30);
        Date expirationDate = Date.today().addDays(35);

        // finally, we insert the Prior Auth records
        insert new List<PJN_Prior_Authorization__c>{
            new PJN_Prior_Authorization__c(
                PJN_Care_Plan__c = carePlan0.Id,
                PJN_Effective_Date__c = effectiveDate,
                PJN_Expiration_Date__c = expirationDate,
                PJN_Member_Plan__c = plan0.Id,
                PJN_Outcome__c = 'Approved'
            ),
            new PJN_Prior_Authorization__c(
                PJN_Care_Plan__c = carePlan1.Id,
                PJN_Effective_Date__c = effectiveDate,
                PJN_Expiration_Date__c = expirationDate,
                PJN_Member_Plan__c = plan1.Id,
                PJN_Outcome__c = 'Approved'
            )
        };
    }

    private static User buildUser(String name, Id profileId) {
        return new User(
            FirstName = 'Testy',
            LastName = name,
            Email = name.toLowerCase() + '@testcode.com',
            Username = name.toLowerCase() + 'coordinator@testcode.com.test',
            ProfileId = profileId,
            Alias = name.toLowerCase().substring(0, 5),
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            LocalesIdKey='en_US',
            TimezonesIdKey='America/Los_Angeles',
            Street = 'Test Street',
            MobilePhone = '12345678',
            Phone = '12345678'
        );
    }
}