force-app/main/default/src/objects/PJN_Care_Plan_Timeline_Case__mdt/PJN_Care_Plan_Timeline_Case__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Care Plan Timeline
Purpose: Define status and icon for cases to be displayed on the care plan activity timeline sidebar.
Metadata Relationship(s): Program, Care Plan Timeline Case Field
Created by Mavens: Yes</description>
    <label>Care Plan Timeline Case</label>
    <pluralLabel>Care Plan Timeline Cases</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Care_Plan_Timeline_Case__mdt/fields/PJN_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Activity_Type__c</fullName>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>closed</fullName>
                <default>true</default>
                <label>closed</label>
            </value>
            <value>
                <fullName>open</fullName>
            </value>
            <value>
                <fullName>planned</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Timeline_Case__mdt/fields/PJN_Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Icon_Name__c</fullName>
    <label>Icon Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Timeline_Case__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Care Plan Timeline Cases</relationshipLabel>
    <relationshipName>PJN_Care_Plan_Timeline_Cases</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_CarePlanTimelineCaseMock.cls
@isTest(isParallel=true) public with sharing class PJN_CarePlanTimelineCaseMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if(stubbedMethodName == 'queryByProgramAndActivityType') {
            return this.queryByProgramAndActivityType((String) listOfArgs[0], (String) listOfArgs[1]);
        } else {
            return null;
        }
    }

    private Object queryByProgramAndActivityType(String programDeveloperName, String activityType) {
        return new PJN_Care_Plan_Timeline_Case__mdt(
            MasterLabel = 'Mocked Timeline',
                DeveloperName = 'PJN_Mocked_Timeline',
                PJN_Program__r = new PJN_Program__mdt(
                    MasterLabel = 'Mocked Program',
                    DeveloperName = programDeveloperName
                ),
                PJN_Activity_Type__c = activityType,
                PJN_Icon_Name__c = 'standard:default'
        );
    }
}