force-app/main/default/src/objects/PJN_Medical_History__c/PJN_Medical_History__c.object-meta.xml
<CustomObject>
    <description>Holds details of a patient&apos;s medical history, for example allergies, medications or lab test results.</description>
    <label>Medical History</label>
    <nameField>
        <displayFormat>MH-{00000}</displayFormat>
        <label>Medical History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Medical_History__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the medical history is recorded.</description>
    <label>Care Plan</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The medical history must be related to a Care Plan.</errorMessage>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CarePlan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Medical History</relationshipLabel>
    <relationshipName>PJN_Medical_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Medical_History__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patien for which the medical history is recorded.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Medical history must be related to a Patient account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medical History</relationshipLabel>
    <relationshipName>PJN_Medical_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Medical_History__c/recordTypes/PJN_Allergy.recordType-meta.xml
<RecordType>
    <fullName>PJN_Allergy</fullName>
    <active>true</active>
    <description>Current or historic allergies or intolerances which have affected the patient.</description>
    <label>Allergy/Intolerance</label>
</RecordType>

force-app/main/default/src/objects/PJN_Medical_History__c/recordTypes/PJN_Metric.recordType-meta.xml
<RecordType>
    <fullName>PJN_Metric</fullName>
    <active>true</active>
    <description>Capture a biometric data point</description>
    <label>Metric</label>
</RecordType>

force-app/main/default/src/classes/PJN_MedicalHistoryCtrlTest.cls
/*
 * @description Unit tests for PJN_MedicalHistoryCtrl
 * @author      Mavens
 * @Created     October 2019
 */

@isTest
public class PJN_MedicalHistoryCtrlTest {

    private static final Id PATIENT_RECORDTYPE_ID = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId();
    private static final Id CAREPLAN_RECORDTYPE_ID = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId();

    private static Id MEDICAL_RECORDTYPE_ID_1 = SObjectType.PJN_Medical_History__c.getRecordTypeInfosByDeveloperName().get('PJN_Metric').getRecordTypeId();
    private static Id MEDICAL_RECORDTYPE_ID_2 = SObjectType.PJN_Medical_History__c.getRecordTypeInfosByDeveloperName().get('PJN_Allergy').getRecordTypeId();

    @TestSetup
    static void makeData(){
        Account patient = new Account(
            RecordTypeId = PATIENT_RECORDTYPE_ID,
            LastName = 'Patient'
        );
        insert patient;

        createCarePlanAndMedicalHistory(patient.Id);
    }

    private static Case createCarePlanAndMedicalHistory(Id patientId) {
        Case carePlan = new Case(
            AccountId = patientId,
            RecordTypeId = CAREPLAN_RECORDTYPE_ID
        );
        insert carePlan;

        List<PJN_Medical_History__c> medHistory = new List<PJN_Medical_History__c>();

        for (Integer i=0; i<10; i++) {
            medHistory.add(
                new PJN_Medical_History__c(
                    PJN_Patient__c = patientId,
                    PJN_Care_Plan__c = carePlan.Id,
                    RecordTypeId = MEDICAL_RECORDTYPE_ID_1
                )
            );
        }
        medHistory.add(
            new PJN_Medical_History__c(
                PJN_Patient__c = patientId,
                PJN_Care_Plan__c = carePlan.Id,
                RecordTypeId = MEDICAL_RECORDTYPE_ID_2
            )
        );

        insert medHistory;

        return carePlan;
    }

    @isTest
    private static void itShouldReturnCurrentMedicalHistoryRecordsForARecordType() {
        Case carePlan = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        System.assertEquals(10, PJN_MedicalHistoryCtrl.getMedicalHistory(carePlan.Id, MEDICAL_RECORDTYPE_ID_1, false).size());
        Test.stopTest();
    }


    @isTest
    private static void itShouldReturnAllMedicalHistoryRecordsForARecordType() {
        Case carePlan = [SELECT Id, AccountId FROM Case LIMIT 1];

        carePlan = createCarePlanAndMedicalHistory(carePlan.AccountId);

        Test.startTest();
        System.assertEquals(20, PJN_MedicalHistoryCtrl.getMedicalHistory(carePlan.Id, MEDICAL_RECORDTYPE_ID_1, true).size());
        Test.stopTest();
    }

    @isTest
    private static void itShouldReturnTheMetricRecordTypeId() {
        Id expectedRecordTypeId = SObjectType.PJN_Medical_History__c
            .getRecordTypeInfosByDeveloperName()
            .get('PJN_Metric')
            .getRecordTypeId();

        System.assertEquals(expectedRecordTypeId, PJN_MedicalHistoryCtrl.getMetricRecTypeId());
    }
}