force-app/main/default/src/objects/PJN_Channel_Consent__c/PJN_Channel_Consent__c.object-meta.xml
<CustomObject>
    <description>Object to track patient consent preferences per contact channel.</description>
    <label>Channel Consent</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Channel Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Consent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/Pending_Consent_Status_Batch_MVN__c.field-meta.xml
<CustomField>
    <fullName>Pending_Consent_Status_Batch_MVN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether ChannelConsentStatusBatchMVN should process the channel consent. Set to true when the API can not be called immediately</description>
    <inlineHelpText>Whether ChannelConsentStatusBatchMVN should process the channel consent. Set to true when the API can not be called immediately</inlineHelpText>
    <label>Pending Consent Status Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <description>Lookup(Contact Information), data points of contact.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Channel Consent</relationshipLabel>
    <relationshipName>PJN_Channel_Consent</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Privacy_Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Privacy_Consent_Status__c</fullName>
    <description>Whether the individual associated with this record agrees to this form of contact.</description>
    <label>Privacy Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
            </value>
            <value>
                <fullName>Not Given</fullName>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/classes/ChannelConsentStatusBatchMVN.cls
/**
 * @author Mavens
 * @date Jul 20, 2020
 * @description Batch process to update Marketing Cloud using Channel Consent
 */
@SuppressWarnings('PMD.AvoidGlobalModifier')
global class ChannelConsentStatusBatchMVN implements
    Database.Batchable<sObject>,
    Database.Stateful,
    Database.AllowsCallouts,
    Schedulable
{
    private List<Exception> errors = new List<Exception>();

    public void execute(SchedulableContext sc) {
        ChannelConsentStatusBatchMVN channelConsentStatusBatch = new ChannelConsentStatusBatchMVN();
        database.executebatch(channelConsentStatusBatch, 50);
    }

    global ChannelConsentStatusBatchMVN() {} // NOPMD 

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            ' SELECT PJN_Contact_Information__c, ' +
            '        PJN_Privacy_Consent_Status__c, ' +
            '        Pending_Consent_Status_Batch_MVN__c ' +
            '   FROM PJN_Channel_Consent__c ' +
            '  WHERE Pending_Consent_Status_Batch_MVN__c = true'
        );
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        try {
            List<PJN_Channel_Consent__c> channelConsents = (List<PJN_Channel_Consent__c>) scope;
            new MarketingCloudSubscriberUpdateMVN().updateMarketingCloudSubscriberStatus(channelConsents);
        } catch (Exception ex) {
            errors.add(ex);
        }
    }

    global void finish(Database.BatchableContext bc) {
        if(!errors.isEmpty()) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Errors occurred during Marketing Cloud Subscriber Update process.');
            mail.setTargetObjectId(UserInfo.getUserId());
            mail.setSaveAsActivity(false);
            String body = 'Errors \n';
            for(Exception e : errors) {
                body += '-' + e.getMessage() + '<br>';
                body += e.getStackTraceString() + '<br>';
            }
            mail.setPlainTextBody(body);
            Messaging.sendEmail(new Messaging.Email[] { mail });
        }
    }

    global static void start() {
        System.schedule('Marketing Cloud API job (ChannelConsentStatusBatchMVN) at top of hour', '0 0 * * * ?', new ChannelConsentStatusBatchMVN());
        System.schedule('Marketing Cloud API job (ChannelConsentStatusBatchMVN) at 15 minutes', '0 15 * * * ?', new ChannelConsentStatusBatchMVN());
        System.schedule('Marketing Cloud API job (ChannelConsentStatusBatchMVN) at 30 minutes', '0 30 * * * ?', new ChannelConsentStatusBatchMVN());
        System.schedule('Marketing Cloud API job (ChannelConsentStatusBatchMVN) at 45 minutes', '0 45 * * * ?', new ChannelConsentStatusBatchMVN());
    }
}