force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/PJN_CRM_Connection_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Connection settings for Patient Journey Navigator CRM integrations.</description>
    <label>CRM Connection Setting</label>
    <pluralLabel>CRM Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection setting active?</description>
    <inlineHelpText>Is this connection setting active? If it&apos;s not active it will not run.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Trigger_Field__c.field-meta.xml
<CustomField>
    <fullName>PJN_Trigger_Field__c</fullName>
    <description>The field that needs to be true for the trigger to perform transactions with the corresponding CRM.</description>
    <inlineHelpText>The field that needs to be true for the trigger to perform transactions with the corresponding CRM.</inlineHelpText>
    <label>Trigger Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/classes/PJN_EventToCRMHdlr.cls
/**
 * @author Mavens
 * @date Oct 2020
 * @description This trigger facilitates enrollment processed in PJN to create "Enrollment" record in Veeva CRM.
 * @group event-triggers
 */
public without sharing class PJN_EventToCRMHdlr implements PJN_TriggerDispatcher.HandlerInterface {

    @testVisible private static PJN_CRMConnectionSettingQuery crmConnectionSettingQuery = new PJN_CRMConnectionSettingQuery();

    /**
     * Handle the trigger call
     */
    public void handle() {
        for (PJN_CRM_Connection_Setting__mdt connectionSetting : crmConnectionSettingQuery.queryBySettingByType('Enrollment')) {
            ConnectionWrapper wrapper  = new ConnectionWrapper(connectionSetting);
            for (SObject newEvent : Trigger.new) {
                if ((Test.isRunningTest() && connectionSetting.PJN_Trigger_Field__c != NULL && (Boolean) newEvent.get(connectionSetting.PJN_Trigger_Field__c)) || (connectionSetting.PJN_Trigger_Field__c != NULL && (Boolean) newEvent.get(connectionSetting.PJN_Trigger_Field__c) && connectionSetting.PJN_Active__c)) {
                    wrapper.addEvent((PJN_Event__c) newEvent);
                }
            }
            System.debug('wrapper: ' + wrapper);
            if(!wrapper.eventMap.isEmpty()) {
                System.enqueueJob(new PJN_EventToCRMQueueable(JSON.serialize(wrapper)));
            }
        }
    }

    public class ConnectionWrapper {
        public PJN_CRM_Connection_Setting__mdt connectionSetting;
        public Map<Id, PJN_Event__c> eventMap;

        public ConnectionWrapper(PJN_CRM_Connection_Setting__mdt connectionSetting) {
            this.connectionSetting = connectionSetting;
            this.eventMap = new Map<Id, PJN_Event__c>();
        }

        public void addEvent(PJN_Event__c event) {
            eventMap.put(event.Id, event);
        }
    }
}