force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/PJN_CRM_Connection_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Connection settings for Patient Journey Navigator CRM integrations.</description>
    <label>CRM Connection Setting</label>
    <pluralLabel>CRM Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection setting active?</description>
    <inlineHelpText>Is this connection setting active? If it&apos;s not active it will not run.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Does this connection apply to Case Escalation, Enrollments, or Case Sync transactions?</description>
    <inlineHelpText>Does this connection apply to Case Escalation, Enrollments, or Case Sync transactions?</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Escalation</fullName>
                <default>true</default>
                <label>Case Escalation</label>
            </value>
            <value>
                <fullName>Enrollment</fullName>
            </value>
            <value>
                <fullName>Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_CRMConnectionSettingQueryTest.cls
/**
 * @author Mavens
 * @description Unit tests for PJN_CRMConnectionSettingQuery
 */
@isTest(isParallel=true) public with sharing class PJN_CRMConnectionSettingQueryTest {
    @isTest private static void queryBySettingByTypeTest() {
        PJN_CRMConnectionSettingQuery crmConnectionSettingQuery = new PJN_CRMConnectionSettingQuery();

        Test.startTest();
            List<PJN_CRM_Connection_Setting__mdt> crmConnectionSettings = crmConnectionSettingQuery.queryBySettingByType('Sync');
        Test.stopTest();

        List<PJN_CRM_Connection_Setting__mdt> verifyCrmConnectionSettings = [SELECT Id FROM PJN_CRM_Connection_Setting__mdt WHERE PJN_Type__c = 'Sync' AND PJN_Active__c = TRUE];

        System.assertEquals(verifyCrmConnectionSettings.size(), crmConnectionSettings.size(), 'Query results do not match results from standard query.');
    }
}