force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/PJN_CRM_Connection_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Connection settings for Patient Journey Navigator CRM integrations.</description>
    <label>CRM Connection Setting</label>
    <pluralLabel>CRM Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection setting active?</description>
    <inlineHelpText>Is this connection setting active? If it&apos;s not active it will not run.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Case_Sync_Complete_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case_Sync_Complete_Status__c</fullName>
    <description>Status stamped when Cases are sent to PJN with a Completed status.</description>
    <inlineHelpText>Status stamped when Cases are sent to PJN with a Completed status.</inlineHelpText>
    <label>Case Sync Complete Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Case_Sync_Dismissed_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case_Sync_Dismissed_Status__c</fullName>
    <description>Status stamped when Cases are sent to PJN with a Dismissed status.</description>
    <inlineHelpText>Status stamped when Cases are sent to PJN with a Dismissed status.</inlineHelpText>
    <label>Case Sync Dismissed Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_CRM_Connection_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_CRM_Connection_Class__c</fullName>
    <description>Class being used to connect to the CRM.</description>
    <inlineHelpText>Class being used to connect to the CRM.</inlineHelpText>
    <label>CRM Connection Class</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>PJN_Named_Credential__c</fullName>
    <description>Named credential used to establish the connection to the external CRM.</description>
    <label>Named Credential</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Trigger_Field__c.field-meta.xml
<CustomField>
    <fullName>PJN_Trigger_Field__c</fullName>
    <description>The field that needs to be true for the trigger to perform transactions with the corresponding CRM.</description>
    <inlineHelpText>The field that needs to be true for the trigger to perform transactions with the corresponding CRM.</inlineHelpText>
    <label>Trigger Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Does this connection apply to Case Escalation, Enrollments, or Case Sync transactions?</description>
    <inlineHelpText>Does this connection apply to Case Escalation, Enrollments, or Case Sync transactions?</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Escalation</fullName>
                <default>true</default>
                <label>Case Escalation</label>
            </value>
            <value>
                <fullName>Enrollment</fullName>
            </value>
            <value>
                <fullName>Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_CRMConnectionSettingQuery.cls
/**
 * @author      Mavens
 * @description class to query CRM Connection Settings
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class PJN_CRMConnectionSettingQuery {
    /**
     * query all
     * @param String PJN_Type to filter by.
     * @returns List<PJN_CRM_Connection_Setting__mdt>
     */
    public List<PJN_CRM_Connection_Setting__mdt> queryBySettingByType(String type) {
        System.debug('Querying PJN_CRM_Connection_Setting__mdt');
        return [SELECT PJN_Active__c,
                       PJN_CRM_Connection_Class__c,
                       PJN_Named_Credential__c,
                       PJN_Trigger_Field__c,
                       PJN_Case_Sync_Dismissed_Status__c,
                       PJN_Case_Sync_Complete_Status__c
                  FROM PJN_CRM_Connection_Setting__mdt
                 WHERE PJN_Type__c = :type
                   AND PJN_Active__c = TRUE];
    }
}