force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/HealthCloudGA__EhrMedicationPrescription__c.object-meta.xml
<CustomObject>
    <description>An order for both supply of the medication and the instructions for administration of the medicine to a patient.</description>
    <label>EHR Medication Prescription</label>
    <nameField>
        <displayFormat>Pres-{0}</displayFormat>
        <label>EHR Medication Prescription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Medication Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/fields/HealthCloudGA__DispenseMedicationCode__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__DispenseMedicationCode__c</fullName>
    <description>Code that identify this medication</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Code that identify this medication</inlineHelpText>
    <label>Dispense Medication Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>EHR_Medication_Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Expiration_Date__c</fullName>
    <description>Date insurance plan effective to.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient who is a member of an insurance plan.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Merge_Tool_Setting__mdt/PJN_Merge_Tool_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Merge Tool
Purpose: Defines the child records that will be displayed and merged as part of the Patient Merge Tool.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Merge Tool Setting</label>
    <pluralLabel>Merge Tool Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Merge_Tool_Setting__mdt/fields/PJN_Child_SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Child_SObject_API_Name__c</fullName>
    <description>API Name of the care plan child object.</description>
    <inlineHelpText>API Name of the care plan child object</inlineHelpText>
    <label>Child SObject API Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Merge_Tool_Setting__mdt/fields/PJN_Field_API_Name_to_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name_to_Account__c</fullName>
    <description>API Name of the field that defines the relationship with the account.</description>
    <inlineHelpText>API Name of the field that defines the relationship with the account.</inlineHelpText>
    <label>Field API Name to Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Merge_Tool_Setting__mdt/fields/PJN_Field_API_Name_To_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name_To_Care_Plan__c</fullName>
    <description>API Name of the field that defines the relationship with the care plan.</description>
    <inlineHelpText>API Name of the field that defines the relationship with the care plan.</inlineHelpText>
    <label>Field API Name To Care Plan</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Merge_Tool_Setting__mdt/fields/PJN_Field_List__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_List__c</fullName>
    <description>List of fields to be displayed.</description>
    <inlineHelpText>List of fields to be displayed.</inlineHelpText>
    <label>Field List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_MergeToolSettingMock.cls
/**
* @author Mavens
* @date Apr 2019
* @description Mock Provider for MergeToolSetting class
* @group Mock
*/
@isTest(isParallel=true) public with sharing class PJN_MergeToolSettingMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'getAllSettings') {
            return this.getAllSettings();
        } else if (stubbedMethodName == 'getAllSettingsByObjectName'){
            return this.getAllSettingsByObjectName();
        } else {
            return null;
        }
    }

    private Object getAllSettings() {
        List<PJN_Merge_Tool_Setting__mdt> settingList = new List<PJN_Merge_Tool_Setting__mdt>();
        settingList.add(
            new PJN_Merge_Tool_Setting__mdt(
                MasterLabel = 'Prescription',
                DeveloperName = 'PJN_Prescription',
                PJN_Child_SObject_API_Name__c = 'HealthCloudGA__EhrMedicationPrescription__c',
                PJN_Field_API_Name_To_Care_Plan__c = 'PJN_Care_Plan__c',
                PJN_Field_List__c = 'Name, HealthCloudGA__DispenseMedicationCode__c',
                PJN_Order__c = 10
            )
        );
        settingList.add(
            new PJN_Merge_Tool_Setting__mdt(
                MasterLabel = 'Member Plan	',
                DeveloperName = 'PJN_Member_Plan',
                PJN_Child_SObject_API_Name__c = 'PJN_Member_Plan__c',
                PJN_Field_API_Name_To_Care_Plan__c = 'PJN_Care_Plan__c',
                PJN_Field_API_Name_To_Account__c = 'PJN_Patient__c',
                PJN_Field_List__c = 'Name, PJN_Expiration_Date__c',
                PJN_Order__c = 20
            )
        );
        return settingList;
    }

    private Object getAllSettingsByObjectName() {
        Map<String, PJN_Merge_Tool_Setting__mdt> settingMap = new Map<String, PJN_Merge_Tool_Setting__mdt>{
            'HealthCloudGA__EhrMedicationPrescription__c' => new PJN_Merge_Tool_Setting__mdt(
                                                                MasterLabel = 'Prescription',
                                                                DeveloperName = 'PJN_Prescription',
                                                                PJN_Child_SObject_API_Name__c = 'HealthCloudGA__EhrMedicationPrescription__c',
                                                                PJN_Field_API_Name_To_Care_Plan__c = 'PJN_Care_Plan__c',
                                                                PJN_Field_List__c = 'Name, HealthCloudGA__DispenseMedicationCode__c',
                                                                PJN_Order__c = 10
                                                            ),
            'PJN_Member_Plan__c' => new PJN_Merge_Tool_Setting__mdt(
                                        MasterLabel = 'Member Plan	',
                                        DeveloperName = 'PJN_Member_Plan',
                                        PJN_Child_SObject_API_Name__c = 'PJN_Member_Plan__c',
                                        PJN_Field_API_Name_To_Care_Plan__c = 'PJN_Care_Plan__c',
                                        PJN_Field_API_Name_To_Account__c = 'PJN_Patient__c',
                                        PJN_Field_List__c = 'Name, PJN_Expiration_Date__c',
                                        PJN_Order__c = 20
                                    )
        };
        return settingMap;
    }
}