force-app/main/default/src/objects/Account/recordTypes/PJN_Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>PJN_Pharmacy</fullName>
    <active>true</active>
    <description>Defines a specialty or preferred pharmacy from which patients receive product</description>
    <label>Pharmacy</label>
</RecordType>

force-app/main/default/src/objects/CareProgram/fields/PJN_Filter_Round_Robin_by_Payers__c.field-meta.xml
<CustomField>
    <fullName>PJN_Filter_Round_Robin_by_Payers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, specialty pharmacy round robin assignment will require payers to have a list of pharmacies and there must be some intersection between the program pharmacy list and the payer pharmacy list in order to assign a pharmacy.</description>
    <inlineHelpText>When selected, specialty pharmacy round robin assignment will require payers to have a list of pharmacies and there must be some intersection between the program pharmacy list and the payer pharmacy list in order to assign a pharmacy.</inlineHelpText>
    <label>Filter Round Robin by Payers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related Coverage Investigation where the follow-up Case was generated from.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Follow-Up Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Program_Specialty_Pharmacy__c/PJN_Care_Program_Specialty_Pharmacy__c.object-meta.xml
<CustomObject>
    <description>Defines the relationship between a Care Program and the Speciality Pharmacies which distribute the drug therapy.</description>
    <label>Care Program Specialty Pharmacy</label>
    <nameField>
        <displayFormat>CPSP-{00000}</displayFormat>
        <label>Care Program Specialty Pharmacy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Program Specialty Pharmacies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Care_Program_Specialty_Pharmacy__c/fields/PJN_Last_Round_Robin_Assign_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>PJN_Last_Round_Robin_Assign_Date_Time__c</fullName>
    <description>The last time this specialty pharmacy was assigned for the related program.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The last time this specialty pharmacy was assigned for the related program.</inlineHelpText>
    <label>Last Round Robin Assign Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Program_Specialty_Pharmacy__c/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <description>The Program which the Speciality Pharmacy distributes drug for.</description>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipName>Program_Specialty_Pharmacies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Program_Specialty_Pharmacy__c/fields/PJN_Specialty_Pharmacy__c.field-meta.xml
<CustomField>
    <fullName>PJN_Specialty_Pharmacy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Specialty Pharmacy which distributes drug for the Care Program.</description>
    <label>Specialty Pharmacy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select Account with the Pharmacy record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Pharmacy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Programs</relationshipLabel>
    <relationshipName>Program_Specialty_Pharmacies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>The parent Care Plan where the Coverage Investigation is run from.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Selected_Specialty_Pharmacy__c.field-meta.xml
<CustomField>
    <fullName>PJN_Selected_Specialty_Pharmacy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Specialty Pharmacy which was selected to dispense the drug.</description>
    <label>Selected Specialty Pharmacy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select Pharmacy type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Pharmacy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/PJN_Coverage_Investigation_Item__c.object-meta.xml
<CustomObject>
    <description>Patient Journey Navigator custom object which stores the join between a Coverage Investigation and the items involved such as Member Plans.</description>
    <label>Coverage Investigation Item</label>
    <nameField>
        <displayFormat>CII-{000000}</displayFormat>
        <label>Coverage Investigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <description>The parent Coverage Investigation which the items are related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Therapy_Covered__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Covered__c</fullName>
    <description>Displays the Therapy Covered value from the Member Plan.</description>
    <formula>IF( ISPICKVAL( PJN_Member_Plan__r.PJN_Therapy_Covered__c, &apos;&apos; ), 
    &quot;Pending&quot;,
    TEXT(PJN_Member_Plan__r.PJN_Therapy_Covered__c)
)</formula>
    <label>Therapy Covered?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/recordTypes/PJN_Member_Plan.recordType-meta.xml
<RecordType>
    <fullName>PJN_Member_Plan</fullName>
    <active>true</active>
    <description>A Member Plan benefit investigation item.</description>
    <label>Member Plan</label>
</RecordType>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Payer__c.field-meta.xml
<CustomField>
    <fullName>PJN_Payer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payer related to a Member Plan.</description>
    <label>Payer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesPayer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Plans (Payer)</relationshipLabel>
    <relationshipName>Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Therapy_Covered__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Covered__c</fullName>
    <description>Captures whether the Member Plan covers a patient&apos;s drug therapy.</description>
    <label>Therapy Covered?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Covered</fullName>
            </value>
            <value>
                <fullName>Covered with PA</fullName>
            </value>
            <value>
                <fullName>Not Covered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Payer_Specialty_Pharmacy__c/PJN_Payer_Specialty_Pharmacy__c.object-meta.xml
<CustomObject>
    <description>Stores the relationship between a Payer and a contracted Speciality Pharmacy.</description>
    <label>Payer Specialty Pharmacy</label>
    <nameField>
        <displayFormat>PSP-{00000}</displayFormat>
        <label>Payer Specialty Pharmacy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payer Specialty Pharmacies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Payer_Specialty_Pharmacy__c/fields/PJN_Payer__c.field-meta.xml
<CustomField>
    <fullName>PJN_Payer__c</fullName>
    <description>The parent Payer account which distributes drug via the Speciality Pharmacy.</description>
    <label>Payer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a Payer type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesPayer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specialty Pharmacies</relationshipLabel>
    <relationshipName>Payer_Specialty_Pharmacies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Payer_Specialty_Pharmacy__c/fields/PJN_Specialty_Pharmacy__c.field-meta.xml
<CustomField>
    <fullName>PJN_Specialty_Pharmacy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Specialty Pharmacy account which is contracted with the Payer.</description>
    <label>Specialty Pharmacy</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a Pharmacy type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Pharmacy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payers (Specialty Pharmacy)</relationshipLabel>
    <relationshipName>Payer_Specialty_Pharmacies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/classes/PJN_SPRoundRobinCtrlTest.cls
/**
 * @author      Mavens
 * @date        11/2020
 * @description Unit tests for PJN_SPRoundRobinCtrl
 * @group       Specialty Pharmacy
 */
@isTest
public class PJN_SPRoundRobinCtrlTest {

    @TestSetup
    static void makeData(){
        System.runAs(getRunningUser()) {
            CareProgram program = new CareProgram(
                Name = 'Test Program',
                PJN_Program_DeveloperName__c = 'PJN_CLP',
                StartDate = Date.today()
            );
            insert program;

            Map<String, RecordTypeInfo> accountRecTypes = SObjectType.Account.getRecordTypeInfosByDeveloperName();

            Id pharmacyRecTypeId = accountRecTypes.get('PJN_Pharmacy').getRecordTypeId();
            Account specialtyPharmacy1 = new Account( Name = 'Pharmacy 1', RecordTypeId = pharmacyRecTypeId, Site = 'Pharmacy 1 Site');
            Account specialtyPharmacy2 = new Account( Name = 'Pharmacy 2', RecordTypeId = pharmacyRecTypeId, Site = 'Pharmacy 2 Site');
            Account specialtyPharmacy3 = new Account( Name = 'Pharmacy 3', RecordTypeId = pharmacyRecTypeId, Site = 'Pharmacy 3 Site');

            Id payerRecTypeId = accountRecTypes.get('IndustriesPayer').getRecordTypeId();
            Account payer = new Account( Name = 'Payer', RecordTypeId = payerRecTypeId);

            insert new List<Account> {
                specialtyPharmacy1, specialtyPharmacy2, specialtyPharmacy3, payer
            };

            // create program pharmacies
            insert new List<PJN_Care_Program_Specialty_Pharmacy__c> {
                new PJN_Care_Program_Specialty_Pharmacy__c(
                    PJN_Program__c = program.Id,
                    PJN_Specialty_Pharmacy__c = specialtyPharmacy1.Id
                ),
                new PJN_Care_Program_Specialty_Pharmacy__c(
                    PJN_Program__c = program.Id,
                    PJN_Specialty_Pharmacy__c = specialtyPharmacy2.Id
                    // PJN_Last_Round_Robin_Assign_Date_Time__c = DateTime.now().addDays(-2)
                ),
                new PJN_Care_Program_Specialty_Pharmacy__c(
                    PJN_Program__c = program.Id,
                    PJN_Specialty_Pharmacy__c = specialtyPharmacy3.Id
                    // PJN_Last_Round_Robin_Assign_Date_Time__c = DateTime.now().addDays(-1)
                )
            };

            Account patient = new Account (
                LastName = 'Patient',
                RecordTypeId = accountRecTypes.get('PJN_Patient').getRecordTypeId()
            );
            insert patient;

            // create care plan for patient
            Id carePlanRecTypeId = SObjectType.Case
                .getRecordTypeInfosByDeveloperName()
                .get('CarePlan')
                .getRecordTypeId();

            Case carePlan = new Case(
                RecordTypeId = carePlanRecTypeId,
                AccountId = patient.Id,
                PJN_Program__c = program.Id
            );
            insert carePlan;

            PJN_Member_Plan__c mp = new PJN_Member_Plan__c(
                PJN_Care_Plan__c = carePlan.Id,
                PJN_Payer__c = payer.Id,
                PJN_Therapy_Covered__c = 'Covered'
            );
            insert mp;

            PJN_Coverage_Investigation__c investigation = new PJN_Coverage_Investigation__c(
                PJN_Care_Plan__c = carePlan.Id
            );
            insert investigation;

            insert new PJN_Coverage_Investigation_Item__c(
                PJN_Coverage_Investigation__c = investigation.Id,
                RecordTypeId = SObjectType.PJN_Coverage_Investigation_Item__c
                    .getRecordTypeInfosByDeveloperName()
                    .get('PJN_Member_Plan')
                    .getRecordTypeId(),
                PJN_Member_Plan__c = mp.Id
            );
        }
    }

    @isTest
    private static void itShouldAssignAPharmacyFromCareProgramPharmacies() {
        System.runAs(getRunningUser()) {
            PJN_Coverage_Investigation__c investigation = getInvestigation();
            Test.startTest();
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id);
            Test.stopTest();

            investigation = [
                SELECT PJN_Selected_Specialty_Pharmacy__r.Name
                FROM PJN_Coverage_Investigation__c
                WHERE Id = :investigation.Id
                AND PJN_Selected_Specialty_Pharmacy__c != null
                LIMIT 1
            ];

            System.assertEquals('Pharmacy 1', investigation.PJN_Selected_Specialty_Pharmacy__r.Name);
        }
    }

    @isTest
    private static void itShouldCycleThroughPharmacies() {
        System.runAs(getRunningUser()) {
            PJN_Coverage_Investigation__c investigation = getInvestigation();
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id); // "itShouldAssignAPharmacyFromCareProgramPharmacies" proves this is pharmacy 1
            Test.startTest();
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id); // try again and it should be pharmacy 2
            investigation = [
                SELECT PJN_Selected_Specialty_Pharmacy__r.Name
                FROM PJN_Coverage_Investigation__c
                WHERE Id = :investigation.Id
                AND PJN_Selected_Specialty_Pharmacy__c != null
                LIMIT 1
            ];

            System.assertEquals('Pharmacy 2', investigation.PJN_Selected_Specialty_Pharmacy__r.Name);

            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id); // try again and it should now be pharmacy 3
            investigation = [
                SELECT PJN_Selected_Specialty_Pharmacy__r.Name
                FROM PJN_Coverage_Investigation__c
                WHERE Id = :investigation.Id
                AND PJN_Selected_Specialty_Pharmacy__c != null
                LIMIT 1
            ];

            System.assertEquals('Pharmacy 3', investigation.PJN_Selected_Specialty_Pharmacy__r.Name);
            Test.stopTest();
        }
    }

    @isTest
    private static void itShouldAssignFromConfiguredPharmaciesForPayer() {
        System.runAs(getRunningUser()) {
            CareProgram program = [SELECT Id, PJN_Filter_Round_Robin_by_Payers__c FROM CareProgram LIMIT 1];
            program.PJN_Filter_Round_Robin_by_Payers__c = true;
            update program;

            List<Account> pharmacies = [SELECT Id FROM Account WHERE Site IN ('Pharmacy 2 Site', 'Pharmacy 3 Site') ORDER BY Site]; // order by name to ensure order
            Id payerRTId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesPayer').getRecordTypeId();
            Account Payer = [SELECT Id FROM Account WHERE RecordTypeId = :payerRTId LIMIT 1];

            insert new PJN_Payer_Specialty_Pharmacy__c(PJN_Payer__c = payer.id, PJN_Specialty_Pharmacy__c = pharmacies[0].Id);
            insert new PJN_Payer_Specialty_Pharmacy__c(PJN_Payer__c = payer.id, PJN_Specialty_Pharmacy__c = pharmacies[1].Id);

            Test.startTest();
            PJN_Coverage_Investigation__c investigation = [SELECT Id FROM PJN_Coverage_Investigation__c LIMIT 1];
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id);
            investigation = [
                SELECT PJN_Selected_Specialty_Pharmacy__r.Name FROM PJN_Coverage_Investigation__c WHERE Id = :investigation.Id
            ];

            System.assertEquals('Pharmacy 3', investigation.PJN_Selected_Specialty_Pharmacy__r.Name);

            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id); // try again and it should now be pharmacy 3
            investigation = [
                SELECT PJN_Selected_Specialty_Pharmacy__r.Name FROM PJN_Coverage_Investigation__c WHERE Id = :investigation.Id
            ];

            System.assertEquals('Pharmacy 2', investigation.PJN_Selected_Specialty_Pharmacy__r.Name);
            Test.stopTest();

            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id); // one more time again and it should now be pharmacy 2 again
            investigation = [
                SELECT PJN_Selected_Specialty_Pharmacy__r.Name FROM PJN_Coverage_Investigation__c WHERE Id = :investigation.Id
            ];

            System.assertEquals('Pharmacy 3', investigation.PJN_Selected_Specialty_Pharmacy__r.Name);


        }
    }

    @isTest
    private static void itShouldErrorWhenPayerNotPresentOnMemberPlan() {
        CareProgram program = [SELECT Id, PJN_Filter_Round_Robin_by_Payers__c FROM CareProgram LIMIT 1];
        program.PJN_Filter_Round_Robin_by_Payers__c = true;
        update program;

        PJN_Member_Plan__c mp = [SELECT Id,PJN_Payer__c FROM PJN_Member_Plan__c LIMIT 1];
        mp.PJN_Payer__c = null;
        update mp;

        Test.startTest();
        String errorMessage;
        try {
            PJN_Coverage_Investigation__c investigation = [SELECT Id FROM PJN_Coverage_Investigation__c LIMIT 1];
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id);
        } catch (System.AuraHandledException ex) {
            errorMessage = ex.getMessage();
        }
        Test.stopTest();

        System.assertEquals(
            errorMessage,
            'The application is unable to find a member plan coverage investigation item for this investigation that is marked as covered and has an associated payer.',
            errorMessage
        );
    }

    @isTest
    private static void itShouldErrorWhenPayerDoesNotHaveSpecialtyPharmacies() {
        CareProgram program = [SELECT Id, PJN_Filter_Round_Robin_by_Payers__c FROM CareProgram LIMIT 1];
        program.PJN_Filter_Round_Robin_by_Payers__c = true;
        update program;

        Test.startTest();
        String errorMessage;
        try {
            PJN_Coverage_Investigation__c investigation = [SELECT Id FROM PJN_Coverage_Investigation__c LIMIT 1];
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id);
        } catch (System.AuraHandledException ex) {
            errorMessage = ex.getMessage();
        }
        Test.stopTest();

        System.assert(errorMessage.contains('The payer associated with the member plan'), errorMessage);
        System.assert(errorMessage.contains('cannot be found or does not have an associated list of specialty pharmacies'), errorMessage);
    }

    @isTest
    private static void itShouldErrorWhenUnableToAssignPharmacy() {
        delete [SELECT Id FROM PJN_Care_Program_Specialty_Pharmacy__c];

        Test.startTest();
        String errorMessage;
        try {
            PJN_Coverage_Investigation__c investigation = [SELECT Id FROM PJN_Coverage_Investigation__c LIMIT 1];
            PJN_SPRoundRobinCtrl.assignSpecialtyPharmacy(investigation.Id);
        } catch (System.AuraHandledException ex) {
            errorMessage = ex.getMessage();
        }
        Test.stopTest();

        System.assert(errorMessage.contains('Unable to find a specialty pharmacy to assign to.'), errorMessage);
    }

    private static User getRunningUser() {
        try {
            return [SELECT Id FROM User WHERE Alias = 'pjnusr'];
        } catch (System.QueryException ex) {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'PJN - PS User'  LIMIT 1];
            User psUser = new User(alias = 'pjnusr', email='test@pjn.com', emailencodingkey='UTF-8',
                FirstName = 'Test', Lastname='User', languagelocalekey='en_US',  localesidkey='en_US',
                profileid = p.Id, timezonesidkey='America/Los_Angeles', isActive = true,
                username='test@pjn.com'
            );

            insert psUser;

            PermissionSet bps = [SELECT Id FROM PermissionSet WHERE Name = 'PJN_Base_Permissions'];
            insert new PermissionSetAssignment(AssigneeId = psUser.Id, PermissionSetId = bps.Id);

            PermissionSet cips = [SELECT Id FROM PermissionSet WHERE Name = 'PJN_Coverage_Investigation'];
            insert new PermissionSetAssignment(AssigneeId = psUser.Id, PermissionSetId = cips.Id);
            return psUser;
        }
    }

    private static PJN_Coverage_Investigation__c getInvestigation() {
        return [SELECT Id FROM PJN_Coverage_Investigation__c LIMIT 1];
    }

}