force-app/main/default/src/objects/Account/recordTypes/PJN_Organization.recordType-meta.xml
<RecordType>
    <fullName>PJN_Organization</fullName>
    <active>true</active>
    <description>Defines a healthcare organization where physicians and staff work</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/src/objects/PJN_Affiliation__c/PJN_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Stores the hierarchical relationship between people and organizations.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFFL-{0000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Child_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Child_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup(Account) where account is affiliated with.</description>
    <label>Child Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Staff,PJN_Physician,PJN_Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated To</relationshipLabel>
    <relationshipName>Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/PJN_Network_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Network Object Setting</label>
    <pluralLabel>Network Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_DCR_Record_Field_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Record_Field_Id__c</fullName>
    <description>Field API Name to link the record.</description>
    <inlineHelpText>Field API Name to link the record.</inlineHelpText>
    <label>DCR Record Field Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_DCR_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Record_Type_Name__c</fullName>
    <description>Record type associated to the DCR to be created.</description>
    <label>DCR Record Type Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_DCR_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Record_Types_Allowed__c</fullName>
    <description>Record type names which allows DCR creation. This names should be separate by comma. &apos;All&apos; will include every single record type.</description>
    <inlineHelpText>Record type names which allows DCR creation. This names should be separate by comma. &apos;All&apos; will include every single record type.</inlineHelpText>
    <label>SObject Record Types Allowed</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Parent_Account_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Account_Field_Name__c</fullName>
    <description>Parent Account field API name associated.</description>
    <label>Parent Account Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Search_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Search_Record_Types_Allowed__c</fullName>
    <description>Record types allowed to search in Network.</description>
    <label>Search Record Types Allowed</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Name__c</fullName>
    <description>SObject Name for the DCR.</description>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Sync_Delay__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Delay__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sync delay in minutes - No delay with value 0</description>
    <inlineHelpText>Sync delay in minutes - No delay with value 0</inlineHelpText>
    <label>Sync Delay</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Sync_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Record_Types_Allowed__c</fullName>
    <defaultValue>&quot;All&quot;</defaultValue>
    <label>Sync Record Types Allowed</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkObjectSettingsMock.cls
/**
 * Mock for PJN_NetworkObjectSettingsQuery
 * @author  Mavens
 * @group   Network
 */
@IsTest
public with sharing class PJN_NetworkObjectSettingsMock implements System.StubProvider {

    private static final String PREFIX = Schema.SObjectType.PJN_Network_Object_Setting__mdt.getKeyPrefix();

    @SuppressWarnings('PMD.ExcessiveParameterList')
    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'queryAll') {
            return this.queryAll();
        } else {
            return null;
        }
    }

    /**
     * Mock all Network Object Settings metadatas
     * @returns `List<PJN_Network_Object_Setting__mdt>`
     */
    public List<PJN_Network_Object_Setting__mdt> queryAll() {
        List<PJN_Network_Object_Setting__mdt> networkObjectSettings = new List<PJN_Network_Object_Setting__mdt>();

        networkObjectSettings.add(
            new PJN_Network_Object_Setting__mdt(
                Label = 'Account',
                PJN_SObject_Name__c = 'Account',
                PJN_DCR_Record_Type_Name__c = PJN_NetworkConstants.DCR_ACCOUNT,
                PJN_DCR_Record_Field_Id__c = 'PJN_Account__c',
                PJN_DCR_Record_Types_Allowed__c = 'All',
                PJN_Search_Record_Types_Allowed__c = 'PJN_Organization,PJN_Physician,PJN_Staff',
                PJN_Sync_Record_Types_Allowed__c = 'All',
                PJN_Sync_Delay__c = 120,
                id = PREFIX + '000000000001'
            )
        );

        networkObjectSettings.add(
            new PJN_Network_Object_Setting__mdt(
                Label = 'Address',
                PJN_SObject_Name__c = 'PJN_Contact_Information__c',
                PJN_DCR_Record_Type_Name__c = PJN_NetworkConstants.DCR_ADDRESS,
                PJN_DCR_Record_Field_Id__c = 'PJN_Contact_Information__c',
                PJN_Parent_Account_Field_Name__c = 'PJN_Account__c',
                PJN_DCR_Record_Types_Allowed__c = 'All',
                PJN_Sync_Record_Types_Allowed__c = 'All',
                PJN_Sync_Delay__c = 0,
                id = PREFIX + '000000000002'
            )
        );

        networkObjectSettings.add(
            new PJN_Network_Object_Setting__mdt(
                Label = 'License',
                PJN_SObject_Name__c = 'PJN_License__c',
                PJN_DCR_Record_Type_Name__c = PJN_NetworkConstants.DCR_LICENSE,
                PJN_DCR_Record_Field_Id__c = 'PJN_License__c',
                PJN_Parent_Account_Field_Name__c = 'PJN_Account__c',
                PJN_DCR_Record_Types_Allowed__c = 'All',
                PJN_Sync_Record_Types_Allowed__c = 'All',
                PJN_Sync_Delay__c = 0,
                id = PREFIX + '000000000003'
            )
        );

        networkObjectSettings.add(
            new PJN_Network_Object_Setting__mdt(
                Label = 'Affiliation',
                PJN_SObject_Name__c = 'PJN_Affiliation__c',
                PJN_DCR_Record_Type_Name__c = 'PJN_Affiliation',
                PJN_DCR_Record_Field_Id__c = 'PJN_Affiliation__c',
                PJN_Parent_Account_Field_Name__c = 'PJN_Child_Account__c',
                PJN_DCR_Record_Types_Allowed__c = 'none',
                PJN_Sync_Record_Types_Allowed__c = 'All',
                PJN_Sync_Delay__c = 0,
                id = PREFIX + '000000000004'
            )
        );

        return networkObjectSettings;
    }
}