force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/MVN_Program_Event__mdt/MVN_Program_Event__mdt.object-meta.xml
<CustomObject>
    <description>Maps activity and problem statuses to creation of program events. Match made on combo of object, status, program problem or program case developer name</description>
    <label>Program Event</label>
    <pluralLabel>Program_Events</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Program_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Developer_Name__c</fullName>
    <description>The developer name to reference, either Care Plan Problem developer name or Activity developer anem</description>
    <label>Program Developer Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Record_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Record_Status__c</fullName>
    <description>The status of the record to check for.</description>
    <label>Record Status</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_SObject__c.field-meta.xml
<CustomField>
    <fullName>MVN_SObject__c</fullName>
    <description>The SObject this configuration is for</description>
    <label>SObject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HealthCloudGA__CarePlanProblem__c</fullName>
                <label>Care Plan Problem</label>
            </value>
            <value>
                <fullName>Case</fullName>
                <label>Activity</label>
            </value>
            <value>
                <fullName>PJN_Fulfillment_Request__c</fullName>
                <label>Fulfillment Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Therapy_Status__c</fullName>
    <description>The status to set on the new event</description>
    <label>Therapy Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Therapy_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Therapy_Sub_Status__c</fullName>
    <description>The sub-status to set on the new event</description>
    <label>Therapy Sub-Status</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Use_Care_Plan_current_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Use_Care_Plan_current_Therapy_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked the current therapy status on the care plan will be set to the new therapy status on the event</description>
    <inlineHelpText>If checked the current therapy status on the care plan will be set to the new therapy status on the event</inlineHelpText>
    <label>Use Care Plan&apos;s current Therapy Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/classes/MVN_ProgramEventQuery.cls
/**
* @author Mavens
* @description Queries for program event records
* @group Events
*/
public with sharing class MVN_ProgramEventQuery {

    public Map<String, List<MVN_Program_Event__mdt>> forProblems() {
        return query(SObjectType.HealthCloudGA__CarePlanProblem__c.getName());
    }

    public Map<String, List<MVN_Program_Event__mdt>> forActivities() {
        return query(SObjectType.Case.getName());
    }

    public Map<String, List<MVN_Program_Event__mdt>> forFulfillmentRequests() {
        return query(SObjectType.PJN_Fulfillment_Request__c.getName());
    }

    private Map<String, List<MVN_Program_Event__mdt>> query(String sObjectName) {
        Map<String, List<MVN_Program_Event__mdt>> eventDetailsByDevName = new Map<String, List<MVN_Program_Event__mdt>>();

        List<MVN_Program_Event__mdt> eventDetailList = [
            SELECT
                MVN_Program_Developer_Name__c,
                MVN_Record_Status__c,
                MVN_SObject__c,
                MVN_Therapy_Status__c,
                MVN_Therapy_Sub_Status__c,
                MVN_Use_Care_Plan_current_Therapy_Status__c
            FROM
                MVN_Program_Event__mdt
            WHERE
                MVN_SObject__c = :sObjectName
        ];

        for (MVN_Program_Event__mdt eventDetail : eventDetailList) {
            if (!eventDetailsByDevName.containsKey(eventDetail.MVN_Program_Developer_Name__c)) {
                eventDetailsByDevName.put(
                    eventDetail.MVN_Program_Developer_Name__c,
                    new List<MVN_Program_Event__mdt>()
                );
            }
            eventDetailsByDevName.get(eventDetail.MVN_Program_Developer_Name__c).add(eventDetail);
        }

        return eventDetailsByDevName;
    }
}