force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/PJN_Program_Problem__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Define the attributes of the problems/stages that comprise a Program. Program Problems are distinct stages in the patient’s journey that are (typically) completed before moving on to the next stage.
Metadata Relationship(s): Program; Program Case
Created by Mavens: Yes</description>
    <label>Program Problem</label>
    <pluralLabel>Program Problems</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_CarePlanPathProblemActionsCtrl.cls
/**
 * @author      Mavens
 * @group       CarePlan-UI
 * @description class to kick off several care plan problem actions
 */
public without sharing class PJN_CarePlanPathProblemActionsCtrl {
    /**
     * program problem query
     */
    @testVisible private static PJN_ProgramProblemQuery programProblemQuery = new PJN_ProgramProblemQuery();

    /**
     * get program problem
     * @param   String        programProblemDeveloperName
     * @returns  Boolean
     */
    @auraEnabled public static PJN_Program_Problem__mdt getProgramProblem(String programProblemDeveloperName) {
        try {
            return programProblemQuery.queryByDeveloperName(programProblemDeveloperName);
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }

    /**
     * start care plan problem
     * @param   HealthCloudGA__CarePlanProblem__c        carePlanProblem
     * @returns  Boolean
     */
    @auraEnabled public static Boolean startCarePlanProblem(HealthCloudGA__CarePlanProblem__c carePlanProblem) {
        try {
            PJN_CarePlanWrapper carePlan = new PJN_CarePlanWrapper(carePlanProblem.HealthCloudGA__CarePlan__c);
            carePlan.startProblem(carePlanProblem.Id, true);
            return true;
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }

    /**
     * skip care plan problem
     * @param   HealthCloudGA__CarePlanProblem__c        carePlanProblem
     * @returns  Boolean
     */
    @auraEnabled public static Boolean skipCarePlanProblem(HealthCloudGA__CarePlanProblem__c carePlanProblem) {
        try {
            PJN_CarePlanWrapper carePlan = new PJN_CarePlanWrapper(carePlanProblem.HealthCloudGA__CarePlan__c);
            carePlan.skipProblem(carePlanProblem.Id, true);
            return true;
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }

    /**
     * delete care plan problem
     * @param   HealthCloudGA__CarePlanProblem__c        carePlanProblem
     * @returns  Boolean
     */
    @auraEnabled public static Boolean deleteCarePlanProblem(HealthCloudGA__CarePlanProblem__c carePlanProblem) {
        try {
            return Database.delete(carePlanProblem).isSuccess();
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }
}