force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/MVN_Program_Event__mdt/MVN_Program_Event__mdt.object-meta.xml
<CustomObject>
    <description>Maps activity and problem statuses to creation of program events. Match made on combo of object, status, program problem or program case developer name</description>
    <label>Program Event</label>
    <pluralLabel>Program_Events</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Program_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Developer_Name__c</fullName>
    <description>The developer name to reference, either Care Plan Problem developer name or Activity developer anem</description>
    <label>Program Developer Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Record_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Record_Status__c</fullName>
    <description>The status of the record to check for.</description>
    <label>Record Status</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_SObject__c.field-meta.xml
<CustomField>
    <fullName>MVN_SObject__c</fullName>
    <description>The SObject this configuration is for</description>
    <label>SObject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HealthCloudGA__CarePlanProblem__c</fullName>
                <label>Care Plan Problem</label>
            </value>
            <value>
                <fullName>Case</fullName>
                <label>Activity</label>
            </value>
            <value>
                <fullName>PJN_Fulfillment_Request__c</fullName>
                <label>Fulfillment Request</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Therapy_Status__c</fullName>
    <description>The status to set on the new event</description>
    <label>Therapy Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Program_Event__mdt/fields/MVN_Therapy_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Therapy_Sub_Status__c</fullName>
    <description>The sub-status to set on the new event</description>
    <label>Therapy Sub-Status</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_ProgramEventQueryMock.cls
/**
* @author Mavens
* @description Mocks for Program Event Query
* @group Events
*/
public with sharing class MVN_ProgramEventQueryMock implements System.StubProvider{

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {

        if (stubbedMethodName == 'forProblems') {
            return new Map<String, List<MVN_Program_Event__mdt>> {
                'PJN_RLN_Missing_Info_Stage' => new List<MVN_Program_Event__mdt>{
                    new MVN_Program_Event__mdt(
                        MVN_Program_Developer_Name__c = 'PJN_RLN_Missing_Info_Stage',
                        MVN_Record_Status__c = 'Open',
                        MVN_SObject__c = 'HealthCloudGA__CarePlanProblem__c',
                        MVN_Therapy_Status__c = 'Pending',
                        MVN_Therapy_Sub_Status__c = 'Program Initiation In Progress'
                    )
                }
            };
        }

        if (stubbedMethodName == 'forActivities') {
            return new Map<String, List<MVN_Program_Event__mdt>> {
                '' => new List<MVN_Program_Event__mdt>{}
            };
        }

        if (stubbedMethodName == 'forFulfillmentRequests') {
            return new Map<String, List<MVN_Program_Event__mdt>> {
                '' => new List<MVN_Program_Event__mdt>{}
            };
        }

        return null;
    }
}