force-app/main/default/src/objects/Case/fields/Converted_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Converted_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original consumer record whose conversion created this case.</description>
    <label>Converted Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/Record_Type_Key_MVN__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Key_MVN__c</fullName>
    <description>Namespace + RecordType DeveloperName</description>
    <formula>RecordType.NamespacePrefix + RecordType.DeveloperName</formula>
    <label>Record Type Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Effective_Months__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Months__c</fullName>
    <description>Number of months for which written opt-in consent of this type is valid.</description>
    <label>Effective Months (Written)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/HealthCloudGA__CarePlanRecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanRecordTypeName__c</fullName>
    <description>Record Type name to use for Care Plan when we convert this lead into a Patient.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Plan Record Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/HealthCloudGA__CarePlanRecordTypeNamespace__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanRecordTypeNamespace__c</fullName>
    <description>Record Type namespace to use for Care Plan when we convert this lead into a Patient.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Care Plan Record Type Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt.object-meta.xml
<CustomObject>
    <description>Maps lead fields to care plan fields based on care plan record type</description>
    <label>Lead Convert Care Plan Field Mapping</label>
    <pluralLabel>Lead Convert Care Plan Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Is_Active_MVN__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_MVN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Only map the value if the checkbox is checked</description>
    <inlineHelpText>Only map the value if the checkbox is checked</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Lead_Field_Name_MVN__c.field-meta.xml
<CustomField>
    <fullName>Lead_Field_Name_MVN__c</fullName>
    <description>Lead field name to map value from</description>
    <inlineHelpText>Lead field name to map value from</inlineHelpText>
    <label>Lead Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Text_Value_MVN__c.field-meta.xml
<CustomField>
    <fullName>Text_Value_MVN__c</fullName>
    <description>Text value to populate to the target care plan field.</description>
    <inlineHelpText>Text value to populate to the target care plan field.</inlineHelpText>
    <label>Text Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt.object-meta.xml
<CustomObject>
    <description>Maps lead record types to the types of care plan record types that should be created on conversion</description>
    <label>Lead Convert Care Plan RT Mapping</label>
    <pluralLabel>Lead Convert Care Plan RT Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/Care_Program_DeveloperName_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Program_DeveloperName_MVN__c</fullName>
    <description>Developer name corresponding to the field CareProgram.PJN_Program_DeveloperName__c.  Used to determine the care program to associate to the care plan being created on conversion.</description>
    <inlineHelpText>Developer name of the care program to associate to the care plan.</inlineHelpText>
    <label>Care Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/PJN_Channel_Consent__c.object-meta.xml
<CustomObject>
    <description>Object to track patient consent preferences per contact channel.</description>
    <label>Channel Consent</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Channel Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Consent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <description>Lookup(Contact Information), data points of contact.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Channel Consent</relationshipLabel>
    <relationshipName>PJN_Channel_Consent</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Data_Use_Purpose__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Use_Purpose__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The purpose for which consent was given to use the contact information record.</description>
    <label>Data Use Purpose</label>
    <referenceTo>DataUsePurpose</referenceTo>
    <relationshipLabel>Channel Consent</relationshipLabel>
    <relationshipName>PJN_Channel_Consent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_From__c</fullName>
    <description>Date/Time of the consent start.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_To__c</fullName>
    <description>Date/time of consent end.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Channel_Consent__c/fields/PJN_Privacy_Consent_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Privacy_Consent_Status__c</fullName>
    <description>Whether the individual associated with this record agrees to this form of contact.</description>
    <label>Privacy Consent Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opt In</fullName>
            </value>
            <value>
                <fullName>Not Given</fullName>
            </value>
            <value>
                <fullName>Opt Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/classes/PopulateCarePlanHdlrMVN.cls
/**
 * @author      Mavens
 * @group       LeadMVN
 * @description Populating Care Plan from the Lead conversion flow.
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public with sharing class PopulateCarePlanHdlrMVN {

    // List of all Care Plan Wrappers
    private static List<CarePlanWrapperMVN> wrappers;

    // record type setting to see if current careplan is eligible for marketing
    private static Map<String, Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt> recordTypeSettingMap;

    // custom metadata for populating care plan fields
    private static List<Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt> fieldMappingSettings;

    // has lead fields
    private static Boolean hasLeadFieldMappings;

    @InvocableMethod(
        label='Populate Care Plans' 
        description='Populate Care Plans based on Field Mappings in Custom Metadata.' 
        category='Lead'
    )
    public static void populateCarePlans(List<Id> carePlanIds) {

        // collect record type custom metadata
        recordTypeSettingMap = LeadConversionUtilityMVN.queryRecordTypeSettingMap();

        // build initial care plan wrappers
        Map<String, CareProgram> programMap = LeadConversionUtilityMVN.queryCareProgramMap(recordTypeSettingMap.values());
        setCarePlanWrappers(carePlanIds);

        // collect field mappings and leads and populate the care plan in the wrapper.
        processLeadToCarePlanFieldMappings();

        // collect care plans for update and update
        performDML();
    }

    /**
     * Collect leads and assign to wrappers
     */
    private static void processLeadToCarePlanFieldMappings() {

        Set<String> leadIds = getLeadIds();
        hasLeadFieldMappings = false; // set hasLeadFieldMappings to false, should only be set to true when it's found
        fieldMappingSettings = LeadConversionUtilityMVN.queryFieldMappingSettings();
        Map<Id, Lead> leadMap = getLeadMap(leadIds);

        // Take the lead and field wrappers and passes it to the wrappers to populate the wrappers.
        populateCarePlanFieldsOnWrappers(leadMap);
    }

    /**
     * Perform all updates and inserts
     */
    private static void performDML() {
        // collect records for insertion
        List<Case> carePlans = getCarePlansForUpdate();

        // updates
        update carePlans;
    }

    /**
     * Assign Data Use Purpose records to the proper variables in the wrappers.
     * @param dataUsePurposeMap 
     */
    private static void addDataUsePurposes(Map<Id, DataUsePurpose> dataUsePurposeMap) {
        for (CarePlanWrapperMVN wrapper : wrappers) {
            if (wrapper.template.HIPAA_Consent_Data_Use_Purpose_MVN__c != NULL) {
                wrapper.hipaaDUP = dataUsePurposeMap.get(wrapper.template.HIPAA_Consent_Data_Use_Purpose_MVN__c);
            }

            if (wrapper.template.Marketing_Consent_Data_Use_Purpose_MVN__c != NULL) {
                wrapper.marketingDUP = dataUsePurposeMap.get(wrapper.template.Marketing_Consent_Data_Use_Purpose_MVN__c);
            }

            if (wrapper.template.Program_Consent_Data_Use_Purpose_MVN__c != NULL) {
                wrapper.programDUP = dataUsePurposeMap.get(wrapper.template.Program_Consent_Data_Use_Purpose_MVN__c);
            }
        }
    }

    /**
     * Take the lead and field wrappers and passes it to the wrappers to populate the wrappers.
     * @param leadMap 
     */
    private static void populateCarePlanFieldsOnWrappers(Map<Id, Lead> leadMap) {
        for (CarePlanWrapperMVN wrapper : wrappers) {
            if (leadMap.containsKey(wrapper.carePlan.Converted_Lead_MVN__c)) {
                wrapper.mapCarePlanFields(leadMap.get(wrapper.carePlan.Converted_Lead_MVN__c), fieldMappingSettings);
            } else {
                wrapper.mapCarePlanFields(new Lead(), fieldMappingSettings);
            }
        }
    }

    private static PJN_Channel_Consent__c buildChannelConsent(PJN_Contact_Information__c contactInfo, DataUsePurpose dup) {
        Date today = Date.today();

        return new PJN_Channel_Consent__c(
            PJN_Contact_Information__c = contactInfo.Id,
            PJN_Data_Use_Purpose__c = dup.Id,
            PJN_Effective_From__c = today,
            PJN_Effective_To__c = today.addMonths((Integer) dup.PJN_Effective_Months__c),
            PJN_Privacy_Consent_Status__c = 'Opt In'

        );
    }

    private static Set<Id> getAccountIds() {
        Set<Id> result = new Set<Id>();
        for (CarePlanWrapperMVN wrapper : wrappers) {
            if (wrapper.carePlan.AccountId != NULL) {
                result.add(wrapper.carePlan.AccountId);
            }
        }
        return result;
    }

    private static List<Case> getCarePlansForUpdate() {
        List<Case> result = new List<Case>();

        for (CarePlanWrapperMVN wrapper : wrappers) {
            result.add(wrapper.carePlan);
        }

        return result;
    }

    private static String getFieldMappingSoqlString() {
        String soqlString = 'SELECT ConvertedAccountId, HealthCloudGA__CarePlanRecordTypeNamespace__c, HealthCloudGA__CarePlanRecordTypeName__c';
        for (Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt fieldMapping : fieldMappingSettings) {
            if (hasLeadFieldMapping(fieldMapping)) {
                hasLeadFieldMappings = true;
                soqlString += ', ' + fieldMapping.Lead_Field_Name_MVN__c;
            }
        }
        soqlString += ' FROM Lead WHERE Id IN :leadIds ORDER BY CreatedDate';

        return soqlString;
    }

    private static Set<String> getLeadIds() {
        Set<String> leadIds = new Set<String>();

        for (CarePlanWrapperMVN wrapper : wrappers) {
            leadIds.add(wrapper.carePlan.Converted_Lead_MVN__c);
        }

        return leadIds;
    }

    private static Map<Id, Lead> getLeadMap(Set<String> leadIds) {
        Map<Id, Lead> result = new Map<Id, Lead>();

        if (hasLeadFieldMappings) {
            return result;
        }

        return LeadConversionUtilityMVN.queryLeadMap(getFieldMappingSoqlString(), leadIds);
    }

    public static List<CarePlanWrapperMVN> setCarePlanWrappers(List<Id> carePlanIds) {
        Map<String, CareProgram> programMap = LeadConversionUtilityMVN.queryCareProgramMap(recordTypeSettingMap.values());
        wrappers = new List<CarePlanWrapperMVN>();
        for (Case carePlan : LeadConversionUtilityMVN.queryCarePlans(carePlanIds)) {
            Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt recordTypeSetting;
            if (recordTypeSettingMap.containsKey(carePlan.Record_Type_Key_MVN__c)) {
                recordTypeSetting = recordTypeSettingMap.get(carePlan.Record_Type_Key_MVN__c);
                if (programMap.containsKey(recordTypeSetting.Care_Program_DeveloperName_MVN__c)) {
                    CareProgram program = programMap.get(recordTypeSetting.Care_Program_DeveloperName_MVN__c);
                    carePlan.PJN_Program__c = program.Id;
                }
            }
            wrappers.add(new CarePlanWrapperMVN(carePlan));
        }

        return wrappers;
    }

    private static Boolean hasLeadFieldMapping(Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt fieldMapping) {
        return fieldMapping.Is_Active_MVN__c && fieldMapping.Text_Value_MVN__c == NULL;
    }
}