force-app/main/default/src/objects/Case/fields/HealthCloudGA__SortOrder__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SortOrder__c</fullName>
    <description>Rank by which this care gap is sorted.</description>
    <inlineHelpText>Rank by which this care gap is sorted.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Care_Plan_Start_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan_Start_Status__c</fullName>
    <description>Used to trigger a care plan to start and track it&apos;s status</description>
    <label>Care Plan Start Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PJN_Initiate</fullName>
                <label>Initiate</label>
            </value>
            <value>
                <fullName>PJN_Pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>PJN_Started</fullName>
                <label>Started</label>
            </value>
            <value>
                <fullName>PJN_Error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_Start_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Start_Problem__c</fullName>
    <description>The problem to start the program on when initiating. If not provided the first problem is used.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Start Problem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanQuery.cls
/**
 * @author      Mavens
 * @group       CarePlan
 * @description CarePlan Queries
 */
public without sharing class PJN_CarePlanQuery {
    /**
     * fields to query
     */
    public static Set<String> fields = new Set<String>{
        'Id',
        'OwnerId',
        'PJN_Program_DeveloperName__c',
        'AccountId',
        'PJN_Care_Plan_Start_Status__c',
        'PJN_Program_Start_Problem__c'
    };

    public static Case queryById(Id carePlanId) {
        return queryByIds(new Set<Id> {carePlanId}).get(carePlanId);
    }

    /**
     * query care plan by ids
     * @param   Set<Id>       carePlanIds
     * @returns  Map<Id, Case>
     */
    public static Map<Id, Case> queryByIds(Set<Id> carePlanIds) {
        return new Map<Id, Case>(
            (List<Case>) Database.query(
                'SELECT ' +
                    String.join(new List<String>(fields), ', ') + ', ' +
                    '( '+
                        'SELECT ' +
                            String.join(new List<String>(PJN_CarePlanProblemQuery.fields), ', ') + ' ' +
                        'FROM ' +
                            'HealthCloudGA__CarePlanProblems__r ' +
                        'ORDER BY ' +
                            'HealthCloudGA__SortOrder__c ASC NULLS LAST' +
                    '), '+
                    '( '+
                        'SELECT ' +
                            String.join(new List<String>(PJN_CarePlanCaseQuery.fields), ', ') + ' ' +
                        'FROM ' +
                            'Cases' +
                    ') '+
                'FROM ' +
                    'Case ' +
                'WHERE ' +
                    'Id IN :carePlanIds'
            )
        );
    }
}