force-app/main/default/src/objects/Case/fields/HealthCloudGA__DueDate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__DueDate__c</fullName>
    <description>Date by when this care gap should be closed.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date by when this care gap should be closed.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Activity_Timeline_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Activity_Timeline_Status__c</fullName>
    <formula>CASE(
    TEXT(Status), 
    &apos;Open&apos;, &apos;open&apos;, 
    &apos;Closed&apos;, &apos;closed&apos;,
    &apos;Cancelled&apos;, &apos;cancelled&apos;,
    &apos;Open&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity Timeline Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_CarePlan_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarePlan Problem</label>
    <referenceTo>HealthCloudGA__CarePlanProblem__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_Case_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Case_DeveloperName__c</fullName>
    <description>Program Case DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Case DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Program_Problem_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Problem DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanCaseQuery.cls
/**
 * @author      Mavens
 * @group       CarePlan
 * @description CarePlan Case Queries
 */
public with sharing class PJN_CarePlanCaseQuery {
    /**
     * fields to query
     */
    public static Set<String> fields = new Set<String>{
        'Id',
        'Parent.PJN_Program_DeveloperName__c',
        'AccountId',
        'ParentId',
        'PJN_CarePlan_Problem__c',
        'PJN_CarePlan_Problem__r.PJN_Program_Problem_DeveloperName__c',
        'PJN_Program_Case_DeveloperName__c',
        'ClosedDate',
        'HealthCloudGA__DueDate__c',
        'Subject',
        'Status',
        'Owner.Name',
        'Owner.FirstName',
        'Owner.LastName',
        'IsClosed',
        'Parent.AccountId',
        'PJN_Activity_Timeline_Status__c'
    };

    /**
     * query care plan case by id
     * @param   Id       carePlanCaseId
     * @returns  Case
     */
    public static Case queryById(Id carePlanCaseId) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ' ' +
            'FROM ' +
                'Case ' +
            'WHERE ' +
                'Id = :carePlanCaseId'
        );
    }

    /**
     * query care plan case by ids
     * @param   Set<Id>       carePlanCaseIds
     * @returns  Case
     */
    public static Map<Id, Case> queryByIds(Set<Id> carePlanCaseIds) {
        Map<Id, Case> caseMap = new Map<Id, Case>();
        for(Case thisCase : Database.query(
                                'SELECT ' +
                                    String.join(new List<String>(fields), ', ') + ' ' +
                                'FROM ' +
                                    'Case ' +
                                'WHERE ' +
                                    'Id IN :carePlanCaseIds'
                            )) {
            caseMap.put(thisCase.Id, thisCase);
        }
        return caseMap;
    }

    /**
     * query care plan cases by problem
     * @param   Id       carePlanProblemId
     * @returns  List<Case>
     */
    public static List<Case> queryCasesByProblem(Id carePlanProblemId) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ' ' +
            'FROM ' +
                'Case ' +
            'WHERE ' +
                'PJN_CarePlan_Problem__c = :carePlanProblemId ' +
            'ORDER BY ' +
                'ClosedDate NULLS LAST, HealthCloudGA__DueDate__c NULLS LAST'
        );
    }

    /**
     * query care plan cases by problem
     * @param   Id       carePlanProblemId
     * @returns  List<Case>
     */
    public static List<Case> queryCasesByCarePlan(Id carePlanId) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ' ' +
            'FROM ' +
                'Case ' +
            'WHERE ' +
                'PJN_CarePlan_Problem__c = null ' +
            'AND ' +
                'ParentId = :carePlanId ' +
            'ORDER BY ' +
                'ClosedDate NULLS LAST, HealthCloudGA__DueDate__c NULLS LAST'
        );
    }

    /**
     * query open care plan cases by problem
     * @param   Id       carePlanProblemId
     * @returns  List<Case>
     */
    public static List<Case> queryOpenCasesByProblem(Id carePlanProblemId) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ' ' +
            'FROM ' +
                'Case ' +
            'WHERE ' +
                'PJN_CarePlan_Problem__c = :carePlanProblemId ' +
            'AND ' +
                'IsClosed = false'
        );
    }
}