force-app/main/default/src/objects/Case/fields/HealthCloudGA__DueDate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__DueDate__c</fullName>
    <description>Date by when this care gap should be closed.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date by when this care gap should be closed.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/HealthCloudGA__SortOrder__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SortOrder__c</fullName>
    <description>Rank by which this care gap is sorted.</description>
    <inlineHelpText>Rank by which this care gap is sorted.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_CarePlan_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarePlan Problem</label>
    <referenceTo>HealthCloudGA__CarePlanProblem__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_CarePlan_Path_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Path_Status__c</fullName>
    <formula>CASE(
    TEXT(PJN_Status__c), 
    &apos;Planned&apos;, &apos;incomplete&apos;, 
    &apos;Open&apos;, &apos;current&apos;,
    &apos;Cancelled&apos;, &apos;complete&apos;,
    &apos;Closed&apos;, &apos;complete&apos;,
    &apos;incomplete&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CarePlan Path Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Program_Problem_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Problem DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <defaultValue>&apos;Planned&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanProblemQuery.cls
/**
 * @author      Mavens
 * @group       CarePlan
 * @description CarePlan Queries
 */
public with sharing class PJN_CarePlanProblemQuery {
    /**
     * fields to query
     */
    public static Set<String> fields = new Set<String>{
        'Id',
        'Name',
        'PJN_Status__c',
        'PJN_CarePlan_Path_Status__c',
        'PJN_Program_Problem_DeveloperName__c',
        'HealthCloudGA__CarePlan__r.PJN_Program_DeveloperName__c',
        'HealthCloudGA__CarePlan__r.AccountId',
        'HealthCloudGA__CarePlan__r.OwnerId',
        'HealthCloudGA__CarePlan__c',
        'HealthCloudGA__SortOrder__c'
    };

    /**
     * query care plan problem by id
     * @param   Id       carePlanProblemId
     * @returns  HealthCloudGA__CarePlanProblem__c
     */
    public static HealthCloudGA__CarePlanProblem__c queryById(Id carePlanProblemId) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ' ' +
            'FROM ' +
                'HealthCloudGA__CarePlanProblem__c ' +
            'WHERE ' +
                'Id = :carePlanProblemId'
        );
    }

    /**
     * query care plan problem by care plan id
     * @param   Id       carePlanId
     * @returns  List<HealthCloudGA__CarePlanProblem__c>
     */
    public static List<HealthCloudGA__CarePlanProblem__c> queryByCarePlanId(Id carePlanId) {
        return queryByCarePlanId(carePlanId, true);
    }

    /**
     * query care plan problem by care plan id
     * @param   Id       carePlanId
     * @param   Boolean   allCases
     * @returns  List<HealthCloudGA__CarePlanProblem__c>
     */
    public static List<HealthCloudGA__CarePlanProblem__c> queryByCarePlanId(Id carePlanId, Boolean allCases) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ', (' +
                    'SELECT ' +
                        String.join(new List<String>(PJN_CarePlanCaseQuery.fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Cases__r ' +
                    + getOpenCasesWhereClause(allCases) +
                    'ORDER BY ' +
                        'ClosedDate NULLS LAST, HealthCloudGA__DueDate__c NULLS LAST' +
                ') '+
            'FROM ' +
                'HealthCloudGA__CarePlanProblem__c ' +
            'WHERE ' +
                'HealthCloudGA__CarePlan__c = :carePlanId ' +
            'ORDER BY ' +
                'HealthCloudGA__SortOrder__c ASC NULLS LAST, CreatedDate ASC '
        );
    }

    private static String getOpenCasesWhereClause(Boolean allCases) {
        if (allCases) {
            return '';
        }
        return 'WHERE IsClosed = false ';
    }
}