force-app/main/default/src/objects/Case/fields/HealthCloudGA__SortOrder__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SortOrder__c</fullName>
    <description>Rank by which this care gap is sorted.</description>
    <inlineHelpText>Rank by which this care gap is sorted.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_CarePlan_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarePlan Problem</label>
    <referenceTo>HealthCloudGA__CarePlanProblem__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Activity.recordType-meta.xml
<RecordType>
    <fullName>PJN_Activity</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities related to a patient&apos;s care plan</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Program_Problem_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Problem DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <defaultValue>&apos;Planned&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanWrapperTest.cls
/*
 * @author      Mavens
 * @group       CarePlan
 * @description Unit tests for CarPlanWrapper
 */
@isTest
public with sharing class PJN_CarePlanWrapperTest {

    static Case carePlan;
    static List<HealthCloudGA__CarePlanProblem__c> problems;
    static List<Case> activities;
    static {
        carePlan = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Subject='CarePlan'
        );

        insert carePlan;

        problems = new List<HealthCloudGA__CarePlanProblem__c> {
            new HealthCloudGA__CarePlanProblem__c(
                HealthCloudGA__CarePlan__c = carePlan.Id,
                HealthCloudGA__SortOrder__c = 1,
                PJN_Program_Problem_DeveloperName__c = 'PJN_Mocked_Program_Problem_One'
            ),
            new HealthCloudGA__CarePlanProblem__c(
                HealthCloudGA__CarePlan__c = carePlan.Id,
                HealthCloudGA__SortOrder__c = 2,
                PJN_Program_Problem_DeveloperName__c = 'PJN_Mocked_Program_Problem_Two'
            )
        };

        insert problems;

        activities = new List<Case> {
            new Case(
                RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId(),
                Subject='Activity 1',
                PJN_CarePlan_Problem__c = problems[0].Id,
                ParentId = carePlan.Id
            ),
            new Case(
                RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId(),
                Subject='Activity 1',
                PJN_CarePlan_Problem__c = problems[1].Id,
                ParentId = carePlan.Id
            )
        };

        insert activities;
    }

    @isTest
    private static void itShouldConstructAWrapperGivenACarePlanId() {
        Test.startTest();
        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(carePlan.Id);
        Test.stopTest();

        System.assert(wrapper.problems.keySet().containsAll(new Set<Id>{problems[0].Id, problems[1].Id}));
        System.assert(wrapper.activities.keySet().containsAll(new Set<Id>{activities[0].Id, activities[1].Id}));
    }

    @isTest
    private static void itShouldConstructAWrapperGivenACarePlan() {
        Test.startTest();
        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(
            PJN_CarePlanQuery.queryById(carePlan.Id)
        );
        Test.stopTest();

        System.assert(wrapper.problems.keySet().containsAll(new Set<Id>{problems[0].Id, problems[1].Id}));
        System.assert(wrapper.activities.keySet().containsAll(new Set<Id>{activities[0].Id, activities[1].Id}));
    }

    @isTest
    private static void itShouldThrowErrorWhenStartingCarePlanWithNoProblems() {
        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(carePlan); //not queried properly so no problems passed
        Test.startTest();
        Boolean errorCaught = false;
        try {
            wrapper.start();
        } catch(PJN_CarePlanWrapper.PJN_CarePlanWrapperException ex) {
            errorCaught = true;
            System.assertEquals(PJN_CarePlanWrapper.noProblemsToStart, ex.getMessage());
        }
        System.assert(errorCaught);
    }

    @isTest
    private static void itShouldStartTheCarePlan() {
        PJN_CarePlanProblemHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_MappingEngine.mappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());
        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(
            PJN_CarePlanQuery.queryById(carePlan.Id)
        );
        Test.startTest();
        Map<HealthCloudGA__CarePlanProblem__c, List<Case>> returnedData = wrapper.start();
        Test.stopTest();

        System.assert(!returnedData.isEmpty());
        List<HealthCloudGA__CarePlanProblem__c> returnedProblems = new List<HealthCloudGA__CarePlanProblem__c>(returnedData.keySet());
        System.assertEquals('PJN_Mocked_Program_Problem_One', returnedProblems[0].PJN_Program_Problem_DeveloperName__c);
    }

    @isTest
    private static void itShouldStartAProblem() {
        PJN_CarePlanProblemHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_MappingEngine.mappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());

        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(
            PJN_CarePlanQuery.queryById(carePlan.Id)
        );

        Test.startTest();
        wrapper.startProblem(problems[0].Id, true);
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM HealthCloudGA__CarePlanProblem__c WHERE PJN_Status__c = 'Open']);
    }

    @isTest
    private static void itShouldThrowErrorWhenStartingProblemNotOnCarePlan() {
        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(carePlan); //not queried properly so no problems passed
        Test.startTest();
        Boolean errorCaught = false;
        try {
            wrapper.startProblem(carePlan.Id, true);
        } catch(PJN_CarePlanWrapper.PJN_CarePlanWrapperException ex) {
            errorCaught = true;
            System.assertEquals(
                String.format(PJN_CarePlanWrapper.problemDoesNotExistOnCarePlan, new List<String>{carePlan.Id}),
                ex.getMessage()
            );
        }
        System.assert(errorCaught);
    }

    @isTest
    private static void itShouldSkipAProblem() {
        PJN_CarePlanCaseHdlr.programCaseQuery = (PJN_ProgramCaseQuery) Test.createStub(PJN_ProgramCaseQuery.class, new PJN_ProgramCaseMock());
        PJN_CarePlanProblemHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_MappingEngine.mappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());

        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(
            PJN_CarePlanQuery.queryById(carePlan.Id)
        );
        wrapper.startProblem(problems[0].Id, true);
        Test.startTest();
        wrapper.skipProblem(problems[0].Id, true);
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM HealthCloudGA__CarePlanProblem__c WHERE PJN_Status__c = 'Open']);
        System.assertEquals(1, [SELECT COUNT() FROM HealthCloudGA__CarePlanProblem__c WHERE PJN_Status__c = 'Cancelled']);
    }

    @isTest
    private static void itShouldThrowErrorWhenSkippingProblemNotOnCarePlan() {
        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(carePlan); //not queried properly so no problems passed
        Test.startTest();
        Boolean errorCaught = false;
        try {
            wrapper.skipProblem(carePlan.Id, true);
        } catch(PJN_CarePlanWrapper.PJN_CarePlanWrapperException ex) {
            errorCaught = true;
            System.assertEquals(
                String.format(PJN_CarePlanWrapper.problemDoesNotExistOnCarePlan, new List<String>{carePlan.Id}),
                ex.getMessage()
            );
        }
        System.assert(errorCaught);
    }

    @isTest
    private static void itShouldProcessClosedActivity() {
        PJN_CarePlanCaseHdlr.programCaseQuery = (PJN_ProgramCaseQuery) Test.createStub(PJN_ProgramCaseQuery.class, new PJN_ProgramCaseMock());
        PJN_CarePlanProblemHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_MappingEngine.mappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());

        PJN_CarePlanWrapper wrapper = new PJN_CarePlanWrapper(
            PJN_CarePlanQuery.queryById(carePlan.Id)
        );
        Test.startTest();
        Map<HealthCloudGA__CarePlanProblem__c, List<Case>> returnedData = wrapper.activityClosed(activities[0].Id);
        Test.stopTest();

        System.assertEquals(2, returnedData.size());
        List<HealthCloudGA__CarePlanProblem__c> problems = new List<HealthCloudGA__CarePlanProblem__c>(returnedData.keySet());
        System.assertEquals('Closed',problems[0].PJN_Status__c);
        System.assertEquals('Open',problems[1].PJN_Status__c);
    }
}