force-app/main/default/src/objects/Case/fields/MVN_Days_in_Pharmacy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Days_in_Pharmacy_Status__c</fullName>
    <description>The number of days elapsed since the last change in Pharmacy Status.</description>
    <formula>NOW() -  MVN_Last_Pharmacy_Status_Update__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Pharmacy Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Days_in_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Days_in_Therapy_Status__c</fullName>
    <description>The number of days elapsed since the last change in Therapy Status/Sub-Status combination.</description>
    <formula>NOW() -  MVN_Last_Therapy_Status_Update__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Therapy Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Last_Pharmacy_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>MVN_Last_Pharmacy_Status_Update__c</fullName>
    <description>The last time the Pharmacy Status was updated on the Case.  This value is set via automation.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Pharmacy Status Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Last_Therapy_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>MVN_Last_Therapy_Status_Update__c</fullName>
    <description>The last time the Therapy Status or Therapy Sub-Status was updated on the Case.  This value is set via automation.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Therapy Status Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Pharmacy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Pharmacy_Status__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Pharmacy Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Share_with_RBM__c.field-meta.xml
<CustomField>
    <fullName>MVN_Share_with_RBM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if RBMs should have Read-Only access to the Case.  The field is set via automation and referenced in Case sharing rules.</description>
    <label>Share with RBM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Status__c</fullName>
    <description>A patient&apos;s program treatment journey status. Utilizing Status Global Value Set.</description>
    <label>Therapy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Sub_Status__c</fullName>
    <description>A patient&apos;s program treatment journey sub-status. Utilizing Sub-Status Global Value Set.</description>
    <label>Therapy Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Therapy_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_Sub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Complete</fullName>
        <isActive>false</isActive>
        <label>Treatment Complete</label>
    </customValue>
    <customValue>
        <fullName>On Therapy</fullName>
        <isActive>false</isActive>
        <label>On Therapy</label>
    </customValue>
    <description>Status field picklist value set, used for Therapy Status fields. 

Pending: Status assigned to a patient&apos;s care plan confirming they are going through the program enrollment process (new or restart patient).

On Therapy: Status assigned to a patient&apos;s care plan confirming they are fully approved for dispense and awaiting/currently receiving shipments.

Treatment Complete: Status assigned to a patient&apos;s care plan confirming they have completed their treatment journey.

Discontinued: Status assigned to a patient&apos;s care plan confirming they have previously enrolled in a program, but have either chosen or have been deemed ineligible to continue. 

Cancelled: Status assigned to a patient&apos;s care plan confirming they have either chosen not to continue with enrollment, or have been deemed ineligible to continue.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/globalValueSets/PJN_Sub_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Treatment Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Support</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriber Support</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer to SP IAP</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer to SP PAP</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Authorization Support Start</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Authorization Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Authorization Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (1st Level)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (2nd Level)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (3rd Level)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (Peer-to-Peer)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Denied</fullName>
    </customValue>
    <customValue>
        <fullName>PA/Appeal Support Max Attempts</fullName>
    </customValue>
    <customValue>
        <fullName>Claims Support</fullName>
    </customValue>
    <customValue>
        <fullName>Copay Support</fullName>
    </customValue>
    <customValue>
        <fullName>Adverse Event Reported (Call Transfer)</fullName>
    </customValue>
    <customValue>
        <fullName>Adverse Event Reported (Form Submission)</fullName>
    </customValue>
    <customValue>
        <fullName>New Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information, Patient Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information, HCP Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information, RBM Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriber Welcome Call Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriber Welcome Call Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Welcome Call Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Welcome Call Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Copay Card Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Copay Card Not Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer to SP CTTP</fullName>
    </customValue>
    <description>Sub Status picklist with Status as a controlling field. Used for Therapy Sub-Status fields.</description>
    <masterLabel>Sub-Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/MVN_ShareWithRBMBatchSch.cls
/**
 * @author      Mavens
 * @group       RBM
 * @description Batch job to set the Share with RBM flag on Care Plans
 */
public with sharing class MVN_ShareWithRBMBatchSch implements Schedulable, Database.Batchable<sObject> {
    
    public void execute(SchedulableContext SC) {
        Id jobId = Database.executeBatch(new MVN_ShareWithRBMBatchSch());
    }

    public static void schedule(String cronExpression) {
        unschedule();
        MVN_ShareWithRBMBatchSch shareWithRBMSchedulable = new MVN_ShareWithRBMBatchSch();
        Id jobId = System.schedule('ShareWithRBMBatch', cronExpression, shareWithRBMSchedulable);
    }

    public static void unschedule() {
        for ( CronTrigger ct : [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name LIKE :('ShareWithRBMBatch'+'%')] ) {
            System.abortJob(ct.Id);
        }
    }


    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            [
                SELECT Id,
                       RecordTypeId,
                       PJN_Program_DeveloperName__c,
                       PJN_Therapy_Status__c,
                       PJN_Therapy_Sub_Status__c,
                       MVN_Pharmacy_Status__c,
                       MVN_Last_Pharmacy_Status_Update__c,
                       MVN_Days_in_Pharmacy_Status__c,
                       MVN_Last_Therapy_Status_Update__c,
                       MVN_Days_in_Therapy_Status__c,
                       MVN_Share_with_RBM__c
                  FROM Case
                 WHERE RecordType.DeveloperName = 'CarePlan'
            ]
        );
    }

    public void execute(Database.BatchableContext BC, List<Case> scope) {
        List<Case> carePlans = scope;
        MVN_ShareWithRBM.share(carePlans);
        update carePlans;
    }
    
    public void finish(Database.BatchableContext BC) {
    }
}