force-app/main/default/src/objects/Case/fields/MVN_Copay_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copay Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Cases (Copay Assistance Program)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Activity.recordType-meta.xml
<RecordType>
    <fullName>PJN_Activity</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities related to a patient&apos;s care plan</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/src/objects/MVN_Claim__c/MVN_Claim__c.object-meta.xml
<CustomObject>
    <description>Stores the details of submitted and processed claims.</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>MVN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Check_Number__c.field-meta.xml
<CustomField>
    <fullName>MVN_Check_Number__c</fullName>
    <description>Only applicable for check payment. For checks, this number may be delivered in a subsequent record after the original record.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Only applicable for check payment. For checks, this number may be delivered in a subsequent record after the original record.</inlineHelpText>
    <label>Check Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Claim_Create_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Claim_Create_Date__c</fullName>
    <description>Date ConnectiveRx enters the claim into the system for processing.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date ConnectiveRx enters the claim into the system for processing.</inlineHelpText>
    <label>Claim Create Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Claim_Id__c</fullName>
    <description>ConnectiveRx Claim ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Claim Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Copay_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copay Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Copay_Before_Benefit_Applied__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Before_Benefit_Applied__c</fullName>
    <description>Patient responsibility (after primary; before copay). This is required for approved claims only. Rejected claims may or may not have this available.</description>
    <inlineHelpText>Patient responsibility (after primary; before copay). This is required for approved claims only. Rejected claims may or may not have this available.</inlineHelpText>
    <label>Copay Before Benefit Applied</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>MVN_Date_of_Service__c</fullName>
    <description>Required for approved claims only. Rejected claims may or may not have this available.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Required for approved claims only. Rejected claims may or may not have this available.</inlineHelpText>
    <label>Date of Service</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Patient_OOP__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_OOP__c</fullName>
    <description>Amount patient paid after primary and copay program. This is required for approved claims only. Rejected claims may or may not have this available.</description>
    <inlineHelpText>Amount patient paid after primary and copay program. This is required for approved claims only. Rejected claims may or may not have this available.</inlineHelpText>
    <label>Patient OOP</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Payment_Type__c</fullName>
    <description>Required for approved claims only.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Required for approved claims only.</inlineHelpText>
    <label>Payment Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Program_Benefit__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Benefit__c</fullName>
    <description>Amount paid by the copay program. This is required for approved claims only. Rejected claims may or may not have this available.</description>
    <inlineHelpText>Amount paid by the copay program. This is required for approved claims only. Rejected claims may or may not have this available.</inlineHelpText>
    <label>Program Benefit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/fields/MVN_Trace_Number__c.field-meta.xml
<CustomField>
    <fullName>MVN_Trace_Number__c</fullName>
    <description>Only applicable for EFT payment. For EFT payments, this number will be delivered in a subsequent record after the original record as time must elapse before the EFT trace number is returned from the bank.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Only applicable for EFT payment. For EFT payments, this number will be delivered in a subsequent record after the original record as time must elapse before the EFT trace number is returned from the bank.</inlineHelpText>
    <label>Trace Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Claim__c/recordTypes/MVN_Copay_Medical_Claim.recordType-meta.xml
<RecordType>
    <fullName>MVN_Copay_Medical_Claim</fullName>
    <active>true</active>
    <label>Copay Medical Claim</label>
</RecordType>

force-app/main/default/src/objects/MVN_Staging_Claim__c/MVN_Staging_Claim__c.object-meta.xml
<CustomObject>
    <description>Used to stage integration-sourced claims data so that it can be mapped to Claims records.</description>
    <label>Staging Claim</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Staging Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Check_Number__c.field-meta.xml
<CustomField>
    <fullName>MVN_Check_Number__c</fullName>
    <description>Only applicable for check payment. For checks, this number may be delivered in a subsequent record after the original record.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Check #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Claim_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Claim_Created_Date__c</fullName>
    <description>Format: MM/DD/YYYY
Based on date ConnectiveRx enters the claim into the system for processing</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Claim Create Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Claim_Id__c</fullName>
    <description>Claim ID (CRx generated)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Claim ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>MVN_Date_of_Service__c</fullName>
    <description>MM/DD/YYYY This is required for approved claims only. Rejected claims may or may not have this available so validations at Integrichain should only be applied to approved claims.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date of Service</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>MVN_Error_Message__c</fullName>
    <description>Error message from the conversion of Staging Claim to Claim.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Error message from the conversion of Staging Claim to Claim.</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Member_Id__c</fullName>
    <description>ConnectiveRx generated. Once Member ID is assigned, this number must stay with patient</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Member ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Patient_Copay_Before_Benefit__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_Copay_Before_Benefit__c</fullName>
    <description>Patient Responsibility (after primary; before co-pay) This is required for approved claims only. Rejected claims may or may not have this available so validations at Integrichain should only be applied to approved claims.</description>
    <label>Patient Copay before Benefit applied</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Patient_OOP__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_OOP__c</fullName>
    <description>Amount patient paid after primary and co-pay program. This is required for approved claims only. Rejected claims may or may not have this available so validations at Integrichain should only be applied to approved claims.</description>
    <label>Patient OOP</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Payment_Type__c</fullName>
    <description>This is required for approved claims only. 
CTM – Check to Practice
CTP – Check to Patient
ACH – EFT to Practice</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Program_Benefit__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Benefit__c</fullName>
    <description>Amount paid by the co-pay program. This is required for approved claims only. Rejected claims may or may not have this available so validations at Integrichain should only be applied to approved claims.</description>
    <label>Program Benefit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status__c</fullName>
    <description>Status of the conversion from Staging Claim to Claim.</description>
    <inlineHelpText>Status of the conversion from Staging Claim to Claim.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/fields/MVN_Trace_Number__c.field-meta.xml
<CustomField>
    <fullName>MVN_Trace_Number__c</fullName>
    <description>Only applicable for EFT payment . For EFT payments, this number will be delivered in a subsequent record after the original record as time must elapse before the Eft trace number is returned from the bank.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Trace #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_Staging_Claim__c/recordTypes/MVN_Copay_Medical.recordType-meta.xml
<RecordType>
    <fullName>MVN_Copay_Medical</fullName>
    <active>true</active>
    <description>Used for tracking Medical Copay claims.</description>
    <label>Copay Medical</label>
</RecordType>

force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Member_ID__c.field-meta.xml
<CustomField>
    <fullName>MVN_Member_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Member ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/recordTypes/PJN_Copay.recordType-meta.xml
<RecordType>
    <fullName>PJN_Copay</fullName>
    <active>true</active>
    <description>An enrollment into Copay savings program.</description>
    <label>Copay Savings</label>
</RecordType>

force-app/main/default/src/classes/MVN_StagingConvertMedical.cls
/**
 * @author      Mavens
 * @date        June 30, 2021
 * @description Batch job that converts medical Staging Claims to Claims.
 */
public with sharing class MVN_StagingConvertMedical implements Schedulable, Database.Batchable<sObject> {

    /**
     * Schedule execute method which will start batch job
     * @param SC    Schedule context
     */
    public void execute (SchedulableContext SC) {
        Id batchJobId = Database.executeBatch(new MVN_StagingConvertMedical(), 200);
    }

    /**
     * Collect the records or objects to pass to the interface method execute.
     * @param bc
     * @returns `Database.QueryLocator`
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // build the query
        String query = buildStagingClaimQueryString();

        // return the query locator
        return Database.getQueryLocator(query);
    }

    /**
     * Processing for each chunk of data.
     * @param bc
     * @param scope
     */
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<MVN_Staging_Claim__c> stagingClaims = (List<MVN_Staging_Claim__c>) scope;
        Set<String> memberIds = new Set<String>();
        Set<String> datesOfService = new Set<String>();
        
        
        for (MVN_Staging_Claim__c stagingClaim : stagingClaims) {
            if (String.isNotBlank(stagingClaim.MVN_Member_Id__c)) {
                memberIds.add(stagingClaim.MVN_Member_Id__c);
            }
            
            stagingClaim.MVN_Date_of_Service__c = formatDateOfService(stagingClaim.MVN_Date_of_Service__c);

            if (String.isNotBlank(stagingClaim.MVN_Date_of_Service__c)) {
                datesOfService.add(stagingClaim.MVN_Date_of_Service__c);
            }
        }

        // Maps necessary for populating claim
        Map<String, Map<String, MVN_Claim__c>> claimMap = queryClaimMap(memberIds, datesOfService);
        Map<String, PJN_Assistance_Program__c> memberIdToAssistanceProgramMap = queryAssistanceProgramMap(memberIds);

        // Objects that for DML transaction
        Map<Id, MVN_Claim__c> claimsToUpdate = new Map<Id, MVN_Claim__c>();
        List<MVN_Claim__c> claimsToInsert = new List<MVN_Claim__c>();
        List<MVN_Staging_Claim__c> stagingClaimsForUpdate = new List<MVN_Staging_Claim__c>();

        // Loop through Staging Claims and build Claims and edit Staging Claims
        for (MVN_Staging_Claim__c stagingClaim : stagingClaims) {
            // Claim match found by Member Id and Date of Service, build claim
            if (
                claimMap.containsKey(stagingClaim.MVN_Member_Id__c) && 
                claimMap.get(stagingClaim.MVN_Member_Id__c).containsKey(stagingClaim.MVN_Date_of_Service__c)
            ) {
                MVN_Claim__c claim = buildClaim(
                    stagingClaim, 
                    claimMap.get(stagingClaim.MVN_Member_Id__c).get(stagingClaim.MVN_Date_of_Service__c)
                );

                if (claim.Id != null) {
                    claimsToUpdate.put(claim.Id, claim);
                } else {
                    claimsToInsert.add(claim);
                }

                stagingClaim.MVN_Status__c = System.Label.MVN_Staging_Claim_Conversion_Status_Complete;
                stagingClaim.MVN_Error_Message__c = '';

            // Assistance Progam match found by Member Id, build claim
            } else if (String.isNotBlank(stagingClaim.MVN_Member_Id__c) && memberIdToAssistanceProgramMap.containsKey(stagingClaim.MVN_Member_Id__c)) {
                MVN_Claim__c claim = buildClaim(stagingClaim);
                claim.MVN_Copay_Assistance_Program__c = memberIdToAssistanceProgramMap.get(stagingClaim.MVN_Member_Id__c).Id;
                claim.MVN_Care_Plan__c = memberIdToAssistanceProgramMap.get(stagingClaim.MVN_Member_Id__c).PJN_Care_Plan__c;
                claimsToInsert.add(claim);
                stagingClaim.MVN_Status__c = System.Label.MVN_Staging_Claim_Conversion_Status_Complete;
                stagingClaim.MVN_Error_Message__c = '';

            // Member Id is blank, match impossible
            } else if (String.isBlank(stagingClaim.MVN_Member_Id__c)) {
                stagingClaim.MVN_Status__c = System.Label.MVN_Staging_Claim_Conversion_Status_Error;
                stagingClaim.MVN_Error_Message__c = System.Label.MVN_Staging_Claim_Conversion_Error_Msg_Member_Id_is_Blank;

            // Generic no match found error
            } else {
                stagingClaim.MVN_Status__c = System.Label.MVN_Staging_Claim_Conversion_Status_Error;
                stagingClaim.MVN_Error_Message__c = System.Label.MVN_Staging_Claim_Conversion_Error_Copay_Not_Found;
            }
            stagingClaimsForUpdate.add(stagingClaim);
        }

        // Perform DML
        List<MVN_Claim__c> claimsToUpsert = claimsToInsert;
        claimsToUpsert.addAll(claimsToUpdate.values());

        upsert claimsToUpsert;
        update stagingClaimsForUpdate;

        createActivities(claimsToUpsert);

    }

    /**
     * Finish method.
     * @param bc
     */
    public void finish(Database.BatchableContext bc) { //NOPMD
    }

    /**
     * @description Remove any leading '0' number for days and months in the String date to match Salesforce format
     * @param  dateOfService String Date Of Service
     * @return Strin
     */
    private String formatDateOfService(String dateOfService) {
        if (dateOfService == null) {
            return dateOfService;
        }
        List<String> dateSplit = dateOfService.split('/');
        return dateSplit[0].removeStart('0') + '/' + dateSplit[1].removeStart('0') + '/' + dateSplit[2];
    }


    /**
     * Build a Claim based on Staging Claim and old Claim.
     * @param stagingClaim
     * @param oldClaim
     * @return  `MVN_Claim__c`
     */
    private MVN_Claim__c buildClaim(MVN_Staging_Claim__c stagingClaim, MVN_Claim__c oldClaim) {

        Id recordTypeId = Schema.SObjectType.MVN_Claim__c.getRecordTypeInfosByDeveloperName().get('MVN_Copay_Medical_Claim').getRecordTypeId();
        MVN_Claim__c claim;

        if (oldClaim != NULL) {
            claim = new MVN_Claim__c(
                Id = oldClaim.Id,
                MVN_Copay_Assistance_Program__c = oldClaim.MVN_Copay_Assistance_Program__c
            );
        } else {
            claim = new MVN_Claim__c(RecordTypeId = recordTypeId);
        }

        claim.MVN_Claim_Id__c = stagingClaim.MVN_Claim_Id__c;
        claim.MVN_Claim_Create_Date__c = stagingClaim.MVN_Claim_Created_Date__c;
        claim.MVN_Date_of_Service__c = stagingClaim.MVN_Date_of_Service__c;
        claim.MVN_Payment_Type__c = stagingClaim.MVN_Payment_Type__c;
        claim.MVN_Copay_Before_Benefit_Applied__c = stagingClaim.MVN_Patient_Copay_Before_Benefit__c;
        claim.MVN_Program_Benefit__c = stagingClaim.MVN_Program_Benefit__c;
        claim.MVN_Patient_OOP__c = stagingClaim.MVN_Patient_OOP__c;
        claim.MVN_Check_Number__c = stagingClaim.MVN_Check_Number__c;
        claim.MVN_Trace_Number__c = stagingClaim.MVN_Trace_Number__c;
        claim.MVN_Payment_Date__c = stagingClaim.MVN_Payment_Date__c;
        claim.MVN_Claim_Outcome__c = stagingClaim.MVN_Claim_Outcome__c;
        claim.MVN_Copay_Coinsurance_Amount__c = stagingClaim.MVN_Copay_Amount__c;
        claim.MVN_Claim_Receipt_Date__c = stagingClaim.MVN_Claim_Receipt_Date__c;
        claim.MVN_Claim_Closed_Date__c = stagingClaim.MVN_Claim_Closed_Date__c;
        claim.MVN_Rejected_Reason__c = stagingClaim.MVN_Rejected_Reason__c;
        claim.MVN_EOB_Date__c = stagingClaim.MVN_EOB_Date__c;

        return claim;
    }

    /**
     * Overloaded method that will build a Claim based on Staging Claim.
     * @param stagingClaim
     * @return  `MVN_Claim__c`
     */
    private MVN_Claim__c buildClaim(MVN_Staging_Claim__c stagingClaim) {
        return buildClaim(stagingClaim, null);
    }

    /**
     * Returns a query string for Database.QueryLocator
     * @return  `String`
     */
    private String buildStagingClaimQueryString() {
        Id recordTypeId = Schema.SObjectType.MVN_Staging_Claim__c.getRecordTypeInfosByDeveloperName().get('MVN_Copay_Medical').getRecordTypeId();
        String query = 'SELECT MVN_Check_Number__c,';
              query += '       MVN_Claim_Closed_Date__c,';
              query += '       MVN_Claim_Created_Date__c,';
              query += '       MVN_Claim_Id__c,';
              query += '       MVN_Claim_Outcome__c,';
              query += '       MVN_Claim_Receipt_Date__c,';
              query += '       MVN_Copay_Amount__c,';
              query += '       MVN_Date_of_Service__c,';
              query += '       MVN_EOB_Date__c,';
              query += '       MVN_Error_Message__c,';
              query += '       MVN_Member_Id__c,';
              query += '       MVN_Patient_Copay_Before_Benefit__c,';
              query += '       MVN_Patient_OOP__c,';
              query += '       MVN_Payment_Date__c,';
              query += '       MVN_Payment_Type__c,';
              query += '       MVN_Program_Benefit__c,';
              query += '       MVN_Rejected_Reason__c,';
              query += '       MVN_Status__c,';
              query += '       MVN_Trace_Number__c';
              query += '  FROM MVN_Staging_Claim__c';
              query += ' WHERE RecordTypeId = \'' + recordTypeId + '\'';
              query += '   AND MVN_Status__c IN (\'Pending\', \'Error\')';
        return query;
    }

    private void createActivities(List<MVN_Claim__c> claims) {
        // Create activities when a Copay Medical Claims are approved or rejected.
        List<Case> activitiesToInsert = new List<Case>();
        if (claims.size() > 0) {
            Map<Id, PJN_Assistance_Program__c> assistanceProgramMap = queryAssistanceProgramMap(claims);

            for (MVN_Claim__c claim : claims) {
                if (assistanceProgramMap.containsKey(claim.MVN_Copay_Assistance_Program__c) && claim.MVN_Claim_Outcome__c != null) {
                    PJN_Assistance_Program__c program = assistanceProgramMap.get(claim.MVN_Copay_Assistance_Program__c);
                    Boolean coordinatorEmpty = program.PJN_Care_Plan__r.MVN_Coordinator__c != NULL;

                    activitiesToInsert.add(
                        new Case(
                            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId(),
                            AccountId = program.PJN_Account__c,
                            ParentId = program.PJN_Care_Plan__c,
                            HealthCloudGA__DueDate__c = Date.today().addDays(1),
                            Subject = System.Label.MVN_Staging_Claim_Activity_Subject,
                            Description = System.Label.MVN_Staging_Claim_Activity_Description,
                            OwnerId = coordinatorEmpty ? program.PJN_Care_Plan__r.MVN_Coordinator__c : program.PJN_Care_Plan__r.OwnerId
                        )
                    );
                }
            }
        }

        insert activitiesToInsert;
    }

    /**
     * Query the MVN_Claim__c object returning a map with a key of Member ID and Date of Service.
     * @param memberIds
     * @param datesOfService
     * @return  `Map<String, MVN_Claim__c>`
     */
    private Map<String, Map<String,  MVN_Claim__c>> queryClaimMap(Set<String> memberIds, Set<String> datesOfService) {
        
        Map<String, Map<String, MVN_Claim__c>> result = new Map<String, Map<String, MVN_Claim__c>>();
        
        for (MVN_Claim__c claim : [
            SELECT 
                MVN_Care_Plan__c, MVN_Copay_Assistance_Program__c, MVN_Copay_Member_Id__c, 
                MVN_Date_Of_Service_myRare_String__c 
            FROM MVN_Claim__c 
            WHERE 
                MVN_Copay_Member_Id__c IN :memberIds AND 
                MVN_Date_Of_Service_myRare_String__c IN :datesOfService
        ]) {
            if (!result.containsKey(claim.MVN_Copay_Member_Id__c)) {
                result.put(claim.MVN_Copay_Member_Id__c, new Map<String, MVN_Claim__c>());
            }
            if (!result.get(claim.MVN_Copay_Member_Id__c).containsKey(claim.MVN_Date_Of_Service_myRare_String__c)) {
                result.get(claim.MVN_Copay_Member_Id__c).put(claim.MVN_Date_Of_Service_myRare_String__c, claim);
            }
        }

        return result;
    }

    /**
     * Query the PJN_Assistance_Program__c object returning a map with a key of Member ID.
     * @param memberIds
     * @return  `Map<String, PJN_Assistance_Program__c>`
     */
    private Map<String, PJN_Assistance_Program__c> queryAssistanceProgramMap(Set<String> memberIds) {
        Id recordTypeId = Schema.SObjectType.PJN_Assistance_Program__c.getRecordTypeInfosByDeveloperName().get('PJN_Copay').getRecordTypeId();
        Map<String, PJN_Assistance_Program__c> result = new Map<String, PJN_Assistance_Program__c>();
        for (PJN_Assistance_Program__c program : [SELECT MVN_Copay_Member_Id__c, PJN_Care_Plan__c FROM PJN_Assistance_Program__c WHERE MVN_Copay_Member_Id__c = :memberIds AND RecordTypeId = :recordTypeId]) {
            result.put(program.MVN_Copay_Member_Id__c, program);
        }
        return result;
    }

    /**
     * Query the PJN_Assistance_Program__c object returning a map with a key of Id
     * @param claims
     * @return  `Map<Id, PJN_Assistance_Program__c>`
     */
    private Map<Id, PJN_Assistance_Program__c> queryAssistanceProgramMap(List<MVN_Claim__c> claims) {
        Set<Id> copayProgramIds = new Set<Id>();
        for (MVN_Claim__c claim : claims) {
            copayProgramIds.add(claim.MVN_Copay_Assistance_Program__c);
        }

        return new Map<Id, PJN_Assistance_Program__c>([SELECT PJN_Account__c, PJN_Care_Plan__c, PJN_Care_Plan__r.MVN_Coordinator__c, PJN_Care_Plan__r.OwnerId FROM PJN_Assistance_Program__c WHERE Id = :copayProgramIds]);
    }
}