force-app/main/default/src/objects/Case/fields/MVN_Days_in_Pharmacy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Days_in_Pharmacy_Status__c</fullName>
    <description>The number of days elapsed since the last change in Pharmacy Status.</description>
    <formula>NOW() -  MVN_Last_Pharmacy_Status_Update__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Pharmacy Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Days_in_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Days_in_Therapy_Status__c</fullName>
    <description>The number of days elapsed since the last change in Therapy Status/Sub-Status combination.</description>
    <formula>NOW() -  MVN_Last_Therapy_Status_Update__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Therapy Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Last_Pharmacy_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>MVN_Last_Pharmacy_Status_Update__c</fullName>
    <description>The last time the Pharmacy Status was updated on the Case.  This value is set via automation.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Pharmacy Status Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Last_Therapy_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>MVN_Last_Therapy_Status_Update__c</fullName>
    <description>The last time the Therapy Status or Therapy Sub-Status was updated on the Case.  This value is set via automation.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Therapy Status Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Pharmacy_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Pharmacy_Status__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Pharmacy Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Share_with_RBM__c.field-meta.xml
<CustomField>
    <fullName>MVN_Share_with_RBM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if RBMs should have Read-Only access to the Case.  The field is set via automation and referenced in Case sharing rules.</description>
    <label>Share with RBM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Status__c</fullName>
    <description>A patient&apos;s program treatment journey status. Utilizing Status Global Value Set.</description>
    <label>Therapy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Sub_Status__c</fullName>
    <description>A patient&apos;s program treatment journey sub-status. Utilizing Sub-Status Global Value Set.</description>
    <label>Therapy Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Therapy_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_Sub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/MVN_RBM_Sharing_Setting__mdt.object-meta.xml
<CustomObject>
    <description>A record represents the number of days that a Case with a given Therapy Status/Sub-Status combination or Pharmacy Status is visible to the RBM group.</description>
    <label>RBM Sharing Setting</label>
    <pluralLabel>RBM Sharing Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Days_Visible__c.field-meta.xml
<CustomField>
    <fullName>MVN_Days_Visible__c</fullName>
    <description>Amount of time, in days, that records with either a Therapy Status/Sub-Status or a Pharmacy Status should be visible to RBMs.</description>
    <label>Days Visible</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status__c</fullName>
    <description>Therapy Status or Pharmacy Status value that the setting applies to.</description>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Sub_Status__c</fullName>
    <description>Therapy Sub-Status that the setting applies to.</description>
    <label>Sub-Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Type__c</fullName>
    <description>The Status field that the setting applies to.  &apos;Therapy&apos; for Therapy Status, &apos;Pharmacy&apos; for Pharmacy Status.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Therapy</fullName>
                <default>true</default>
                <label>Therapy</label>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Complete</fullName>
        <isActive>false</isActive>
        <label>Treatment Complete</label>
    </customValue>
    <customValue>
        <fullName>On Therapy</fullName>
        <isActive>false</isActive>
        <label>On Therapy</label>
    </customValue>
    <description>Status field picklist value set, used for Therapy Status fields. 

Pending: Status assigned to a patient&apos;s care plan confirming they are going through the program enrollment process (new or restart patient).

On Therapy: Status assigned to a patient&apos;s care plan confirming they are fully approved for dispense and awaiting/currently receiving shipments.

Treatment Complete: Status assigned to a patient&apos;s care plan confirming they have completed their treatment journey.

Discontinued: Status assigned to a patient&apos;s care plan confirming they have previously enrolled in a program, but have either chosen or have been deemed ineligible to continue. 

Cancelled: Status assigned to a patient&apos;s care plan confirming they have either chosen not to continue with enrollment, or have been deemed ineligible to continue.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/globalValueSets/PJN_Sub_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Treatment Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Support</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriber Support</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer to SP IAP</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer to SP PAP</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Authorization Support Start</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Authorization Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Prior Authorization Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (1st Level)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (2nd Level)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (3rd Level)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Support (Peer-to-Peer)</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Denied</fullName>
    </customValue>
    <customValue>
        <fullName>PA/Appeal Support Max Attempts</fullName>
    </customValue>
    <customValue>
        <fullName>Claims Support</fullName>
    </customValue>
    <customValue>
        <fullName>Copay Support</fullName>
    </customValue>
    <customValue>
        <fullName>Adverse Event Reported (Call Transfer)</fullName>
    </customValue>
    <customValue>
        <fullName>Adverse Event Reported (Form Submission)</fullName>
    </customValue>
    <customValue>
        <fullName>New Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information, Patient Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information, HCP Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Information, RBM Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriber Welcome Call Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriber Welcome Call Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Welcome Call Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Welcome Call Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Copay Card Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Copay Card Not Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer to SP CTTP</fullName>
    </customValue>
    <description>Sub Status picklist with Status as a controlling field. Used for Therapy Sub-Status fields.</description>
    <masterLabel>Sub-Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/MVN_ShareWithRBM.cls
/**
 * @author      Mavens
 * @group       RBM
 * @description Sets the Share with RBM flag on Care Plans based on RBM Sharing Settings custom metadata
 */
public with sharing class MVN_ShareWithRBM {

    @TestVisible
    private static MVN_RBMSharingSettingsQuery query = new MVN_RBMSharingSettingsQuery();

    public static void share(List<Case> carePlans) {

        // Collect the Program Name, Therapy Status, Sub Status and Pharmacy Status from the Care Plans
        Map<String,Map<String,List<String>>> programTherapyStatusMap = new Map<String,Map<String,List<String>>>();
        Map<String,Set<String>> programPharmacyStatusMap = new Map<String,Set<String>>();

        for (Case carePlan : carePlans) {
            if (String.isNotBlank(carePlan.PJN_Program_DeveloperName__c)) {

                if (String.isNotBlank(carePlan.PJN_Therapy_Status__c) && String.isNotBlank(carePlan.PJN_Therapy_Sub_Status__c)) {
                    
                    if (programTherapyStatusMap.containsKey(carePlan.PJN_Program_DeveloperName__c)) {
                        Map<String,List<String>> therapyStatusMap = programTherapyStatusMap.get(carePlan.PJN_Program_DeveloperName__c);
                        if (therapyStatusMap.containsKey(carePlan.PJN_Therapy_Status__c)) {
                            List<String> therapySubstatuses = therapyStatusMap.get(carePlan.PJN_Therapy_Status__c);
                            if (!therapySubstatuses.contains(carePlan.PJN_Therapy_Sub_Status__c)) {
                                therapySubstatuses.add(carePlan.PJN_Therapy_Sub_Status__c);
                            }
                        } else {
                            therapyStatusMap.put(carePlan.PJN_Therapy_Status__c, new List<String> { carePlan.PJN_Therapy_Sub_Status__c });
                        }
                    } else {
                        Map<String,List<String>> therapyStatusMap = new Map<String,List<String>>();
                        therapyStatusMap.put(carePlan.PJN_Therapy_Status__c, new List<String> { carePlan.PJN_Therapy_Sub_Status__c });
                        programTherapyStatusMap.put(carePlan.PJN_Program_DeveloperName__c, therapyStatusMap);
                    }
                    
                }
    
                if (String.isNotBlank(carePlan.MVN_Pharmacy_Status__c)) {
                    if (programPharmacyStatusMap.containsKey(carePlan.PJN_Program_DeveloperName__c)) {
                        programPharmacyStatusMap.get(carePlan.PJN_Program_DeveloperName__c).add(carePlan.MVN_Pharmacy_Status__c);
                    } else {
                        programPharmacyStatusMap.put(carePlan.PJN_Program_DeveloperName__c, new Set<String> { carePlan.MVN_Pharmacy_Status__c });
                    }
                }
            }
        }

        System.debug(LoggingLevel.DEBUG, 'Therapy Statuses on Care Plans');
        System.debug(LoggingLevel.DEBUG, programTherapyStatusMap);
        System.debug(LoggingLevel.DEBUG, 'Pharmacy Statuses on Care Plans');
        System.debug(LoggingLevel.DEBUG, programPharmacyStatusMap);
        
        // Query RMB Sharing Settings for the Therapy Status, Sub Status and Pharmacy Status values
        List<MVN_RBM_Sharing_Setting__mdt> rbmSharingSettings = new List<MVN_RBM_Sharing_Setting__mdt>();
        rbmSharingSettings.addAll(query.forProgramTherapyStatusMap(programTherapyStatusMap));
        rbmSharingSettings.addAll(query.forProgramPharmacyStatusMap(programPharmacyStatusMap));

        System.debug('RBM Sharing Settings that matched values on the Care Plan');
        System.debug(rbmSharingSettings);

        for (Case carePlan : carePlans) {

            System.debug(LoggingLevel.DEBUG, 'Setting Share with RBM for Care Plan');
            System.debug(LoggingLevel.DEBUG, carePlan);

            // The Share with RBM flag is referenced in Case sharing rules to provide visibility to Care Plans
            // for RBMs based on visibility rules defined in RBM Sharing Settings custom metadata.
            carePlan.MVN_Share_with_RBM__c = false;

            // The Share with RBM flag is set based on the latest update to either Therapy or Pharmacy Status
            Boolean useTherapyStatus;

            if (carePlan.MVN_Last_Pharmacy_Status_Update__c == null && carePlan.MVN_Last_Therapy_Status_Update__c != null) {
                useTherapyStatus = true;
            } else if (carePlan.MVN_Last_Pharmacy_Status_Update__c != null && carePlan.MVN_Last_Therapy_Status_Update__c == null) {
                useTherapyStatus = false;
            } else if (carePlan.MVN_Last_Pharmacy_Status_Update__c != null && carePlan.MVN_Last_Therapy_Status_Update__c != null) {
                if (carePlan.MVN_Last_Pharmacy_Status_Update__c > carePlan.MVN_Last_Therapy_Status_Update__c) {
                    useTherapyStatus = false;
                } else {
                    useTherapyStatus = true;
                }
            }

            System.debug(LoggingLevel.DEBUG, 'Use Therapy Status instead of Pharmacy Status?');
            System.debug(LoggingLevel.DEBUG, useTherapyStatus);

            if (useTherapyStatus != null) {
                if (useTherapyStatus) {
                    for (MVN_RBM_Sharing_Setting__mdt rbmSharingSetting : rbmSharingSettings) {
                        if (rbmSharingSetting.MVN_Type__c.equalsIgnoreCase('Therapy') && 
                            rbmSharingSetting.MVN_Status__c.equalsIgnoreCase(carePlan.PJN_Therapy_Status__c) && 
                            rbmSharingSetting.MVN_Sub_Status__c.equalsIgnoreCase(carePlan.PJN_Therapy_Sub_Status__c) && 
                            rbmSharingSetting.MVN_Days_Visible__c > carePlan.MVN_Days_in_Therapy_Status__c) {
                                System.debug(LoggingLevel.DEBUG, 'Sharing with RBM because Therapy Status was Last Updated and is within Days Visible');
                                carePlan.MVN_Share_with_RBM__c = true;
                                break;
                        }
                    }
                } else {
                    for (MVN_RBM_Sharing_Setting__mdt rbmSharingSetting : rbmSharingSettings) {
                        if (rbmSharingSetting.MVN_Type__c.equalsIgnoreCase('Pharmacy') && 
                            rbmSharingSetting.MVN_Status__c.equalsIgnoreCase(carePlan.MVN_Pharmacy_Status__c) && 
                            rbmSharingSetting.MVN_Days_Visible__c > carePlan.MVN_Days_in_Pharmacy_Status__c) {
                                
                                System.debug(LoggingLevel.DEBUG, 'Sharing with RBM because Pharmacy Status was Last Updated and is within Days Visible');
                                carePlan.MVN_Share_with_RBM__c = true;
                                break;
                        }
                    }
                }
            } else {
                System.debug(LoggingLevel.DEBUG, 'No Therapy or Pharmacy Status set on the Care Plan');
            }   
        }
    }

}