force-app/main/default/src/objects/Case/fields/MVN_Case_National_Sales_Director_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_Case_National_Sales_Director_Email__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>National Sales Director Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Case_National_Sales_Director_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Case_National_Sales_Director_Name__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>National Sales Director Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Case_RBM_Director_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_Case_RBM_Director_Email__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RBM Director Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Case_RBM_Director_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Case_RBM_Director_Name__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RBM Director Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Case_RD_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_Case_RD_Email__c</fullName>
    <description>Regional Director Email - for email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RD Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Case_RD_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Case_RD_Name__c</fullName>
    <description>Regional Director Name - for email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RD Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_RBM_TerrName__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_TerrName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RBM Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_RBM_User__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RBM User assigned to this Care Plan.</description>
    <label>RBM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Sales_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_Sales_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>MS Sales Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Sales_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Sales_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>MS Sales Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Enrollment_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Region__c.field-meta.xml
<CustomField>
    <fullName>PJN_Region__c</fullName>
    <description>The region that this case is assigned to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The region that this case is assigned to.</inlineHelpText>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Run_ZTT_Against_Enrollment_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Run_ZTT_Against_Enrollment_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set to TRUE the code will use the enrollment address of the Physician on Physician update in order to apply the Zip To Team mapping.</description>
    <label>Run ZTT Against Enrollment Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Territory__c.field-meta.xml
<CustomField>
    <fullName>PJN_Territory__c</fullName>
    <description>The territory the case is assigned to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The territory the case is assigned to.</inlineHelpText>
    <label>MS Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Zip_To_Team__c.field-meta.xml
<CustomField>
    <fullName>PJN_Zip_To_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The record used to align this case to a care team - Created July 11, 2019</description>
    <label>Zip To Team</label>
    <referenceTo>PJN_Zip_To_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (50): Contact Information External ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Primary__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary__c</fullName>
    <formula>IF(RecordType.DeveloperName = &quot;PJN_Address&quot;, 
  Id = PJN_Account__r.PJN_Primary_Address__c,
  IF(RecordType.DeveloperName = &quot;PJN_Email&quot;,
    Id = PJN_Account__r.PJN_Primary_Email__c,
    IF(RecordType.DeveloperName = &quot;PJN_Phone&quot;,
      Id = PJN_Account__r.PJN_Primary_Phone__c,
      IF(RecordType.DeveloperName = &quot;PJN_Fax&quot;,
        Id = PJN_Account__r.PJN_Primary_Fax__c,
        FALSE
      )
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/PJN_Zip_To_Team__c.object-meta.xml
<CustomObject>
    <description>Zip to Team is used to record mapping between zip codes and Case Managers, Therapeutic Specialists, regions and territories.</description>
    <label>Zip To Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip To Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip To Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_National_Sales_Director_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_National_Sales_Director_Email__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>National Sales Director Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_National_Sales_Director_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_National_Sales_Director_Name__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>National Sales Director Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RBM_Director_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_Director_Email__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RBM Director Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RBM_Director_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_Director_Name__c</fullName>
    <description>For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RBM Director Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RBM_TerrName__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_TerrName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RBM Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RBM_User__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for RBM User, the RBM user assigned to care plans linked to this Zip To Team record.</description>
    <label>RBM User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zip_To_Team_RBM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RD_Email__c.field-meta.xml
<CustomField>
    <fullName>MVN_RD_Email__c</fullName>
    <description>Regional Director Email - For email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RD Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RD_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_RD_Name__c</fullName>
    <description>Regional Director Name - for email alerts in the flow &quot;Send Email to RBM and MS Sales&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>RD Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for ZTT, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (100) External ID field (unique).</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Region__c.field-meta.xml
<CustomField>
    <fullName>PJN_Region__c</fullName>
    <description>The region any case tied to this ZTT is assigned to. Created July 12, 2019</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The region any case tied to this ZTT is assigned to.</inlineHelpText>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Territory__c.field-meta.xml
<CustomField>
    <fullName>PJN_Territory__c</fullName>
    <description>The territory any case tied to this ZTT is assigned to. Created July 12, 2019</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The territory any case tied to this ZTT is assigned to.</inlineHelpText>
    <label>Territory</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_ZipToTeamAssignmentBatchSch.cls
/**
 * @author      Mavens
 * @group       ZipToTeam
 * @description Scheduler batch job of Zip To team Reassignment.
 *              Search by (zip+country+program) key.
 *              The address used is the one selected during Enrollment and stored as a Lookup to the
 *                  Contact Information object in the field "Enrollment Address" in the Care Plan.
 *              If no Physician, then take patient primary address.
 */
public with sharing class MVN_ZipToTeamAssignmentBatchSch implements Schedulable, Database.Batchable<sObject>, Database.AllowsCallouts {

    /**
     * Schedule execute method which will execute the Zip to team reassignment
     * @param SC    Schedule context
     */
    public void execute (SchedulableContext SC) {
        MVN_ZipToTeamAssignmentBatchSch zttAssignmentBatch = new MVN_ZipToTeamAssignmentBatchSch();
        ID batchprocessid = Database.executeBatch(zttAssignmentBatch, 2000);
    }

    /**
     * Start batch job querying all CarePlans to be reassigned
     * @param BC    Batch Context
     * @return  `Database.QueryLocator`
     */
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    AccountId,
                    PJN_Physician__c,
                    PJN_Enrollment_Address__c,
                    PJN_Enrollment_Address__r.PJN_Account__c,
                    PJN_Run_ZTT_Against_Enrollment_Address__c,
                    PJN_Program_DeveloperName__c,
                    MVN_Case_RBM_Director_Name__c,
                    MVN_Case_RBM_Director_Email__c,
                    MVN_Case_National_Sales_Director_Name__c,
                    MVN_Case_National_Sales_Director_Email__c,
                    MVN_Case_RD_Name__c,
                    MVN_Case_RD_Email__c
                FROM
                    Case
                WHERE
                    RecordType.DeveloperName = 'CarePlan' 
            ]
        );
    }

    /**
     * Execute batch job reassigning the CarePlans to the correct Zip To Team
     * @param BC    Batch Context
     * @param scope CarePlans to be reassigned
     */
    public void execute(Database.BatchableContext BC, List<Case> scope) {
        Set<Id> accountIds = new Set<Id>();
        Set<Id> enrollmentContactInformationIds = new Set<Id>();
        Map<Id, List<Case>> carePlansToProcessByAccountId = new Map<Id, List<Case>>();
        for (Case thisCase : scope) {
            if (thisCase.PJN_Physician__c != null) {
                if (!carePlansToProcessByAccountId.containsKey(thisCase.PJN_Physician__c)) {
                    carePlansToProcessByAccountId.put(thisCase.PJN_Physician__c, new List<Case>());
                }
                carePlansToProcessByAccountId.get(thisCase.PJN_Physician__c).add(thisCase);
                if (thisCase.PJN_Enrollment_Address__c != null && thisCase.PJN_Enrollment_Address__r.PJN_Account__c == thisCase.PJN_Physician__c) {
                    enrollmentContactInformationIds.add(thisCase.PJN_Enrollment_Address__c);
                } else {
                    accountIds.add(thisCase.PJN_Physician__c);
                }
            } else if (thisCase.AccountId != null) {
                if (!carePlansToProcessByAccountId.containsKey(thisCase.AccountId)) {
                    carePlansToProcessByAccountId.put(thisCase.AccountId, new List<Case>());
                }
                carePlansToProcessByAccountId.get(thisCase.AccountId).add(thisCase);
                accountIds.add(thisCase.AccountId);
            }
        }
        List<PJN_Contact_Information__c> contactInformations = getContactInformations(enrollmentContactInformationIds, accountIds);
        Set<String> externalIds = new Set<String>();
        Map<Id, Map<String,String>> externalIdByAccountId = buildExternalIds(contactInformations, carePlansToProcessByAccountId, externalIds);
        Map<String, PJN_Zip_To_Team__c> zipToTeamByExternalId = getZipToTeamInformation(externalIds);
        assignCarePlanToCareTeam(carePlansToProcessByAccountId, externalIdByAccountId, zipToTeamByExternalId);
    }

    /**
     * Get Contact Information records for patients and Physicians
     * @param enrollmentContactInformationIds   Set of Contact Information Ids
     * @param accountIds                        Set of Account Ids
     * @return  `List<PJN_Contact_Information__c>`
     */
    private List<PJN_Contact_Information__c> getContactInformations(Set<Id> enrollmentContactInformationIds, Set<Id> accountIds) {
        return [
            SELECT
                PJN_Account__c,
                PJN_Postal_Code__c,
                PJN_Country__c
            FROM
                PJN_Contact_Information__c
            WHERE
                (
                    Id IN :enrollmentContactInformationIds
                )
                OR
                (
                    RecordTypeId = :Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId()
                AND
                    PJN_Account__c IN :accountIds
                AND
                    PJN_Primary__c = true
                )
        ];
    }

    /**
     * Build external ids to query the Zip_To_Team__c object:
     *   External Id = Physician_primary_address.zip_code + '_' + Physician_primary_address_country + '_' + program_developer_name
     *   (If there is no Physician, then it would be patient_primary_address
     * @param contactInformations           List of contact informations to build the ext id
     * @param carePlansToProcessByAccountId Map of care plans by patient/physician
     * @param externalIds                   External Ids
     * @return  `Map<Id, Map<String, String>>`
     */
    private Map<Id, Map<String, String>> buildExternalIds(List<PJN_Contact_Information__c> contactInformations,
                                            Map<Id, List<Case>> carePlansToProcessByAccountId,
                                            Set<String> externalIds) {

        Map<Id, Map<String, String>> externalIdsMap = new Map<Id, Map<String, String>>();
        for (PJN_Contact_Information__c address : contactInformations) {
            String postalCode = address.PJN_Postal_Code__c;
            if (postalCode != null && postalCode.length()>=5) {
                postalCode = postalCode.substring(0,5);
            }
            externalIdsMap.put(address.PJN_Account__c, new Map<String, String>());
            for (Case thisCase : carePlansToProcessByAccountId.get(address.PJN_Account__c)) {
                String externalId = postalCode + '_' +
                                    address.PJN_Country__c + '_' +
                                    thisCase.PJN_Program_DeveloperName__c;
                externalIdsMap.get(address.PJN_Account__c).put(thisCase.PJN_Program_DeveloperName__c, externalId);
                externalIds.add(externalId);
            }
        }
        return externalIdsMap;
    }

    /**
     * Get Zip To Team records by external ids
     * @param externalIds   Set of external ids to run the query
     * @return  `Map<String, PJN_Zip_To_Team__c>`
     */
    private Map<String, PJN_Zip_To_Team__c> getZipToTeamInformation(Set<String> externalIds) {
        List<PJN_Zip_To_Team__c> zipToTeamList = [
            SELECT
                Id,
                PJN_External_ID__c,
                PJN_Region__c,
                PJN_Territory__c,
                MVN_RBM_User__c,
                MVN_RBM_TerrName__c, 
                MVN_Sales_Name__c,
                MVN_Sales_Email__c,
                MVN_RBM_Director_Name__c,
                MVN_RBM_Director_Email__c,
                MVN_National_Sales_Director_Name__c,
                MVN_National_Sales_Director_Email__c,
                MVN_RD_Name__c,
                MVN_RD_Email__c
            FROM
                PJN_Zip_To_Team__c
            WHERE
                PJN_External_ID__c = :externalIds
        ];
        Map<String, PJN_Zip_To_Team__c> zipToTeamByExternalId = new Map<String, PJN_Zip_To_Team__c>();
        for (PJN_Zip_To_Team__c zipToTeam :zipToTeamList) {
            zipToTeamByExternalId.put(zipToTeam.PJN_External_ID__c, zipToTeam);
        }
        return zipToTeamByExternalId;
    }

    /**
     * Copy the information stored in the Zip To Team table to the Care Plan:
     * @param carePlansToProcessByAccountId Map of CarePlans by Patient/Physician
     * @param externalIdByAccountId         ZTT External Id by Patient/Physician
     * @param zipToTeamByExternalId         Zip to Team record by ZTT External Id
     */
    private void assignCarePlanToCareTeam(Map<Id, List<Case>> carePlansToProcessByAccountId,
                                            Map<Id, Map<String, String>> externalIdByAccountId,
                                            Map<String, PJN_Zip_To_Team__c> zipToTeamByExternalId) {

        List<Case> casesToMap = new List<Case>();
        List<Id> sourceObjectIds = new List<Id>();
        for (Id accountId : carePlansToProcessByAccountId.keySet()) {
            for (Case thisCase : carePlansToProcessByAccountId.get(accountId)) {
                Map<String, String> externalIdByProgram = externalIdByAccountId.get(accountId);
                if (externalIdByProgram == null) {
                    continue;
                }
                String externalId = externalIdByProgram.get(thisCase.PJN_Program_DeveloperName__c);
                PJN_Zip_To_Team__c zipToTeam = zipToTeamByExternalId.get(externalId);
                if (zipToTeam == null) {
                    continue;
                }

                thisCase.PJN_Zip_To_Team__c = zipToTeam.Id;
                thisCase.PJN_Run_ZTT_Against_Enrollment_Address__c = false;
                thisCase.PJN_Region__c = zipToTeam.PJN_Region__c;
                thisCase.PJN_Territory__c = zipToTeam.PJN_Territory__c;
                thisCase.MVN_RBM_User__c = zipToTeam.MVN_RBM_User__c;
                thisCase.MVN_RBM_TerrName__c = zipToTeam.MVN_RBM_TerrName__c;
                thisCase.MVN_Sales_Name__c  = zipToTeam.MVN_Sales_Name__c;
                thisCase.MVN_Sales_Email__c = zipToTeam.MVN_Sales_Email__c;
                thisCase.MVN_Case_RBM_Director_Name__c = zipToTeam.MVN_RBM_Director_Name__c;
                thisCase.MVN_Case_RBM_Director_Email__c = zipToTeam.MVN_RBM_Director_Email__c;
                thisCase.MVN_Case_National_Sales_Director_Name__c = zipToTeam.MVN_National_Sales_Director_Name__c;
                thisCase.MVN_Case_National_Sales_Director_Email__c = zipToTeam.MVN_National_Sales_Director_Email__c;
                thisCase.MVN_Case_RD_Name__c = zipToTeam.MVN_RD_Name__c;
                thisCase.MVN_Case_RD_Email__c = zipToTeam.MVN_RD_Email__c;
                casesToMap.add(thisCase);
                sourceObjectIds.add(zipToTeam.Id);
            }
        }
        if (!casesToMap.isEmpty()) {
            PJN_MappingEngine mappingEngine = new PJN_MappingEngine();
            mappingEngine.initiate('PJN_Care_Team_Mapping');
            mappingEngine.run(
                new Map<String, List<Id>> { 'zipToTeam' => sourceObjectIds },
                casesToMap
            );
        }
        update casesToMap;
    }

    /**
     * Finish batch job method
     * @param BC
     */
    public void finish(Database.BatchableContext BC) {
    }
}