force-app/main/default/src/objects/Case/fields/MVN_Copay_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copay Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Cases (Copay Assistance Program)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/recordTypes/PJN_Copay.recordType-meta.xml
<RecordType>
    <fullName>PJN_Copay</fullName>
    <active>true</active>
    <description>An enrollment into Copay savings program.</description>
    <label>Copay Savings</label>
</RecordType>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copay Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Fulfillment Requests</relationshipLabel>
    <relationshipName>Fulfillment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Master-details relationship with Case object.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Fulfillment Requests</relationshipLabel>
    <relationshipName>Fulfillment_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_NewFulfillmentRequestCtrlTest.cls
/**
 * @author      Mavens
 * @group       Fulfillment
 * @description Unit tests for PJN_NewFulfillmentRequestCtrl
 */
@isTest
public with sharing class PJN_NewFulfillmentRequestCtrlTest {

    @TestSetup
    static void makeData(){
        Case carePlan = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Status = 'Test',
            Subject = 'Care Plan',
            PJN_Program_DeveloperName__c = 'PJN_Test_Program'
        );
        insert careplan;
    }

    @isTest
    private static void getFulfillmentRequest() {
        // mocks
        PJN_MappingJobQuery mockMappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());
        PJN_MappingQuery mockMappingQuery = (PJN_MappingQuery) Test.createStub(PJN_MappingQuery.class, new PJN_MappingMock());
        PJN_MappingEngine.mappingJobQuery = mockMappingJobQuery;
        PJN_MappingEngine mockFulfillmentRequestMappingEngine = new PJN_MappingEngine();
        mockFulfillmentRequestMappingEngine.mappingQuery = mockMappingQuery;
        PJN_NewFulfillmentRequestCtrl.fulfillmentRequestMappingEngine = mockFulfillmentRequestMappingEngine;
        PJN_FulfillmentRequestCreationQuery mockFulfillmentRequestCreationQuery = (PJN_FulfillmentRequestCreationQuery) Test.createStub(PJN_FulfillmentRequestCreationQuery.class, new PJN_FulfillmentRequestCreateMock());
        PJN_NewFulfillmentRequestCtrl.fulfillmentRequestCreationQuery = mockFulfillmentRequestCreationQuery;

        // setup data
        RecordType expectedRecordType = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'PJN_Fulfillment_Request__c' AND IsActive = true LIMIT 1];
        Case carePlan = [SELECT Id, PJN_Program_DeveloperName__c FROM Case LIMIT 1];

        PJN_Fulfillment_Request__c expectedFulfillmentRequest = new PJN_Fulfillment_Request__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Program_DeveloperName__c = carePlan.PJN_Program_DeveloperName__c,
            RecordTypeId = expectedRecordType.Id
        );

        // run test
        Test.startTest();
            PJN_Fulfillment_Request__c actualFulfillmentRequest = PJN_NewFulfillmentRequestCtrl.getFulfillmentRequest(expectedFulfillmentRequest);
        Test.stopTest();

        // assert
        System.assertNotEquals(null, actualFulfillmentRequest, 'fulfillment request not populated at all');
        System.assertEquals(expectedFulfillmentRequest.PJN_Program_DeveloperName__c, actualFulfillmentRequest.PJN_Program_DeveloperName__c, 'fulfillment request program not set');
        System.assertEquals(expectedFulfillmentRequest.RecordTypeId, actualFulfillmentRequest.RecordTypeId, 'fulfillment request record type not set');
    }

    @isTest
    private static void getFulfillmentRequestNoMapping() {
        // mocks
        PJN_FulfillmentRequestCreationQuery mockFulfillmentRequestCreationQuery = (PJN_FulfillmentRequestCreationQuery) Test.createStub(PJN_FulfillmentRequestCreationQuery.class, new PJN_FulfillmentRequestCreateMock());
        PJN_NewFulfillmentRequestCtrl.fulfillmentRequestCreationQuery = mockFulfillmentRequestCreationQuery;

        // setup data
        RecordType expectedRecordType = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'PJN_Fulfillment_Request__c' AND IsActive = true LIMIT 1];
        Case carePlan = [SELECT Id, PJN_Program_DeveloperName__c FROM Case LIMIT 1 FOR UPDATE];
        carePlan.PJN_Program_DeveloperName__c = 'PJN_NO_MAPPING';
        update carePlan;

        PJN_Fulfillment_Request__c expectedFulfillmentRequest = new PJN_Fulfillment_Request__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Program_DeveloperName__c = carePlan.PJN_Program_DeveloperName__c,
            RecordTypeId = expectedRecordType.Id
        );

        // run test
        Test.startTest();
            PJN_Fulfillment_Request__c actualFulfillmentRequest = PJN_NewFulfillmentRequestCtrl.getFulfillmentRequest(expectedFulfillmentRequest);
        Test.stopTest();

        // assert
        System.assertNotEquals(null, actualFulfillmentRequest, 'fulfillment request not populated at all');
        System.assertEquals(expectedFulfillmentRequest.PJN_Program_DeveloperName__c, actualFulfillmentRequest.PJN_Program_DeveloperName__c, 'fulfillment request program not set');
        System.assertEquals(expectedFulfillmentRequest.RecordTypeId, actualFulfillmentRequest.RecordTypeId, 'fulfillment request record type not set');
    }

    @isTest
    private static void getFulfillmentRequestNoMappingJobError() {
        // mocks
        PJN_FulfillmentRequestCreationQuery mockFulfillmentRequestCreationQuery = (PJN_FulfillmentRequestCreationQuery) Test.createStub(PJN_FulfillmentRequestCreationQuery.class, new PJN_FulfillmentRequestCreateMock());
        PJN_NewFulfillmentRequestCtrl.fulfillmentRequestCreationQuery = mockFulfillmentRequestCreationQuery;

        // setup data
        RecordType expectedRecordType = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'PJN_Fulfillment_Request__c' AND IsActive = true LIMIT 1];
        Case carePlan = [SELECT Id, PJN_Program_DeveloperName__c FROM Case LIMIT 1];

        PJN_Fulfillment_Request__c expectedFulfillmentRequest = new PJN_Fulfillment_Request__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Program_DeveloperName__c = carePlan.PJN_Program_DeveloperName__c,
            RecordTypeId = expectedRecordType.Id
        );

        // run test
        Test.startTest();
            try {
                PJN_Fulfillment_Request__c actualFulfillmentRequest = PJN_NewFulfillmentRequestCtrl.getFulfillmentRequest(expectedFulfillmentRequest);
            } catch(AuraHandledException auraEx) {
                // assert
                System.assertNotEquals(null, auraEx, 'no expected exception');
                System.assert(
                    auraEx.getMessage().startsWith(
                        String.format(
                            Label.PJN_Contact_Admin,
                            new List<String> { '' }
                        )
                    ),
                    'incorrect message set'
                );
            }
        Test.stopTest();
    }

    @isTest
    private static void insertFulfillmentRequest() {
        // mocks
        PJN_MappingJobQuery mockMappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());
        PJN_MappingQuery mockMappingQuery = (PJN_MappingQuery) Test.createStub(PJN_MappingQuery.class, new PJN_MappingMock());
        PJN_MappingEngine.mappingJobQuery = mockMappingJobQuery;
        PJN_MappingEngine mockFulfillmentRequestMappingEngine = new PJN_MappingEngine();
        mockFulfillmentRequestMappingEngine.mappingQuery = mockMappingQuery;
        PJN_NewFulfillmentRequestCtrl.fulfillmentRequestMappingEngine = mockFulfillmentRequestMappingEngine;
        PJN_FulfillmentRequestCreationQuery mockFulfillmentRequestCreationQuery = (PJN_FulfillmentRequestCreationQuery) Test.createStub(PJN_FulfillmentRequestCreationQuery.class, new PJN_FulfillmentRequestCreateMock());
        PJN_NewFulfillmentRequestCtrl.fulfillmentRequestCreationQuery = mockFulfillmentRequestCreationQuery;

        // setup data
        RecordType expectedRecordType = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'PJN_Fulfillment_Request__c' AND IsActive = true LIMIT 1];
        Case carePlan = [SELECT Id, PJN_Program_DeveloperName__c FROM Case LIMIT 1];

        PJN_Assistance_Program__c assistanceProgram = new PJN_Assistance_Program__c(
            RecordTypeId = Schema.SObjectType.PJN_Assistance_Program__c.getRecordTypeInfosByDeveloperName().get('PJN_Copay').getRecordTypeId(),
            PJN_Care_Plan__c = carePlan.Id
        );
        insert assistanceProgram;
        
        PJN_Fulfillment_Request__c expectedFulfillmentRequest = new PJN_Fulfillment_Request__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Program_DeveloperName__c = carePlan.PJN_Program_DeveloperName__c,
            RecordTypeId = expectedRecordType.Id,
            MVN_Copay_Assistance_Program__c = assistanceProgram.Id
        );

        // run test
        Test.startTest();
            PJN_Fulfillment_Request__c actualFulfillmentRequest = PJN_NewFulfillmentRequestCtrl.getFulfillmentRequest(expectedFulfillmentRequest);
            insert actualFulfillmentRequest;
        Test.stopTest();

        // assert
        System.assertNotEquals(null, actualFulfillmentRequest, 'fulfillment request not populated at all');
        System.assertEquals(expectedFulfillmentRequest.PJN_Program_DeveloperName__c, actualFulfillmentRequest.PJN_Program_DeveloperName__c, 'fulfillment request program not set');
        System.assertEquals(expectedFulfillmentRequest.RecordTypeId, actualFulfillmentRequest.RecordTypeId, 'fulfillment request record type not set');
    }
}