force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Missing_Information_Config__mdt/PJN_Missing_Information_Config__mdt.object-meta.xml
<CustomObject>
    <description>Missing Information Configuration to identify the fields with missing information in the Care Plan related.
All these configurations are applied to the Care Plan with a specific Program.</description>
    <label>Missing Information Config</label>
    <pluralLabel>Missing Information Configs</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Missing_Information_Config__mdt/fields/PJN_Field_Path__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_Path__c</fullName>
    <description>Field API name path to verify the missing information. Eg: Account.FirstName or CaseNumber</description>
    <inlineHelpText>Field API name path to verify the missing information. Eg: Account.FirstName or CaseNumber</inlineHelpText>
    <label>Field Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Missing_Information_Config__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <description>Care Plan program which applies this configuration. Eg: Evkeeza</description>
    <inlineHelpText>Care Plan program which applies this configuration. Eg: Evkeeza</inlineHelpText>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Missing Information Configs</relationshipLabel>
    <relationshipName>PJN_Missing_Information_Configs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_MissingInformationConfigQuery.cls
/**
 * @author      Mavens
 * @group       MissingInformation
 * @description Missing Information Config Queries
 */
public with sharing class PJN_MissingInformationConfigQuery {

    /**
     * CACHE Missing Information Config
     */
    private Map<String, List<PJN_Missing_Information_Config__mdt>> missingInfoConfigsByProgramName;

    /**
     * Query Missing Information Config by Program Case Developer Name
     * @param programCaseDeveloperName  Program Case Developer Name
     * @return  `List<PJN_Missing_Information_Config__mdt>`
     */
    public List<PJN_Missing_Information_Config__mdt> queryMissingInfoConfigsByProgramName(String programCaseDeveloperName) {
        if (missingInfoConfigsByProgramName == null) {
            missingInfoConfigsByProgramName = new  Map<String, List<PJN_Missing_Information_Config__mdt>>();
        }
        if (!missingInfoConfigsByProgramName.containsKey(programCaseDeveloperName)) {
            for (PJN_Missing_Information_Config__mdt missingInfoConfig : queryAllMissingInfoConfigs()) {
                List<PJN_Missing_Information_Config__mdt> currentMICs = missingInfoConfigsByProgramName.containsKey(missingInfoConfig.PJN_Program__r.DeveloperName) ?
                    missingInfoConfigsByProgramName.get(missingInfoConfig.PJN_Program__r.DeveloperName) :
                    new List<PJN_Missing_Information_Config__mdt>();
                currentMICs.add(missingInfoConfig);
                missingInfoConfigsByProgramName.put(missingInfoConfig.PJN_Program__r.DeveloperName, currentMICs);
            }
        }
        return missingInfoConfigsByProgramName.containsKey(programCaseDeveloperName) ?
            missingInfoConfigsByProgramName.get(programCaseDeveloperName) :
            new List<PJN_Missing_Information_Config__mdt>();
    }

    /**
     * Query All Missing Information Configs
     * @return  `List<PJN_Missing_Information_Config__mdt>`
     */
    private static List<PJN_Missing_Information_Config__mdt> queryAllMissingInfoConfigs() {
        return [
            SELECT
                Id,
                DeveloperName,
                MasterLabel,
                PJN_Program__c,
                PJN_Program__r.DeveloperName,
                PJN_Field_Path__c
            FROM
                PJN_Missing_Information_Config__mdt
        ];
    }
}