force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Case__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case that triggered the Event.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_New_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_New_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New physician account related to a care plan.</description>
    <label>New Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events (New Physician)</relationshipLabel>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient to whose care plan the event is related.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Previous_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Previous_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous physician account related to a care plan.</description>
    <label>Previous Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events (Previous Physician)</relationshipLabel>
    <relationshipName>Events2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/PJN_Physician_Change.recordType-meta.xml
<RecordType>
    <fullName>PJN_Physician_Change</fullName>
    <active>true</active>
    <description>Defines an event representing a known physician change for a patient</description>
    <label>Physician Change</label>
</RecordType>

force-app/main/default/src/classes/PJN_EventCreation.cls
/**
 * @author Mavens
 * @date May 2019
 * @description Creates an Event if the physician lookup on the Care Plan is updated
 * @group event-triggers
 */
public with sharing class PJN_EventCreation implements PJN_TriggerDispatcher.HandlerInterface {

    /**
     * Handle the trigger call
     */
    public void handle() {
        Set<Id> caseIds = new Set<Id>();
        for (Case currentCase : (List<Case>)Trigger.new) {
            if (this.isPhysicianUpdated(currentCase.Id)) {
                caseIds.add(currentCase.Id);
            }
        }
        createEvents(caseIds);
    }
    /**
     * Checks if the Physician lookup field has been updated for a care plan case
     * @param  caseId case id
     * @returns Boolean
     */
    private Boolean isPhysicianUpdated(Id caseId) {
        Case oldCase = (Case) Trigger.oldMap.get(caseId);
        Case newCase = (Case) Trigger.newMap.get(caseId);
        if (newCase.RecordTypeId == SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId()
            && oldCase.PJN_Physician__c != newCase.PJN_Physician__c) {
            return true;
        }
        return false;
    }

    /**
     * Create Event records with record type Physician Change
     * @param  caseIds case Ids to create the events against
     */
    private void createEvents(Set<Id> caseIds) {
        List<PJN_Event__c> events = new List<PJN_Event__c>();
        if (!caseIds.isEmpty()) {
            for (Id caseId : caseIds) {
                Case oldCase = (Case) Trigger.oldMap.get(caseId);
                Case newCase = (Case) Trigger.newMap.get(caseId);
                events.add(
                    new PJN_Event__c(
                        RecordTypeId = SObjectType.PJN_Event__c.getRecordTypeInfosByDeveloperName().get('PJN_Physician_Change').getRecordTypeId(),
                        PJN_Patient__c = newCase.AccountId,
                        PJN_Case__c = newCase.Id,
                        PJN_New_Physician__c = newCase.PJN_Physician__c,
                        PJN_Previous_Physician__c = oldCase.PJN_Physician__c
                    )
                );
            }
            insert events;
        }
    }
}