force-app/main/default/src/objects/Case/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related Coverage Investigation where the follow-up Case was generated from.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Follow-Up Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Activity.recordType-meta.xml
<RecordType>
    <fullName>PJN_Activity</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities related to a patient&apos;s care plan</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Coverage Investigation where the Assistance Program was generated from.</description>
    <label>Coverage Investigation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.PJN_Care_Plan__c</field>
            <operation>equals</operation>
            <valueField>PJN_Coverage_Investigation__c.PJN_Care_Plan__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Member Plan which a Copay Assistance Program is linked to.</description>
    <label>Member Plan</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a Member Plan from the same Care Plan.</errorMessage>
        <filterItems>
            <field>PJN_Member_Plan__c.PJN_Care_Plan__c</field>
            <operation>equals</operation>
            <valueField>$Source.PJN_Care_Plan__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Copay Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>The parent Care Plan where the Coverage Investigation is run from.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/PJN_Coverage_Investigation_Item__c.object-meta.xml
<CustomObject>
    <description>Patient Journey Navigator custom object which stores the join between a Coverage Investigation and the items involved such as Member Plans.</description>
    <label>Coverage Investigation Item</label>
    <nameField>
        <displayFormat>CII-{000000}</displayFormat>
        <label>Coverage Investigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Assistance Programs being assessed in the Coverage Investigation.</description>
    <label>Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <description>The parent Coverage Investigation which the items are related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Prior_Authorization__c.field-meta.xml
<CustomField>
    <fullName>PJN_Prior_Authorization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Prior Authorization</label>
    <referenceTo>PJN_Prior_Authorization__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Case__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case that triggered the Event.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Coverage Investigation where the Therapy Access event is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Therapy Access</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient to whose care plan the event is related.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/PJN_Therapy_Access.recordType-meta.xml
<RecordType>
    <fullName>PJN_Therapy_Access</fullName>
    <active>true</active>
    <description>Defines an event representing how a patient is accessing therapy and the date periods.</description>
    <label>Therapy Access</label>
</RecordType>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Coverage_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Order__c</fullName>
    <description>Picklist for the plan&apos;s coverage order number as part of the coordination of benefits rules.</description>
    <label>Coverage Order</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient who is a member of an insurance plan.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/PJN_Prior_Authorization__c.object-meta.xml
<CustomObject>
    <description>Custom object to track prior authorizations related to member plans.</description>
    <label>Prior Authorization</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Prior Authorization Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan the parent member plan belongs to.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Coverage Investigation which the Prior Authorization is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <description>Master detail relationship with Member Plan.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Submitted_Date__c</fullName>
    <description>Prior authorization submission date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/classes/PJN_CoverageInvestigationUpdaterCtrl.cls
/**
 * @author      Mavens
 * @date        12/2020
 * @description Controller for pjnCoverageInvestigationUpdater lwc
 * @group       CoverageInvestigation
 */
public with sharing class PJN_CoverageInvestigationUpdaterCtrl {

    private class PJN_CoverageInvestigationUpdaterCtrlException extends exception {}

    @AuraEnabled
    public static PJN_DataTable getTable(String investigationId, String childObjectApiName){
        try {
            switch on (childObjectApiName) {
                when 'PJN_Member_Plan__c' { return memberPlanTable(investigationId); }
                when 'PJN_Prior_Authorization__c' { return priorAuthTable(investigationId); }
                when 'PJN_Assistance_Program__c' { return assistanceProgramTable(investigationId); }
            }
            throw new PJN_CoverageInvestigationUpdaterCtrlException('Unable to process object with api name ' + childObjectApiName + '. Please check spelling.');
        } catch (Exception e) {
            AuraHandledException ex = new AuraHandledException(e.getMessage());
            ex.setMessage(e.getMessage());
            throw ex;
        }
    }

    @AuraEnabled
    public static List<InputField> getFields(String objectApiName){
        try {
            List<InputField> inputFields = new List<InputField>();
            for (FieldSetMember fsm : Schema.getGlobalDescribe().get(objectApiName).getDescribe().fieldSets.getMap().get('PJN_Coverage_Investigation_Update_Screen').getFields()) {
                inputFields.add( new InputField(fsm));
            }
            return inputFields;
        } catch (Exception e) {
            AuraHandledException ex = new AuraHandledException(e.getMessage());
            ex.setMessage(e.getMessage());
            throw ex;
        }
    }

    public class InputField {
        @AuraEnabled public String name;
        @AuraEnabled public Boolean required;

        public InputField(FieldSetMember fsm) {
            this.name = fsm.getFieldPath();
            this.required = fsm.getRequired();
        }
    }

    @AuraEnabled
    public static String getTherapyAccessRecTypeId() {
        return PJN_Event__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PJN_Therapy_Access').getRecordTypeId();
    }

    @AuraEnabled
    public static void submit(Map<String, SObject> data){
        try {
            if (data.containsKey('PJN_Coverage_Investigation__c')) {
                PJN_Coverage_Investigation__c investigation = (PJN_Coverage_Investigation__c) data.get('PJN_Coverage_Investigation__c');
                update investigation;
            }

            if (data.containsKey('Case')) {
                Case activity = (Case) data.get('Case');
                Case carePlanInfo = getCarePlanInfo(activity.PJN_Coverage_Investigation__c);
                activity.ParentId = carePlanInfo.Id;
                activity.AccountId = carePlanInfo.AccountId;
                activity.PJN_Program__c = carePlanInfo.PJN_Program__c;
                activity.PJN_Program_DeveloperName__c = carePlanInfo.PJN_Program_DeveloperName__c;
                activity.RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId();
                insert activity;
            }

            if (data.containsKey('PJN_Event__c')) {
                PJN_Event__c event = (PJN_Event__c) data.get('PJN_Event__c');
                Case carePlanInfo = getCarePlanInfo(event.PJN_Coverage_Investigation__c);
                event.PJN_Case__c = carePlanInfo.Id;
                event.PJN_Patient__c = carePlanInfo.AccountId;
                event.PJN_Program_DeveloperName__c = carePlanInfo.PJN_Program_DeveloperName__c;
                event.RecordTypeId = PJN_Event__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PJN_Therapy_Access').getRecordTypeId();
                insert event;
            }
        } catch (Exception e) {
            AuraHandledException ex = new AuraHandledException(e.getMessage());
            ex.setMessage(e.getMessage() + ' ' + e.getStackTraceString());
            throw ex;
        }
    }

    private static Case getCarePlanInfo(Id investigationId) {
        PJN_Coverage_Investigation__c investigation = [
            SELECT PJN_Care_Plan__r.Id, PJN_Care_Plan__r.AccountId, PJN_Care_Plan__r.PJN_Program__c, PJN_Care_Plan__r.PJN_Program_DeveloperName__c
            FROM PJN_Coverage_Investigation__c
            WHERE Id = :investigationId
        ];

        return investigation.PJN_Care_Plan__r;
    }


    /*
     * Query for member plans attached to investigation items
     */
    private static PJN_DataTable memberPlanTable(String investigationId) {

        PJN_DataTable table = new PJN_DataTable();
        table.columns = new List<PJN_FieldWrapper>();

        List<PJN_Coverage_Investigation_Item__c> items = [
            SELECT PJN_Member_Plan__c
            FROM PJN_Coverage_Investigation_Item__c
            WHERE PJN_Coverage_Investigation__c = :investigationId
        ];

        Set<Id> memberPlanIds = new Set<Id>();
        for (PJN_Coverage_Investigation_Item__c item : items) {
            memberPlanIds.add(item.PJN_Member_Plan__c);
        }

        List<String> fields = new List<String>();
        Map<String, Schema.SObjectField> fieldMap = PJN_Member_Plan__c.SObjectType.getDescribe().fields.getMap();

        for (FieldSetMember fsm : Schema.SObjectType.PJN_Member_Plan__c.fieldSets.PJN_Coverage_Investigation_Update_Screen.getFields()) {
            // prepare the fields for query
            fields.add(fsm.fieldpath);

            // add the fields as columns for the data table
            table.columns.add(
                new PJN_FieldWrapper('PJN_Member_Plan__c', fieldMap.get(fsm.fieldpath).getDescribe())
            );
        }

        String queryString = String.format(
            'SELECT {0} FROM PJN_Member_Plan__c WHERE Id IN :memberPlanIds ORDER BY PJN_Coverage_Order__c',
            new List<String> { String.join(fields, ', ') }
        );

        System.debug('QueryString: ' + queryString);
        table.data = Database.query(queryString);

        return table;
    }

    /*
     * Query for prior authorizations attached to the investigation
     */
    private static PJN_DataTable priorAuthTable(String investigationId) {
        PJN_DataTable table = new PJN_DataTable();
        table.columns = new List<PJN_FieldWrapper>();

        List<String> fields = new List<String>();
        Map<String, Schema.SObjectField> fieldMap = PJN_Prior_Authorization__c.SObjectType.getDescribe().fields.getMap();

        for (FieldSetMember fsm : Schema.SObjectType.PJN_Prior_Authorization__c.fieldSets.PJN_Coverage_Investigation_Update_Screen.getFields()) {
            // prepare the fields for query
            fields.add(fsm.fieldpath);

            // add the fields as columns for the data table
            table.columns.add(
                new PJN_FieldWrapper('PJN_Prior_Authorization__c', fieldMap.get(fsm.fieldpath).getDescribe())
            );
        }

        String queryString = String.format(
            'SELECT {0} FROM PJN_Prior_Authorization__c WHERE PJN_Coverage_Investigation__c = :investigationId ORDER BY PJN_Submitted_Date__c DESC',
            new List<String> { String.join(fields, ', ') }
        );

        System.debug('QueryString: ' + queryString);
        table.data = Database.query(queryString);

        return table;
    }

    /*
     * Query for assistance programs attached to the investigation
     */
    private static PJN_DataTable assistanceProgramTable(String investigationId) {
        PJN_DataTable table = new PJN_DataTable();
        table.columns = new List<PJN_FieldWrapper>();

        List<String> fields = new List<String>();
        Map<String, Schema.SObjectField> fieldMap = PJN_Assistance_Program__c.SObjectType.getDescribe().fields.getMap();

        for (FieldSetMember fsm : Schema.SObjectType.PJN_Assistance_Program__c.fieldSets.PJN_Coverage_Investigation_Update_Screen.getFields()) {
            // prepare the fields for query
            fields.add(fsm.fieldpath);

            // add the fields as columns for the data table
            table.columns.add(
                new PJN_FieldWrapper('PJN_Assistance_Program__c', fieldMap.get(fsm.fieldpath).getDescribe())
            );
        }

        String queryString = String.format(
            'SELECT {0} FROM PJN_Assistance_Program__c WHERE PJN_Coverage_Investigation__c = :investigationId',
            new List<String> { String.join(fields, ', ') }
        );

        System.debug('QueryString: ' + queryString);
        table.data = Database.query(queryString);

        return table;
    }
}