force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Setting__mdt/PJN_Enrollment_Wizard_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Enrollment Wizard
Purpose: Define enrollment wizard settings by program developer name. This is the first step in setting up the Enrollment Wizard.
Metadata Relationship(s): Enrollment Wizard Step
Created by Mavens: Yes</description>
    <label>Enrollment Wizard Setting</label>
    <pluralLabel>Enrollment Wizard Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Setting__mdt/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Step__mdt/PJN_Enrollment_Wizard_Step__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Enrollment Wizard
Purpose: Define enrollment wizard screen and its order for a specific enrollment wizard setting. This is step 2 in setting up the Enrollment Wizard.
Metadata Relationship(s): Enrollment Wizard Setting; Enrollment Wizard Component
Created by Mavens: Yes</description>
    <label>Enrollment Wizard Step</label>
    <pluralLabel>Enrollment Wizard Steps</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Step__mdt/fields/PJN_Enrollment_Wizard_Setting__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Wizard_Setting__c</fullName>
    <label>Enrollment Wizard Setting</label>
    <referenceTo>PJN_Enrollment_Wizard_Setting__mdt</referenceTo>
    <relationshipLabel>Enrollment Wizard Steps</relationshipLabel>
    <relationshipName>PJN_Enrollment_Wizard_Steps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Step__mdt/fields/PJN_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/classes/PJN_EnrollmentWizardStepMock.cls
/**
* @author Mavens
* @date Apr 2019
* @description Mock Provider for Enrollment Wizard Step custom metadata
* @group Mock
*/
@isTest(isParallel=true) public with sharing class PJN_EnrollmentWizardStepMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {

        if (stubbedMethodName == 'getEnrollmentStepsByProgram'){
            return this.getEnrollmentStepsByProgram((String) listOfArgs[0]);
        } else {
            return null;
        }
    }

    private Object getEnrollmentStepsByProgram(String programDevName) {
        if (programDevName == null) {
            String msg = 'No enrollment settings found. Please contact your administrator';
            throw new PJN_EnrollmentWizardException(msg);
        }
        PJN_Enrollment_Wizard_Setting__mdt setting = new PJN_Enrollment_Wizard_Setting__mdt(
            MasterLabel = 'Cholecap Enrollment Setting',
            PJN_Program_DeveloperName__c = 'PJN_CLP'
        );

        List<PJN_Enrollment_Wizard_Step__mdt> stepList = new List<PJN_Enrollment_Wizard_Step__mdt>();
        stepList.add(
            new PJN_Enrollment_Wizard_Step__mdt(
                MasterLabel = 'Case Step',
                DeveloperName = 'PJN_Case_Step',
                PJN_Enrollment_Wizard_Setting__c = setting.Id,
                PJN_Order__c = 10
            )
        );
        stepList.add(
            new PJN_Enrollment_Wizard_Step__mdt(
                MasterLabel = 'Prescription Step',
                DeveloperName = 'PJN_Prescription_Step',
                PJN_Enrollment_Wizard_Setting__c = setting.Id,
                PJN_Order__c = 20
            )
        );
        return stepList;
    }
}