force-app/main/default/src/objects/Case/fields/PJN_Activity_Timeline_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Activity_Timeline_Status__c</fullName>
    <formula>CASE(
    TEXT(Status), 
    &apos;Open&apos;, &apos;open&apos;, 
    &apos;Closed&apos;, &apos;closed&apos;,
    &apos;Cancelled&apos;, &apos;cancelled&apos;,
    &apos;Open&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity Timeline Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_Case_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Case_DeveloperName__c</fullName>
    <description>Program Case DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Case DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Program_Problem_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Problem DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Care_Plan_Timeline_Case_Field__mdt/PJN_Care_Plan_Timeline_Case_Field__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Care Plan Timeline
Purpose: Define the fields to be displayed for each case in the care plan timeline, based on case Status.
Metadata Relationship(s): Care Plan Timeline Case
Created by Mavens: Yes</description>
    <label>Care Plan Timeline Case Field</label>
    <pluralLabel>Care Plan Timeline Case Fields</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Care_Plan_Timeline_Case_Field__mdt/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Case__mdt/PJN_Program_Case__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Case activities that are specific to a Program Problem, and are created automatically on a Care Plan when the patient enters that Program Problem/Stage.
Metadata Relationship(s): Program Problem; Program Case Dependency
Created by Mavens: Yes</description>
    <label>Program Case</label>
    <pluralLabel>Program Cases</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_CarePlanProblemCasesCtrl.cls
/**
 * @author      Mavens
 * @group       CarePlan-UI
 * @description get care plan problem cases
 */
public with sharing class PJN_CarePlanProblemCasesCtrl {
    /**
     * program case query
     */
    @testVisible private static PJN_ProgramCaseQuery programCaseQuery = new PJN_ProgramCaseQuery();

    /**
     * care plan timeline case field query
     */
    @testVisible private static PJN_CarePlanTimelineCaseFieldQuery carePlanTimelineCaseFieldQuery = new PJN_CarePlanTimelineCaseFieldQuery();

    /**
     * get care plan problem cases for this problem
     * @param   HealthCloudGA__CarePlanProblem__c        carePlanProblem
     * @returns  List<PJN_CarePlanCaseWrapper>
     */
    @auraEnabled public static List<PJN_CarePlanCaseWrapper> getCarePlanProblemCases(HealthCloudGA__CarePlanProblem__c carePlanProblem) {
        List<PJN_CarePlanCaseWrapper> carePlanCases = new List<PJN_CarePlanCaseWrapper>();
        Set<String> carePlanCaseSet = new Set<String>();
        PJN_CarePlanCaseQuery.fields.addAll(addTimelineCaseFields(carePlanProblem.HealthCloudGA__CarePlan__r.PJN_Program_DeveloperName__c));
        for(Case thisCase : PJN_CarePlanCaseQuery.queryCasesByProblem(carePlanProblem.Id)) {
            if(String.isBlank(thisCase.PJN_Program_Case_DeveloperName__c)) {
                carePlanCases.add(new PJN_CarePlanCaseWrapper(thisCase));
            } else {
                carePlanCaseSet.add(thisCase.PJN_Program_Case_DeveloperName__c);
                carePlanCases.add(new PJN_CarePlanCaseWrapper(thisCase));
            }
        }
        for(PJN_Program_Case__mdt thisProgramCase : programCaseQuery.queryByProgramProblemDeveloperName(carePlanProblem.PJN_Program_Problem_DeveloperName__c)) {
            if(!carePlanCaseSet.contains(thisProgramCase.DeveloperName)) {
                carePlanCaseSet.add(thisProgramCase.DeveloperName);
                carePlanCases.add(new PJN_CarePlanCaseWrapper(thisProgramCase));
            }
        }
        return carePlanCases;
    }

    /**
     * get care plan cases by care plan program
     * @param   Id        carePlanId
     * @returns  List<PJN_CarePlanCaseWrapper>
     */
    @auraEnabled public static List<PJN_CarePlanCaseWrapper> getCarePlanCases(Id carePlanId) {
        List<PJN_CarePlanCaseWrapper> carePlanCases = new List<PJN_CarePlanCaseWrapper>();
        Case carePlan = PJN_CarePlanQuery.queryById(carePlanId);
        PJN_CarePlanCaseQuery.fields.addAll(addTimelineCaseFields(carePlan.PJN_Program_DeveloperName__c));
        for(Case thisCase : PJN_CarePlanCaseQuery.queryCasesByCarePlan(carePlanId)) {
            carePlanCases.add(new PJN_CarePlanCaseWrapper(thisCase));
        }
        return carePlanCases;
    }

    /**
     * add fields to query for for the timeline feed config
     * @param   String        programDeveloperName
     * @returns  Set<String>
     */
    private static Set<String> addTimelineCaseFields(String programDeveloperName) {
        Set<String> fields = new Set<String> { 'PJN_Activity_Timeline_Status__c' };
        for(PJN_Care_Plan_Timeline_Case_Field__mdt thisTimelineCaseField : carePlanTimelineCaseFieldQuery.queryByCarePlanProgram(programDeveloperName)) {
            fields.add(thisTimelineCaseField.PJN_Field_API_Name__c);
        }
        return fields;
    }

    /**
     * Get record type id by developer name
     * @param  developerName  record type developer name
     * @returns Id
     */
    @AuraEnabled public static Id getRecordTypeId(String developerName){
        return SObjectType.Case.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
    }
}