force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/HealthCloudGA__EhrMedicationPrescription__c.object-meta.xml
<CustomObject>
    <description>An order for both supply of the medication and the instructions for administration of the medicine to a patient.</description>
    <label>EHR Medication Prescription</label>
    <nameField>
        <displayFormat>Pres-{0}</displayFormat>
        <label>EHR Medication Prescription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EHR Medication Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/fields/HealthCloudGA__Account__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Individual account which represents the patient in force.com</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medication Prescriptions</relationshipLabel>
    <relationshipName>MedicationPrescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>EHR_Medication_Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The prescription prescriber.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prescriptions (Physician)</relationshipLabel>
    <relationshipName>PrescriptionsPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__EhrMedicationPrescription__c/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>DeveloperName of the program to which this record&apos;s Care Plan relates.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Point_Type_Consent__c/PJN_Contact_Point_Type_Consent__c.object-meta.xml
<CustomObject>
    <description>Contact Point Type Consent custom object.</description>
    <label>Consent</label>
    <nameField>
        <displayFormat>CPTC-{0000000}</displayFormat>
        <label>Consent Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Point_Type_Consent__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Master-detail (Case) to care plan.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>PJN_Contact_Point_Type_Consent</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Point_Type_Consent__c/fields/PJN_Creation_UUID__c.field-meta.xml
<CustomField>
    <fullName>PJN_Creation_UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Creation UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Point_Type_Consent__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient related to the consent record.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Program Participant</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Libtayo Marketing Program Participant</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consents (Patient)</relationshipLabel>
    <relationshipName>PatientConsents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Coverage_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Order__c</fullName>
    <description>Picklist for the plan&apos;s coverage order number as part of the coordination of benefits rules.</description>
    <label>Coverage Order</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient who is a member of an insurance plan.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Set_as_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to indicate that a patient&apos;s member plan should be set to active. Triggers the member plan to be stamped into the PJN_Primary_Member_Plan__c, PJN_Secondary_Member_Plan__c, or PJN_Tertiary_Member_Plan__c case fields (depending on member plan&apos;s PJN_Coverage_Order__c value) and sets the PJN_Active__c checkbox on the member plan to TRUE.</description>
    <label>Set as Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanFieldsMappingTest.cls
/**
 * @author      Mavens
 * @group       CarePlan-UI
 * @description Unit tests for PJN_CarePlanCaseWrapper
 */
@isTest
public class PJN_CarePlanFieldsMappingTest {

    static Map<String, RecordTypeInfo> acctRecTypes = SObjectType.Account.getRecordTypeInfosByDeveloperName();

    @TestSetup
    static void makeData(){
        Account patient = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId(),
            LastName = 'Test Patient'
        );
        Account physician = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
            LastName = 'Test Physician'
        );
        insert new List<Account> {patient, physician};
        Test.startTest();
        Case careplan = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Status = 'Test',
            Subject = 'Care Plan',
            AccountId = patient.Id,
            PJN_Physician__c = physician.Id,
            PJN_Program_DeveloperName__c = 'PJN_Test_Program'
        );
        insert careplan;
        Test.stopTest();
    }

    @isTest
    private static void handleCareplanFieldsMappingForPrescription() {
        Case carePlan = [SELECT Id, AccountId, PJN_Program_DeveloperName__c, PJN_Physician__c FROM Case LIMIT 1];

        HealthCloudGA__EhrMedicationPrescription__c prescriptionToInsert = new HealthCloudGA__EhrMedicationPrescription__c(
            PJN_Care_Plan__c = careplan.Id
        );

        Test.startTest();
            Database.SaveResult actualSaveResult = Database.insert(prescriptionToInsert);
        Test.stopTest();

        HealthCloudGA__EhrMedicationPrescription__c actualPrescription = [
            SELECT
                Id,
                PJN_Care_Plan__c,
                PJN_Program_DeveloperName__c,
                PJN_Creation_UUID__c,
                HealthCloudGA__Account__c,
                PJN_Physician__c
            FROM
                HealthCloudGA__EhrMedicationPrescription__c
            WHERE
                Id = :prescriptionToInsert.Id
        ];

        System.assertEquals(true, actualSaveResult.isSuccess());
        System.assertEquals(careplan.Id, actualPrescription.PJN_Care_Plan__c);
        System.assertEquals(careplan.PJN_Program_DeveloperName__c, actualPrescription.PJN_Program_DeveloperName__c);
        System.assertNotEquals(null, actualPrescription.PJN_Creation_UUID__c);
        System.assertEquals(careplan.AccountId, actualPrescription.HealthCloudGA__Account__c);
        System.assertEquals(careplan.PJN_Physician__c, actualPrescription.PJN_Physician__c);
    }

    @isTest
    private static void handleCareplanFieldsMappingForMemberPlan() {
        Case carePlan = [SELECT Id, AccountId FROM Case LIMIT 1];

        PJN_Member_Plan__c memberPlanToInsert = new PJN_Member_Plan__c(
            PJN_Care_Plan__c = careplan.Id,
            PJN_Set_as_Active__c = true,
            PJN_Coverage_Order__c = 'Primary'
        );

        Test.startTest();
            Database.SaveResult actualSaveResult = Database.insert(memberPlanToInsert);
        Test.stopTest();

        PJN_Member_Plan__c actualMemberPlan = [
            SELECT
                Id,
                PJN_Care_Plan__c,
                PJN_Creation_UUID__c,
                PJN_Patient__c
            FROM
                PJN_Member_Plan__c
            WHERE
                Id = :memberPlanToInsert.Id
        ];

        System.assertEquals(true, actualSaveResult.isSuccess());
        System.assertEquals(careplan.Id, actualMemberPlan.PJN_Care_Plan__c);
        System.assertNotEquals(null, actualMemberPlan.PJN_Creation_UUID__c);
        System.assertEquals(careplan.AccountId, actualMemberPlan.PJN_Patient__c);
    }

    @isTest
    private static void handleCareplanFieldsMappingForConsent() {
        Case carePlan = [SELECT Id, AccountId FROM Case LIMIT 1];

        PJN_Contact_Point_Type_Consent__c consentToInsert = new PJN_Contact_Point_Type_Consent__c(
            PJN_Care_Plan__c = careplan.Id
        );

        Test.startTest();
            Database.SaveResult actualSaveResult = Database.insert(consentToInsert);
        Test.stopTest();

        PJN_Contact_Point_Type_Consent__c actualConsent = [
            SELECT
                Id,
                PJN_Care_Plan__c,
                PJN_Creation_UUID__c,
                PJN_Patient__c
            FROM
                PJN_Contact_Point_Type_Consent__c
            WHERE
                Id = :consentToInsert.Id
        ];

        System.assertEquals(true, actualSaveResult.isSuccess());
        System.assertEquals(careplan.Id, actualConsent.PJN_Care_Plan__c);
        System.assertNotEquals(null, actualConsent.PJN_Creation_UUID__c);
        System.assertEquals(careplan.AccountId, actualConsent.PJN_Patient__c);
    }
}