force-app/main/default/src/objects/Case/fields/PJN_Care_Plan_Start_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan_Start_Status__c</fullName>
    <description>Used to trigger a care plan to start and track it&apos;s status</description>
    <label>Care Plan Start Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PJN_Initiate</fullName>
                <label>Initiate</label>
            </value>
            <value>
                <fullName>PJN_Pending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>PJN_Started</fullName>
                <label>Started</label>
            </value>
            <value>
                <fullName>PJN_Error</fullName>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Event__e/PJN_Program_Event__e.object-meta.xml
<CustomObject>
    <label>Program Event</label>
    <pluralLabel>Program Events</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Event__e/fields/PJN_CarePlan__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan__c</fullName>
    <label>CarePlan</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanStartHdlr.cls
/**
 * @author      Mavens
 * @group       CarePlanHdlr
 * @description Event start events for cases that are inserted or updated with PJN_Program_DeveloperName__c
 *              and the start flag set to true. Optionally start the program at a specific problem

 */
public with sharing class PJN_CarePlanStartHdlr implements PJN_TriggerDispatcher.HandlerInterface {

    private final String NOT_CARE_PLAN_ERROR = 'Only care plans can be started.';
    private final String MISSING_PROGRAM_ERROR = 'A Program Developer Name (PJN_Program_DeveloperName__c) is required to start a care plan.';
    private final String PUBLISHING_ERROR = 'Error publishing care plan start events: ';

    @TestVisible
    private static Set<Id> newlyPendingIds = new Set<Id>();

    public void handle() {
        if (Trigger.isBefore) {
            evalutateCasesForCarePlansToStart();
        } else {
            publishStartEvents();
        }
    }

    private void evalutateCasesForCarePlansToStart() {
        Id carePlanRecTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId();

        for (Case currentCase : (List<Case>) Trigger.new) {
            if (currentCase.PJN_Care_Plan_Start_Status__c != 'PJN_Initiate') {
                continue;
            }

            // Only care plans can be Started
            if (currentCase.RecordTypeId != carePlanRecTypeId) {
                currentCase.addError(NOT_CARE_PLAN_ERROR);
                continue;
            }

            // To start a care plan it needs a developer name
            if (String.isBlank(currentCase.PJN_Program_DeveloperName__c)) {
                currentCase.addError(MISSING_PROGRAM_ERROR);
                continue;
            }

            // By immediately changing to pending there is no need to check if the value is insert or update and changed
            // since it is automatically changed when the value is initiate
            // add to newlyPendingIds to know the ids that need events emitted for them
            currentCase.PJN_Care_Plan_Start_Status__c = 'PJN_Pending';
            if (Trigger.isUpdate) {
                newlyPendingIds.add(currentCase.Id);
            }
        }
    }

    private void publishStartEvents() {

        List<PJN_Program_Event__e> programStartEvents = new List<PJN_Program_Event__e>();
        for (Case currentCase : (List<Case>) Trigger.new) {

            if (currentCase.PJN_Care_Plan_Start_Status__c == 'PJN_Pending'
                && (Trigger.isInsert || newlyPendingIds.contains(currentCase.Id))) {
                programStartEvents.add(
                    new PJN_Program_Event__e( PJN_CarePlan__c = currentCase.Id)
                );
            }
        }
        System.debug('programStartEvents ' + programStartEvents);
        if (!programStartEvents.isEmpty()) {
            List<Database.SaveResult> results = EventBus.publish(programStartEvents);

            for (Integer i=0; i<results.size(); i++) {
                if (!results[i].isSuccess()) {
                    System.debug(programStartEvents[i].PJN_CarePlan__c);
                    Case erroredCase = (Case) Trigger.newMap.get(programStartEvents[i].PJN_CarePlan__c);
                    String error = PUBLISHING_ERROR + getHtmlErrorString(results[i]);
                    erroredCase.addError(error, true);
                }
            }
        }
    }

    private String getHtmlErrorString( Database.SaveResult result) {
        List<String> errors = new List<String>();
        for (Database.Error err : result.getErrors()) {
            errors.add(err.getStatusCode() + ': ' + err.getMessage());
        }
        return String.join(errors, '; ');
    }
}