force-app/main/default/src/objects/Case/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related Coverage Investigation where the follow-up Case was generated from.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Follow-Up Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Access_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Access_Type__c</fullName>
    <description>The type of Access the patient has following the Coverage Investigation.</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Coverage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>The parent Care Plan where the Coverage Investigation is run from.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Access_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Access_Type__c</fullName>
    <description>The patient&apos;s method of obtaining funding and access to therapy during the duration of the Event.</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Coverage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Case__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case that triggered the Event.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Coverage Investigation where the Therapy Access event is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Therapy Access</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Start_Date__c</fullName>
    <description>Start date of the Event.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/PJN_Therapy_Access.recordType-meta.xml
<RecordType>
    <fullName>PJN_Therapy_Access</fullName>
    <active>true</active>
    <description>Defines an event representing how a patient is accessing therapy and the date periods.</description>
    <label>Therapy Access</label>
</RecordType>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Coverage_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Medicaid</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Tricare</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Assistance Program</fullName>
    </customValue>
    <customValue>
        <fullName>Interim Access Program</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Trial Transition Program</fullName>
    </customValue>
    <customValue>
        <fullName>Bridge Program</fullName>
        <isActive>false</isActive>
        <label>Bridge Program</label>
    </customValue>
    <customValue>
        <fullName>Quick Start</fullName>
        <isActive>false</isActive>
        <label>Quick Start</label>
    </customValue>
    <masterLabel>Coverage Types</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_CoverageInvestigationEventHdlrTest.cls
/**
 * @author      Mavens
 * @date        05/2021
 * @description Coverage Investigation Event handler PJN_CoverageInvestigationEventHdlr unit tests
 * @group       CoverageInvestigation
 */
@isTest
public class PJN_CoverageInvestigationEventHdlrTest {

    private static final Integer DATA_SIZE = 200;

    @TestSetup
    static void makeData(){
        List<Case> carePlans = new List<Case>();

        for (Integer i=0; i<DATA_SIZE; i++) {
            carePlans.add(
                new Case(
                    Subject = 'Care plan',
                    RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId()
                )
            );
        }

        insert carePlans;

        List<PJN_Coverage_Investigation__c> investigations = new List<PJN_Coverage_Investigation__c>();
        for (Case carePlan : carePlans) {
            investigations.add(
                new PJN_Coverage_Investigation__c(
                    PJN_Care_Plan__c = carePlan.Id
                )
            );
        }

        insert investigations;
    }

    // Explicitly set the four trigger config values so that customers can delete them but
    // the unit tests can still run, test functionalty, and pass
    static {
        PJN_TriggerHandlerSettingQuery.triggerHandlerSettingBySObjectType.put(
            PJN_Event__c.getSObjectType(),
            new List<PJN_Trigger_Handler_Setting__mdt> {
                new PJN_Trigger_Handler_Setting__mdt(
                    DeveloperName = 'PJN_Event_After_Insert_Access_Type',
                    PJN_Class__c = 'PJN_CoverageInvestigationEventHdlr',
                    PJN_Event__c = 'AFTER_INSERT'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    DeveloperName = 'PJN_Event_After_Insert_Access_Type',
                    PJN_Class__c = 'PJN_CoverageInvestigationEventHdlr',
                    PJN_Event__c = 'AFTER_UPDATE'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    DeveloperName = 'PJN_Event_After_Insert_Access_Type',
                    PJN_Class__c = 'PJN_CoverageInvestigationEventHdlr',
                    PJN_Event__c = 'AFTER_DELETE'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    DeveloperName = 'PJN_Event_After_Insert_Access_Type',
                    PJN_Class__c = 'PJN_CoverageInvestigationEventHdlr',
                    PJN_Event__c = 'AFTER_UNDELETE'
                )
            }
        );
    }

    @isTest
    private static void itShouldSetCoverageInvestigationAccessType() {
        List<PJN_Coverage_Investigation__c> investigations = [
            SELECT Id, PJN_Care_Plan__c FROM PJN_Coverage_Investigation__c
        ];

        System.assertEquals(DATA_SIZE, investigations.size());

        List<PJN_Event__c> events = new List<PJN_Event__c>();
        for (PJN_Coverage_Investigation__c investigation : investigations) {
            events.add(
                new PJN_Event__c(
                    PJN_Case__c = investigation.PJN_Care_Plan__c,
                    PJN_Coverage_Investigation__c = investigation.Id,
                    PJN_Access_Type__c = 'Commercial',
                    PJN_Start_Date__c = Date.today()
                )
            );
        }

        Test.startTest();
        insert events;
        Test.stopTest();

        System.assertEquals(200, [
            SELECT COUNT() FROM PJN_Coverage_Investigation__c WHERE PJN_Access_Type__c = 'Commercial'
        ], 'Coverage investigation access types not updated to "Commercial"');
    }

    @isTest
    private static void itShouldExitOutWhenNoInvestigationsToProcess() {
        // cover the return statement when no coverage invesitation attachded to event
        List<PJN_Coverage_Investigation__c> investigations = [
            SELECT Id, PJN_Care_Plan__c FROM PJN_Coverage_Investigation__c
        ];

        System.assertEquals(DATA_SIZE, investigations.size());

        List<PJN_Event__c> events = new List<PJN_Event__c>();
        for (PJN_Coverage_Investigation__c investigation : investigations) {
            events.add(
                new PJN_Event__c(
                    PJN_Case__c = investigation.PJN_Care_Plan__c,
                    PJN_Coverage_Investigation__c = investigation.Id,
                    PJN_Start_Date__c = Date.today()
                    // explicitly not setting access type
                )
            );
        }

        Test.startTest();
        insert events;
        Test.stopTest();

        System.assertEquals(0, [
            SELECT COUNT() FROM PJN_Coverage_Investigation__c WHERE PJN_Access_Type__c = 'Commercial'
        ], 'No coverage investigations should have been updated');
    }

    @isTest
    private static void itShouldHandleDeletedEvents() {
         // cover the return statement when no coverage invesitation attachded to event
         List<PJN_Coverage_Investigation__c> investigations = [
            SELECT Id, PJN_Care_Plan__c FROM PJN_Coverage_Investigation__c
        ];

        System.assertEquals(DATA_SIZE, investigations.size());

        List<PJN_Event__c> events = new List<PJN_Event__c>();
        for (PJN_Coverage_Investigation__c investigation : investigations) {
            events.add(
                new PJN_Event__c(
                    RecordTypeId = Schema.SObjectType.PJN_Event__c.getRecordTypeInfosByDeveloperName().get('PJN_Therapy_Access').getRecordTypeId(),
                    PJN_Case__c = investigation.PJN_Care_Plan__c,
                    PJN_Coverage_Investigation__c = investigation.Id,
                    PJN_Start_Date__c = Date.today(),
                    PJN_Access_Type__c = 'Cash'
                )
            );
            events.add(
                new PJN_Event__c(
                    PJN_Case__c = investigation.PJN_Care_Plan__c,
                    PJN_Coverage_Investigation__c = investigation.Id,
                    PJN_Start_Date__c = Date.today().addDays(-1),
                    PJN_Access_Type__c = 'Commercial'
                )
            );
        }

        insert events;
        Test.startTest();
        delete [SELECT Id FROM PJN_Event__c WHERE PJN_Access_Type__c = 'Cash'];
        Test.stopTest();

        System.assertEquals(DATA_SIZE, [
            SELECT COUNT() FROM PJN_Coverage_Investigation__c WHERE PJN_Access_Type__c = 'Commercial'
        ], 'Deletion of records not hanlded correctly');
    }

    @isTest
    private static void itShouldHandleNoEventsRemaining() {
        List<PJN_Coverage_Investigation__c> investigations = [
            SELECT Id, PJN_Care_Plan__c FROM PJN_Coverage_Investigation__c
        ];

        System.assertEquals(DATA_SIZE, investigations.size());

        List<PJN_Event__c> events = new List<PJN_Event__c>();
        for (PJN_Coverage_Investigation__c investigation : investigations) {
            events.add(
                new PJN_Event__c(
                    PJN_Case__c = investigation.PJN_Care_Plan__c,
                    PJN_Coverage_Investigation__c = investigation.Id,
                    PJN_Access_Type__c = 'Commercial',
                    PJN_Start_Date__c = Date.today()
                )
            );
        }

        insert events;
        Test.startTest();
        delete events;
        Test.stopTest();

        System.assertEquals(DATA_SIZE, [
            SELECT COUNT() FROM PJN_Coverage_Investigation__c WHERE PJN_Access_Type__c = null
        ], 'Deleting event did not clear the access type');
    }
}