force-app/main/default/src/objects/Case/fields/PJN_Send_to_Veeva_CRM__c.field-meta.xml
<CustomField>
    <fullName>PJN_Send_to_Veeva_CRM__c</fullName>
    <description>Indicates that the Case should be sent to Veeva CRM as a Suggestion.</description>
    <formula>AND(
  IF(!ISBLANK(ParentId),!ISBLANK(Parent.PJN_Physician__r.PJN_NPI__c),
           !ISBLANK(PJN_Physician__r.PJN_NPI__c)),
        Owner:Queue.DeveloperName == &apos;PJN_Escalated_To_CRM&apos;,
        ISBLANK(PJN_Veeva_CRM_Suggestion_Status__c)
)</formula>
    <label>Send to Veeva CRM Suggestion Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/PJN_CRM_Connection_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Connection settings for Patient Journey Navigator CRM integrations.</description>
    <label>CRM Connection Setting</label>
    <pluralLabel>CRM Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection setting active?</description>
    <inlineHelpText>Is this connection setting active? If it&apos;s not active it will not run.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Case_Sync_Complete_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case_Sync_Complete_Status__c</fullName>
    <description>Status stamped when Cases are sent to PJN with a Completed status.</description>
    <inlineHelpText>Status stamped when Cases are sent to PJN with a Completed status.</inlineHelpText>
    <label>Case Sync Complete Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Case_Sync_Dismissed_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case_Sync_Dismissed_Status__c</fullName>
    <description>Status stamped when Cases are sent to PJN with a Dismissed status.</description>
    <inlineHelpText>Status stamped when Cases are sent to PJN with a Dismissed status.</inlineHelpText>
    <label>Case Sync Dismissed Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_CRM_Connection_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_CRM_Connection_Class__c</fullName>
    <description>Class being used to connect to the CRM.</description>
    <inlineHelpText>Class being used to connect to the CRM.</inlineHelpText>
    <label>CRM Connection Class</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>PJN_Named_Credential__c</fullName>
    <description>Named credential used to establish the connection to the external CRM.</description>
    <label>Named Credential</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CRM_Connection_Setting__mdt/fields/PJN_Trigger_Field__c.field-meta.xml
<CustomField>
    <fullName>PJN_Trigger_Field__c</fullName>
    <description>The field that needs to be true for the trigger to perform transactions with the corresponding CRM.</description>
    <inlineHelpText>The field that needs to be true for the trigger to perform transactions with the corresponding CRM.</inlineHelpText>
    <label>Trigger Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_CRMConnectionSettingMock.cls
@SuppressWarnings('PMD.ExcessiveParameterList')
@isTest(isParallel=true) public with sharing class PJN_CRMConnectionSettingMock implements System.StubProvider {


    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        System.debug('stubbedMethodName: ' + stubbedMethodName);
        System.debug('returnType: ' + returnType);
        System.debug('listOfArgs: ' + listOfArgs);
        if (stubbedMethodName == 'queryBySettingByType') {
            return this.queryBySettingByType((String) listOfArgs[0]);
        } else {
            return null;
        }
    }

    private Object queryBySettingByType(String pjnType) {
        List<PJN_CRM_Connection_Setting__mdt> crmConnectionSettings = new List<PJN_CRM_Connection_Setting__mdt>();
        System.debug('pjnType: ' + pjnType);
        if (pjnType == 'Case Escalation') {
            crmConnectionSettings.add(
                new PJN_CRM_Connection_Setting__mdt(
                    PJN_Active__c = true,
                    PJN_CRM_Connection_Class__c = 'PJN_VeevaCRMSuggestionConnector',
                    PJN_Named_Credential__c = 'PJN_Veeva_CRM',
                    PJN_Trigger_Field__c = 'PJN_Send_to_Veeva_CRM__c'
                )
            );
        } else if (pjnType == 'Sync') {
            crmConnectionSettings.add(
                new PJN_CRM_Connection_Setting__mdt(
                    PJN_Active__c = true,
                    PJN_CRM_Connection_Class__c = 'PJN_VeevaCRMToCaseConnector',
                    PJN_Named_Credential__c = 'PJN_Veeva_CRM',
                    PJN_Case_Sync_Dismissed_Status__c = 'Cancelled',
                    PJN_Case_Sync_Complete_Status__c = 'Closed'
                )
            );
        } else if (pjnType == 'Enrollment') {
            crmConnectionSettings.add(
                new PJN_CRM_Connection_Setting__mdt(
                    PJN_Active__c = true,
                    PJN_CRM_Connection_Class__c = 'PJN_VeevaCRMEnrollmentConnector',
                    PJN_Named_Credential__c = 'PJN_Veeva_CRM',
                    PJN_Trigger_Field__c = 'PJN_Send_to_Veeva_CRM__c'
                )
            );
        }
        return crmConnectionSettings;
    }
}