force-app/main/default/src/objects/Case/fields/PJN_Active_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The investigation representing the Patient&apos;s current coverage</description>
    <inlineHelpText>The investigation representing the Patient&apos;s current coverage</inlineHelpText>
    <label>Active Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Care_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related Coverage Investigation where the follow-up Case was generated from.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Follow-Up Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>The parent Care Plan where the Coverage Investigation is run from.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Is_Active_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Active_Investigation__c</fullName>
    <description>Indicates this record is the active investigation on the parent Care Plan</description>
    <formula>PJN_Care_Plan__r.PJN_Active_Coverage_Investigation__c =  Id</formula>
    <inlineHelpText>Indicates this record is the active investigation on the parent Care Plan</inlineHelpText>
    <label>Is Active Investigation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Set_as_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controlled by the PJN_ActiveCoverageInvestigationHdlr trigger handler.  When checked, kicks off the logic to set this record as the active on the parent care plan. This value will be reset to false to allow re-triggering of the logic.</description>
    <inlineHelpText>Triggers an update to the Care Plan to set this Coverage Investigation as the Active Investigation</inlineHelpText>
    <label>Set as Active on Care Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Coverage Investigation where the Therapy Access event is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Therapy Access</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/classes/PJN_ActiveCoverageInvestigatnHdlrTest.cls
/**
 * @author      Mavens
 * @date        11/2020
 * @description Unit tests for PJN_ActiveCoverageInvestigatnHdlr
 * @group       CoverageInvestigation
 */
@isTest
public with sharing class PJN_ActiveCoverageInvestigatnHdlrTest {

    private static final Integer DATA_SIZE = 200;

    @TestSetup
    static void makeData(){
        List<Account> patients = new List<Account>();
        for (Integer i=0; i<200; i++) {
            patients.add(
                new Account(
                    LastName = 'Patient' + i,
                    FirstName = 'Test',
                    RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId()
                )
            );
        }

        insert patients;

        List<Case> carePlans = new List<Case>();
        for (Account patient : patients) {
            carePlans.add(
                new Case (
                    AccountId = patient.Id,
                    RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId()
                )
            );
        }
        insert carePlans;

        // query for all settings for this object and mock the ones we need turned on
        List<PJN_Trigger_Handler_Setting__mdt> settings = new List<PJN_Trigger_Handler_Setting__mdt>();
        List<PJN_Trigger_Handler_Setting__mdt> allObjSettings = [
            SELECT PJN_Class__c, PJN_Event__c, PJN_Active__c
            FROM PJN_Trigger_Handler_Setting__mdt
            WHERE PJN_SObject_API_Name__c = 'PJN_Coverage_Investigation__c'
            ORDER BY PJN_Order__c ASC
        ];

        // already active? keep it. If not active but is the class we care about then treat as active
        for (PJN_Trigger_Handler_Setting__mdt setting : allObjSettings) {
            if (setting.PJN_Active__c || setting.PJN_Class__c == 'PJN_ActiveCoverageInvestigationHdlr') {
                settings.add(setting);
            }
        }

        PJN_TriggerHandlerSettingQuery.triggerHandlerSettingBySObjectType.put(
            PJN_Coverage_Investigation__c.getSObjectType(),
            settings
        );
    }

    @isTest
    private static void itShouldSetCoverageInvestigationAsActiveOnInsert() {
        List<Case> carePlans = [SELECT Id FROM Case];

        List<PJN_Coverage_Investigation__c> investigations = new List<PJN_Coverage_Investigation__c>();
        for (Case carePlan : carePlans) {
            investigations.add(
                new PJN_Coverage_Investigation__c(
                    PJN_Care_Plan__c = carePlan.Id,
                    PJN_Set_as_Active__c = true
                )
            );
        }

        Test.startTest();
        insert investigations;
        Test.stopTest();

        System.assertEquals(200, [SELECT COUNT() FROM Case WHERE PJN_Active_Coverage_Investigation__c != null]);
        System.assertEquals(200, [
            SELECT COUNT()
            FROM PJN_Coverage_Investigation__c
            WHERE PJN_Is_Active_Investigation__c = true
            AND PJN_Set_as_Active__c = false
        ]);
    }

    @isTest
    private static void itShouldSetCoverageInvestigationAsActiveOnUpdate() {
        List<Case> carePlans = [SELECT Id FROM Case];

        List<PJN_Coverage_Investigation__c> investigations = new List<PJN_Coverage_Investigation__c>();
        for (Case carePlan : carePlans) {
            investigations.add(
                new PJN_Coverage_Investigation__c(
                    PJN_Care_Plan__c = carePlan.Id,
                    PJN_Set_as_Active__c = false
                )
            );
        }

        insert investigations;

        Test.startTest();
        for (PJN_Coverage_Investigation__c investigation : investigations) {
            investigation.PJN_Set_as_Active__c = true;
        }
        update investigations;
        Test.stopTest();

        System.assertEquals(200, [SELECT COUNT() FROM Case WHERE PJN_Active_Coverage_Investigation__c != null]);
        System.assertEquals(200, [
            SELECT COUNT()
            FROM PJN_Coverage_Investigation__c
            WHERE PJN_Is_Active_Investigation__c = true
            AND PJN_Set_as_Active__c = false
        ]);
    }
}