force-app/main/default/src/objects/PJN_Veeva_Network__e/PJN_Veeva_Network__e.object-meta.xml
<CustomObject>
    <label>Veeva Network</label>
    <pluralLabel>Veeva Network</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Veeva_Network__e/fields/PJN_DCR_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Id__c</fullName>
    <description>Data Change Request Id</description>
    <label>DCR Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkQueueHdlr.cls
/**
 * Queue DCRs from Event DCRs
 * @author  Mavens
 * @group   DCR
 */
public with sharing class PJN_NetworkQueueHdlr implements PJN_TriggerDispatcher.HandlerInterface {
    /**
     * handler
     */
    public void handle() {
        Set<Id> dcrIds = new Set<Id>();
        Set<Id> outcomeIds = new Set<Id>();

        for(PJN_Veeva_Network__e networkEvent : (List<PJN_Veeva_Network__e>) Trigger.new) {
            if (networkEvent.PJN_DCR_Id__c != null && !dcrIds.contains(networkEvent.PJN_DCR_Id__c)) {
                dcrIds.add(networkEvent.PJN_DCR_Id__c);
            }
        }

        if (!dcrIds.isEmpty()) {
            PJN_NetworkCreateDCRQueueable networkCreateDCRQueue = new PJN_NetworkCreateDCRQueueable(dcrIds);
            System.enqueueJob(networkCreateDCRQueue);
        }
    }
}