force-app/main/default/src/objects/Account/fields/HealthCloudGA__SourceSystemId__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SourceSystemId__c</fullName>
    <description>Unique external id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source System ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/recordTypes/PJN_Organization.recordType-meta.xml
<RecordType>
    <fullName>PJN_Organization</fullName>
    <active>true</active>
    <description>Defines a healthcare organization where physicians and staff work</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/src/classes/MVN_DataLakeCMHCO.cls
/**
 * @author      Mavens
 * @group       DataLake
 * @description Wrapper for the MVN_DataLakeCMHCO HCO DataLake Object
 */
public with sharing class MVN_DataLakeCMHCO {

    /**
     * Datalake HCO objects
     */
    public String hco_id;
    public String hco_name;
    public String hco_type_cd;
    public String hco_status_type_cd;

    /**
     * Search HCO Populated Fields
     */
    private Map<String, Object> reqAccountPopulatedFields;

    /**
     * Constructor to get all search fields and store into this wrapper to build they query
     * @param reqAccountPopulatedFields HCO Search populated fields
     */
    public MVN_DataLakeCMHCO(Map<String, Object> reqAccountPopulatedFields) {
        this.reqAccountPopulatedFields = reqAccountPopulatedFields;
        if (this.reqAccountPopulatedFields == null || this.reqAccountPopulatedFields.isEmpty()) {
            return;
        }
        this.hco_id = MVN_DataLakeCMSearchUtil.getStringValue(this.reqAccountPopulatedFields, 'id');
        this.hco_name = MVN_DataLakeCMSearchUtil.getStringValue(this.reqAccountPopulatedFields, 'Name');
        this.hco_status_type_cd = 'A';
    }

    /**
     * Get HCO Search filter using the populated fields
     * @return  `String`
     */
    public String getSearchFilters() {
        String filters = '';
        if (String.isNotBlank(this.hco_name)) {
            filters += MVN_DataLakeCMSearchUtil.getFieldFilter('hco_name', this.hco_name);
        }
        if (String.isNotBlank(filters)) {
            MVN_DataLakeCMSearchHdlr.hasSearchFilter = true;
        }
        filters += 'Upper(hco_status_type_cd) = \'' + this.hco_status_type_cd + '\' AND ';
        return filters.substringBeforeLast(' AND ');
    }

    /**
     * Get SFDC Record using the wrapper parameters obtained from the search
     * @return  `Account`
     */
    public Account getSFDCRecord() {
        return new Account (
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Organization').getRecordTypeId(),
            Name = this.hco_name,
            PJN_Status__c = MVN_DataLakeCMSearchUtil.getStatusFromMapped(this.hco_status_type_cd),
            HealthCloudGA__SourceSystemId__c = this.hco_id
        );
    }
}