force-app/main/default/src/objects/Account/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Healthcare plan for this patient</description>
    <inlineHelpText>Healthcare plan for this patient</inlineHelpText>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PatientAccounts</relationshipLabel>
    <relationshipName>PatientAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/HealthCloudGA__SortOrder__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SortOrder__c</fullName>
    <description>Rank by which this care gap is sorted.</description>
    <inlineHelpText>Rank by which this care gap is sorted.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>MVN_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>myRARE team member focused on all aspects of benefits investigation, verification, and support related to pharmacy, medical, and buy/bill claims.</description>
    <label>Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Program_Problem_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Problem DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <defaultValue>&apos;Planned&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/PJN_Program_Problem__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Define the attributes of the problems/stages that comprise a Program. Program Problems are distinct stages in the patient’s journey that are (typically) completed before moving on to the next stage.
Metadata Relationship(s): Program; Program Case
Created by Mavens: Yes</description>
    <label>Program Problem</label>
    <pluralLabel>Program Problems</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Program Problems</relationshipLabel>
    <relationshipName>PJN_Program_Problems</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanPathProblemActionsCtrlTest.cls
/**
 * @author      Mavens
 * @group       CarePlan-UI
 * @description Unit tests for PJN_CarePlanPathProblemActionsCtrl
 */
@isTest(isParallel=true) public with sharing class PJN_CarePlanPathProblemActionsCtrlTest {
    @isTest private static void startCarePlanProblem() {
        MVN_ProgramEventHdlr.programEventQuery = (MVN_ProgramEventQuery) Test.createStub(
            MVN_ProgramEventQuery.class,
             new MVN_ProgramEventQueryMock()
        );
        String programDeveloperName = [SELECT DeveloperName FROM PJN_Program__mdt LIMIT 1].DeveloperName;
        String programProblemDeveloperName = [SELECT DeveloperName FROM PJN_Program_Problem__mdt WHERE PJN_Program__r.DeveloperName = :programDeveloperName LIMIT 1].DeveloperName;
        Account expectedAccount = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId(),
            FirstName = 'Test',
            LastName = 'Ing'
        );
        insert expectedAccount;
        Case expectedCase = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            AccountId = expectedAccount.Id,
            PJN_Program_DeveloperName__c = programDeveloperName,
            MVN_Coordinator__c = UserInfo.getUserId(),
            Subject = 'Care Plan'
        );
        insert expectedCase;
        HealthCloudGA__CarePlanProblem__c expectedCarePlanProblem = new HealthCloudGA__CarePlanProblem__c(
            HealthCloudGA__CarePlan__c = expectedCase.Id,
            Name = 'Test Problem One',
            PJN_Status__c = 'Planned',
            PJN_Program_Problem_DeveloperName__c = programProblemDeveloperName,
            HealthCloudGA__SortOrder__c = 1
        );
        insert expectedCarePlanProblem;
        expectedCarePlanProblem = PJN_CarePlanProblemQuery.queryById(expectedCarePlanProblem.Id);

        Test.startTest();
            Boolean isSuccess = PJN_CarePlanPathProblemActionsCtrl.startCarePlanProblem(expectedCarePlanProblem);
        Test.stopTest();

        System.assertEquals(true, isSuccess);
        HealthCloudGA__CarePlanProblem__c actualCarePlanProblem = [SELECT Id, PJN_Status__c FROM HealthCloudGA__CarePlanProblem__c WHERE Id = :expectedCarePlanProblem.Id];
        System.assertEquals(expectedCarePlanProblem.Id, actualCarePlanProblem.Id);
        System.assertNotEquals(expectedCarePlanProblem.PJN_Status__c, actualCarePlanProblem.PJN_Status__c);
    }

    @isTest private static void skipCarePlanProblem() {
        String programDeveloperName = [SELECT DeveloperName FROM PJN_Program__mdt LIMIT 1].DeveloperName;
        String programProblemDeveloperName = [SELECT DeveloperName FROM PJN_Program_Problem__mdt WHERE PJN_Program__r.DeveloperName = :programDeveloperName LIMIT 1].DeveloperName;
        Account expectedAccount = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
            FirstName = 'Test',
            LastName = 'Ing'
        );
        insert expectedAccount;
        Case expectedCase = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            AccountId = expectedAccount.Id,
            PJN_Program_DeveloperName__c = programDeveloperName,
            Subject = 'Care Plan'
        );
        insert expectedCase;
        HealthCloudGA__CarePlanProblem__c expectedCarePlanProblem = new HealthCloudGA__CarePlanProblem__c(
            HealthCloudGA__CarePlan__c = expectedCase.Id,
            Name = 'Test Problem One',
            PJN_Status__c = 'Planned',
            PJN_Program_Problem_DeveloperName__c = programProblemDeveloperName,
            HealthCloudGA__SortOrder__c = 1
        );
        insert expectedCarePlanProblem;
        expectedCarePlanProblem = PJN_CarePlanProblemQuery.queryById(expectedCarePlanProblem.Id);

        Test.startTest();
            Boolean isSuccess = PJN_CarePlanPathProblemActionsCtrl.skipCarePlanProblem(expectedCarePlanProblem);
        Test.stopTest();

        System.assertEquals(true, isSuccess);
        HealthCloudGA__CarePlanProblem__c actualCarePlanProblem = [SELECT Id, PJN_Status__c FROM HealthCloudGA__CarePlanProblem__c WHERE Id = :expectedCarePlanProblem.Id];
        System.assertEquals(expectedCarePlanProblem.Id, actualCarePlanProblem.Id);
        System.assertNotEquals(expectedCarePlanProblem.PJN_Status__c, actualCarePlanProblem.PJN_Status__c);
    }

    @isTest private static void deleteCarePlanProblem() {
        String programDeveloperName = [SELECT DeveloperName FROM PJN_Program__mdt LIMIT 1].DeveloperName;
        String programProblemDeveloperName = [SELECT DeveloperName FROM PJN_Program_Problem__mdt WHERE PJN_Program__r.DeveloperName = :programDeveloperName LIMIT 1].DeveloperName;
        Account expectedAccount = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
            FirstName = 'Test',
            LastName = 'Ing'
        );
        insert expectedAccount;
        Case expectedCase = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            AccountId = expectedAccount.Id,
            PJN_Program_DeveloperName__c = programDeveloperName,
            Subject = 'Care Plan'
        );
        insert expectedCase;
        HealthCloudGA__CarePlanProblem__c expectedCarePlanProblem = new HealthCloudGA__CarePlanProblem__c(
            HealthCloudGA__CarePlan__c = expectedCase.Id,
            Name = 'Test Problem One',
            PJN_Status__c = 'Planned',
            PJN_Program_Problem_DeveloperName__c = programProblemDeveloperName,
            HealthCloudGA__SortOrder__c = 1
        );
        insert expectedCarePlanProblem;
        expectedCarePlanProblem = PJN_CarePlanProblemQuery.queryById(expectedCarePlanProblem.Id);

        Test.startTest();
            Boolean isSuccess = PJN_CarePlanPathProblemActionsCtrl.deleteCarePlanProblem(expectedCarePlanProblem);
        Test.stopTest();

        System.assertEquals(true, isSuccess);
        try {
            HealthCloudGA__CarePlanProblem__c actualCarePlanProblem = [SELECT Id, PJN_Status__c FROM HealthCloudGA__CarePlanProblem__c WHERE Id = :expectedCarePlanProblem.Id];
            System.assert(false, 'if this is executed, something went wrong');
        } catch(System.QueryException queryException) {
            System.assertEquals('List has no rows for assignment to SObject', queryException.getMessage());
        }
    }
}