force-app/main/default/src/objects/Account/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Healthcare plan for this patient</description>
    <inlineHelpText>Healthcare plan for this patient</inlineHelpText>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PatientAccounts</relationshipLabel>
    <relationshipName>PatientAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/Care_Plan_Template_External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Template_External_ID_MVN__c</fullName>
    <description>The external ID of the care plan template which should be assigned automatically by code.</description>
    <formula>IF( NOT( ISBLANK( Care_Plan_Template_Ext_ID_Override_MVN__c ) ),
    Care_Plan_Template_Ext_ID_Override_MVN__c, /* return the override */
    CASE( RecordType.DeveloperName,

        /* DEDSI logic */
        &quot;CarePlan&quot;,
        CASE( Account.Screening_Results_on_Conversion_MVN__c,
            &quot;Signs of DR&quot;, 
            IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot; &amp;&amp; 
                Account.Specialists_Shared_on_Conversion_MVN__c = &quot;Yes&quot;,
                &quot;CPT-a0956000002t50X&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot; &amp;&amp; 
                    Account.Specialists_Shared_on_Conversion_MVN__c = &quot;No&quot;,
                    &quot;CPT-a0956000002t50N&quot;,
                    IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;No&quot; &amp;&amp; 
                        Account.Specialists_Shared_on_Conversion_MVN__c = &quot;Yes&quot;,
                        &quot;CPT-a0956000002t50S&quot;, 
                        IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;No&quot; &amp;&amp; 
                            Account.Specialists_Shared_on_Conversion_MVN__c = &quot;No&quot;,
                            &quot;CPT-a0956000002WMTv&quot;, 
                            &quot;&quot;
                        )
                    )
                )
            ),
            &quot;No Signs of DR&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot;,
                    &quot;CPT-a09S000000DEWHkIAP&quot;,
                    &quot;CPT-a0956000002nKd9&quot;
                ), 
                    &quot;Not Yet Screened&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot;,
                    &quot;CPT-a09S000000DEWHpIAP&quot;,
                    &quot;CPT-a0956000002nFSg&quot;
                ), 
                    &quot;Unknown&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot;,
                    &quot;CPT-a09S000000DEWHpIAP&quot;,
                    &quot;CPT-a0956000002nFSg&quot;
                ),
            &quot;&quot;
        ),

        /* Libtayo logic */
        &quot;Libtayo_Marketing_Care_Plan_MVN&quot;,

            CASE( TEXT( Qualification_Status_MVN__c ),

                    /* Qualified */
                    &quot;Qualified&quot;,
                    CASE( TEXT( Type ),
                    &quot;Patient&quot;,
                        IF( ISPICKVAL( Origin, &quot;Libtayo Surround&quot; ),
                            &quot;CPT-libtayo-marketing-qualified-surround-patient&quot;,
                            IF( ISPICKVAL( Email_Opt_In_MVN__c, &quot;Yes&quot; ),
                                &quot;CPT-libtayo-marketing-qualified-website-patient&quot;,
                            &quot;CPT-libtayo-marketing-qualified-web-patient-mail&quot;
                               )
                           ),
                    &quot;Caregiver&quot;, &quot;CPT-libtayo-marketing-qualified-caregiver&quot;,
                    &quot;&quot;
                ),

                /* Unqualified */
                &quot;Unqualified&quot;, &quot;CPT-libtayo-marketing-unqualified&quot;,

            /* Default Qualification_Status__c */
            &quot;&quot;
        ),

    /* Default RecordType.DeveloperName */
    &quot;&quot;
    )
)</formula>
    <label>Care Plan Template External ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/HealthCloudGA__CarePlanGoal__c.object-meta.xml
<CustomObject>
    <description>Health improvement goal to address a particular health problem for a given patient as part of their care plan</description>
    <label>Goal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this goal is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>CarePlanGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__CarePlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template</label>
    <referenceTo>HealthCloudGA__CarePlanTemplate__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cognition Improvement</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Muscle Strength Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__Description__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__Priority__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <color>#FFFF66</color>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <color>#FF6600</color>
                <label>Medium</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#FF0000</color>
                <label>High</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/HealthCloudGA__CarePlanTemplate__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID of the care plan template. Used in mapping the correct template upon creation of a care plan.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Health</fullName>
            </value>
            <value>
                <fullName>Endocrinology and Metabolism</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Disease Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/HealthCloudGA__Description__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/HealthCloudGA__CarePlanTemplateGoal__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template Goal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Template Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID for the care plan template goal. Used for automatic assignment of care plan templates.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/HealthCloudGA__CarePlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template</label>
    <referenceTo>HealthCloudGA__CarePlanTemplate__c</referenceTo>
    <relationshipLabel>Care Plan Template Goals</relationshipLabel>
    <relationshipName>Care_Plan_Template_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cognition Improvement</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Muscle Strength Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/HealthCloudGA__Priority__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/HealthCloudGA__CarePlanTemplateTask__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template Task</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Template Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID for the care plan template task. Used for automatic assignment of care plan templates.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__CarePlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template</label>
    <referenceTo>HealthCloudGA__CarePlanTemplate__c</referenceTo>
    <relationshipLabel>Care Plan Template Tasks</relationshipLabel>
    <relationshipName>Care_Plan_Template_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__CarePlanTemplateGoal__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplateGoal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template Goal</label>
    <referenceTo>HealthCloudGA__CarePlanTemplateGoal__c</referenceTo>
    <relationshipLabel>Care Plan Template Tasks</relationshipLabel>
    <relationshipName>CarePlanTemplateTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diagnosis</fullName>
            </value>
            <value>
                <fullName>Counselling</fullName>
            </value>
            <value>
                <fullName>Vaccination</fullName>
            </value>
            <value>
                <fullName>Exercise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Description__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/classes/ApplyCarePlanTemplateHdlrMVN.cls
/**
 * @author      Mavens
 * @group       ApplyCarePlanTemplate
 * @description On case creation apply a care plan template if defined 
 */
public with sharing class ApplyCarePlanTemplateHdlrMVN {
   
    /*
     * List of all newly inserted Care Plans
     */
    private static List<Case> newCarePlans;

    /*
     * Map of Accounts related to the care plan, specifically to get to the PersonContactId
     */
    private static Map<Id, Account> carePlanAccountsById;

    /*
     * Set of Care Plan Template External Ids that will be queried for
     */
    private static Set<String> carePlanTemplateExtIds;

    /*
     * Map of Care plan templates that will be used
     */
    private static Map<String, HealthCloudGA__CarePlanTemplate__c> templatesByExtId;

    /*
     * Map of template tasks by goal Id
     */
    private static Map<Id, List<HealthCloudGA__CarePlanTemplateTask__c>> templateTasksByTemplateGoalId;

    /*
     * Map of Care Team Members by Role for each care plan
     */
    private static Map<Id, Map<String, Id>> teamMemberByRoleByCarePlan; 

    /*
     * Provides a method that a flow can invoke
     * Orchestrates the sequence of apply the care plan templates
     */
    @InvocableMethod(label='Apply Care Plan Template' description='Applys CarePlan Indicated in the Care Plan Template External Id' category='Case')
    public static void applyCarePlanTemplates(List<Id> carePlanIds) {
        newCarePlans = new List<Case>();
        carePlanAccountsById = new Map<Id, Account>();
        carePlanTemplateExtIds = new Set<String>();
        templatesByExtId = new Map<String, HealthCloudGA__CarePlanTemplate__c>();
        templateTasksByTemplateGoalId = new Map<Id, List<HealthCloudGA__CarePlanTemplateTask__c>>();
        teamMemberByRoleByCarePlan = new Map<Id, Map<String, Id>>();

        getNewCarePlans(carePlanIds);
        getCaseTeamMemberMaps();
        applyCarePlanTemplates();
    }

    /*
     * Determine all cases which need a care plan template applied; 
     * The field Care_Plan_Template_External_ID_MVN__c will indicate the external id of the template to apply
     */
    private static void getNewCarePlans(List<Id> carePlanIds) {
        Set<Id> carePlanAccountIds = new Set<Id>();

        newCarePlans = [
            SELECT 
                Id,
                AccountId,
                RecordTypeId,
                Care_Plan_Template_External_ID_MVN__c
            FROM
                Case
            WHERE
                Id IN :carePlanIds
        ];

        for (Case thisCase : newCarePlans) {
            if (String.isNotBlank(thisCase.Care_Plan_Template_External_ID_MVN__c)) {
                carePlanAccountIds.add(thisCase.AccountId);
                carePlanTemplateExtIds.add(thisCase.Care_Plan_Template_External_ID_MVN__c);
            }
        }

        carePlanAccountsById = new Map<Id, Account>([
            SELECT Id, PersonContactId 
            FROM Account 
            WHERE Id IN :carePlanAccountIds
        ]);
    }

    /*
     * For all new care plans figure out who is on the care team, mapped by role
     */
    private static void getCaseTeamMemberMaps() {
        List<CaseTeamMember> teamMembers = [
            SELECT MemberId, ParentId, TeamRole.Name FROM CaseTeamMember WHERE ParentId IN :newCarePlans
        ];

        for (CaseTeamMember teamMember : teamMembers) {
            if (!teamMemberByRoleByCarePlan.containsKey(teamMember.ParentId)) {
                teamMemberByRoleByCarePlan.put(teamMember.ParentId, new Map<String, Id>());
            }
            teamMemberByRoleByCarePlan.get(teamMember.ParentId).put(teamMember.TeamRole.Name, teamMember.MemberId);
        }
    }

    /*
     * Apply the care plan templates for the cases
     */
    private static void applyCarePlanTemplates() {
        setupTemplatesAndTasks();

        List<HealthCloudGA__CarePlanGoal__c> newGoals = new List<HealthCloudGA__CarePlanGoal__c>();
        List<Task> newTasks = new List<Task>();

        for (Case carePlan : newCarePlans) {
            if (!templatesByExtId.containsKey(carePlan.Care_Plan_Template_External_ID_MVN__c)) {
                continue;
            }
            HealthCloudGA__CarePlanTemplate__c template = templatesByExtId.get(carePlan.Care_Plan_Template_External_ID_MVN__c);
            Map<String, Id> caseTeamMembers = teamMemberByRoleByCarePlan.get(carePlan.Id);

            Id carePlanTaskId = SObjectType.Task
                .getRecordTypeInfosByDeveloperName()
                .get('CarePlanTask')
                .getRecordTypeId();

            for (HealthCloudGA__CarePlanTemplateGoal__c templateGoal : template.HealthCloudGA__Care_Plan_Template_Goals__r) {
                HealthCloudGA__CarePlanGoal__c goal = new HealthCloudGA__CarePlanGoal__c(
                    Name = templateGoal.Name,
                    HealthCloudGA__CarePlan__c = carePlan.Id,
                    HealthCloudGA__CarePlanTemplate__c = template.Id,
                    HealthCloudGA__Category__c = templateGoal.HealthCloudGA__Category__c,
                    HealthCloudGA__Description__c = templateGoal.HealthCloudGA__Description__c,
                    HealthCloudGA__Priority__c = templateGoal.HealthCloudGA__Priority__c,
                    HealthCloudGA__SortOrder__c = templateGoal.HealthCloudGA__SortOrder__c,
                    Insert_Foreign_Key__c = '' + carePlan.Id + templateGoal.Id
                );

                newGoals.add(goal);

                if (templateTasksByTemplateGoalId.containsKey(templateGoal.Id)) {
                    List<HealthCloudGA__CarePlanTemplateTask__c> taskTemplates = templateTasksByTemplateGoalId.get(templateGoal.Id);
                    for (HealthCloudGA__CarePlanTemplateTask__c taskTemplate : taskTemplates) {
                        Id assignedToId = UserInfo.getUserId();
                        if (String.isNotBlank(taskTemplate.HealthCloudGA__AssignedTo__c)
                            && caseTeamMembers != null
                            && caseTeamMembers.containsKey(taskTemplate.HealthCloudGA__AssignedTo__c)
                        ) {
                            assignedToId = caseTeamMembers.get(taskTemplate.HealthCloudGA__AssignedTo__c);
                        }

                        Integer taskDayToDue = 0;
                        if (taskTemplate.HealthCloudGA__Offset__c != null) {
                            taskDayToDue = Integer.valueOf(taskTemplate.HealthCloudGA__Offset__c);
                        }

                        Id whoId = null;
                        if (carePlanAccountsById.containsKey(carePlan.AccountId)) {
                            whoId = carePlanAccountsById.get(carePlan.AccountId).PersonContactId;
                        }
                        newTasks.add(
                            new Task(
                                WhoId = whoId,
                                WhatId = carePlan.id,
                                OwnerId = assignedToId,
                                Subject = taskTemplate.HealthCloudGA__Subject__c,
                                Description = taskTemplate.HealthCloudGA__Description__c,
                                ActivityDate = Date.today().addDays(taskDayToDue),
                                HealthCloudGA__CarePlanGoal__r = new HealthCloudGA__CarePlanGoal__c(
                                    Insert_Foreign_Key__c = goal.Insert_Foreign_Key__c
                                ),
                                HealthCloudGA__CarePlanTemplate__c = template.Id,
                                HealthCloudGA__SortOrder__c = taskTemplate.HealthCloudGA__SortOrder__c,
                                HealthCloudGA__TaskType__c = taskTemplate.HealthCloudGA__Type__c,                
                                RecordTypeId = carePlanTaskId,
                                Priority = taskTemplate.HealthCloudGA__Priority__c,
                                Status = taskTemplate.HealthCloudGA__Status__c,
                                Survey_MVN__c = taskTemplate.Survey_MVN__c                                                          
                            )
                        );
                    }
                }
            }
        }

        insert newGoals;
        insert newTasks;
    }

     /*
     * Prepare the Care plan templates by querying for data and setting up maps corectly
     */
    private static void setupTemplatesAndTasks() {
        if (carePlanTemplateExtIds.isEmpty()) {
            return;
        }

        List<HealthCloudGA__CarePlanTemplate__c> templates = [
            SELECT
                Id,
                External_ID_MVN__c,
                (
                    SELECT
                        Id,
                        Name,
                        HealthCloudGA__Category__c,
                        HealthCloudGA__Description__c,
                        External_ID_MVN__c,
                        HealthCloudGA__Priority__c,
                        HealthCloudGA__SortOrder__c
                    FROM
                        HealthCloudGA__Care_Plan_Template_Goals__r
                    WHERE
                        HealthCloudGA__Active__c = true
                )
            FROM
                HealthCloudGA__CarePlanTemplate__c
            WHERE
                External_ID_MVN__c IN :carePlanTemplateExtIds
        ];

        Set<Id> goalIds = new Set<Id>();
        for (HealthCloudGA__CarePlanTemplate__c template : templates) {
            templatesByExtId.put(template.External_ID_MVN__c, template);
            Map<Id, HealthCloudGA__CarePlanTemplateGoal__c> goals = new Map<Id, HealthCloudGA__CarePlanTemplateGoal__c>(
                template.HealthCloudGA__Care_Plan_Template_Goals__r
            );
            goalIds.addAll(goals.keySet());
        }

        if (goalIds.isEmpty()) {
            return;
        }

        List<HealthCloudGA__CarePlanTemplateTask__c> templateTasks = [
            SELECT
                Id,
                HealthCloudGA__AssignedTo__c,
                HealthCloudGA__CarePlanTemplateGoal__c,
                HealthCloudGA__Category__c,
                HealthCloudGA__Description__c,
                HealthCloudGA__Offset__c,
                HealthCloudGA__Priority__c,
                HealthCloudGA__SortOrder__c,
                HealthCloudGA__Status__c,
                HealthCloudGA__Subject__c,
                HealthCloudGA__Type__c,
                Survey_MVN__c         
            FROM
                HealthCloudGA__CarePlanTemplateTask__c
            WHERE
                HealthCloudGA__Active__c = true
            AND
                HealthCloudGA__CarePlanTemplateGoal__c IN :goalIds
        ];
        
        for (HealthCloudGA__CarePlanTemplateTask__c templateTask : templateTasks) {
            if (!templateTasksByTemplateGoalId.containsKey(templateTask.HealthCloudGA__CarePlanTemplateGoal__c)) {
                templateTasksByTemplateGoalId.put(
                    templateTask.HealthCloudGA__CarePlanTemplateGoal__c, 
                    new List<HealthCloudGA__CarePlanTemplateTask__c>()
                );
            }
            templateTasksByTemplateGoalId
                .get(templateTask.HealthCloudGA__CarePlanTemplateGoal__c)
                .add(templateTask);
        }
    }
}