force-app/main/default/src/objects/Account/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Healthcare plan for this patient</description>
    <inlineHelpText>Healthcare plan for this patient</inlineHelpText>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PatientAccounts</relationshipLabel>
    <relationshipName>PatientAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/CareProgramProduct/fields/PJN_NDC__c.field-meta.xml
<CustomField>
    <fullName>PJN_NDC__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>NDC code of the therapeutic product.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NDC</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/CareProgramProduct/fields/PJN_Program_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Developer_Name__c</fullName>
    <description>Program Developer Name that this product is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_CarePlan_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Problem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarePlan Problem</label>
    <referenceTo>HealthCloudGA__CarePlanProblem__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Enrollment_Completed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enrollment Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_Case_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Case_DeveloperName__c</fullName>
    <description>Program Case DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Case DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Status__c</fullName>
    <description>A patient&apos;s program treatment journey status. Utilizing Status Global Value Set.</description>
    <label>Therapy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/HealthCloudGA__CarePlanProblem__c.object-meta.xml
<CustomObject>
    <description>Patients heath issue to be addressed by a care plan</description>
    <label>Problem</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/HealthCloudGA__CarePlan__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan this problem is a part of</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>CarePlanProblems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Program_Problem_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Problem DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanProblem__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <defaultValue>&apos;Planned&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__ReciprocalRole__c/HealthCloudGA__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Case_Field_Configuration__mdt/PJN_Case_Field_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search (Select Account); Case Team Member assignation
Purpose: For the Account Search on a Case, when selecting a related Account, depending on the account record type that relationship must be stored in a specific field on the Case, which this CMT record defines. For the Case Team Member assignation, this CMT also defines the case team role given to that Account on the Case Team and the reciprocal and inverse roles if required.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Case Field Configuration</label>
    <pluralLabel>Case Field Configurations</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Case_Field_Configuration__mdt/fields/PJN_Case_Team_Role_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case_Team_Role_Mapping__c</fullName>
    <description>The case team role this field maps to. Used by CaseCareTeamManager.cls trigger handler</description>
    <label>Case Team Role Mapping</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Complete</fullName>
        <isActive>false</isActive>
        <label>Treatment Complete</label>
    </customValue>
    <customValue>
        <fullName>On Therapy</fullName>
        <isActive>false</isActive>
        <label>On Therapy</label>
    </customValue>
    <description>Status field picklist value set, used for Therapy Status fields. 

Pending: Status assigned to a patient&apos;s care plan confirming they are going through the program enrollment process (new or restart patient).

On Therapy: Status assigned to a patient&apos;s care plan confirming they are fully approved for dispense and awaiting/currently receiving shipments.

Treatment Complete: Status assigned to a patient&apos;s care plan confirming they have completed their treatment journey.

Discontinued: Status assigned to a patient&apos;s care plan confirming they have previously enrolled in a program, but have either chosen or have been deemed ineligible to continue. 

Cancelled: Status assigned to a patient&apos;s care plan confirming they have either chosen not to continue with enrollment, or have been deemed ineligible to continue.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_CarePlanMissingInformationHdlrTest.cls
/**
 * @author      Mavens
 * @group       CarePlanHdlr
 * @description Test for PJN_CarePlanMissingInformationHdlr
 */
@IsTest
private class PJN_CarePlanMissingInformationHdlrTest {

    private static final Integer BULK_SIZE = 200;

    static {
        PJN_CarePlanMissingInformationHdlr.missingInformationQuery = (PJN_MissingInformationConfigQuery) Test.createStub(PJN_MissingInformationConfigQuery.class, new PJN_MissingInformationConfigMock());
        PJN_CarePlanMissingInformationHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_MappingEngine.mappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());
        PJN_CarePlanProblemHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_ProgramCase.programCaseQuery = (PJN_ProgramCaseQuery) Test.createStub(PJN_ProgramCaseQuery.class, new PJN_ProgramCaseMock());
    }

    @TestSetup
    static void makeData(){
        Test.startTest();
        CareProgram program = new CareProgram(
            Name = 'Test Program',
            PJN_Program_DeveloperName__c = 'PJN_CLP',
            StartDate = Date.today()
        );
        insert program;
        CareProgramProduct product = new CareProgramProduct(
            CareProgramId = program.Id,
            PJN_Program_Developer_Name__c = 'PJN_CLP',
            PJN_NDC__c = '1234567890',
            Name = 'Test Product'
        );
        insert product;
        Account patient = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId(),
            LastName = 'Test Patient'
        );
        Account physician = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
            LastName = 'Test Physician'
        );
        insert new List<Account> {patient, physician};
        List<Case> carePlans = new List<Case>();
        for (Integer i = 0; i < BULK_SIZE; i++) {
            carePlans.add(
                new Case (
                    RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
                    Status = 'Test ' + i,
                    Subject = 'Care Plan ' + i,
                    AccountId = patient.Id,
                    PJN_Physician__c = physician.Id,
                    PJN_Program_DeveloperName__c = 'PJN_CLP',
                    PJN_Program__c = program.Id
                )
            );
        }
        insert carePlans;

        List<PJN_Case_Field_Configuration__mdt> configList = new PJN_TestFactoryCaseFieldConfiguration().createCaseFieldsConfigurationDefaulted();
        List<CaseTeamRole> caseTeamRoleList = new List<CaseTeamRole>();
        for (PJN_Case_Field_Configuration__mdt config : configList) {
            caseTeamRoleList.add(
                new CaseTeamRole(
                    Name = config.PJN_Case_Team_Role_Mapping__c,
                    AccessLevel = 'Read'
                )
            );
        }
        Database.insert(caseTeamRoleList, false);

        HealthCloudGA__ReciprocalRole__c healthCloudRole = new HealthCloudGA__ReciprocalRole__c(
            Name='Patient',
            HealthCloudGA__InverseRole__c='Caregiver',
            RecordTypeId=SObjectType.HealthCloudGA__ReciprocalRole__c.getRecordTypeInfosByName().get('Contact Role').getRecordTypeId()
        );
        insert healthCloudRole;
        Test.stopTest();
    }

    @IsTest
    static void testIfCarePlanObtainMissingInformationStageAndActivity() {
        List<Case> carePlans = getCarePlans();
        carePlans = updateInitialEnrollmentCompleteDate(carePlans);
        Test.startTest();
        update carePlans;
        Test.stopTest();
        List<HealthCloudGA__CarePlanProblem__c> carePlanProblems = getCarePlanProblems(carePlans);
        System.assertEquals(BULK_SIZE, carePlanProblems.size(), 'Process must create the Missing Information Stage for the Care Plans');
        List<Case> missingInfos = getMissingInfoActivities(carePlans);
        System.assert(!carePlanProblems.isEmpty(), 'Process must create the Missing Information Activities for the Care Plans');
    }

    private static List<Case> getCarePlans() {
        return [
            SELECT
                Id,
                Status,
                Subject,
                AccountId,
                PJN_Physician__c,
                PJN_Program_DeveloperName__c,
                PJN_Program__c,
                PJN_Enrollment_Completed__c
            FROM
                Case
            WHERE
                RecordType.DeveloperName = 'CarePlan'
        ];
    }

    private static List<Case> updateInitialEnrollmentCompleteDate(List<Case> carePlans) {
        for (Case carePlan : carePlans) {
            carePlan.PJN_Enrollment_Completed__c = true;
        }
        return carePlans;
    }

    private static List<HealthCloudGA__CarePlanProblem__c> getCarePlanProblems(List<Case> carePlans) {
        return [
            SELECT
                Id,
                PJN_Program_Problem_DeveloperName__c,
                PJN_Status__c,
                HealthCloudGA__CarePlan__c,
                HealthCloudGA__CarePlan__r.AccountId,
                HealthCloudGA__CarePlan__r.PJN_Program_DeveloperName__c,
                HealthCloudGA__CarePlan__r.PJN_Therapy_Status__c,
                HealthCloudGA__CarePlan__r.OwnerId
            FROM
                HealthCloudGA__CarePlanProblem__c
            WHERE
                HealthCloudGA__CarePlan__c IN :carePlans
            AND
                PJN_Program_Problem_DeveloperName__c = 'PJN_CLP_MI_Stage'
            AND
                PJN_Status__c = 'Open'
        ];
    }

    private static List<Case> getMissingInfoActivities(List<Case> carePlans) {
        return [
            SELECT
                Id,
                OwnerId,
                AccountId,
                PJN_Program_DeveloperName__c,
                ParentId,
                PJN_CarePlan_Problem__c,
                PJN_Program_Case_DeveloperName__c,
                Subject,
                Origin,
                RecordTypeId
            FROM
                Case
            WHERE
                ParentId IN :carePlans
        ];
    }
}