force-app/main/default/src/objects/Account/fields/HealthCloudGA__Active__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/HealthCloudGA__SortOrder__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SortOrder__c</fullName>
    <description>Rank by which this care gap is sorted.</description>
    <inlineHelpText>Rank by which this care gap is sorted.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/HealthCloudGA__CarePlanGoal__c.object-meta.xml
<CustomObject>
    <description>Health improvement goal to address a particular health problem for a given patient as part of their care plan</description>
    <label>Goal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__CarePlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template</label>
    <referenceTo>HealthCloudGA__CarePlanTemplate__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cognition Improvement</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Muscle Strength Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__Description__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__Priority__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <color>#FFFF66</color>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
                <color>#FF6600</color>
                <label>Medium</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#FF0000</color>
                <label>High</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanGoal__c/fields/HealthCloudGA__SortOrder__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SortOrder__c</fullName>
    <label>Sort Order</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/HealthCloudGA__CarePlanTemplate__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID of the care plan template. Used in mapping the correct template upon creation of a care plan.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Health</fullName>
            </value>
            <value>
                <fullName>Endocrinology and Metabolism</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Disease Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/HealthCloudGA__Description__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/HealthCloudGA__CarePlanTemplateGoal__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template Goal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Template Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID for the care plan template goal. Used for automatic assignment of care plan templates.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/HealthCloudGA__CarePlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template</label>
    <referenceTo>HealthCloudGA__CarePlanTemplate__c</referenceTo>
    <relationshipLabel>Care Plan Template Goals</relationshipLabel>
    <relationshipName>Care_Plan_Template_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cognition Improvement</fullName>
            </value>
            <value>
                <fullName>Weight Management</fullName>
            </value>
            <value>
                <fullName>Muscle Strength Improvement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateGoal__c/fields/HealthCloudGA__Priority__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/HealthCloudGA__CarePlanTemplateTask__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template Task</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Template Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID for the care plan template task. Used for automatic assignment of care plan templates.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__AssignedTo__c</fullName>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Care Coordinator</fullName>
                <default>true</default>
                <label>Care Coordinator</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__CarePlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template</label>
    <referenceTo>HealthCloudGA__CarePlanTemplate__c</referenceTo>
    <relationshipLabel>Care Plan Template Tasks</relationshipLabel>
    <relationshipName>Care_Plan_Template_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__CarePlanTemplateGoal__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__CarePlanTemplateGoal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Plan Template Goal</label>
    <referenceTo>HealthCloudGA__CarePlanTemplateGoal__c</referenceTo>
    <relationshipLabel>Care Plan Template Tasks</relationshipLabel>
    <relationshipName>CarePlanTemplateTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Category__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diagnosis</fullName>
            </value>
            <value>
                <fullName>Counselling</fullName>
            </value>
            <value>
                <fullName>Vaccination</fullName>
            </value>
            <value>
                <fullName>Exercise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Description__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Offset__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Offset__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offset</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Priority__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Status__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
                <isActive>false</isActive>
                <label>Waiting on someone else</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Subject__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Subject__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/ApplyCarePlanTemplateHdlrTestMVN.cls
/**
 * @author      Mavens
 * @group       ApplyCarePlanTemplate
 * @description Unit tests for ApplyCarePlanTemplateHdlrMVN
 */
@isTest(isParallel=true)
public class ApplyCarePlanTemplateHdlrTestMVN {
    
    private static final Integer DATA_SIZE = 200;

    @TestSetup
    static void makeData(){
        System.runAs(new User(Id=UserInfo.getUserId())) {
            List<CaseTeamRole> ctr = [SELECT Id FROM CaseTeamRole WHERE Name='Care Coordinator'];
            if (ctr.isEmpty()) {
                insert new CaseTeamRole(Name='Care Coordinator', AccessLevel='Edit');
            }
        }

        List<Account> programParticipants = new List<Account>();
        for (Integer i=0; i<DATA_SIZE; i++) {
            programParticipants.add(
                new Account(
                    LastName = 'Test Account' + i,
                    RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Program_Participant_MVN').getRecordTypeId()
                )
            );
        }
        insert programParticipants;

        insert new List<SObject> {
            new HealthCloudGA__CarePlanTemplate__c(
                Name = 'DEDSI - DR Negative/Not Yet Screened',
                HealthCloudGA__Active__c = true,
                HealthCloudGA__Category__c = null,
                HealthCloudGA__Description__c = 'Test Care Plan Template',
                External_ID_MVN__c = 'Test_CPT'
            ),

            new HealthCloudGA__CarePlanTemplateGoal__c (
                HealthCloudGA__Active__c = true,
                HealthCloudGA__CarePlanTemplate__r = new HealthCloudGA__CarePlanTemplate__c(
                    External_ID_MVN__c = 'Test_CPT' 
                ),
                HealthCloudGA__Description__c = 'Goal Description',
                HealthCloudGA__Priority__c = 'Medium',
                HealthCloudGA__SortOrder__c = 1,
                External_ID_MVN__c = 'Test_CPTGoal'
            ),

            new HealthCloudGA__CarePlanTemplateTask__c(
                HealthCloudGA__Active__c = true,
                HealthCloudGA__AssignedTo__c = 'Care Coordinator',
                HealthCloudGA__CarePlanTemplateGoal__r = new HealthCloudGA__CarePlanTemplateGoal__c (
                    External_ID_MVN__c = 'Test_CPTGoal'
                ),
                HealthCloudGA__Category__c = null,
                HealthCloudGA__Description__c = null,
                HealthCloudGA__Offset__c = 10,
                HealthCloudGA__Priority__c = 'Normal',
                HealthCloudGA__SortOrder__c = 1,
                HealthCloudGA__Status__c = 'Open',
                HealthCloudGA__Subject__c = 'Test Subject 1',
                HealthCloudGA__Type__c = 'Uncategorized',
                External_ID_MVN__c = 'Test_CPTTask1'
            ),

            new HealthCloudGA__CarePlanTemplateTask__c(
                HealthCloudGA__Active__c = true,
                HealthCloudGA__AssignedTo__c = 'Care Coordinator',
                HealthCloudGA__CarePlanTemplateGoal__r = new HealthCloudGA__CarePlanTemplateGoal__c (
                    External_ID_MVN__c = 'Test_CPTGoal'
                ),
                HealthCloudGA__Category__c = null,
                HealthCloudGA__Description__c = null,
                HealthCloudGA__Offset__c = 20,
                HealthCloudGA__Priority__c = 'Normal',
                HealthCloudGA__SortOrder__c = 2,
                HealthCloudGA__Status__c = 'Open',
                HealthCloudGA__Subject__c = 'Test Subject 2',
                HealthCloudGA__Type__c = 'Uncategorized',
                External_ID_MVN__c = 'Test_CPTTask2'
            )
        };
    }

    @isTest
    private static void itShouldApplyCarePlanTemplates() {
        List<Case> newCarePlans = createCarePlans('Test_CPT');
        insert newCarePlans;

        List<Id> newCarePlanIds = new List<Id>((new Map<Id, Case>(newCarePlans)).keySet());

        CaseTeamRole tr = [SELECT Id FROM CaseTeamRole WHERE Name ='Care Coordinator' LIMIT 1];
        List<CaseTeamMember> caseTeamMembers = new List<CaseTeamMember>();
        for (Case carePlan : newCarePlans) {
            caseTeamMembers.add(
                new caseTeamMember (
                    ParentId = carePlan.Id,
                    MemberId = UserInfo.getUserId(),
                    TeamRoleId=tr.Id
                )
            );
        }
        insert caseTeamMembers;

        Test.startTest();
        ApplyCarePlanTemplateHdlrMVN.applyCarePlanTemplates(newCarePlanIds);
        Test.stopTest();

        System.assertEquals(DATA_SIZE, [SELECT COUNT() FROM Case WHERE RecordType.DeveloperName = 'CarePlan']);
        HealthCloudGA__CarePlanGoal__c[] goals = [SELECT Id FROM HealthCloudGA__CarePlanGoal__c WHERE HealthCloudGA__CarePlan__c IN :newCarePlans];
        System.assertEquals(DATA_SIZE, goals.size());
        System.assertEquals(DATA_SIZE*2, [SELECT COUNT() FROM Task WHERE HealthCloudGA__CarePlanGoal__c IN :goals]);
    }

    @isTest
    private static void itShouldSkipApplicationOfCarePlanTemplateWhenTemplateDoesNotExist() {
        List<Case> newCarePlans = createCarePlans('Test_CPT_Bad_Value');
        insert newCarePlans;
        List<Id> newCarePlanIds = new List<Id>((new Map<Id, Case>(newCarePlans)).keySet());
        Test.startTest();
        ApplyCarePlanTemplateHdlrMVN.applyCarePlanTemplates(newCarePlanIds);
        Test.stopTest();

        System.assertEquals(DATA_SIZE, [SELECT COUNT() FROM Case WHERE RecordType.DeveloperName = 'CarePlan']);
        HealthCloudGA__CarePlanGoal__c[] goals = [SELECT Id FROM HealthCloudGA__CarePlanGoal__c WHERE HealthCloudGA__CarePlan__c IN :newCarePlans];
        System.assertEquals(0, goals.size());
    }

    @isTest
    private static void itShouldSkipApplicationOfCarePlanTemplateWhenNoneGiven() {
        List<Case> newCarePlans = createCarePlans('');
        insert newCarePlans;
        List<Id> newCarePlanIds = new List<Id>((new Map<Id, Case>(newCarePlans)).keySet());
        Test.startTest();
        ApplyCarePlanTemplateHdlrMVN.applyCarePlanTemplates(newCarePlanIds);
        Test.stopTest();

        System.assertEquals(DATA_SIZE, [SELECT COUNT() FROM Case WHERE RecordType.DeveloperName = 'CarePlan']);
        HealthCloudGA__CarePlanGoal__c[] goals = [SELECT Id FROM HealthCloudGA__CarePlanGoal__c WHERE HealthCloudGA__CarePlan__c IN :newCarePlans];
        System.assertEquals(0, goals.size());
    }


    private static List<Case> createCarePlans(String templateName) {
        List<Case> newCarePlans = new List<Case>();
        Id carePlanRecTypeId = SObjectType.Case
            .getRecordTypeInfosByDeveloperName()
            .get('CarePlan')
            .getRecordTypeId();
        List<Account> programParticipants = [SELECT Id FROM Account];

        for (Account programParticipant : programParticipants) {
            newCarePlans.add(
                new Case (
                    // set the override so tests don't rely on configuration
                    Care_Plan_Template_Ext_ID_Override_MVN__c = templateName,
                    RecordTypeId = carePlanRecTypeId,
                    AccountId = programParticipant.Id
                )
            );
        }

        return newCarePlans;
    }
    
}