force-app/main/default/src/objects/Account/fields/HealthCloudGA__SourceSystemId__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SourceSystemId__c</fullName>
    <description>Unique external id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source System ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Account/recordTypes/PJN_Organization.recordType-meta.xml
<RecordType>
    <fullName>PJN_Organization</fullName>
    <active>true</active>
    <description>Defines a healthcare organization where physicians and staff work</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/MVN_DataLakeCMSearchHdlrTest.cls
/**
 * @author      Mavens
 * @group       DataLake
 * @description Test for MVN_DataLakeCMSearchHdlr
 */
@IsTest
private class MVN_DataLakeCMSearchHdlrTest {

    static {

    }

    @TestSetup
    static void makeData(){
        Test.startTest();
        List<Account> accounts = new List<Account>();
        accounts.add(buildHCP());
        accounts.add(buildHCO());
        insert accounts;
        Test.stopTest();
    }

    private static Account buildHCP() {
        return new Account (
            HealthCloudGA__SourceSystemId__c = '12345678902',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
            FirstName = 'May',
            LastName = 'Venn'
        );
    }

    private static Account buildHCO() {
        return new Account (
            HealthCloudGA__SourceSystemId__c = '12345678901',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Organization').getRecordTypeId(),
            Name = 'Test HCO for Affiliation'
        );
    }

    @IsTest
    static void testIfSearchHCPCorrectlyWithResults() {
        Test.setMock(HttpCalloutMock.class, new MVN_DataLakeCMSearchMock.SearchSuccessMock());
        Account acc = new Account(
            FirstName = 'John',
            LastName = 'Smith'
        );
        PJN_Contact_Information__c contactInfo = new PJN_Contact_Information__c(
            PJN_City__c = 'Chicago'
        );
        PJN_AccountSearchRqst req = buildAccountSearchRequest(true, acc, contactInfo);
        List<PJN_AccountSearchRslt> searchRslts;
        Test.startTest();
        MVN_DataLakeCMSearchHdlr handler = new MVN_DataLakeCMSearchHdlr();
        searchRslts = handler.search(req);
        Test.stopTest();
        System.assertNotEquals(null, searchRslts, 'Results cannot be null.');
        System.assert(!searchRslts.isEmpty(), 'It must have results.');
        for (PJN_AccountSearchRslt searchRslt : searchRslts) {
            System.assertNotEquals(null, searchRslt.accountDetail, 'It must have an account');
            System.assertEquals('JOHN', searchRslt.accountDetail.FirstName, 'FirstName must be John');
            System.assertEquals('SMITH', searchRslt.accountDetail.LastName, 'LastName must be Smith');
        }
    }

    @IsTest
    static void testIfSearchHCPCorrectlyWithResultsAndInsert() {
        Test.setMock(HttpCalloutMock.class, new MVN_DataLakeCMSearchMock.SearchSuccessMock());
        Account acc = new Account(
            FirstName = 'John',
            LastName = 'Smith'
        );
        PJN_Contact_Information__c contactInfo = new PJN_Contact_Information__c(
            PJN_City__c = 'Chicago'
        );
        PJN_AccountSearchRqst req = buildAccountSearchRequest(true, acc, contactInfo);
        MVN_DataLakeCMSearchHdlr handler = new MVN_DataLakeCMSearchHdlr();
        List<PJN_AccountSearchRslt> searchRslts = handler.search(req);
        System.assertNotEquals(null, searchRslts, 'Results cannot be null.');
        System.assert(!searchRslts.isEmpty(), 'It must have results.');
        for (PJN_AccountSearchRslt searchRslt : searchRslts) {
            System.assertNotEquals(null, searchRslt.accountDetail, 'It must have an account');
            System.assertEquals('JOHN', searchRslt.accountDetail.FirstName, 'FirstName must be John');
            System.assertEquals('SMITH', searchRslt.accountDetail.LastName, 'LastName must be Smith');
        }
        Id accountId;
        Test.startTest();
        accountId = handler.insertAccountDetails(searchRslts[0]);
        Test.stopTest();
        System.assertNotEquals(null, accountId, 'Account has not been inserted.');
    }

    @IsTest
    static void testIfSearchHCOCorrectlyWithResults() {
        Test.setMock(HttpCalloutMock.class, new MVN_DataLakeCMSearchMock.SearchSuccessMock());
        Account acc = new Account(
            Name = 'MAVENS HEALTH CLINIC'
        );
        PJN_Contact_Information__c contactInfo = new PJN_Contact_Information__c(
            PJN_Country__c = 'United States'
        );
        PJN_AccountSearchRqst req = buildAccountSearchRequest(false, acc, contactInfo);
        List<PJN_AccountSearchRslt> searchRslts;
        Test.startTest();
        MVN_DataLakeCMSearchHdlr handler = new MVN_DataLakeCMSearchHdlr();
        searchRslts = handler.search(req);
        Test.stopTest();
        System.assertNotEquals(null, searchRslts, 'Results cannot be null.');
        System.assert(!searchRslts.isEmpty(), 'It must have results.');
        for (PJN_AccountSearchRslt searchRslt : searchRslts) {
            System.assertNotEquals(null, searchRslt.accountDetail, 'It must have an account');
            System.assertEquals('MAVENS HEALTH CLINIC', searchRslt.accountDetail.Name, 'Name must be MAVENS HEALTH CLINIC');
        }
    }

    @IsTest
    static void testIfSearchHCOCorrectlyWithResultsAndInsert() {
        Test.setMock(HttpCalloutMock.class, new MVN_DataLakeCMSearchMock.SearchSuccessMock());
        Account acc = new Account(
            Name = 'MAVENS HEALTH CLINIC'
        );
        PJN_Contact_Information__c contactInfo = new PJN_Contact_Information__c(
            PJN_Country__c = 'United States'
        );
        PJN_AccountSearchRqst req = buildAccountSearchRequest(false, acc, contactInfo);
        MVN_DataLakeCMSearchHdlr handler = new MVN_DataLakeCMSearchHdlr();
        List<PJN_AccountSearchRslt> searchRslts = handler.search(req);
        System.assertNotEquals(null, searchRslts, 'Results cannot be null.');
        System.assert(!searchRslts.isEmpty(), 'It must have results.');
        for (PJN_AccountSearchRslt searchRslt : searchRslts) {
            System.assertNotEquals(null, searchRslt.accountDetail, 'It must have an account');
            System.assertEquals('MAVENS HEALTH CLINIC', searchRslt.accountDetail.Name, 'Name must be MAVENS HEALTH CLINIC');
        }
        Id accountId;
        Test.startTest();
        accountId = handler.insertAccountDetails(searchRslts[0]);
        Test.stopTest();
        System.assertNotEquals(null, accountId, 'Account has not been inserted.');
    }

    private static PJN_AccountSearchRqst buildAccountSearchRequest(Boolean isPersonSearch, Account acc, PJN_Contact_Information__c contactInfo) {
        PJN_AccountSearchRqst req = new PJN_AccountSearchRqst();
        req.isPersonSearch = isPersonSearch;
        req.account = acc;
        req.contactInfo = contactInfo;
        return req;
    }
}