force-app/main/default/src/objects/Account/fields/HealthCloudGA__SourceSystemId__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__SourceSystemId__c</fullName>
    <description>Unique external id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source System ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/PJN_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Stores the hierarchical relationship between people and organizations.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFFL-{0000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/MVN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Child_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Child_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup(Account) where account is affiliated with.</description>
    <label>Child Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Staff,PJN_Physician,PJN_Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated To</relationshipLabel>
    <relationshipName>Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Account__c</fullName>
    <description>Master-Detail (Account) with Affiliation Members as children accounts.</description>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Members</relationshipLabel>
    <relationshipName>Affiliation1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>PIcklist, affiliation statuses.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/MVN_DataLakeCMAffiliation.cls
/**
 * @author      Mavens
 * @group       DataLake
 * @description Wrapper for the MVN_DataLakeCMAffiliation Affiliation DataLake Object
 */
public with sharing class MVN_DataLakeCMAffiliation {

    /**
     * DataLake Affiliation objects
     */
    public String hco_hcp_affiliation_id;
    public String hco_hcp_affiliation_status;
    public String hco_hcp_affiliation_hco_id;
    public String hco_hcp_affiliation_hcp_id;

    /**
     * Get SFDC Record using the wrapper parameters obtained from the search
     * @return  `PJN_Affiliation__c`
     */
    public PJN_Affiliation__c getSFDCRecord() {
        return new PJN_Affiliation__c(
            PJN_Child_Account__r = new Account(
                HealthCloudGA__SourceSystemId__c = this.hco_hcp_affiliation_hcp_id
            ),
            PJN_Parent_Account__r = new Account(
                HealthCloudGA__SourceSystemId__c = this.hco_hcp_affiliation_hco_id
            ),
            PJN_Status__c = MVN_DataLakeCMSearchUtil.getCompleteStatusFromMapped(this.hco_hcp_affiliation_status),
            MVN_External_Id__c = this.hco_hcp_affiliation_id
        );
    }
}