force-app/main/default/src/objects/Account/fields/HealthCloudGA__Disabled__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Account/recordTypes/PJN_Organization.recordType-meta.xml
<RecordType>
    <fullName>PJN_Organization</fullName>
    <active>true</active>
    <description>Defines a healthcare organization where physicians and staff work</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Mapping_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping_Type__c</fullName>
    <label>Mapping Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PJN_Field</fullName>
                <default>true</default>
                <label>Field</label>
            </value>
            <value>
                <fullName>PJN_Label</fullName>
                <label>Label</label>
            </value>
            <value>
                <fullName>PJN_Queue</fullName>
                <label>Queue</label>
            </value>
            <value>
                <fullName>PJN_Record_Type</fullName>
                <label>Record Type</label>
            </value>
            <value>
                <fullName>PJN_Date_Formula</fullName>
                <label>Date Formula</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Source_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Object_API_Name__c</fullName>
    <description>Source Object API Name</description>
    <label>Source Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Source_Object_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Object_Type_Name__c</fullName>
    <description>Source Object Type Name</description>
    <label>Source Object Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingEngineFieldHdlrTest.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description Unit tests for PJN_MappingEngineFieldHdlr
 */
@isTest(isParallel=true) private class PJN_MappingEngineFieldHdlrTest {
    @isTest private static void mapRecord() {
        PJN_MappingFieldQuery mockMappingFieldQuery = (PJN_MappingFieldQuery) Test.createStub(PJN_MappingFieldQuery.class, new PJN_MappingFieldMock());
        PJN_MappingEngineFieldHdlr actualMappingEngineFieldHdlr = new PJN_MappingEngineFieldHdlr();
        actualMappingEngineFieldHdlr.mappingFieldQuery = mockMappingFieldQuery;
        actualMappingEngineFieldHdlr.useMapping(
            new PJN_Mapping__mdt(
                MasterLabel = 'Mocked Mapping',
                DeveloperName = 'PJN_Mocked_Mapping',
                PJN_Source_Object_Type_Name__c = 'Account',
                PJN_Source_Object_API_Name__c = 'Account',
                PJN_Mapping_Type__c = 'PJN_Field'
            )
        );

        Account parentAccount = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Organization').getRecordTypeId(),
            Name = 'Test Parent Account'
        );
        insert parentAccount;
        Account sourceAccount = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Organization').getRecordTypeId(),
            ParentId = parentAccount.Id,
            Name = 'Test Source Account'
        );
        insert sourceAccount;
        Account targetAccount = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Organization').getRecordTypeId(),
            Name = 'Test Target Account'
        );

        Test.startTest();
            Account actualTargetAccount = (Account) actualMappingEngineFieldHdlr.mapRecord(sourceAccount, targetAccount);
        Test.stopTest();

        System.assertEquals(false, actualTargetAccount.HealthCloudGA__Disabled__c, 'HealthCloudGA__Disabled__c is not set correctly');
    }

    @isTest private static void mapRecordError() {
        PJN_MappingFieldQuery mockMappingFieldQuery = (PJN_MappingFieldQuery) Test.createStub(PJN_MappingFieldQuery.class, new PJN_MappingFieldMock());
        PJN_MappingEngineFieldHdlr actualMappingEngineFieldHdlr = new PJN_MappingEngineFieldHdlr();
        actualMappingEngineFieldHdlr.mappingFieldQuery = mockMappingFieldQuery;
        PJN_Mapping__mdt mapping = new PJN_Mapping__mdt(
            MasterLabel = 'Mocked Mapping',
            DeveloperName = 'PJN_DOES_NOT_EXIST',
            PJN_Source_Object_Type_Name__c = 'Account',
            PJN_Source_Object_API_Name__c = 'Account',
            PJN_Mapping_Type__c = 'PJN_Field'
        );

        Test.startTest();
            try {
                actualMappingEngineFieldHdlr.useMapping(
                    mapping
                );
                System.assertEquals(1, 0, 'No error thrown...');
            } catch(PJN_MappingEngineException ex) {
                System.assertEquals(
                    'No specific Mapping for ' + mapping.Label + '(' + mapping.DeveloperName + ') found.',
                    ex.getMessage(),
                    'Error not thrown correctly'
                );
            } catch(Exception ex) {
                System.assertEquals(1, 0, 'Unexpected error thrown...');
            }
        Test.stopTest();
    }

    @isTest private static void getSourceFields() {
        PJN_MappingFieldQuery mockMappingFieldQuery = (PJN_MappingFieldQuery) Test.createStub(PJN_MappingFieldQuery.class, new PJN_MappingFieldMock());
        PJN_MappingEngineFieldHdlr actualMappingEngineFieldHdlr = new PJN_MappingEngineFieldHdlr();
        actualMappingEngineFieldHdlr.mappingFieldQuery = mockMappingFieldQuery;
        actualMappingEngineFieldHdlr.useMapping(
            new PJN_Mapping__mdt(
                MasterLabel = 'Mocked Mapping',
                DeveloperName = 'PJN_Mocked_Mapping',
                PJN_Source_Object_Type_Name__c = 'Account',
                PJN_Source_Object_API_Name__c = 'Account',
                PJN_Mapping_Type__c = 'PJN_Field'
            )
        );

        Test.startTest();
            List<String> actualFields = actualMappingEngineFieldHdlr.getSourceFields();
        Test.stopTest();

        System.assertEquals(3, actualFields.size(), 'number of fields are incorrect');
        System.assertEquals('Id', actualFields.get(0), 'Field is not set correctly');
        System.assertEquals('Parent.Name', actualFields.get(1), 'Field is not set correctly');
        System.assertEquals('HealthCloudGA__Disabled__c', actualFields.get(2), 'Field is not set correctly');
    }
}