force-app/main/default/src/objects/Account/fields/MVN_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>MVN_Birthdate__c</fullName>
    <description>Custom Birthdate field that supports encryption and inclusion as search criteria/results in the custom Account Search</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_SP_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_SP_Patient_Id__c</fullName>
    <description>Dispensing pharmacy unique identifier for the patient.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>SP Patient Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Effective_Months__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Months__c</fullName>
    <description>Number of months for which written opt-in consent of this type is valid.</description>
    <label>Effective Months (Written)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <description>Id used to represent record across systems and assist with data loading</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program Consent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/PJN_Shipment__c.object-meta.xml
<CustomObject>
    <description>Shipments of products to patients as part of a care plan.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Shipment__c/fields/MVN_Next_Fill_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Next_Fill_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Fill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient care plan to which the shipment relates.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_Date_Shipped__c.field-meta.xml
<CustomField>
    <fullName>PJN_Date_Shipped__c</fullName>
    <description>Date the shipment left the SP.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_Dispense_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Dispense_Type__c</fullName>
    <description>DISPENSE_TYPE, used for inbound data mapping.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Dispense Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient to whose care plan the shipment relates.</description>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>DeveloperName of the Program to which this record&apos;s parent Care Plan relates.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_Quantity_Dispensed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Quantity_Dispensed__c</fullName>
    <description>QUANTITY_DISPENSED, used for inbound data mapping.</description>
    <label>Quantity Dispensed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Shipment__c/fields/PJN_SP_Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_SP_Patient_ID__c</fullName>
    <description>SP_PATIENT_ID, used for inbound data mapping.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SP Patient ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/PJN_Transaction_Log_Object__c.object-meta.xml
<CustomObject>
    <description>Streamline error handling/logging for integrations.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Callout_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Callout_Request__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Callout Request</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Callout_Response__c.field-meta.xml
<CustomField>
    <fullName>PJN_Callout_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Callout Response</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Incoming_URL__c.field-meta.xml
<CustomField>
    <fullName>PJN_Incoming_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Incoming URL</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Level__c.field-meta.xml
<CustomField>
    <fullName>PJN_Level__c</fullName>
    <description>Transaction log level (debug, error)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Level</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Message__c.field-meta.xml
<CustomField>
    <fullName>PJN_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Record_Related__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Related__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Related</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Running_User__c.field-meta.xml
<CustomField>
    <fullName>PJN_Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Running user once error occurred.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJN_Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Transaction log type</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_OrsiniShipmentAPITest.cls
@IsTest
private class MVN_OrsiniShipmentAPITest {

    private static final Integer BULK_DATA = 200;
    private static List<Account> patients;

    @TestSetup
    static void makeData(){
        Test.startTest();
        CareProgram cp = createCareProgram();
        createProgramDataUsePurpose(cp);
        createHealthInfoDataUsePurpose(cp);
        patients = createPatients();
        createCarePlans(cp);
        Test.stopTest();
    }

    private static CareProgram createCareProgram() {
        CareProgram cp;
        try {
            cp = [
                SELECT
                    Id
                FROM
                    CareProgram
                WHERE
                    PJN_Program_DeveloperName__c = :Label.MVN_MyRare_Enrollment_ProgramDevName
            ];
        } catch (System.QueryException ex) {
            cp = new CareProgram(
                Name = 'Test Program',
                PJN_Program_DeveloperName__c = Label.MVN_MyRare_Enrollment_ProgramDevName,
                StartDate = Date.today()
            );
            insert cp;
        }
        return cp;
    }

    static void createProgramDataUsePurpose(CareProgram careProgram) {
        try {
            DataUsePurpose dup = [
                SELECT
                    Id
                FROM
                    DataUsePurpose
                WHERE
                    Name = 'TestProgram'
            ];
        } catch (System.QueryException ex) {
            insert new DataUsePurpose(
                Name = 'TestProgram',
                PJN_Effective_Months__c = 12,
                PurposeId = careProgram.Id,
                PJN_External_Id__c = 'MVN_Test_ProgramConsent'
            );
        }
    }

    static void createHealthInfoDataUsePurpose(CareProgram careProgram) {
        try {
            DataUsePurpose dup = [
                SELECT
                    Id
                FROM
                    DataUsePurpose
                WHERE
                    Name = 'Disclose/Use Health Information'
            ];
        } catch (System.QueryException ex) {
            insert new DataUsePurpose(
                Name = 'Disclose/Use Health Information',
                PJN_Effective_Months__c = 12,
                PurposeId = careProgram.Id,
                PJN_External_Id__c = 'MVN_Test_HealthInformationPrg'
            );
        }
    }

    private static List<Account> createPatients() {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < BULK_DATA; i++) {
            accounts.add(
                new Account (
                    FirstName = 'Orsini Patient',
                    LastName = 'Test',
                    MVN_Birthdate__c = Date.valueOf('1988-12-06'),
                    HealthCloudGA__Gender__pc = 'Male',
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId()
                )
            );
        }
        insert accounts;
        return accounts;
    }

    private static void createCarePlans(CareProgram careProgram) {
        List<Case> carePlans = new List<Case>();
        Integer currentSPPatientId = 123123000;
        for (Account patient : patients) {
            carePlans.add(
                new Case (
                    RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
                    AccountId = patient.Id,
                    MVN_SP_Patient_Id__c = String.valueOf(currentSPPatientId),
                    PJN_Program__c = careProgram.Id,
                    Status = 'Open'
                )
            );
            currentSPPatientId++;
        }
        insert carePlans;
    }

    @IsTest
    static void testIfSPShipmentWorksCorrectly() {
        List<Case> carePlans = getCarePlans();
        buildRequestContext(carePlans, true);
        MVN_OrsiniShipmentResponse orsiniShipmentResponse;
        Test.startTest();
        orsiniShipmentResponse = MVN_OrsiniShipmentAPI.handleOrsiniShipmentPostAPI();
        Test.stopTest();
        String transactionLogError = getTransactionLogError();
        System.assertNotEquals(null, orsiniShipmentResponse, 'Response cannot be null. Error: ' + transactionLogError);
        System.assertEquals('success', orsiniShipmentResponse.status, 'Orsini Shipment API must succeed. Error: ' + transactionLogError);
        System.assertEquals(null, orsiniShipmentResponse.message, 'No message in the response. Error: ' + transactionLogError);
        System.assertNotEquals(null, orsiniShipmentResponse.shipments, 'shipments cannot be null. Error: ' + transactionLogError);
        System.assert(!orsiniShipmentResponse.shipments.isEmpty(), 'shipments cannot be empty. Error: ' + transactionLogError);
        for (MVN_OrsiniShipmentResult shipmentResult : orsiniShipmentResponse.shipments) {
            System.assert(shipmentResult.success, 'Shipment must succeed. Error: ' + transactionLogError);
            System.assertEquals(null, shipmentResult.message, 'Shipment message must be null. Error: ' + transactionLogError);
        }
        List<PJN_Shipment__c> shipments = getShipments(carePlans);
        System.assertEquals(carePlans.size(), shipments.size(), 'Shipments must match number of CarePlans. Error: ' + transactionLogError);
        for (PJN_Shipment__c shipment : shipments) {
            System.assertNotEquals(null, shipment.PJN_Patient__c, 'Patient Id cannot be null. Error: ' + transactionLogError);
            System.assertNotEquals(null, shipment.PJN_Care_Plan__c, 'CarePlan Id cannot be null. Error: ' + transactionLogError);
            System.assertNotEquals(null, shipment.PJN_SP_Patient_ID__c, 'SP Patient Id cannot be null. Error: ' + transactionLogError);
            System.assertEquals('COM', shipment.PJN_Dispense_Type__c, 'Dispense must be COM. Error: ' + transactionLogError);
            System.assertEquals(System.today(), shipment.PJN_Date_Shipped__c, 'Date shipped must be today. Error: ' + transactionLogError);
            System.assertEquals(System.today().addMonths(1), shipment.MVN_Next_Fill_Date__c, 'Next Fill Date date must be in a month. Error: ' + transactionLogError);
            System.assertEquals('ndc', shipment.PJN_NDC__c, 'NDC must be ndc value. Error: ' + transactionLogError);
            System.assertEquals('product description', shipment.PJN_Product_Description__c, 'Shipment must have a product description.');
            System.assertEquals(12, shipment.PJN_Quantity_Dispensed__c, 'Shipment must have a quantity dispensed. Error: ' + transactionLogError);
        }
    }

    @IsTest
    static void testIfSPShipmentWorksNoEvent() {
        List<Case> carePlans = new List<Case>();
        buildRequestContext(carePlans, true);
        MVN_OrsiniShipmentResponse orsiniShipmentResponse;
        Test.startTest();
        orsiniShipmentResponse = MVN_OrsiniShipmentAPI.handleOrsiniShipmentPostAPI();
        Test.stopTest();
        String transactionLogError = getTransactionLogError();
        System.assertNotEquals(null, orsiniShipmentResponse, 'Response cannot be null. Error: ' + transactionLogError);
        System.assertEquals('error', orsiniShipmentResponse.status, 'Orsini Shipment API must error. Error: ' + transactionLogError);
        System.assertNotEquals(null, orsiniShipmentResponse.message, 'No message in the response. Error: ' + transactionLogError);
        System.assertEquals(null, orsiniShipmentResponse.shipments, 'shipments must be null. Error: ' + transactionLogError);
    }

    @IsTest
    static void testIfSPShipmentWorksWrong() {
        List<Case> carePlans = getCarePlans();
        buildRequestContext(carePlans, false);
        MVN_OrsiniShipmentResponse orsiniShipmentResponse;
        Test.startTest();
        orsiniShipmentResponse = MVN_OrsiniShipmentAPI.handleOrsiniShipmentPostAPI();
        Test.stopTest();
        String transactionLogError = getTransactionLogError();
        System.assertNotEquals(null, orsiniShipmentResponse, 'Response cannot be null. Error: ' + transactionLogError);
        System.assertEquals('error', orsiniShipmentResponse.status, 'Orsini Shipment API must error. Error: ' + transactionLogError);
        System.assertNotEquals(null, orsiniShipmentResponse.shipments, 'shipments cannot be null. Error: ' + transactionLogError);
        System.assert(!orsiniShipmentResponse.shipments.isEmpty(), 'shipments cannot be empty. Error: ' + transactionLogError);
        Boolean oneIsSuccess = false;
        for (MVN_OrsinishipmentResult shipmentResult : orsiniShipmentResponse.shipments) {
            System.assert(!shipmentResult.success || !oneIsSuccess, 'Shipment must be wrong. Error: ' + transactionLogError);
            System.assert(shipmentResult.message != null || !oneIsSuccess, 'Shipment message must be null. Error: ' + transactionLogError);
            oneIsSuccess = oneIsSuccess || shipmentResult.success;
        }
        List<PJN_Shipment__c> shipments = getShipments(carePlans);
        System.assertEquals(1, shipments.size(), 'Only one Shipment should be created. Error: ' + transactionLogError);
    }

    private static List<Case> getCarePlans() {
        return [
            SELECT
                Id,
                MVN_SP_Patient_Id__c
            FROM
                Case
            WHERE
                RecordType.DeveloperName = 'CarePlan'
        ];
    }
    private static void buildRequestContext(List<Case> carePlans, Boolean hasPatientId) {
        String jsonRequestBody = getJsonRequestBody(carePlans, hasPatientId);

        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(jsonRequestBody); // Add JSON Message as a POST

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
    }

    private static String getJsonRequestBody(List<Case> carePlans, Boolean hasPatientId) {
        List<MVN_OrsiniShipmentRequest> requests = new List<MVN_OrsiniShipmentRequest>();
        Boolean oneAtLeast = false;
        List<Id> returningCarePlanIds = new List<Id>();
        for (Case carePlan : carePlans) {
            MVN_OrsiniShipmentRequest request = new MVN_OrsiniShipmentRequest();
            request.unique_id = carePlan.MVN_SP_Patient_Id__c;
            request.sp_patient_id = hasPatientId || !oneAtLeast ? carePlan.MVN_SP_Patient_Id__c : '99999999';
            request.dispense_type = 'COM';
            request.dispense_date = System.today();
            request.next_fill_date = System.today().addMonths(1);
            request.ndc = 'ndc';
            request.product_description = 'product description';
            request.quantity_dispensed = 12;
            requests.add(request);
            if (hasPatientId || !oneAtLeast) {
                returningCarePlanIds.add(carePlan.Id);
            }
            Test.setFixedSearchResults(returningCarePlanIds);
            oneAtLeast = true;
        }
        return System.JSON.serializePretty(requests);
    }

    private static List<PJN_Shipment__c> getShipments(List<Case> carePlans) {
        return [
            SELECT
                Id,
                PJN_Care_Plan__c,
                PJN_Care_Plan__r.MVN_SP_Patient_Id__c,
                PJN_Patient__c,
                PJN_SP_Patient_ID__c,
                PJN_Dispense_Type__c,
                PJN_Date_Shipped__c,
                MVN_Next_Fill_Date__c,
                PJN_NDC__c,
                PJN_Product_Description__c,
                PJN_Quantity_Dispensed__c
            FROM
                PJN_Shipment__c
            WHERE
                PJN_Care_Plan__c IN :carePlans
        ];
    }

    private static String getTransactionLogError() {
        List<PJN_Transaction_Log_Object__c> transactionLogs = [
            SELECT
                Id,
                PJN_Callout_Request__c,
                PJN_Callout_Response__c,
                PJN_Incoming_URL__c,
                PJN_Level__c,
                PJN_Record_Related__c,
                PJN_Running_User__c,
                PJN_Type__c,
                PJN_Message__c
            FROM
                PJN_Transaction_Log_Object__c
        ];
        String transactionLogError;
        if (!transactionLogs.isEmpty()) {
            transactionLogError = transactionLogs[0].PJN_Callout_Response__c;
        }
        return transactionLogError;
    }
}