force-app/main/default/src/objects/Account/fields/MVN_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>MVN_Birthdate__c</fullName>
    <description>Custom Birthdate field that supports encryption and inclusion as search criteria/results in the custom Account Search</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_DEA__c.field-meta.xml
<CustomField>
    <fullName>PJN_DEA__c</fullName>
    <description>Text (9) field for Physician Account DEA.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DEA</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_NPI__c.field-meta.xml
<CustomField>
    <fullName>PJN_NPI__c</fullName>
    <description>Text (10) NPI field.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Professional_Designation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Professional_Designation__c</fullName>
    <description>Picklist for Physician Account Credentials or Professional Designation.</description>
    <label>Professional Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_SLN__c.field-meta.xml
<CustomField>
    <fullName>PJN_SLN__c</fullName>
    <description>Text (15) field for Physician Account SLN.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>SLN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Specialty__c.field-meta.xml
<CustomField>
    <fullName>PJN_Specialty__c</fullName>
    <description>Picklist, Physician Account Specialties.</description>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Allergy and Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Diagnostic Radiology</fullName>
            </value>
            <value>
                <fullName>Emergency Medicine</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Family Medicine</fullName>
            </value>
            <value>
                <fullName>Internal Medicine</fullName>
            </value>
            <value>
                <fullName>Lipidology</fullName>
            </value>
            <value>
                <fullName>Medical Geneticist</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Obstetrics and Gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Pediatric Cardiology</fullName>
            </value>
            <value>
                <fullName>Pediatric Endocrinology</fullName>
            </value>
            <value>
                <fullName>Pediatric Lipidology</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physical Medicine and Rehabilitation</fullName>
            </value>
            <value>
                <fullName>Preventative Medicine</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Caregiver__c.field-meta.xml
<CustomField>
    <fullName>PJN_Caregiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caregiver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Caregiver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Caregiver)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Staff__c.field-meta.xml
<CustomField>
    <fullName>PJN_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan staff account.</description>
    <label>Staff</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Staff</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Staff)</relationshipLabel>
    <relationshipName>CasesStaff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Effective_Months__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Months__c</fullName>
    <description>Number of months for which written opt-in consent of this type is valid.</description>
    <label>Effective Months (Written)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <description>Id used to represent record across systems and assist with data loading</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Email__c</fullName>
    <description>Email: Correspondence email address.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (50): Contact Information External ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Email.recordType-meta.xml
<RecordType>
    <fullName>PJN_Email</fullName>
    <active>true</active>
    <description>Defines email contact information</description>
    <label>Email</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Phone.recordType-meta.xml
<RecordType>
    <fullName>PJN_Phone</fullName>
    <active>true</active>
    <description>Defines phone contact information</description>
    <label>Phone</label>
</RecordType>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/MVN_StampPrimaryPhoneOnCasesHdlrTest.cls
/**
 * @author      Mavens
 * @group       ServiceCloudVoice
 * @description Test for MVN_StampPrimaryPhoneOnCasesHdlr
 */
@isTest
private class MVN_StampPrimaryPhoneOnCasesHdlrTest {
    private static List<Account> accounts;
    private static Account patient;
    private static Account physician;
    private static Account caregiver;
    private static Account staff;
    private static Case carePlan;

    static {
        PJN_TriggerHandlerSettingQuery.triggerHandlerSettingBySObjectType = new Map<SObjectType, List<PJN_Trigger_Handler_Setting__mdt>> {
            SObjectType.PJN_Contact_Information__c.getSObjectType() => new List<PJN_Trigger_Handler_Setting__mdt> {
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_StampPrimaryPhoneOnCasesHdlr',
                    PJN_Event__c = 'BEFORE_INSERT',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_StampPrimaryPhoneOnCasesHdlr',
                    PJN_Event__c = 'BEFORE_UPDATE',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_StampPrimaryPhoneOnCasesHdlr',
                    PJN_Event__c = 'AFTER_INSERT',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_StampPrimaryPhoneOnCasesHdlr',
                    PJN_Event__c = 'AFTER_UPDATE',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                )
            }
        };

        CareProgram cp = createCareProgram();
        createProgramDataUsePurpose(cp);
        createHealthInfoDataUsePurpose(cp);
        accounts = new List<Account> {
            buildPatient(),
            buildPhysician(),
            buildCaregiver(),
            buildStaff()
        };
        insert accounts;
        patient = getAccount(accounts, 'PJN_Patient');
        physician = getAccount(accounts, 'PJN_Physician');
        caregiver = getAccount(accounts, 'PJN_Caregiver');
        staff = getAccount(accounts, 'PJN_Staff');

        carePlan = createCarePlan(cp);
    }

    private static CareProgram createCareProgram() {
        CareProgram cp;
        try {
            cp = [
                SELECT
                    Id
                FROM
                    CareProgram
                WHERE
                    PJN_Program_DeveloperName__c = :Label.MVN_MyRare_Enrollment_ProgramDevName
            ];
        } catch (System.QueryException ex) {
            cp = new CareProgram(
                Name = 'Test Program',
                PJN_Program_DeveloperName__c = Label.MVN_MyRare_Enrollment_ProgramDevName,
                StartDate = Date.today()
            );
            insert cp;
        }
        return cp;
    }

    static void createProgramDataUsePurpose(CareProgram careProgram) {
        try {
            DataUsePurpose dup = [
                SELECT
                    Id
                FROM
                    DataUsePurpose
                WHERE
                    Name = 'TestProgram'
            ];
        } catch (System.QueryException ex) {
            insert new DataUsePurpose(
                Name = 'TestProgram',
                PJN_Effective_Months__c = 12,
                PurposeId = careProgram.Id,
                PJN_External_Id__c = 'MVN_Test_ProgramConsent'
            );
        }
    }

    static void createHealthInfoDataUsePurpose(CareProgram careProgram) {
        try {
            DataUsePurpose dup = [
                SELECT
                    Id
                FROM
                    DataUsePurpose
                WHERE
                    Name = 'Disclose/Use Health Information'
            ];
        } catch (System.QueryException ex) {
            insert new DataUsePurpose(
                Name = 'Disclose/Use Health Information',
                PJN_Effective_Months__c = 12,
                PurposeId = careProgram.Id,
                PJN_External_Id__c = 'MVN_Test_HealthInformationPrg'
            );
        }
    }

    private static Account buildPatient() {
        Account patient = new Account (
            FirstName = 'Patient',
            LastName = 'Test',
            MVN_Birthdate__c = Date.valueOf('1988-12-06'),
            HealthCloudGA__Gender__pc = 'Male',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId()
        );
        return patient;
    }

    private static Account buildPhysician() {
        Account physician = new Account (
            FirstName = 'Physician',
            LastName = 'Test',
            PJN_Professional_Designation__c = 'MD',
            PJN_DEA__c = '123456789',
            PJN_NPI__c = '987654321',
            PJN_SLN__c = '123789456',
            PJN_Specialty__c = 'Anesthesiology',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId()
        );
        return physician;
    }

    private static Account buildCaregiver() {
        Account caregiver = new Account (
            FirstName = 'Caregiver',
            LastName = 'Test',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Caregiver').getRecordTypeId()
        );
        return caregiver;
    }

    private static Account buildStaff() {
        Account staff = new Account (
            FirstName = 'Staff',
            LastName = 'Test',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Staff').getRecordTypeId()
        );
        return staff;
    }

    private static Account getAccount(List<Account> accounts, String recordTypeDevName) {
        return [
            SELECT
                Id
            FROM
                Account
            WHERE
                Id IN :accounts
            AND
                RecordType.DeveloperName = :recordTypeDevName
            LIMIT 1
        ];
    }

    private static List<PJN_Contact_Information__c> buildContactInformations(Account acc) {
        List<PJN_Contact_Information__c> cis = new List<PJN_Contact_Information__c>();
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = acc.Id,
                PJN_Address_Line_1__c = '123 Main Street',
                PJN_Address_Line_2__c = 'Building 1',
                PJN_City__c = 'Chicago',
                PJN_State__c = 'IL',
                PJN_Postal_Code__c = '60606',
                PJN_Country__c = 'United States',
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId()
            )
        );
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = acc.Id,
                PJN_Email__c = 'test@test.test',
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Email').getRecordTypeId()
            )
        );
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = acc.Id,
                PJN_Phone__c = '8005551111',
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId()
            )
        );
        return cis;
    }

    private static Case createCarePlan(CareProgram careProgram) {
        Case carePlan = new Case (
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            AccountId = patient.Id,
            PJN_Physician__c = physician.Id,
            PJN_Caregiver__c = caregiver.Id,
            PJN_Staff__c = staff.Id,
            PJN_Program__c = careProgram.Id,
            Status = 'Open'
        );
        insert carePlan;
        return carePlan;
    }

    @isTest
    static void testStampPrimaryPhoneOnCasesOnCIInsert() {
        List<PJN_Contact_Information__c> cis = new List<PJN_Contact_Information__c>();
        cis.addAll(buildContactInformations(patient));
        cis.addAll(buildContactInformations(physician));
        cis.addAll(buildContactInformations(caregiver));
        cis.addAll(buildContactInformations(staff));
        insert cis;

        carePlan = [
            SELECT Id,
                   MVN_Patient_Primary_Phone_E164__c,
                   MVN_Caregiver_Primary_Phone_E164__c,
                   MVN_Physician_Primary_Phone_E164__c,
                   MVN_Staff_Primary_Phone_E164__c
              FROM Case 
             WHERE Id = :carePlan.Id
        ];
        
        System.assertEquals(carePlan.MVN_Patient_Primary_Phone_E164__c, '+18005551111');
        System.assertEquals(carePlan.MVN_Caregiver_Primary_Phone_E164__c, '+18005551111');
        System.assertEquals(carePlan.MVN_Physician_Primary_Phone_E164__c, '+18005551111');
        System.assertEquals(carePlan.MVN_Staff_Primary_Phone_E164__c, '+18005551111');
    }

    @isTest
    static void testStampPrimaryPhoneOnCasesOnCIUpdate() {
        List<PJN_Contact_Information__c> cis = new List<PJN_Contact_Information__c>();
        cis.addAll(buildContactInformations(patient));
        cis.addAll(buildContactInformations(physician));
        cis.addAll(buildContactInformations(caregiver));
        cis.addAll(buildContactInformations(staff));
        insert cis;

        cis.clear();
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = patient.Id,
                PJN_Phone__c = '8005552222',
                PJN_Set_as_Primary__c = false,
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId()
            )
        );
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = physician.Id,
                PJN_Phone__c = '8005552222',
                PJN_Set_as_Primary__c = false,
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId()
            )
        );
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = caregiver.Id,
                PJN_Phone__c = '8005552222',
                PJN_Set_as_Primary__c = false,
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId()
            )
        );
        cis.add(
            new PJN_Contact_Information__c (
                PJN_Account__c = staff.Id,
                PJN_Phone__c = '8005552222',
                PJN_Set_as_Primary__c = false,
                RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId()
            )
        );
        insert cis;
        
        for (PJN_Contact_Information__c ci : cis) {
            ci.PJN_Set_as_Primary__c = true;
        }
        Test.startTest();
        update cis;
        Test.stopTest();

        carePlan = [
            SELECT Id,
                   MVN_Patient_Primary_Phone_E164__c,
                   MVN_Caregiver_Primary_Phone_E164__c,
                   MVN_Physician_Primary_Phone_E164__c,
                   MVN_Staff_Primary_Phone_E164__c
              FROM Case 
             WHERE Id = :carePlan.Id
        ];

        System.assertEquals(carePlan.MVN_Patient_Primary_Phone_E164__c, '+18005552222');
        System.assertEquals(carePlan.MVN_Caregiver_Primary_Phone_E164__c, '+18005552222');
        System.assertEquals(carePlan.MVN_Physician_Primary_Phone_E164__c, '+18005552222');
        System.assertEquals(carePlan.MVN_Staff_Primary_Phone_E164__c, '+18005552222');
    }

}