force-app/main/default/src/objects/Account/fields/MVN_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>MVN_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Shipping Address)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/MVN_SMS_Phone__c.field-meta.xml
<CustomField>
    <fullName>MVN_SMS_Phone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SMS Phone</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (SMS Phone)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/MVN_Set_as_Shipping__c.field-meta.xml
<CustomField>
    <fullName>MVN_Set_as_Shipping__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this record should be set as the shipping address. A trigger will manage this update.</description>
    <inlineHelpText>Indicates this record should be set as the address where product should be shipped for a patient.</inlineHelpText>
    <label>Set as Shipping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/MVN_Set_as_SMS__c.field-meta.xml
<CustomField>
    <fullName>MVN_Set_as_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this record should be set as the SMS phone number. A trigger will manage this update.</description>
    <inlineHelpText>Indicates this record should be set as the SMS phone number.</inlineHelpText>
    <label>Set as SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Email.recordType-meta.xml
<RecordType>
    <fullName>PJN_Email</fullName>
    <active>true</active>
    <description>Defines email contact information</description>
    <label>Email</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Fax.recordType-meta.xml
<RecordType>
    <fullName>PJN_Fax</fullName>
    <active>true</active>
    <description>Defines fax contact information</description>
    <label>Fax</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Phone.recordType-meta.xml
<RecordType>
    <fullName>PJN_Phone</fullName>
    <active>true</active>
    <description>Defines phone contact information</description>
    <label>Phone</label>
</RecordType>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/PJN_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search
Purpose: Definition of handler class used for the Account Search and the number max of results to be displayed. Global setting for all Programs; change only the max results field.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Global Setting</label>
    <pluralLabel>Global Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Account_Search_Handler_Classes__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account_Search_Handler_Classes__c</fullName>
    <defaultValue>&quot;PJN_AccountSearchHdlr&quot;</defaultValue>
    <description>Comma separated list of classes used in the Account Search. Results from each class are merged.</description>
    <inlineHelpText>Comma separated list of classes used in the Account Search. Results from each class are merged. The win order is the order they are listed (eg: A,B,C means A&gt;B&gt;C with A being the winner).</inlineHelpText>
    <label>Account Search Handler Classes</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Account_Search_Max_Results__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account_Search_Max_Results__c</fullName>
    <defaultValue>50</defaultValue>
    <description>Max number of search results returned by account search.  Cannot exceed the SOSL limit of 200.</description>
    <label>Account Search Max Results</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Address_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Address_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info address record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info address record types.</inlineHelpText>
    <label>Contact Info Address Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Email_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Email_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info email record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info email record types.</inlineHelpText>
    <label>Contact Info Email Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Fax_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Fax_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info fax record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info fax record types.</inlineHelpText>
    <label>Contact Info Fax Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Phone_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Phone_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info phone record types.</description>
    <label>Contact Info Phone Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Create_DCR__c.field-meta.xml
<CustomField>
    <fullName>PJN_Create_DCR__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allow Data Change Request creation</description>
    <inlineHelpText>Allow Data Change Request creation</inlineHelpText>
    <label>Create DCR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Enable_Event_Automation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enable_Event_Automation__c</fullName>
    <defaultValue>true</defaultValue>
    <description>The Event Automation Handler can be disabled by turning this setting off.</description>
    <label>Enable Event Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Include_Open_Data_Network__c.field-meta.xml
<CustomField>
    <fullName>PJN_Include_Open_Data_Network__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tick this checkbox to include the Open Data records searching, synchronising or downloading any record.</description>
    <inlineHelpText>Tick this checkbox to include the Open Data records searching, synchronising or downloading any record.</inlineHelpText>
    <label>Include Open Data Network?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_API_Version__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_API_Version__c</fullName>
    <defaultValue>&quot;v19.0&quot;</defaultValue>
    <description>Veeva Network API version.</description>
    <label>Network API Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Named_Credential__c</fullName>
    <defaultValue>&quot;PJN_Veeva_Network&quot;</defaultValue>
    <description>Named credential used to connect with Veeva Network.</description>
    <inlineHelpText>Named credential used to connect with Veeva Network.</inlineHelpText>
    <label>Network Named Credential</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Network_System__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_System__c</fullName>
    <defaultValue>&quot;PJN&quot;</defaultValue>
    <description>System used to identify in every connection with Veeva Network.</description>
    <inlineHelpText>System used to identify in every connection with Veeva Network.</inlineHelpText>
    <label>Network System</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Transaction_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>PJN_Transaction_Log_Level__c</fullName>
    <defaultValue>&quot;All&quot;</defaultValue>
    <description>Transaction log levels accepted - None, All, Errors</description>
    <inlineHelpText>Transaction log levels accepted - None, All, Errors</inlineHelpText>
    <label>Transaction Log Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Veeva_Network__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows Veeva Network connection (Send/Retrieve DCRs, Sync, Search...)</description>
    <inlineHelpText>Allows Veeva Network connection</inlineHelpText>
    <label>Veeva Network</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/MVN_SetShippingAndSMSContactInfoHdlrTest.cls
@IsTest
private class MVN_SetShippingAndSMSContactInfoHdlrTest {

    @TestSetup
    static void makeData(){
        new PJN_TestFactoryAccount().create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Account.getRecordTypeInfosByName().get('Patient').getRecordTypeId(),
                'LastName' => 'Patient 1 Test'
            }
        );
    }

    static {
        PJN_Utilities.globalSetting = new PJN_Global_Setting__mdt(
            PJN_Account_Search_Handler_Classes__c = 'PJN_AccountSearchHdlr',
            PJN_Account_Search_Max_Results__c = 20.0,
            PJN_Create_DCR__c = false,
            PJN_Enable_Event_Automation__c = true,
            PJN_Include_Open_Data_Network__c = false,
            PJN_Network_API_Version__c = 'v19.0',
            PJN_Network_Named_Credential__c = 'ARGX_Veeva_Network',
            PJN_Network_System__c = 'PJN',
            PJN_Transaction_Log_Level__c = 'All',
            PJN_Veeva_Network__c = true,
            PJN_Contact_Info_Address_Record_Types__c = 'PJN_Address',
            PJN_Contact_Info_Email_Record_Types__c = 'PJN_Email',
            PJN_Contact_Info_Phone_Record_Types__c = 'PJN_Phone',
            PJN_Contact_Info_Fax_Record_Types__c = 'PJN_Fax'
        );

        PJN_TriggerHandlerSettingQuery.triggerHandlerSettingBySObjectType = new Map<SObjectType, List<PJN_Trigger_Handler_Setting__mdt>> {
            SObjectType.PJN_Contact_Information__c.getSObjectType() => new List<PJN_Trigger_Handler_Setting__mdt> {
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_SetShippingAndSMSContactInfoHdlr',
                    PJN_Event__c = 'BEFORE_INSERT',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_SetShippingAndSMSContactInfoHdlr',
                    PJN_Event__c = 'BEFORE_UPDATE',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_SetShippingAndSMSContactInfoHdlr',
                    PJN_Event__c = 'AFTER_INSERT',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'MVN_SetShippingAndSMSContactInfoHdlr',
                    PJN_Event__c = 'AFTER_UPDATE',
                    PJN_SObject_API_Name__c = 'PJN_Contact_Information__c'
                )
            }
        };
    }

    @isTest
    private static void testSetShippingAndSMSContactInformationOnInsert() {
        Account patient = getPatient();
        List<PJN_Contact_Information__c> contactInfoList = new List<PJN_Contact_Information__c>();
        contactInfoList.add(new PJN_Contact_Information__c(
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId(),
            PJN_Address_Line_1__c = 'address test',
            PJN_Account__c = patient.Id,
            MVN_Set_as_Shipping__c = true
        ));
        contactInfoList.add(new PJN_Contact_Information__c(
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId(),
            PJN_Phone__c = '123456789',
            PJN_Account__c = patient.Id,
            MVN_Set_as_SMS__c = true
        ));
        Test.startTest();
        insert contactInfoList;
        Test.stopTest();

        for (PJN_Contact_Information__c contactInfoResult : getContactInformation(contactInfoList)) {
            System.assert(!contactInfoResult.MVN_Set_as_SMS__c);
            System.assert(!contactInfoResult.MVN_Set_as_Shipping__c);
        }
        Account accResult = getPatient(patient.Id);
        System.assert(accResult.MVN_Shipping_Address__c == contactInfoList.get(0).Id);
        System.assert(accResult.MVN_SMS_Phone__c == contactInfoList.get(1).Id);
    }

    @isTest
    private static void testSetShippingAndSMSContactInformationOnUpdate() {
        Account patient = getPatient();
        List<PJN_Contact_Information__c> contactInfoList = new List<PJN_Contact_Information__c>();
        contactInfoList.add(new PJN_Contact_Information__c(
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId(),
            PJN_Address_Line_1__c = 'address test',
            PJN_Account__c = patient.Id,
            MVN_Set_as_Shipping__c = false
        ));
        contactInfoList.add(new PJN_Contact_Information__c(
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId(),
            PJN_Phone__c = '123456789',
            PJN_Account__c = patient.Id,
            MVN_Set_as_SMS__c = false
        ));
        insert contactInfoList;
        patient = getPatient(patient.Id);
        System.assertEquals(null, patient.MVN_Shipping_Address__c, 'Patient cannot have a Shipping Address at this stage.');
        System.assertEquals(null, patient.MVN_SMS_Phone__c, 'Patient cannot have a SMS Phone at this stage.');
        Test.startTest();
        contactInfoList[0].MVN_Set_as_Shipping__c = true;
        contactInfoList[1].MVN_Set_as_SMS__c = true;
        update contactInfoList;
        Test.stopTest();
        patient = getPatient(patient.Id);
        System.assertNotEquals(null, patient.MVN_Shipping_Address__c, 'Patient must have a Shipping Address at this stage.');
        System.assertNotEquals(null, patient.MVN_SMS_Phone__c, 'Patient must have a SMS Phone at this stage.');
    }

    @isTest
    private static void testUpdateSMSContactInformation() {
        Account patient = getPatient();
        PJN_Contact_Information__c contactInfo = new PJN_Contact_Information__c(
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Phone').getRecordTypeId(),
            PJN_Phone__c = '123456789',
            PJN_Account__c = patient.Id,
            MVN_Set_as_SMS__c = true
        );
        insert contactInfo;
        patient = getPatient(patient.Id);
        System.assertEquals(null, patient.MVN_Shipping_Address__c, 'Patient cannot have a Shipping Address at this stage.');
        System.assertEquals(contactInfo.Id, patient.MVN_SMS_Phone__c, 'Patient must have a SMS Phone at this stage.');
        Test.startTest();
        PJN_Contact_Information__c newContactInfo = new PJN_Contact_Information__c(
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Fax').getRecordTypeId(),
            PJN_Phone__c = '123456789',
            PJN_Account__c = patient.Id,
            MVN_Set_as_SMS__c = true
        );
        insert newContactInfo;
        Test.stopTest();
        patient = getPatient(patient.Id);
        System.assertEquals(newContactInfo.Id, patient.MVN_SMS_Phone__c, 'Patient must have a SMS Phone at this stage.');
    }

    private static List<PJN_Contact_Information__c> getContactInformation(List<PJN_Contact_Information__c> contactInfoList) {
        return [
            SELECT
                MVN_Set_as_SMS__c,
                MVN_Set_as_Shipping__c
            FROM
                PJN_Contact_Information__c
            WHERE
                Id IN :contactInfoList
        ];
    }

    private static Account getPatient(Id patientId) {
        return [
            SELECT
                MVN_Shipping_Address__c,
                MVN_SMS_Phone__c
            FROM
                Account
            WHERE
                Id = :patientId
        ];
    }

    private static Account getPatient() {
        return [SELECT Id FROM Account LIMIT 1];
    }

}