force-app/main/default/src/objects/Account/fields/MVN_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>MVN_Birthdate__c</fullName>
    <description>Custom Birthdate field that supports encryption and inclusion as search criteria/results in the custom Account Search</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/MVN_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_Id__c</fullName>
    <description>Unique identifier for the patient. Displays a Legacy Id if one is available or the Salesforce Id if there is no Legacy Id.</description>
    <formula>IF(ISBLANK(MVN_Patient_Legacy_Id__c), MVN_Patient_Id_Auto_Number__c, MVN_Patient_Legacy_Id__c)</formula>
    <label>Patient Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_Id__c</fullName>
    <formula>Account.MVN_Patient_Id__c</formula>
    <label>Patient Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_SP_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_SP_Patient_Id__c</fullName>
    <description>Dispensing pharmacy unique identifier for the patient.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>SP Patient Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Effective_Months__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Months__c</fullName>
    <description>Number of months for which written opt-in consent of this type is valid.</description>
    <label>Effective Months (Written)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <description>Id used to represent record across systems and assist with data loading</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program Consent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Patient_Id__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Patient Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Case__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case that triggered the Event.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Patient__c.field-meta.xml
<CustomField>
    <fullName>PJN_Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient to whose care plan the event is related.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_SP_Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_SP_Patient_ID__c</fullName>
    <description>SP_PATIENT_ID, used for inbound data mapping.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>SP Patient ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>STATUS, used for inbound data mapping.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Status_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status_Date__c</fullName>
    <description>STATUS_DATE, used for inbound data mapping.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sub_Status__c</fullName>
    <description>SUBSTATUS, used for inbound data mapping.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Sub-Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/MVN_Pharmacy_Status_Update.recordType-meta.xml
<RecordType>
    <fullName>MVN_Pharmacy_Status_Update</fullName>
    <active>true</active>
    <description>Defines an event representing an update to the patient&apos;s pharmacy status and/or sub-status</description>
    <label>Pharmacy Status Update</label>
</RecordType>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/PJN_Transaction_Log_Object__c.object-meta.xml
<CustomObject>
    <description>Streamline error handling/logging for integrations.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Callout_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Callout_Request__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Callout Request</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Callout_Response__c.field-meta.xml
<CustomField>
    <fullName>PJN_Callout_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Callout Response</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Incoming_URL__c.field-meta.xml
<CustomField>
    <fullName>PJN_Incoming_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Incoming URL</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Level__c.field-meta.xml
<CustomField>
    <fullName>PJN_Level__c</fullName>
    <description>Transaction log level (debug, error)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Level</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Message__c.field-meta.xml
<CustomField>
    <fullName>PJN_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Record_Related__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Related__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Related</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Running_User__c.field-meta.xml
<CustomField>
    <fullName>PJN_Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Running user once error occurred.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PJN_Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Transaction_Log_Object__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Transaction log type</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_OrsiniStatusAPITest.cls
@IsTest
private class MVN_OrsiniStatusAPITest {

    private static final Integer BULK_DATA = 200;
    private static List<Account> patients;

    @TestSetup
    static void makeData(){
        Test.startTest();
        CareProgram cp = createCareProgram();
        createProgramDataUsePurpose(cp);
        createHealthInfoDataUsePurpose(cp);
        patients = createPatients();
        createCarePlans(cp);
        Test.stopTest();
    }

    private static CareProgram createCareProgram() {
        CareProgram cp;
        try {
            cp = [
                SELECT
                    Id
                FROM
                    CareProgram
                WHERE
                    PJN_Program_DeveloperName__c = :Label.MVN_MyRare_Enrollment_ProgramDevName
            ];
        } catch (System.QueryException ex) {
            cp = new CareProgram(
                Name = 'Test Program',
                PJN_Program_DeveloperName__c = Label.MVN_MyRare_Enrollment_ProgramDevName,
                StartDate = Date.today()
            );
            insert cp;
        }
        return cp;
    }

    static void createProgramDataUsePurpose(CareProgram careProgram) {
        try {
            DataUsePurpose dup = [
                SELECT
                    Id
                FROM
                    DataUsePurpose
                WHERE
                    Name = 'TestProgram'
            ];
        } catch (System.QueryException ex) {
            insert new DataUsePurpose(
                Name = 'TestProgram',
                PJN_Effective_Months__c = 12,
                PurposeId = careProgram.Id,
                PJN_External_Id__c = 'MVN_Test_ProgramConsent'
            );
        }
    }

    static void createHealthInfoDataUsePurpose(CareProgram careProgram) {
        try {
            DataUsePurpose dup = [
                SELECT
                    Id
                FROM
                    DataUsePurpose
                WHERE
                    Name = 'Disclose/Use Health Information'
            ];
        } catch (System.QueryException ex) {
            insert new DataUsePurpose(
                Name = 'Disclose/Use Health Information',
                PJN_Effective_Months__c = 12,
                PurposeId = careProgram.Id,
                PJN_External_Id__c = 'MVN_Test_HealthInformationPrg'
            );
        }
    }

    private static List<Account> createPatients() {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < BULK_DATA; i++) {
            accounts.add(
                new Account (
                    FirstName = 'ConnectiveRx Patient',
                    LastName = 'Test',
                    MVN_Birthdate__c = Date.valueOf('1988-12-06'),
                    HealthCloudGA__Gender__pc = 'Male',
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId()
                )
            );
        }
        insert accounts;
        return accounts;
    }

    private static void createCarePlans(CareProgram careProgram) {
        List<Case> carePlans = new List<Case>();
        for (Account patient : patients) {
            carePlans.add(
                new Case (
                    RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
                    AccountId = patient.Id,
                    PJN_Program__c = careProgram.Id,
                    Status = 'Open'
                )
            );
        }
        insert carePlans;
    }

    @IsTest
    static void testIfSPStatusWorksCorrectly() {
        List<Case> carePlans = getCarePlans();
        buildRequestContext(carePlans, true);
        MVN_OrsiniStatusResponse orsiniStatusResponse;
        Test.startTest();
        orsiniStatusResponse = MVN_OrsiniStatusAPI.handleOrsiniStatusPostAPI();
        Test.stopTest();
        String transactionLogError = getTransactionLogError();
        System.assertNotEquals(null, orsiniStatusResponse, 'Response cannot be null. Error: ' + transactionLogError);
        System.assertEquals('success', orsiniStatusResponse.status, 'Orsini Patient API must succeed. Error: ' + transactionLogError);
        System.assertEquals(null, orsiniStatusResponse.message, 'No message in the response. Error: ' + transactionLogError);
        System.assertNotEquals(null, orsiniStatusResponse.events, 'Events cannot be null. Error: ' + transactionLogError);
        System.assert(!orsiniStatusResponse.events.isEmpty(), 'Events cannot be empty. Error: ' + transactionLogError);
        for (MVN_OrsiniEventResult eventResult : orsiniStatusResponse.events) {
            System.assert(eventResult.success, 'Event must succeed. Error: ' + transactionLogError);
            System.assertEquals(null, eventResult.message, 'Event message must be null. Error: ' + transactionLogError);
        }
        List<PJN_Event__c> events = getEvents(carePlans);
        System.assertEquals(carePlans.size(), events.size(), 'Events must match number of CarePlans. Error: ' + transactionLogError);
        for (PJN_Event__c event : events) {
            System.assertNotEquals(null, event.PJN_Patient__r.MVN_Patient_Id__c, 'Patient Id cannot be null. Error: ' + transactionLogError);
            System.assertNotEquals(null, event.PJN_Case__c, 'CarePlan Id cannot be null. Error: ' + transactionLogError);
            System.assertNotEquals(null, event.PJN_SP_Patient_Id__c, 'SP Patient Id cannot be null. Error: ' + transactionLogError);
            System.assertEquals(event.PJN_SP_Patient_Id__c, event.PJN_Case__r.MVN_SP_Patient_Id__c, 'CarePlan SP Patient Id cannot be null. Error: ' + transactionLogError);
            System.assertEquals('Pending', event.PJN_Status__c, 'Status must be Pending. Error: ' + transactionLogError);
            System.assertEquals('P01', event.PJN_Sub_Status__c, 'SubStatus must be P01. Error: ' + transactionLogError);
            System.assertEquals(System.today(), event.PJN_Status_Date__c, 'Status date must be today. Error: ' + transactionLogError);
        }
    }

    @IsTest
    static void testIfSPStatusWorksNoEvent() {
        List<Case> carePlans = new List<Case>();
        buildRequestContext(carePlans, true);
        MVN_OrsiniStatusResponse orsiniStatusResponse;
        Test.startTest();
        orsiniStatusResponse = MVN_OrsiniStatusAPI.handleOrsiniStatusPostAPI();
        Test.stopTest();
        String transactionLogError = getTransactionLogError();
        System.assertNotEquals(null, orsiniStatusResponse, 'Response cannot be null. Error: ' + transactionLogError);
        System.assertEquals('error', orsiniStatusResponse.status, 'Orsini Patient API must error. Error: ' + transactionLogError);
        System.assertNotEquals(null, orsiniStatusResponse.message, 'No message in the response. Error: ' + transactionLogError);
        System.assertEquals(null, orsiniStatusResponse.events, 'Events must be null. Error: ' + transactionLogError);
    }

    @IsTest
    static void testIfSPStatusWorksWrong() {
        List<Case> carePlans = getCarePlans();
        buildRequestContext(carePlans, false);
        MVN_OrsiniStatusResponse orsiniStatusResponse;
        Test.startTest();
        orsiniStatusResponse = MVN_OrsiniStatusAPI.handleOrsiniStatusPostAPI();
        Test.stopTest();
        String transactionLogError = getTransactionLogError();
        System.assertNotEquals(null, orsiniStatusResponse, 'Response cannot be null. Error: ' + transactionLogError);
        System.assertEquals('error', orsiniStatusResponse.status, 'Orsini Patient API must error. Error: ' + transactionLogError);
        System.assertNotEquals(null, orsiniStatusResponse.events, 'Events cannot be null. Error: ' + transactionLogError);
        System.assert(!orsiniStatusResponse.events.isEmpty(), 'Events cannot be empty. Error: ' + transactionLogError);
        Boolean oneIsSuccess = false;
        for (MVN_OrsiniEventResult eventResult : orsiniStatusResponse.events) {
            System.assert(!eventResult.success || !oneIsSuccess, 'Event must be wrong. Error: ' + transactionLogError);
            System.assert(eventResult.message != null || !oneIsSuccess, 'Event message must be null. Error: ' + transactionLogError);
            oneIsSuccess = oneIsSuccess || eventResult.success;
        }
        List<PJN_Event__c> events = getEvents(carePlans);
        System.assertEquals(1, events.size(), 'Only one event should be created. Error: ' + transactionLogError);
    }

    private static List<Case> getCarePlans() {
        return [
            SELECT
                Id,
                Account.MVN_Patient_Id__c
            FROM
                Case
            WHERE
                RecordType.DeveloperName = 'CarePlan'
        ];
    }
    private static void buildRequestContext(List<Case> carePlans, Boolean hasPatientId) {
        String jsonRequestBody = getJsonRequestBody(carePlans, hasPatientId);

        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(jsonRequestBody); // Add JSON Message as a POST

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
    }

    private static String getJsonRequestBody(List<Case> carePlans, Boolean hasPatientId) {
        List<MVN_OrsiniStatusRequest> requests = new List<MVN_OrsiniStatusRequest>();
        Boolean oneAtLeast = false;
        for (Case carePlan : carePlans) {
            MVN_OrsiniStatusRequest request = new MVN_OrsiniStatusRequest();
            request.pharmacy_patient_id = hasPatientId || !oneAtLeast ? carePlan.Account.MVN_Patient_Id__c : '1234567890';
            request.hub_patient_id = hasPatientId || !oneAtLeast ? carePlan.Account.MVN_Patient_Id__c : '1234567890';
            request.status = 'Pending';
            request.substatus = 'P01';
            request.substatus_description = 'New Referral';
            request.status_date = System.now();
            requests.add(request);
            oneAtLeast = true;
        }
        return System.JSON.serializePretty(requests);
    }

    private static List<PJN_Event__c> getEvents(List<Case> carePlans) {
        return [
            SELECT
                Id,
                PJN_Case__c,
                PJN_Case__r.MVN_SP_Patient_Id__c,
                PJN_Patient__c,
                PJN_Patient__r.MVN_Patient_Id__c,
                PJN_SP_Patient_Id__c,
                PJN_Status__c,
                PJN_Sub_Status__c,
                PJN_Status_Date__c
            FROM
                PJN_Event__c
            WHERE
                PJN_Case__c IN :carePlans
            AND
                RecordType.DeveloperName = 'MVN_Pharmacy_Status_Update'
        ];
    }

    private static String getTransactionLogError() {
        List<PJN_Transaction_Log_Object__c> transactionLogs = [
            SELECT
                Id,
                PJN_Callout_Request__c,
                PJN_Callout_Response__c,
                PJN_Incoming_URL__c,
                PJN_Level__c,
                PJN_Record_Related__c,
                PJN_Running_User__c,
                PJN_Type__c,
                PJN_Message__c
            FROM
                PJN_Transaction_Log_Object__c
        ];
        String transactionLogError;
        if (!transactionLogs.isEmpty()) {
            transactionLogError = transactionLogs[0].PJN_Callout_Response__c;
        }
        return transactionLogError;
    }
}