force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Status of the contact information</description>
    <inlineHelpText>Status of the contact information</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Picklist: Correspondence label or type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>PO Box</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information to be modified.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Part of the Patient Service accelerator: local data change request status which defines what happens next with the data change request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Part of the Patient Service accelerator: data change request type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/PJN_Data_Change_Request_Line__c.object-meta.xml
<CustomObject>
    <description>Lists all of the specific data changes that are being requested in a data change request.</description>
    <label>Data Change Request Line</label>
    <nameField>
        <displayFormat>DCRL - {000000000}</displayFormat>
        <label>DCR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information record related to the DCR Line.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Change_Request__c</fullName>
    <description>Part of the Patient Service accelerator: Parent data change request.</description>
    <label>Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>The status of the license</description>
    <inlineHelpText>The status of the license</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>The type of license</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STATE</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>CDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/classes/PJN_DCRUpdateRecordTest.cls
/**
 * Test for PJN_DCRUpdateRecord
 * @author  Mavens
 * @group   DCR
 */
@IsTest
public with sharing class PJN_DCRUpdateRecordTest {
    private static final Integer DATA_SIZE = 100;

    static {
        PJN_NetworkObjectSetting.NetworkObjectSettingsQuery = (PJN_NetworkObjectSettingsQuery) Test.createStub(PJN_NetworkObjectSettingsQuery.class, new PJN_NetworkObjectSettingsMock());
        PJN_NetworkObjectSetting.NetworkRecordTypeMappingsQuery = (PJN_NetworkRecordTypeMappingsQuery) Test.createStub(PJN_NetworkRecordTypeMappingsQuery.class, new PJN_NetworkRecordTypeMappingsMock());
        PJN_NetworkObjectSetting.NetworkFieldMappingsQuery = (PJN_NetworkFieldMappingsQuery) Test.createStub(PJN_NetworkFieldMappingsQuery.class, new PJN_NetworkFieldMappingsMock());

        PJN_NetworkStatusMapping.networkStatusMappingQuery = (PJN_NetworkStatusMappingQuery) Test.createStub(PJN_NetworkStatusMappingQuery.class, new PJN_NetworkStatusMappingMock());
        Test.setMock(HttpCalloutMock.class, new PJN_NetworkSyncMock.RetrieveHCPSuccessMock());
    }

    @TestSetup
    static void makeData(){
        PJN_TestFactoryGlobalSetting.setMock();

        Test.startTest();
        List<Account> accounts = createAccounts(DATA_SIZE);
        createAddresses(accounts);
        createLicenses(accounts);
        Test.stopTest();
    }

    private static List<Account> createAccounts(Integer numOfAccounts) {
        List<Account> accounts = new List<Account>();

        for (Integer accIndex = 0; accIndex < numOfAccounts; accIndex++) {
            Integer currentAccountNetworkId = 6000 + accIndex;

            accounts.add(
                new Account(
                    FirstName = 'Test' + accIndex,
                    LastName = 'Test' + accIndex,
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
                    PersonMobilePhone = '555555555555',
                    PJN_Veeva_Network_Id__c = '93358025901211' + currentAccountNetworkId
                )
            );
        }

        insert accounts;

        return accounts;
    }

    private static void createAddresses(List<Account> accounts) {
        List<PJN_Contact_Information__c> address = new List<PJN_Contact_Information__c>();

        Integer currentCount = 6000;

        for (Account thisAccount : accounts) {
            address.add(
                new PJN_Contact_Information__c(
                    PJN_Address_Line_1__c = 'Main Street 123',
                    PJN_Account__c = thisAccount.Id,
                    PJN_Veeva_Network_Id__c = '93358025901200' + currentCount,
                    RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId()
                )
            );
            currentCount++;
        }

        insert address;
    }

    private static void createLicenses(List<Account> accounts) {
        List<PJN_License__c> licenses = new List<PJN_License__c>();

        Integer currentCount = 6000;

        for (Account thisAccount : accounts) {
            licenses.add(
                new PJN_License__c(
                    Name = '1234567',
                    PJN_Type__c = 'NPI',
                    PJN_Account__c = thisAccount.Id,
                    PJN_Veeva_Network_Id__c = '93291072424496' + currentCount
                )
            );
            currentCount++;
        }

        insert licenses;
    }

    @IsTest
    static void testIfDCRUpdateRecords() {
        List<PJN_Data_Change_Request__c> dcrs = getDCRsWithStatusUpdated();
        List<PJN_Data_Change_Request_Line__c> dcrLines = new List<PJN_Data_Change_Request_Line__c>();

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            dcrLines.addAll(dcr.PJN_Data_Change_Request_Lines__r);
        }

        // update dcrLines;

        Test.startTest();
        PJN_DCR.updateFromNetwork = true;
        update dcrs;
        Test.stopTest();

        dcrs = [
            SELECT
                Id,
                PJN_Status__c
            FROM
                PJN_Data_Change_Request__c
        ];

        System.assert(!dcrs.isEmpty(), 'NO DCR found.');

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            System.assertEquals(PJN_NetworkConstants.DCR_STATUS_UPDATED, dcr.PJN_Status__c, 'DCR Status must be ' + PJN_NetworkConstants.DCR_STATUS_UPDATED);
        }
    }

    private static List<PJN_Data_Change_Request__c> getDCRsWithStatusUpdated() {
        List<PJN_Data_Change_Request__c> dcrs = [
            SELECT
                Id,
                PJN_Status__c,
                (
                    SELECT
                        Id,
                        Name,
                        PJN_Account__c,
                        PJN_Field_Label__c,
                        PJN_Field_API_Name__c,
                        PJN_Old_Value__c,
                        PJN_New_Value__c,
                        PJN_Final_Value__c
                    FROM
                        PJN_Data_Change_Request_Lines__r
                )
            FROM
                PJN_Data_Change_Request__c
        ];

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            dcr.PJN_Status__c = PJN_NetworkConstants.DCR_STATUS_PROCESSED;
            for (PJN_Data_Change_Request_Line__c dcrLine : dcr.PJN_Data_Change_Request_lines__r) {
                if (String.isBlank(dcrLine.PJN_New_Value__c)) {
                    continue;
                }
                dcrLine.PJN_Final_Value__c = dcrLine.PJN_New_Value__c + 'Updated';
            }
        }

        return dcrs;
    }
}