force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Error__c.field-meta.xml
<CustomField>
    <fullName>PJN_Error__c</fullName>
    <description>Part of the Patient Service accelerator: Details of any errors that occurred during outbound DCR requests to Veeva Network, or inbound DCR updates from Veeva Network. Errors are cleared after DCR is successfully processed.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Details of any errors that occurred during outbound DCR requests to Veeva Network, or inbound DCR updates from Veeva Network. Errors are cleared after DCR is successfully processed.</inlineHelpText>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Data Change Request ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>External Data Change Request ID</inlineHelpText>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Parent_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Data_Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: Link to parent DCR. Used only if multiple DCRs are created in a single step. Account DCR is always a parent. Other DCRs link to it.</description>
    <label>Parent Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Sent_Datetime__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sent_Datetime__c</fullName>
    <description>Part of the Patient Service accelerator: Time the record has been sent to the MDM system for approval.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Time the record has been sent to the MDM system for approval.</inlineHelpText>
    <label>Sent Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Part of the Patient Service accelerator: local data change request status which defines what happens next with the data change request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/PJN_Data_Change_Request_Line__c.object-meta.xml
<CustomObject>
    <description>Lists all of the specific data changes that are being requested in a data change request.</description>
    <label>Data Change Request Line</label>
    <nameField>
        <displayFormat>DCRL - {000000000}</displayFormat>
        <label>DCR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Change_Request__c</fullName>
    <description>Part of the Patient Service accelerator: Parent data change request.</description>
    <label>Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <description>Part of the Patient Service accelerator: Field API name in PS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Field API Name</label>
    <length>43</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_New_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_New_Value__c</fullName>
    <description>Part of the Patient Service accelerator: Field value after user update.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/PJN_Network_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data change request field mapping for Veeva Network</description>
    <label>Network Field Mapping</label>
    <pluralLabel>Network Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <description>Field API name to map into Veeva Network.</description>
    <inlineHelpText>Field API name to map into Veeva Network.</inlineHelpText>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Required_for_DCR_Transmission__c.field-meta.xml
<CustomField>
    <fullName>PJN_Required_for_DCR_Transmission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is required for every DCR transmission otherwise an error will be returned.</description>
    <inlineHelpText>This field is required for every DCR transmission otherwise an error will be returned.</inlineHelpText>
    <label>Required for DCR Transmission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Parent_Object_Filter__mdt/PJN_Network_Parent_Object_Filter__mdt.object-meta.xml
<CustomObject>
    <description>Parent Object filters for Network Object Setting related</description>
    <label>Network Parent Object Filter</label>
    <pluralLabel>Network Parent Object Filters</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Parent_Object_Filter__mdt/fields/PJN_DCR__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does filter apply on DCR process?</description>
    <label>DCR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Parent_Object_Filter__mdt/fields/PJN_Parent_Field__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Field__c</fullName>
    <description>Parent field which applies the filter</description>
    <label>Parent Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Parent_Object_Filter__mdt/fields/PJN_Parent_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Field_Value__c</fullName>
    <description>Parent Field filter value</description>
    <label>Parent Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_DCRCreateHelper.cls
/**
 * Helper creating DCRs
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_DCRCreateHelper {

    /**
     * Gets accounts related to the records in a map by account id
     * @returns `Map<Id, Account>`
     */
    public static Map<Id, Account> getAccountsRelatedMap(List<SObject> records) {
        Set<Id> accountIds = new Set<Id>();

        for (SObject thisRecord : records) {
            if (thisRecord.get('PJN_Account__c') == null) {
                continue;
            }

            accountIds.add(String.valueOf(thisRecord.get('PJN_Account__c')));
        }

        Set<String> fieldNames = new Set<String> {
            'Id',
            'RecordType.DeveloperName',
            'PJN_Veeva_Network_Id__c'
        };

        for (PJN_Network_Field_Mapping__mdt networkFieldMapping : PJN_NetworkObjectSetting.getMappingsByName(Account.sObjectType.getDescribe().getName())) {
            if (!networkFieldMapping.PJN_Required_for_DCR_Transmission__c) {
                continue;
            }

            fieldNames.add(networkFieldMapping.PJN_Field_API_Name__c);
        }

        List<String> fieldNameList = new List<String>();
        fieldNameList.addAll(fieldNames);

        String query = 'SELECT ' +
            String.join(fieldNameList, ',') + ' ' +
            'FROM ' + Account.sObjectType.getDescribe().getName() + ' ' +
            'WHERE Id IN :accountIds';

        return new Map<Id, Account> ((List<Account>) Database.query(String.escapeSingleQuotes(query)));
    }

    /**
     * Upsert DCR Lines when those are created during DCR Create process
     * @param dcrLines  Data change request lines to be insert or updated
     */
    public static void upsertDCRLines(List<PJN_Data_Change_Request_Line__c> dcrLines) {
        Set<String> dcrExternalIds = new Set<String>();
        Set<String> fieldNames = new Set<String>();

        for (PJN_Data_Change_Request_Line__c dcrLine : dcrLines) {
            dcrExternalIds.add(dcrLine.PJN_Data_Change_Request__r.PJN_External_Id__c);
            fieldNames.add(dcrLine.PJN_Field_API_Name__c);
        }

        Map<String, PJN_Data_Change_Request_Line__c> existingDCRLineByKey = new Map<String, PJN_Data_Change_Request_Line__c>();

        for (PJN_Data_Change_Request_Line__c existingDCRLine : PJN_DCRQuery.queryDCRLinesWithFieldName(dcrExternalIds, fieldNames)) {
            existingDCRLineByKey.put(getDCRLineKey(existingDCRLine), existingDCRLine);
        }

        Map<String, PJN_Data_Change_Request_Line__c> upsertDcrLinesByKey = new Map<String, PJN_Data_Change_Request_Line__c>();

        for (PJN_Data_Change_Request_Line__c dcrLine : dcrLines) {
            String mapKey = getDCRLineKey(dcrLine);

            if (!existingDCRLineByKey.containsKey(mapKey)) {
                upsertDcrLinesByKey.put(mapKey, dcrLine);
                continue;
            }

            PJN_Data_Change_Request_Line__c existingDcrLine = existingDCRLineByKey.get(mapKey);
            existingDcrLine.PJN_New_Value__c = dcrLine.PJN_New_Value__c;
            upsertDcrLinesByKey.put(mapKey, existingDcrLine);
        }

        upsert upsertDcrLinesByKey.values();
    }

    /**
     * Get DCR Line key map to identify DCR Lines for same DCR and field name
     * @param dcrLine   Data change request line to get the key
     * @returns `String`
     */
    private static String getDCRLineKey(PJN_Data_Change_Request_Line__c dcrLine) {
        return dcrLine.PJN_Data_Change_Request__r.PJN_External_Id__c + '|' + dcrLine.PJN_Field_API_Name__c;
    }



    /**
     * Handles DCRs with error to update them to Cancelled
     * @param dcrs                  List of DCRs
     * @param errorMessageByDCRId   Map of error messages by DCR id
     */
    public static void updateDCRsWithError(List<PJN_Data_Change_Request__c> dcrs, Map<Id, String> errorMessageByDCRId) {
        if (errorMessageByDCRId == null || errorMessageByDCRId.isEmpty()) {
            return;
        }

        List<PJN_Data_Change_Request__c> updateDCRs = new List<PJN_Data_Change_Request__c>();

        for(PJN_Data_Change_Request__c dcr : dcrs) {
            Id dcrId = dcr.PJN_Parent_Data_Change_Request__c != null ?
                dcr.PJN_Parent_Data_Change_Request__c :
                dcr.Id;

            if (!errorMessageByDCRId.containsKey(dcrId)) {
                continue;
            }

            dcr.PJN_Error__c = errorMessageByDCRId.get(dcrId);
            dcr.PJN_Status__c = PJN_NetworkConstants.DCR_STATUS_CANCELLED;
            dcr.PJN_Sent_Datetime__c = System.now();

            updateDCRs.add(dcr);
        }

        if (updateDCRs != null && !updateDCRs.isEmpty()) {
            update updateDCRs;
        }
    }

    /**
     * Send List of parent object filters and check if allowed to create DCRs
     * @param networkParentFilters  List of Network Object Parent Filters
     * @param parentAccount         Parent account record
     * @returns `Boolean`
     */
    public static Boolean isParentObjectFilterAllowed(List<PJN_Network_Parent_Object_Filter__mdt> networkParentFilters, Account parentAccount) {
        Boolean noParentFilter = networkParentFilters != null && networkParentFilters.isEmpty();

        if (noParentFilter) {
            return false;
        }

        if (networkParentFilters != null) {
            for (PJN_Network_Parent_Object_Filter__mdt networkParentFilter : networkParentFilters) {
                if (!networkParentFilter.PJN_DCR__c) {
                    continue;
                }

                String parentFilter = networkParentFilter.PJN_Parent_Field__c.contains('.') ?
                    String.valueOf(parentAccount.getSObject(networkParentFilter.PJN_Parent_Field__c.substringBefore('.')).get(networkParentFilter.PJN_Parent_Field__c.substringAfter('.'))) :
                    String.valueOf(parentAccount.get(networkParentFilter.PJN_Parent_Field__c));

                Boolean noMatchFilter = parentFilter != networkParentFilter.PJN_Parent_Field_Value__c;

                if (noMatchFilter) {
                    return false;
                }
            }
        }

        return true;
    }
}