force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (50): Contact Information External ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Type_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information to be modified.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Data Change Request ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>External Data Change Request ID</inlineHelpText>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_License_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information (Address) related to License which is updated.</description>
    <label>License Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests (License Address)</relationshipLabel>
    <relationshipName>PJN_License_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License_Address_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_License_Address_Network_Id__c</fullName>
    <description>Contact Information (Address) Network Id related to License which is updated.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>License Address Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Type_Name__c</fullName>
    <description>Record associated record type developer name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/recordTypes/PJN_Account.recordType-meta.xml
<RecordType>
    <fullName>PJN_Account</fullName>
    <active>true</active>
    <description>Defines a data change request for a physician or organization</description>
    <label>Account</label>
</RecordType>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/recordTypes/PJN_Affiliation.recordType-meta.xml
<RecordType>
    <fullName>PJN_Affiliation</fullName>
    <active>true</active>
    <description>Defines a data change request to create an affiliation for a parent organization in the MDM system</description>
    <label>Affiliation</label>
</RecordType>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/recordTypes/PJN_Contact_Information.recordType-meta.xml
<RecordType>
    <fullName>PJN_Contact_Information</fullName>
    <active>true</active>
    <description>Defines a data change request for an address</description>
    <label>Contact Information</label>
</RecordType>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/recordTypes/PJN_License.recordType-meta.xml
<RecordType>
    <fullName>PJN_License</fullName>
    <active>true</active>
    <description>Defines a data change request for a physician&apos;s license</description>
    <label>License</label>
</RecordType>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/PJN_Data_Change_Request_Line__c.object-meta.xml
<CustomObject>
    <description>Lists all of the specific data changes that are being requested in a data change request.</description>
    <label>Data Change Request Line</label>
    <nameField>
        <displayFormat>DCRL - {000000000}</displayFormat>
        <label>DCR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information record related to the DCR Line.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Change_Request__c</fullName>
    <description>Part of the Patient Service accelerator: Parent data change request.</description>
    <label>Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <description>Part of the Patient Service accelerator: Field API name in PS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Field API Name</label>
    <length>43</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_New_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_New_Value__c</fullName>
    <description>Part of the Patient Service accelerator: Field value after user update.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/PJN_Network_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data change request field mapping for Veeva Network</description>
    <label>Network Field Mapping</label>
    <pluralLabel>Network Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <description>Field API name to map into Veeva Network.</description>
    <inlineHelpText>Field API name to map into Veeva Network.</inlineHelpText>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/PJN_Network_Record_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Object record type to Veeva Network entity type mapping</description>
    <label>Network Record Type Mapping</label>
    <pluralLabel>Network Record Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Network_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Record_Type__c</fullName>
    <description>Veeva Network entity type</description>
    <label>Network Record Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Record_Type_Mapping__mdt/fields/PJN_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Type_Name__c</fullName>
    <description>Salesforce record type developer name</description>
    <label>Record Type Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkRecord.cls
/**
 * Veeva Network entity or child format
 * @author  Mavens
 * @group   Network
 */
public class PJN_NetworkRecord {

    /**
     * Decides if reserve Veeva Network Id sending DCR
     */
    public Boolean reserveVid;

    /**
     * The external record vid_key supplied by the client.
     */
    public String vidKey;

    /**
     * The ID of the network record
     */
    public String vid;

    /**
     * The external license address vid_key supplied by the client.
     */
    public String licenseAddressVidKey;

    /**
     * The external license address vid supplied by the client.
     */
    public String licenseAddressVid;

    /**
     * Network Record Type
     */
    public String entityType;

    /**
     *
     */
    private String objectId;

    /**
     * Network fields
     */
    public Map<String, Object> attributes;

    /**
     * An array of change requests for addresses, one per address, for the entity provided
     */
    public List<PJN_NetworkRecord> addresses;

    /**
     * An array of change requests for licenses, one per license, for the entity provided
     */
    public List<PJN_NetworkRecord> licenses;

    /**
     * An array of change requests for affiliations, one per affiliation, for the entity provided
     */
    public List<PJN_NetworkRecord> affiliations;

    /**
     * Constructor of Network DCR structure using DCR Wrapper
     * @param dcrWrapper
     */
    public PJN_NetworkRecord(PJN_DCR dcrWrapper) {
        Boolean isParentDCR = dcrWrapper.parentDcr != null;

        PJN_Data_Change_Request__c entityDCR = isParentDCR ? dcrWrapper.parentDcr : dcrWrapper.dcr;
        List<PJN_Data_Change_Request_Line__c> entityDCRLines = isParentDCR ? dcrWrapper.parentDcrLines : dcrWrapper.dcrLines;

        this.reserveVid = String.isBlank(entityDCR.PJN_Veeva_Network_Id__c);
        this.vid = entityDCR.PJN_Veeva_Network_Id__c;

        this.vidKey = String.isNotBlank(entityDCR.PJN_Veeva_Network_Id__c) ?
            'Network:' + getNetworkEntityString(entityDCR) + ':' + this.vid :
            entityDCR.PJN_External_Id__c.substringBeforeLast('|');

        this.entityType = String.isNotBlank(entityDCR.PJN_Record_Type_Name__c) ?
            entityDCR.PJN_Record_Type_Name__c :
            Account.getSObjectType().getDescribe().getRecordTypeInfosById().get(entityDCR.PJN_Account__r.RecordTypeId).getDeveloperName();

        addAttributes(Account.getSObjectType().getDescribe().getName(), this.entityType, entityDCRLines);

        this.addresses = new List<PJN_NetworkRecord>();
        this.licenses = new List<PJN_NetworkRecord>();
        this.affiliations = new List<PJN_NetworkRecord>();
    }

    public PJN_NetworkRecord(Schema.DescribeSObjectResult sobjectDescribe, PJN_Data_Change_Request__c dcr, List<PJN_Data_Change_Request_Line__c> dcrLines) {
        this.reserveVid = String.isNotBlank(dcr.PJN_Veeva_Network_Id__c);

        this.vid = dcr.PJN_Veeva_Network_Id__c;
        this.vidKey = String.isNotBlank(dcr.PJN_Veeva_Network_Id__c) ?
            'Network:' + getNetworkEntityString(dcr) + ':' + this.vid :
            dcr.PJN_External_Id__c.substringBeforeLast('|');

        if (String.isNotBlank(dcr.PJN_Record_Type_Name__c)) {
            this.entityType = dcr.PJN_Record_Type_Name__c;
        } else if (sobjectDescribe.getRecordTypeInfosById() != null && !sobjectDescribe.getRecordTypeInfosById().isEmpty()) {
            String recordTypeId;
            if (dcr.PJN_Contact_Information__c != null) {
                recordTypeId = dcr.PJN_Contact_Information__r.RecordTypeId;
            } else if (dcr.PJN_License__c != null) {
                recordTypeId = dcr.PJN_License__r.RecordTypeId;
            }

            this.entityType = sobjectDescribe.getRecordTypeInfosById().get(recordTypeId).getDeveloperName();
        }

        if (String.IsNotBlank(dcr.PJN_License_Address__c)) {
            String systemName = PJN_DCR.pjnSetting != null ? PJN_DCR.pjnSetting.PJN_Network_System__c : PJN_NetworkConstants.NETWORK_SYSTEM;
            this.licenseAddressVidKey = String.IsNotBlank(dcr.PJN_License_Address_Network_Id__c) ?
                'Network:' + PJN_NetworkConstants.NETWORK_ADDRESS_TYPE + ':' + dcr.PJN_License_Address_Network_Id__c :
                systemName + ':' + PJN_NetworkConstants.NETWORK_ADDRESS_TYPE + ':' + dcr.PJN_License_Address__c;
        }

        addAttributes(sobjectDescribe.getName(), this.entityType, dcrLines);
    }

    private Map<String, PJN_Network_Field_Mapping__mdt> getNetworkFieldMappingsByFieldName(List<PJN_Network_Field_Mapping__mdt> networkFieldMappings) {
        Map<String, PJN_Network_Field_Mapping__mdt> networkFieldMappingsByFieldName = new Map<String, PJN_Network_Field_Mapping__mdt>();

        for (PJN_Network_Field_Mapping__mdt networkFieldMapping : networkFieldMappings) {
            networkFieldMappingsByFieldName.put(networkFieldMapping.PJN_Field_API_Name__c, networkFieldMapping);
        }

        return networkFieldMappingsByFieldName;
    }

    /**
     * Add child dcr records to Network structure
     * @param dcrWrapper    DCR Wrapper to retrieves the child record
     */
    public void addChildDCR(PJN_DCR dcrWrapper) {
        if (dcrWrapper.dcr.PJN_Contact_Information__c != null) {
            this.addresses.add(new PJN_NetworkRecord(PJN_Contact_Information__c.getSObjectType().getDescribe(), dcrWrapper.dcr, dcrWrapper.dcrLines));
        } else if (dcrWrapper.dcr.PJN_License__c != null) {
            this.licenses.add(new PJN_NetworkRecord(PJN_License__c.getSObjectType().getDescribe(), dcrWrapper.dcr, dcrWrapper.dcrLines));
        }
    }

    /**
     * Veeva Network Entity or child constructor using Network response provided
     * @param entityResponse    Network entity response
     */
    public PJN_NetworkRecord(Map<String, Object> entityResponse) {
        this.attributes = entityResponse;

        this.vidKey = String.valueOf(entityResponse.get('vid_key'));
        this.vid = String.valueOf(entityResponse.get('vid__v'));
        this.objectId = String.valueOf(entityResponse.get('object_id'));
        this.licenseAddressVidKey = entityResponse.get(PJN_NetworkConstants.NETWORK_DCR_LICENSE_ADDRESS_ID_FIELD) != null && String.valueOf(entityResponse.get(PJN_NetworkConstants.NETWORK_DCR_LICENSE_ADDRESS_ID_FIELD)).contains('final_value') ?
            String.valueOf(((Map<String, Object>) entityResponse.get(PJN_NetworkConstants.NETWORK_DCR_LICENSE_ADDRESS_ID_FIELD)).get('final_value')) :
            String.valueOf(entityResponse.get(PJN_NetworkConstants.NETWORK_DCR_LICENSE_ADDRESS_ID_FIELD));
        this.licenseAddressVid = String.valueOf(entityResponse.get(PJN_NetworkConstants.NETWORK_SYNC_LICENSE_ADDRESS_ID_FIELD));
        this.entityType = String.valueOf(entityResponse.get('type__v'));

        this.addresses = getNetworkChildren('addresses__v');
        this.licenses = getNetworkChildren('licenses__v');
        this.affiliations = getNetworkChildren('parent_hcos__v');
    }

    /**
     * Initialize children from Network response
     * @param childrenParamName Children parameter name on Network response
     * @returns `List<PJN_NetworkRecord>`
     */
    private List<PJN_NetworkRecord> getNetworkChildren(String childrenParamName) {
        List<PJN_NetworkRecord> networkChildren = new List<PJN_NetworkRecord>();

        if (!attributes.containsKey(childrenParamName)) {
            return networkChildren;
        }

        for (Object networkResponseChild : (List<Object>) attributes.get(childrenParamName)) {
            networkChildren.add(new PJN_NetworkRecord((Map<String, Object>) networkResponseChild));
        }

        return networkChildren;
    }

    /**
     * Get Network attribute
     * @param fieldName External Network Field name
     * @returns `String`
    */
    public String getAttribute(String fieldName) {
        return this.attributes != null && this.attributes.containsKey(fieldName) ?
            String.valueOf(this.attributes.get(fieldName)) :
            null;
    }

    public String getNetworkEntityString(PJN_Data_Change_Request__c dcr) {
        String dcrRecordDevName = PJN_Data_Change_Request__c.getSObjectType().getDescribe().getRecordTypeInfosById().get(dcr.RecordTypeId).getDeveloperName();

        switch on dcrRecordDevName {
            when 'PJN_Account' {
                return 'Entity';
            } when 'PJN_Affiliation' {
                return 'ParentHCO';
            } when 'PJN_Contact_Information' {
                return 'PJN_Address';
            } when 'PJN_License' {
                return 'License';
            } when else {
                return '';
            }
        }
    }

    private void addAttributes(String sobjectName, String recordTypeName, List<PJN_Data_Change_Request_Line__c> dcrLines) {
        List<PJN_Network_Field_Mapping__mdt> networkFieldMappings;

        if (String.IsNotBlank(recordTypeName)) {
            networkFieldMappings = PJN_NetworkObjectSetting.getMappingsByNameAndRecordType(sobjectName, recordTypeName);

            PJN_Network_Record_Type_Mapping__mdt networkRecordTypeMapping = PJN_NetworkObjectSetting.getNetworkRecordTypeMappingByObjectAndRecordTypeName(sobjectName, recordTypeName);

            this.entityType = networkRecordTypeMapping != null ? networkRecordTypeMapping.PJN_Network_Record_Type__c : null;
        } else {
            networkFieldMappings = PJN_NetworkObjectSetting.getMappingsByName(sobjectName);
        }

        Map<String, PJN_Network_Field_Mapping__mdt> networkFieldMappingsByFieldName = getNetworkFieldMappingsByFieldName(networkFieldMappings);

        this.attributes = new Map<String, Object>();

        for (PJN_Data_Change_Request_Line__c dcrLine : dcrLines) {
            PJN_Network_Field_Mapping__mdt currentNetworkFieldMapping = networkFieldMappingsByFieldName.get(dcrLine.PJN_Field_API_Name__c);

            if (currentNetworkFieldMapping == null) {
                continue;
            }

            String newValue = dcrLine.PJN_New_Value__c;

            if (currentNetworkFieldMapping.PJN_Network_Value_Mappings__r != null) {
                for (PJN_Network_Value_Mapping__mdt valueMapping : currentNetworkFieldMapping.PJN_Network_Value_Mappings__r) {
                    if (valueMapping.PJN_Outbound__c && valueMapping.PJN_Value__c.equalsIgnoreCase(newValue)) {
                        newValue = valueMapping.PJN_External_Value__c;
                        break;
                    }
                }
            }

            this.attributes.put(currentNetworkFieldMapping.PJN_External_Field_Name__c, newValue);
        }
    }
}