force-app/main/default/src/objects/Account/fields/PJN_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Address record type.</description>
    <label>Primary Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Address</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Email record type.</description>
    <label>Primary Email</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Email</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Primary Email)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Primary_Fax__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Fax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Fax record type.</description>
    <label>Primary Fax</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Fax</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Primary Fax)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Phone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Phone record type.</description>
    <label>Primary Phone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Phone</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Primary Phone)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Set_as_Primary__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates this record should be set as primary. A trigger will manage this update.</description>
    <inlineHelpText>Indicates this record should be set as primary.</inlineHelpText>
    <label>Set as Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/PJN_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search
Purpose: Definition of handler class used for the Account Search and the number max of results to be displayed. Global setting for all Programs; change only the max results field.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Global Setting</label>
    <pluralLabel>Global Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Address_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Address_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info address record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info address record types.</inlineHelpText>
    <label>Contact Info Address Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Email_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Email_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info email record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info email record types.</inlineHelpText>
    <label>Contact Info Email Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Fax_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Fax_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info fax record types.</description>
    <inlineHelpText>Semi-colon delimited list of all contact info fax record types.</inlineHelpText>
    <label>Contact Info Fax Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Contact_Info_Phone_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Phone_Record_Types__c</fullName>
    <description>Semi-colon delimited list of all contact info phone record types.</description>
    <label>Contact Info Phone Record Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_SetPrimaryContactInfo.cls
/**
 * @author Mavens
 * @date Mar 2019
 * @description Set Contact Information record as primary and update the corresponding primary field
 *              on the Account
 * @group ContactInformation
 */
public with sharing class PJN_SetPrimaryContactInfo implements PJN_TriggerDispatcher.HandlerInterface {

    public static List<PJN_Contact_Information__c> cisToSetAsPrimary = new List<PJN_Contact_Information__c>();

    Map<String, RecordTypeInfo> ciRecordTypes;
    Map<Id, Map<String, Id>> accountToPrimaryFields;

    /**
     * Initialize variables
     */
    public PJN_SetPrimaryContactInfo() {
        ciRecordTypes = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName();
        accountToPrimaryFields = new Map<Id, Map<String, Id>>();
    }

    /**
     * Handle trigger
     */
    public void handle() {
        if (Trigger.isBefore) {
            for (PJN_Contact_Information__c contactInfo : (List<PJN_Contact_Information__c>) Trigger.new) {
                if (contactInfo.PJN_Set_as_Primary__c) {
                    cisToSetAsPrimary.add(contactInfo);
                    contactInfo.PJN_Set_as_Primary__c = false;
                }
            }
        } else {
            for (PJN_Contact_Information__c contactInfo : cisToSetAsPrimary) {
                if (!accountToPrimaryFields.containsKey(contactInfo.PJN_Account__c)) {
                    accountToPrimaryFields.put(contactInfo.PJN_Account__c, new Map<String, Id>());
                }
                String acctFieldToUpdate = getFieldToUpdate(contactInfo);
                if (String.isNotBlank(acctFieldToUpdate)) {
                    accountToPrimaryFields.get(contactInfo.PJN_Account__c).put(acctFieldToUpdate, contactInfo.Id);
                }
            }
            queryAndUpdateAccounts(accountToPrimaryFields);
        }
    }

    /**
     * Get the field to update on the Account record based on the contact information record type
     * @param  contactInfo contact information record
     * @returns String
     */
    private String getFieldToUpdate(PJN_Contact_Information__c contactInfo) {
        String fieldToUpdate = null;
        PJN_Global_Setting__mdt globalSetting = PJN_Utilities.globalSetting;

        Set<Id> addressRecTypeIds = new Set<Id>();
        for (String recTypeName : globalSetting.PJN_Contact_Info_Address_Record_Types__c.split(';')) {
            addressRecTypeIds.add(ciRecordTypes.get(recTypeName).getRecordTypeId());
        }
        if (addressRecTypeIds.contains(contactInfo.RecordTypeId)) {
            fieldToUpdate = 'PJN_Primary_Address__c';
        }

        Set<Id> emailRecTypeIds = new Set<Id> ();
        for (String recTypeName : globalSetting.PJN_Contact_Info_Email_Record_Types__c.split(';')) {
            emailRecTypeIds.add(ciRecordTypes.get(recTypeName).getRecordTypeId());
        }
        if (emailRecTypeIds.contains(contactInfo.RecordTypeId)) {
            fieldToUpdate = 'PJN_Primary_Email__c';
        }


        Set<Id> phoneRecTypeIds = new Set<Id> ();
        for (String recTypeName : globalSetting.PJN_Contact_Info_Phone_Record_Types__c.split(';')) {
            phoneRecTypeIds.add(ciRecordTypes.get(recTypeName).getRecordTypeId());
        }
        if (phoneRecTypeIds.contains(contactInfo.RecordTypeId)) {
            fieldToUpdate = 'PJN_Primary_Phone__c';
        }

        Set<Id> faxRecTypeIds = new Set<Id> ();
        for (String recTypeName : globalSetting.PJN_Contact_Info_Fax_Record_Types__c.split(';')) {
            faxRecTypeIds.add(ciRecordTypes.get(recTypeName).getRecordTypeId());
        }
        if (faxRecTypeIds.contains(contactInfo.RecordTypeId)) {
            fieldToUpdate = 'PJN_Primary_Fax__c';
        }
        return fieldToUpdate;
    }

    /**
     * query accounts and update them with the primary field value
     * @param  accountToPrimaryFields map of fields to be updated by account id
     */
    private void queryAndUpdateAccounts(Map<Id, Map<String, Id>> accountToPrimaryFields) {
        List<Account> accounts = getAccounts(accountToPrimaryFields.keySet());
        for (Account acct : accounts) {
            Map<String, Id> primaryFieldsToUpdate = accountToPrimaryFields.get(acct.Id);
            for (String field : primaryFieldsToUpdate.keySet()) {
                acct.put(field, primaryFieldsToUpdate.get(field));
            }
        }
        update accounts;
    }

    /**
     * get accounts
     * @param  accountIds account id set
     * @returns List<Account>
     */
    private List<Account> getAccounts(Set<Id> accountIds) {
        return [
            SELECT
                Id,
                PJN_Primary_Address__c,
                PJN_Primary_Email__c,
                PJN_Primary_Phone__c,
                PJN_Primary_Fax__c
            FROM
                Account
            WHERE
                Id IN :accountIds
        ];
    }
}