force-app/main/default/src/objects/Account/fields/PJN_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Address record type.</description>
    <label>Primary Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Address</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Email record type.</description>
    <label>Primary Email</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Email</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Primary Email)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Primary_Fax__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Fax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Fax record type.</description>
    <label>Primary Fax</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Fax</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Primary Fax)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Phone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Phone record type.</description>
    <label>Primary Phone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Phone</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Primary Phone)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Email__c</fullName>
    <description>Email: Correspondence email address.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Fax__c.field-meta.xml
<CustomField>
    <fullName>PJN_Fax__c</fullName>
    <description>Fax: Correspondence fax number.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PrimaryCIChangeHdlrMVN.cls
/**
 * @author      Mavens
 * @group       PrimaryCIChangeHdlrMVN
 * @description When any primary contact info changes map data to account fields
 */
public with sharing class PrimaryCIChangeHdlrMVN implements PJN_TriggerDispatcher.HandlerInterface {

    private Map<Id, PJN_Contact_Information__c> contactInformation;
    private List<Account> changedAccounts;

    public void handle() {
        getChangedAccounts();

        for (Account changedAccount : changedAccounts) {
            setPrimaryEmail(changedAccount);
            setPrimaryPhone(changedAccount);
            setPrimaryFax(changedAccount);
            setPrimaryAddress(changedAccount);
        }
    }

    private void getChangedAccounts() {
        Set<Id> contactInfoIds = new Set<Id>();
        changedAccounts = new List<Account>();
        for (Account acct : (List<Account>) Trigger.new) {
            if (hasChanged(acct)) {
                changedAccounts.add(acct);
                contactInfoIds.add(acct.PJN_Primary_Phone__c);
                contactInfoIds.add(acct.PJN_Primary_Email__c);
                contactInfoIds.add(acct.PJN_Primary_Address__c);
                contactInfoIds.add(acct.PJN_Primary_Fax__c);
            }
        }

        contactInformation = new Map<Id, PJN_Contact_Information__c>([
            SELECT
                Id,
                PJN_Phone__c,
                PJN_Email__c,
                PJN_Fax__c,
                PJN_Address_Line_1__c,
                PJN_Address_Line_2__c,
                PJN_City__c,
                PJN_State__c,
                PJN_Postal_Code__c,
                PJN_Country__c
            FROM
                PJN_Contact_Information__c
            WHERE
                Id IN :contactInfoIds
        ]);
    }

    private Boolean hasChanged(Account acct) {
        if (Trigger.isInsert) {
            return true;
        }
        Account oldAccount = (Account)Trigger.oldMap.get(acct.Id);
        return acct.PJN_Primary_Phone__c != oldAccount.PJN_Primary_Phone__c
            || acct.PJN_Primary_Email__c != oldAccount.PJN_Primary_Email__c
            || acct.PJN_Primary_Address__c != oldAccount.PJN_Primary_Address__c
            || acct.PJN_Primary_Fax__c != oldAccount.PJN_Primary_Fax__c;
    }

    private void setPrimaryEmail(Account changedAccount) {
        PJN_Contact_Information__c email = contactInformation.get(changedAccount.PJN_Primary_Email__c);
        changedAccount.PersonEmail = null;
        if (changedAccount.isPersonAccount && email != null) {
            changedAccount.PersonEmail = email.PJN_Email__c;
        }
    }

    private void setPrimaryPhone(Account changedAccount) {
        PJN_Contact_Information__c phone = contactInformation.get(changedAccount.PJN_Primary_Phone__c);
        changedAccount.Phone = null;
        if (phone != null) {
            changedAccount.Phone = phone.PJN_Phone__c;
        }
    }

    private void setPrimaryFax(Account changedAccount) {
        PJN_Contact_Information__c fax = contactInformation.get(changedAccount.PJN_Primary_Fax__c);
        changedAccount.Fax = null;
        if (fax != null) {
            changedAccount.Fax = fax.PJN_Fax__c;
        }
    }
    private void setPrimaryAddress(Account changedAccount) {
        PJN_Contact_Information__c address = contactInformation.get(changedAccount.PJN_Primary_Address__c);

        changedAccount.PersonMailingStreet = null;
        changedAccount.PersonMailingCity = null;
        changedAccount.PersonMailingState = null;
        changedAccount.PersonMailingPostalCode = null;
        changedAccount.PersonMailingCountry = null;

        changedAccount.BillingStreet = null;
        changedAccount.BillingCity = null;
        changedAccount.BillingState = null;
        changedAccount.BillingPostalCode = null;
        changedAccount.BillingCountry = null;

        if (address != null) {
            if (changedAccount.isPersonAccount) {
                changedAccount.PersonMailingStreet = address.PJN_Address_Line_1__c;
                if (String.isNotBlank(address.PJN_Address_Line_2__c)) {
                    changedAccount.PersonMailingStreet += '\n' + address.PJN_Address_Line_2__c;
                }
                changedAccount.PersonMailingCity = address.PJN_City__c;
                changedAccount.PersonMailingState = address.PJN_State__c;
                changedAccount.PersonMailingPostalCode = address.PJN_Postal_Code__c;
                changedAccount.PersonMailingCountry = address.PJN_Country__c;
            } else {
                changedAccount.BillingStreet = address.PJN_Address_Line_1__c;
                if (String.isNotBlank(address.PJN_Address_Line_2__c)) {
                    changedAccount.BillingStreet += '\n' + address.PJN_Address_Line_2__c;
                }
                changedAccount.BillingCity = address.PJN_City__c;
                changedAccount.BillingState = address.PJN_State__c;
                changedAccount.BillingPostalCode = address.PJN_Postal_Code__c;
                changedAccount.BillingCountry = address.PJN_Country__c;
            }
        }
    }
}