force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (50): Contact Information External ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Status of the contact information</description>
    <inlineHelpText>Status of the contact information</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information to be modified.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Error__c.field-meta.xml
<CustomField>
    <fullName>PJN_Error__c</fullName>
    <description>Part of the Patient Service accelerator: Details of any errors that occurred during outbound DCR requests to Veeva Network, or inbound DCR updates from Veeva Network. Errors are cleared after DCR is successfully processed.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Details of any errors that occurred during outbound DCR requests to Veeva Network, or inbound DCR updates from Veeva Network. Errors are cleared after DCR is successfully processed.</inlineHelpText>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Part of the Patient Service accelerator: local data change request status which defines what happens next with the data change request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/PJN_Data_Change_Request_Line__c.object-meta.xml
<CustomObject>
    <description>Lists all of the specific data changes that are being requested in a data change request.</description>
    <label>Data Change Request Line</label>
    <nameField>
        <displayFormat>DCRL - {000000000}</displayFormat>
        <label>DCR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information record related to the DCR Line.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Change_Request__c</fullName>
    <description>Part of the Patient Service accelerator: Parent data change request.</description>
    <label>Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <description>Part of the Patient Service accelerator: Field API name in PS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Field API Name</label>
    <length>43</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_New_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_New_Value__c</fullName>
    <description>Part of the Patient Service accelerator: Field value after user update.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Old_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_Old_Value__c</fullName>
    <description>Part of the Patient Service accelerator: field value before user update</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>The status of the license</description>
    <inlineHelpText>The status of the license</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/classes/PJN_DCRAccountHdlrTest.cls
/**
 * Test for PJN_DCRAccountHdlr trigger handler
 * @author  Mavens
 * @group   Network
 */
@IsTest
public with sharing class PJN_DCRAccountHdlrTest {

    private static final Integer DATA_SIZE = 49;

    static {
        PJN_NetworkObjectSetting.NetworkObjectSettingsQuery = (PJN_NetworkObjectSettingsQuery) Test.createStub(PJN_NetworkObjectSettingsQuery.class, new PJN_NetworkObjectSettingsMock());
        PJN_NetworkObjectSetting.NetworkRecordTypeMappingsQuery = (PJN_NetworkRecordTypeMappingsQuery) Test.createStub(PJN_NetworkRecordTypeMappingsQuery.class, new PJN_NetworkRecordTypeMappingsMock());
        PJN_NetworkObjectSetting.NetworkFieldMappingsQuery = (PJN_NetworkFieldMappingsQuery) Test.createStub(PJN_NetworkFieldMappingsQuery.class, new PJN_NetworkFieldMappingsMock());

        PJN_NetworkStatusMapping.networkStatusMappingQuery = (PJN_NetworkStatusMappingQuery) Test.createStub(PJN_NetworkStatusMappingQuery.class, new PJN_NetworkStatusMappingMock());
        Test.setMock(HttpCalloutMock.class, new PJN_NetworkCalloutMock.SuccessMock());

        PJN_NetworkCallout.noRunInTest = false;
    }

    @IsTest
    static void testInsertAccountSucessfully(){
        PJN_TestFactoryGlobalSetting.setMock();
        List<Account> accounts = buildAccounts(DATA_SIZE);

        Test.startTest();
        insert accounts;
        Test.getEventBus().deliver();
        Test.stopTest();

        List<PJN_Data_Change_Request__c> dcrs = getDCRsAndLines(accounts, PJN_NetworkConstants.DCR_TYPE_NEW);
        System.assert(!dcrs.isEmpty(), 'No DCRs created.');
        System.assertEquals(DATA_SIZE, dcrs.size(), 'No all DCRs have been created.');

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            System.assertNotEquals(null, dcr.PJN_Account__c, 'Account related to DCR cannot be null.');
            System.assertEquals(PJN_NetworkConstants.DCR_STATUS_SUBMITTED, dcr.PJN_Status__c, 'DCR Status must be Submitted');
            System.assert(!dcr.PJN_Data_Change_Request_Lines__r.isEmpty(), 'No DCR Lines created.');

            for (PJN_Data_Change_Request_Line__c dcrLine : dcr.PJN_Data_Change_Request_Lines__r) {
                System.assertEquals(null, dcrLine.PJN_Old_Value__c, 'DCR Old Value must be null, because it is a new record.');
                System.assertNotEquals(null, dcrLine.PJN_New_Value__c, 'DCR New Value cannot be null.');
            }
        }
    }

    @IsTest
    static void testInsertAccountError(){
        PJN_TestFactoryGlobalSetting.setMock();
        Test.setMock(HttpCalloutMock.class, new PJN_NetworkCreateDCRMock.ErrorMock());
        List<Account> accounts = buildAccounts(DATA_SIZE);

        Test.startTest();
        insert accounts;
        Test.getEventBus().deliver();
        Test.stopTest();

        List<PJN_Data_Change_Request__c> dcrs = getDCRsAndLines(accounts, PJN_NetworkConstants.DCR_TYPE_NEW);
        System.assert(!dcrs.isEmpty(), 'No DCRs created.');
        System.assertEquals(DATA_SIZE, dcrs.size(), 'No all DCRs have been created.');

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            System.assertNotEquals(null, dcr.PJN_Account__c, 'Account related to DCR cannot be null.');
            System.assertEquals(PJN_NetworkConstants.DCR_STATUS_CANCELLED, dcr.PJN_Status__c, 'DCR Status must be Cancelled.');
            System.assertEquals('Required fields are missing: lastname__v', dcr.PJN_Error__c, 'It must get the error message missing field.');
        }
    }

    @IsTest
    static void testInsertAndUpdatePendingAccountSucessfully(){
        PJN_TestFactoryGlobalSetting.setMock();
        List<Account> accounts = buildAccounts(DATA_SIZE);
        insert accounts;

        delete [SELECT Id FROM PJN_Data_Change_Request__c];

        for (Account thisAccount : accounts) {
            thisAccount.LastName = 'NewTestValue';
        }

        Test.startTest();
        update accounts;
        Test.getEventBus().deliver();
        Test.stopTest();

        List<PJN_Data_Change_Request__c> dcrs = getDCRsAndLines(accounts, PJN_NetworkConstants.DCR_TYPE_EDIT);
        System.assert(!dcrs.isEmpty(), 'No DCRs created.');
        System.assertEquals(DATA_SIZE, dcrs.size(), 'No all DCRs have been created.');

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            System.assertNotEquals(null, dcr.PJN_Account__c, 'Account related to DCR cannot be null.');
            System.assertEquals(PJN_NetworkConstants.DCR_STATUS_SUBMITTED, dcr.PJN_Status__c, 'DCR Status must be Submitted.');
            System.assert(!dcr.PJN_Data_Change_Request_Lines__r.isEmpty(), 'No DCR Lines created.');

            for (PJN_Data_Change_Request_Line__c dcrLine : dcr.PJN_Data_Change_Request_Lines__r) {
                System.assertNotEquals(null, dcrLine.PJN_Old_Value__c, 'DCR Old Value cannot be null. FieldName: ' + dcrLine.PJN_Field_API_Name__c);
                System.assertNotEquals(null, dcrLine.PJN_New_Value__c, 'DCR New Value cannot be null. FieldName: ' + dcrLine.PJN_Field_API_Name__c);
            }
        }
    }

    @IsTest
    static void testUpdateAccountSucessfully(){
        PJN_TestFactoryGlobalSetting.setMock();
        PJN_NetworkCallout.noRunInTest = true;
        List<Account> accounts = buildAccounts(DATA_SIZE);

        insert accounts;

        for (Account thisAccount : accounts) {
            thisAccount.LastName = 'NewTestValue';
            thisAccount.PJN_Veeva_Network_Id__c = 'VN'+thisAccount.FirstName;
        }

        delete [SELECT Id FROM PJN_Data_Change_Request__c WHERE PJN_Account__c IN :accounts];

        Test.startTest();
        update accounts;
        Test.getEventBus().deliver();
        Test.stopTest();

        List<PJN_Data_Change_Request__c> dcrs = getDCRsAndLines(accounts, PJN_NetworkConstants.DCR_TYPE_EDIT);
        System.assert(!dcrs.isEmpty(), 'No DCRs created.');
        System.assertEquals(DATA_SIZE, dcrs.size(), 'Not all DCRs have been created successfully.');

        for (PJN_Data_Change_Request__c dcr : dcrs) {
            System.assertNotEquals(null, dcr.PJN_Account__c, 'Account related to DCR cannot be null.');
            System.assertEquals(PJN_NetworkConstants.DCR_STATUS_PENDING, dcr.PJN_Status__c, 'DCR Status must be Pending.');
            System.assert(!dcr.PJN_Data_Change_Request_Lines__r.isEmpty(), 'No DCR Lines created.');

            for (PJN_Data_Change_Request_Line__c dcrLine : dcr.PJN_Data_Change_Request_Lines__r) {
                System.assertNotEquals(null, dcrLine.PJN_Old_Value__c, 'DCR Old Value cannot be null, because it is a record edited.');
                System.assertNotEquals(null, dcrLine.PJN_New_Value__c, 'DCR New Value cannot be null');
            }
        }
    }

    @isTest
    private static void testUpdateDCRsWithError() {
        PJN_NetworkCallout.noRunInTest = true;
        List<Account> accounts = buildAccounts(DATA_SIZE);
        insert accounts;
        List<PJN_Data_Change_Request__c> dcrs = getDCRsAndLines(accounts, PJN_NetworkConstants.DCR_TYPE_NEW);
        Map<Id, String> errorMessageByDCRId = new Map<Id, String>();
        for(PJN_Data_Change_Request__c thisDCR : dcrs) {
            errorMessageByDCRId.put(thisDCR.Id, 'Error: ' + thisDCR.Id);
        }
        PJN_DCRAccountHdlr dCRAccountHdlr = new PJN_DCRAccountHdlr();

        Test.startTest();
            dCRAccountHdlr.updateDCRsWithError(dcrs, errorMessageByDCRId);
        Test.stopTest();

        List<PJN_Data_Change_Request__c> actualDcrs = getDCRsAndLines(accounts, PJN_NetworkConstants.DCR_TYPE_NEW);
        System.assertEquals(dcrs.size(), actualDcrs.size(), 'DCRs do not match.');
    }

    private static List<Account> buildAccounts(Integer numOfAccounts) {
        List<Account> accounts = new List<Account>();

        for (Integer accIndex = 0; accIndex < numOfAccounts; accIndex++) {
            accounts.add(
                new Account(
                    FirstName = 'Test' + accIndex,
                    LastName = 'Test' + accIndex,
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
                    PersonMobilePhone = '555555555555'
                )
            );
        }

        return accounts;
    }

    private static List<PJN_Data_Change_Request__c> getDCRsAndLines(List<Account> accounts, String dcrType) {
        return [
            SELECT
                Id,
                Name,
                RecordTypeId,
                PJN_Status__c,
                PJN_Account__c,
                PJN_Contact_Information__c,
                PJN_License__c,
                PJN_Veeva_Network_Id__c,
                PJN_External_Id__c,
                PJN_Type__c,
                PJN_Error__c,
                PJN_Record_Type_Name__c,
                (
                    SELECT
                        Id,
                        Name,
                        PJN_Account__c,
                        PJN_Field_Label__c,
                        PJN_Field_API_Name__c,
                        PJN_Old_Value__c,
                        PJN_New_Value__c
                    FROM
                        PJN_Data_Change_Request_Lines__r
                )
            FROM
                PJN_Data_Change_Request__c
            WHERE
                PJN_Account__c IN :accounts
            AND
                PJN_Type__c = :dcrType
        ];
    }
}