force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related Coverage Investigation where the follow-up Case was generated from.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Follow-Up Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Therapy_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Therapy_Status__c</fullName>
    <description>A patient&apos;s program treatment journey status. Utilizing Status Global Value Set.</description>
    <label>Therapy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Activity.recordType-meta.xml
<RecordType>
    <fullName>PJN_Activity</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities related to a patient&apos;s care plan</description>
    <label>Activity</label>
</RecordType>

force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Coverage Investigation where the Assistance Program was generated from.</description>
    <label>Coverage Investigation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.PJN_Care_Plan__c</field>
            <operation>equals</operation>
            <valueField>PJN_Coverage_Investigation__c.PJN_Care_Plan__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Member Plan which a Copay Assistance Program is linked to.</description>
    <label>Member Plan</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a Member Plan from the same Care Plan.</errorMessage>
        <filterItems>
            <field>PJN_Member_Plan__c.PJN_Care_Plan__c</field>
            <operation>equals</operation>
            <valueField>$Source.PJN_Care_Plan__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Copay Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>The parent Care Plan where the Coverage Investigation is run from.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>The status of the Coverage Investigation.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/PJN_Coverage_Investigation_Item__c.object-meta.xml
<CustomObject>
    <description>Patient Journey Navigator custom object which stores the join between a Coverage Investigation and the items involved such as Member Plans.</description>
    <label>Coverage Investigation Item</label>
    <nameField>
        <displayFormat>CII-{000000}</displayFormat>
        <label>Coverage Investigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Assistance Programs being assessed in the Coverage Investigation.</description>
    <label>Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <description>The parent Coverage Investigation which the items are related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Prior_Authorization__c.field-meta.xml
<CustomField>
    <fullName>PJN_Prior_Authorization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Prior Authorization</label>
    <referenceTo>PJN_Prior_Authorization__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Coverage Investigation where the Therapy Access event is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Therapy Access</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>STATUS, used for inbound data mapping.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/PJN_Therapy_Access.recordType-meta.xml
<RecordType>
    <fullName>PJN_Therapy_Access</fullName>
    <active>true</active>
    <description>Defines an event representing how a patient is accessing therapy and the date periods.</description>
    <label>Therapy Access</label>
</RecordType>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/PJN_Prior_Authorization__c.object-meta.xml
<CustomObject>
    <description>Custom object to track prior authorizations related to member plans.</description>
    <label>Prior Authorization</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Prior Authorization Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan the parent member plan belongs to.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Coverage Investigation which the Prior Authorization is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <description>Master detail relationship with Member Plan.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Prior authorization status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Complete</fullName>
        <isActive>false</isActive>
        <label>Treatment Complete</label>
    </customValue>
    <customValue>
        <fullName>On Therapy</fullName>
        <isActive>false</isActive>
        <label>On Therapy</label>
    </customValue>
    <description>Status field picklist value set, used for Therapy Status fields. 

Pending: Status assigned to a patient&apos;s care plan confirming they are going through the program enrollment process (new or restart patient).

On Therapy: Status assigned to a patient&apos;s care plan confirming they are fully approved for dispense and awaiting/currently receiving shipments.

Treatment Complete: Status assigned to a patient&apos;s care plan confirming they have completed their treatment journey.

Discontinued: Status assigned to a patient&apos;s care plan confirming they have previously enrolled in a program, but have either chosen or have been deemed ineligible to continue. 

Cancelled: Status assigned to a patient&apos;s care plan confirming they have either chosen not to continue with enrollment, or have been deemed ineligible to continue.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_CoverageInvestigationUpdaterCtrlTest.cls
/**
 * @author      Mavens
 * @date        1/2021
 * @description Unit tests for pjnCoverageInvestigationUpdater lwc
 * @group       CoverageInvestigation
 */

@isTest
public class PJN_CoverageInvestigationUpdaterCtrlTest {

    @TestSetup
    static void makeData(){
        Account patient = new Account(
            LastName = 'Patient Test',
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByName().get('Patient').getRecordTypeId()
        );
        insert patient;

        PJN_TestFactoryCase caseFactory = new PJN_TestFactoryCase();
        Case carePlan = caseFactory.create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Case.getRecordTypeInfosByName().get('CarePlan').getRecordTypeId(),
                'Status' => 'Test',
                'Subject' => 'Care Plan Case',
                'AccountId' => patient.Id,
                'PJN_Therapy_Status__c' => 'Active'
            }
        );

        PJN_Coverage_Investigation__c investigation = new PJN_Coverage_Investigation__c(
            PJN_Care_Plan__c = carePlan.Id
        );
        insert investigation;

        PJN_Member_Plan__c plan = new PJN_Member_Plan__c(
            PJN_Care_Plan__c = carePlan.Id
        );
        insert plan;

        insert new PJN_Coverage_Investigation_Item__c (
            PJN_Coverage_Investigation__c = investigation.Id,
            PJN_Member_Plan__c = plan.Id
        );

        insert new PJN_Prior_Authorization__c(
            PJN_Member_Plan__c = plan.Id,
            PJN_Coverage_Investigation__c = investigation.Id
        );

        insert new PJN_Assistance_Program__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Coverage_Investigation__c = investigation.Id
        );
    }

    @isTest
    private static void itShouldGetTables() {
        PJN_Coverage_Investigation__c investigation = [SELECT Id FROM PJN_Coverage_Investigation__c LIMIT 1];

        AuraHandledException badObjectException;

        Test.startTest();
        PJN_DataTable memberPlanDataTable = PJN_CoverageInvestigationUpdaterCtrl.getTable(investigation.Id, 'PJN_Member_Plan__c');
        PJN_DataTable priorAuthDataTable = PJN_CoverageInvestigationUpdaterCtrl.getTable(investigation.Id, 'PJN_Prior_Authorization__c');
        PJN_DataTable assistProgDataTable = PJN_CoverageInvestigationUpdaterCtrl.getTable(investigation.Id, 'PJN_Assistance_Program__c');
        try {
            PJN_CoverageInvestigationUpdaterCtrl.getTable(investigation.Id, 'bad_object');
        } catch (AuraHandledException ex) {
            badObjectException = ex;
        }
        Test.stopTest();

        System.assertEquals(1, memberPlanDataTable.data.size());
        System.assertNotEquals(null, memberPlanDataTable.columns);

        System.assertEquals(1, priorAuthDataTable.data.size());
        System.assertNotEquals(null, priorAuthDataTable.columns);

        System.assertEquals(1, assistProgDataTable.data.size());
        System.assertNotEquals(null, assistProgDataTable.columns);

        System.assertNotEquals(null, badObjectException);
    }

    @isTest
    private static void itShouldGetFields() {
        AuraHandledException badObjectException;

        Test.startTest();
        List<PJN_CoverageInvestigationUpdaterCtrl.InputField> fields =  PJN_CoverageInvestigationUpdaterCtrl.getFields('PJN_Member_Plan__c');
        try {
            PJN_CoverageInvestigationUpdaterCtrl.getFields('bad_object');
        } catch (AuraHandledException ex) {
            badObjectException = ex;
        }
        Test.stopTest();

        System.assertNotEquals(0, fields.size());
        System.assertNotEquals(null, badObjectException);
    }

    @isTest
    private static void itShouldSubmit() {
        Case carePlan = [SELECT Id FROM Case WHERE RecordType.developerName = 'CarePlan' LIMIT 1];
        PJN_Coverage_Investigation__c investigation = [SELECT Id, PJN_Status__c FROM PJN_Coverage_Investigation__c LIMIT 1];
        investigation.PJN_Status__c = 'Completed';
        Map<String, SObject> data = new Map<String, SObject> {
            'PJN_Coverage_Investigation__c' => investigation,
            'Case' => new Case(Subject = 'Test', PJN_Coverage_Investigation__c = investigation.Id),
            'PJN_Event__c' => new PJN_Event__c(PJN_Coverage_Investigation__c = investigation.Id)
        };

        Test.startTest();
        PJN_CoverageInvestigationUpdaterCtrl.submit(data);
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM PJN_Coverage_Investigation__c WHERE Id = :investigation.Id AND PJN_Status__c = 'Completed']);
        Id activityRTId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Activity').getRecordTypeId();
        System.assertEquals(1, [SELECT COUNT() FROM Case WHERE ParentId = :carePlan.Id AND RecordTypeId = :activityRTId]);
    }

    @isTest
    private static void itShouldGetTherapyAccessRecordTypeId() {
        System.assertEquals(
            PJN_Event__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PJN_Therapy_Access').getRecordTypeId(),
            PJN_CoverageInvestigationUpdaterCtrl.getTherapyAccessRecTypeId()
        );
    }

    @isTest
    private static void itShouldThrowAuraExceptionOnBadSubmit() {
        AuraHandledException badSubmitException;

        Test.startTest();
        try {
            PJN_CoverageInvestigationUpdaterCtrl.submit(new Map<String, SObject>{'PJN_Coverage_Investigation__c' => new PJN_Coverage_Investigation__c()});
        } catch (AuraHandledException ex) {
            badSubmitException = ex;
        }
        Test.stopTest();

        System.assertNotEquals(null, badSubmitException);
    }
}