force-app/main/default/src/objects/Account/fields/PJN_Last_Date_Network_Modified__c.field-meta.xml
<CustomField>
    <fullName>PJN_Last_Date_Network_Modified__c</fullName>
    <description>Last date network record is modified.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Date Network Modified</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Last_Date_Network_Synced__c.field-meta.xml
<CustomField>
    <fullName>PJN_Last_Date_Network_Synced__c</fullName>
    <description>Last date network record is synced.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Date Network Synced</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Status of the contact information</description>
    <inlineHelpText>Status of the contact information</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_Value__c</fullName>
    <description>Set by workflow when contact info is created or updated, this field stores the formatted value. This used to be a formula but prevented encryption of phone fields used in formulas</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information to be modified.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_DCR_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_External_ID__c</fullName>
    <description>Part of the Patient Service accelerator: External Data Change Request ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>DCR External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License__c.field-meta.xml
<CustomField>
    <fullName>PJN_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: License to be modified.</description>
    <label>License</label>
    <referenceTo>PJN_License__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Parent_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Data_Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of the Patient Service accelerator: Link to parent DCR. Used only if multiple DCRs are created in a single step. Account DCR is always a parent. Other DCRs link to it.</description>
    <label>Parent Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Part of the Patient Service accelerator: local data change request status which defines what happens next with the data change request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>The status of the license</description>
    <inlineHelpText>The status of the license</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/PJN_Network_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Network Object Setting</label>
    <pluralLabel>Network Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Sync_Delay__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Delay__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sync delay in minutes - No delay with value 0</description>
    <inlineHelpText>Sync delay in minutes - No delay with value 0</inlineHelpText>
    <label>Sync Delay</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_Sync_Record_Types_Allowed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Record_Types_Allowed__c</fullName>
    <defaultValue>&quot;All&quot;</defaultValue>
    <label>Sync Record Types Allowed</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/PJN_Network_Value_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data change request value mapping for those values which needs a transformation to go into Veeva Network</description>
    <label>Network Value Mapping</label>
    <pluralLabel>Network Value Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_External_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Value__c</fullName>
    <description>Veeva Network external value.</description>
    <inlineHelpText>Veeva Network external value.</inlineHelpText>
    <label>External value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_Inbound__c.field-meta.xml
<CustomField>
    <fullName>PJN_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does this map from Veeva Network to Salesforce?</description>
    <label>Inbound?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkSyncUtility.cls
/**
 * Network Sync Utility methods
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_NetworkSyncUtility {

    /**
     * Account record types allowed
     */
    public static String accountRecordTypesAllowed = PJN_NetworkObjectSetting.getSettingByName('Account').PJN_Sync_Record_Types_Allowed__c.toLowerCase();

    /**
     * Address record types allowed
     */
    public static String addressRecordTypesAllowed = PJN_NetworkObjectSetting.getSettingByName('PJN_Contact_Information__c').PJN_Sync_Record_Types_Allowed__c.toLowerCase();

    /**
     * License record types allowed
     */
    public static String licenseRecordTypesAllowed = PJN_NetworkObjectSetting.getSettingByName('PJN_License__c').PJN_Sync_Record_Types_Allowed__c.toLowerCase();

    /**
     * DCR Statuses to sync before account sync
     */
    private static final Set<String> DCR_STATUS_SYNC_BEFORE_ACCOUNT = new Set<String> {
        PJN_NetworkConstants.DCR_STATUS_PENDING,
        PJN_NetworkConstants.DCR_STATUS_SUBMITTED
    };

    /**
     * Query accounts and children
     * @param accountIds Account Ids
     * @returns `List<Account>`
     */
    public static List<Account> queryAccounts(Set<String> accountIds) {
        if (accountIds == null || accountIds.isEmpty()) {
            return null;
        }

        return [
            SELECT
                Id,
                RecordType.DeveloperName,
                PJN_Veeva_Network_Id__c,
                PJN_Last_Date_Network_Synced__c,
                PJN_Last_Date_Network_Modified__c,
                LastModifiedDate,
                (
                    SELECT
                        Id,
                        RecordType.DeveloperName,
                        PJN_Veeva_Network_Id__c
                    FROM
                        PJN_Contact_Information__r
                ),
                (
                    SELECT
                        Id,
                        PJN_Veeva_Network_Id__c
                    FROM
                        PJN_Licenses__r
                ),
                (
                    SELECT
                        Id,
                        PJN_DCR_External_ID__c,
                        PJN_Status__c
                    FROM
                        PJN_Data_Change_Requests__r
                    WHERE
                        PJN_Status__c IN :DCR_STATUS_SYNC_BEFORE_ACCOUNT
                    AND
                        PJN_DCR_External_ID__c != null
                )
            FROM
                Account
            WHERE
                Id IN :accountIds
        ];
    }

    /**
     * Update Account Network Last modified date
     * @param thisAccount           Account record to be synced
     * @param accountNetworkRecord  Account Network record
     * @returns `Account`
     */
    public static Account updateLastModifiedDate(Account thisAccount, PJN_NetworkRecord accountNetworkRecord) {
        if (thisAccount == null || accountNetworkRecord == null) {
            return thisAccount;
        }

        String networkModifiedDate = String.valueOf(accountNetworkRecord.getAttribute('modified_date__v'));

        if (String.isNotBlank(networkModifiedDate)) {
            thisAccount.PJN_Last_Date_Network_Modified__c = (DateTime)JSON.deserialize('"' + networkModifiedDate + '"', DateTime.class);
        }

        return thisAccount;
    }

    /**
     * Checks if this account is allowed to be synced
     * @param thisAccount           Account record to be synced
     * @param networkAccountSetting Network Account settings
     * @returns `Boolean`
     */
    public static Boolean isAccountAllowedToSync(Account thisAccount, PJN_Network_Object_Setting__mdt networkAccountSetting) {
        // Account is synced when
        // Never synced before - PJN_Last_Date_Network_Synced__c == null
        // No modified date returned from Network - PJN_Last_Date_Network_Modified__c == null
        // Network modified data after synced - PJN_Last_Date_Network_Synced__c < PJN_Last_Date_Network_Modified__c
        // Network modified data after record - LastModifiedDate < PJN_Last_Date_Network_Modified__c
        Boolean allowedToSync = thisAccount.PJN_Last_Date_Network_Synced__c == null
            || thisAccount.PJN_Last_Date_Network_Modified__c == null
            || thisAccount.PJN_Last_Date_Network_Synced__c < thisAccount.PJN_Last_Date_Network_Modified__c
            || thisAccount.LastModifiedDate < thisAccount.PJN_Last_Date_Network_Modified__c;

        // Account not modified last sync delay minutes configured - PJN_Last_Date_Network_Synced__c < NOW - PJN_Sync_Delay__c minutes
        if (networkAccountSetting.PJN_Sync_Delay__c > 0) {
            Integer syncDelay = Integer.valueOf(networkAccountSetting.PJN_Sync_Delay__c);
            allowedToSync = allowedToSync || thisAccount.LastModifiedDate < System.now().addMinutes(-syncDelay);
        }

        return allowedToSync;
    }

    /**
     * Get Entity Value mapped using PJN_Network_Value_Mapping__mdt
     * @param valueMappings PJN_Network_Value_Mapping__mdt records
     * @param entityValue   Entity value responded by Network
     * @returns `Object`
     */
    public static Object getEntityValueMapped(List<PJN_Network_Value_Mapping__mdt> valueMappings, Object entityValue) {
        if (valueMappings == null) {
            return entityValue;
        }

        for (PJN_Network_Value_Mapping__mdt valueMapping : valueMappings) {
            if (valueMapping.PJN_Inbound__c && valueMapping.PJN_External_Value__c == String.valueOf(entityValue)) {
                entityValue = valueMapping.PJN_Value__c;
                break;
            }
        }

        return entityValue;
    }

    public static Map<String, Map<String, PJN_Data_Change_Request__c>> getDCRsByExtIdFromNetworkResponse(List<PJN_NetworkEntity> networkChangeRequests) {
        Map<String, Map<String, PJN_Data_Change_Request__c>> dcrsByExtId = new Map<String, Map<String, PJN_Data_Change_Request__c>>();

        if (networkChangeRequests == null || networkChangeRequests.isEmpty()) {
            return dcrsByExtId;
        }

        Set<String> networkChangeRequestIds = new Set<String>();

        for (PJN_NetworkEntity networkChangeRequest : networkChangeRequests) {
            if (String.isBlank(networkChangeRequest.changeRequestId)) {
                continue;
            }

            networkChangeRequestIds.add(networkChangeRequest.changeRequestId);
        }

        for (PJN_Data_Change_Request__c dcr : PJN_DCRQuery.queryWithLinesByNetworkIds(networkChangeRequestIds)) {
            String dcrExternalId = dcr.PJN_Parent_Data_Change_Request__c != null ?
                dcr.PJN_Parent_Data_Change_Request__r.PJN_DCR_External_Id__c :
                dcr.PJN_DCR_External_Id__c;

            Map<String, PJN_Data_Change_Request__c> dcrByRecordId = dcrsByExtId.containsKey(dcrExternalId) ?
                dcrsByExtId.get(dcrExternalId) :
                new Map<String, PJN_Data_Change_Request__c>();

            String recordExtId = String.isNotBlank(dcr.PJN_Veeva_Network_Id__c) ?
                dcr.PJN_Veeva_Network_Id__c :
                dcr.PJN_External_Id__c.substringBeforeLast('|');

            dcrByRecordId.put(recordExtId, dcr);

            dcrsByExtId.put(dcrExternalId, dcrByRecordId);
        }

        return dcrsByExtId;
    }

    /**
     * Get map of network records by veeva network id
     * @param entities  List of entities from Network response
     * @returns `Map<String, Map<String, PJN_NetworkRecord>>`
     */
    public static Map<String, Map<String, PJN_NetworkRecord>> getRecordByNetworkIdsByExtId(List<PJN_NetworkEntity> networkEntities) {
        Map<String, Map<String, PJN_NetworkRecord>> entityByNetworkIdByExtId = new Map<String, Map<String, PJN_NetworkRecord>>();

        if (networkEntities == null || networkEntities.isEmpty()) {
            return entityByNetworkIdByExtId;
        }

        for (PJN_NetworkEntity networkEntity : networkEntities) {
            Map<String, PJN_NetworkRecord> entityByNetworkId = new Map<String, PJN_NetworkRecord>();

            entityByNetworkId.put(networkEntity.entity.vid, networkEntity.entity);

            entityByNetworkId.putAll(getChildNetworkRecord(networkEntity.entity.addresses));
            entityByNetworkId.putAll(getChildNetworkRecord(networkEntity.entity.licenses));

            entityByNetworkIdByExtId.put(networkEntity.entity.vid, entityByNetworkId);
        }

        return entityByNetworkIdByExtId;
    }

    /**
     * Get map of network children records by netowkr id
     * @param networkChildrenRecords    Children Network records to be mapped
     * @returns `Map<String, PJN_NetworkRecord>`
     */
    private static Map<String, PJN_NetworkRecord> getChildNetworkRecord(List<PJN_NetworkRecord> networkChildrenRecords) {
        Map<String, PJN_NetworkRecord> childByNetworkId = new Map<String, PJN_NetworkRecord>();

        for (PJN_NetworkRecord networkChildRecord : networkChildrenRecords) {
            childByNetworkId.put(networkChildRecord.vid, networkChildRecord);
        }

        return childByNetworkId;
    }

    /**
     * Update SFDC Record with Network Record
     * @param thisRecord    SFDC Record
     * @param networkRecord Network Record
     * @param fieldMappings Record field Mappings
     * @returns `SObject`
     */
    public static SObject updateRecordWithNetworkRecord(SObject thisRecord, PJN_NetworkRecord networkRecord, List<PJN_Network_Field_Mapping__mdt> fieldMappings) {
        for (PJN_Network_Field_Mapping__mdt fieldMapping : fieldMappings) {
            if (!fieldMapping.PJN_Sync_Transmission__c) {
                continue;
            }

            Object entityValue = networkRecord.getAttribute(fieldMapping.PJN_External_Field_Name__c);
            entityValue = PJN_NetworkSyncUtility.getEntityValueMapped(fieldMapping.PJN_Network_Value_Mappings__r, entityValue);

            thisRecord.put(fieldMapping.PJN_Field_API_Name__c, getFieldValueWithFieldType(thisRecord.getSObjectType().getDescribe().getName(), fieldMapping.PJN_Field_API_Name__c, String.valueOf(entityValue)));
        }

        return thisRecord;
    }

    private static Object getFieldValueWithFieldType(String sobjectName, String fieldName, String fieldValue) {
        if (String.isBlank(sobjectName) || String.isBlank(fieldName) || String.isBlank(fieldValue)) {
            return fieldValue;
        }
        Object fieldValueObject = fieldValue;

        Schema.DisplayType fieldType = Schema.getGlobalDescribe().get(sobjectName).getDescribe().fields.getMap().get(fieldName).getDescribe().getType();
        if(fieldType == Schema.DisplayType.DATE) {
            fieldValueObject = Date.valueOf(fieldValue);
        } else if(fieldType == Schema.DisplayType.DATETIME) {
            fieldValueObject = Datetime.valueOf(fieldValue);
        } else if (fieldType == Schema.DisplayType.BOOLEAN) {
            fieldValueObject = Boolean.valueOf(fieldValue);
        }

        return fieldValueObject;
    }
}