force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/recordTypes/PJN_Organization.recordType-meta.xml
<RecordType>
    <fullName>PJN_Organization</fullName>
    <active>true</active>
    <description>Defines a healthcare organization where physicians and staff work</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/src/objects/PJN_Affiliation__c/PJN_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Stores the hierarchical relationship between people and organizations.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFFL-{0000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Account__c</fullName>
    <description>Master-Detail (Account) with Affiliation Members as children accounts.</description>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Members</relationshipLabel>
    <relationshipName>Affiliation1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>PIcklist, affiliation statuses.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Status of the contact information</description>
    <inlineHelpText>Status of the contact information</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_Value__c</fullName>
    <description>Set by workflow when contact info is created or updated, this field stores the formatted value. This used to be a formula but prevented encryption of phone fields used in formulas</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/PJN_Network_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data change request field mapping for Veeva Network</description>
    <label>Network Field Mapping</label>
    <pluralLabel>Network Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should this field be included when creating data change requests?</description>
    <inlineHelpText>Should this field be included when creating data change requests?</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_DCR_Transmission__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Transmission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is DCR allowed to be transmitted?</description>
    <inlineHelpText>Is DCR allowed to be transmitted?</inlineHelpText>
    <label>DCR Transmission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_External_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Field_Name__c</fullName>
    <description>External field API name to map in Veeva Network.</description>
    <inlineHelpText>External field API name to map in Veeva Network.</inlineHelpText>
    <label>External Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <description>Field API name to map into Veeva Network.</description>
    <inlineHelpText>Field API name to map into Veeva Network.</inlineHelpText>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Network_Object__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Object__c</fullName>
    <description>SObject which this field mapping is related to</description>
    <inlineHelpText>SObject which this field mapping is related to</inlineHelpText>
    <label>Network Object</label>
    <referenceTo>PJN_Network_Object_Setting__mdt</referenceTo>
    <relationshipLabel>Network Field Mappings</relationshipLabel>
    <relationshipName>PJN_Network_Field_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Required_for_DCR_Transmission__c.field-meta.xml
<CustomField>
    <fullName>PJN_Required_for_DCR_Transmission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is required for every DCR transmission otherwise an error will be returned.</description>
    <inlineHelpText>This field is required for every DCR transmission otherwise an error will be returned.</inlineHelpText>
    <label>Required for DCR Transmission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Record_Type__c</fullName>
    <defaultValue>&quot;ALL&quot;</defaultValue>
    <description>SObject record type associated to this field mapping. &apos;ALL&apos; would be included in all record types.</description>
    <inlineHelpText>SObject record type associated to this field mapping. &apos;ALL&apos; would be included in all record types.</inlineHelpText>
    <label>SObject Record Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Field_Mapping__mdt/fields/PJN_Sync_Transmission__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sync_Transmission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is sync allowed to be transmitted?</description>
    <inlineHelpText>Is sync allowed to be transmitted?</inlineHelpText>
    <label>Sync Transmission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/PJN_Network_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Network Object Setting</label>
    <pluralLabel>Network Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Object_Setting__mdt/fields/PJN_SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Name__c</fullName>
    <description>SObject Name for the DCR.</description>
    <label>SObject Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/PJN_Network_Value_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data change request value mapping for those values which needs a transformation to go into Veeva Network</description>
    <label>Network Value Mapping</label>
    <pluralLabel>Network Value Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_External_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Value__c</fullName>
    <description>Veeva Network external value.</description>
    <inlineHelpText>Veeva Network external value.</inlineHelpText>
    <label>External value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_Inbound__c.field-meta.xml
<CustomField>
    <fullName>PJN_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does this map from Veeva Network to Salesforce?</description>
    <label>Inbound?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_Network_Field_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Network_Field_Mapping__c</fullName>
    <description>Network Field mapping where this value mapping is applied.</description>
    <inlineHelpText>Network Field mapping where this value mapping is applied.</inlineHelpText>
    <label>Network Field Mapping</label>
    <referenceTo>PJN_Network_Field_Mapping__mdt</referenceTo>
    <relationshipLabel>Network Value Mappings</relationshipLabel>
    <relationshipName>PJN_Network_Value_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_Outbound__c.field-meta.xml
<CustomField>
    <fullName>PJN_Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does this map from Salesforce to Veeva Network?</description>
    <label>Outbound?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Network_Value_Mapping__mdt/fields/PJN_Value__c.field-meta.xml
<CustomField>
    <fullName>PJN_Value__c</fullName>
    <description>Salesforce field value</description>
    <inlineHelpText>Salesforce field value</inlineHelpText>
    <label>Value</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_NetworkFieldMappingsMock.cls
/**
 * Mock for PJN_NetworkFieldMappingsQuery
 * @author  Mavens
 * @group   Network
 */
@IsTest
public with sharing class PJN_NetworkFieldMappingsMock implements System.StubProvider {

    private static final String PREFIX = Schema.SObjectType.PJN_Network_Field_Mapping__mdt.getKeyPrefix();

    @SuppressWarnings('PMD.ExcessiveParameterList')
    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'queryAllWithValues') {
            return this.queryAllWithValues();
        } else {
            return null;
        }
    }

    /**
     * Mock all Network Field Mappings metadatas
     * @returns `List<PJN_Network_Field_Mapping__mdt>`
     */
    public List<PJN_Network_Field_Mapping__mdt> queryAllWithValues() {
        List<PJN_Network_Field_Mapping__mdt> networkFieldMappings = new List<PJN_Network_Field_Mapping__mdt>();

        networkFieldMappings.addAll(getAccountNetworkFieldMappings());
        networkFieldMappings.addAll(getAddressNetworkFieldMappings());
        networkFieldMappings.addAll(getLicenseNetworkFieldMappings());
        networkFieldMappings.addAll(getAffiliationNetworkFieldMappings());

        return networkFieldMappings;
    }

    private static List<PJN_Network_Field_Mapping__mdt> getAccountNetworkFieldMappings() {
        List<PJN_Network_Field_Mapping__mdt> networkFieldMappings = new List<PJN_Network_Field_Mapping__mdt>();

        PJN_Network_Field_Mapping__mdt currentNetworkFieldMappings = new PJN_Network_Field_Mapping__mdt (
            PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                PJN_SObject_Name__c = Account.getSObjectType().getDescribe().getName()
            ),
            PJN_SObject_Record_Type__c = 'PJN_Physician',
            PJN_External_Field_Name__c = 'first_name__v',
            PJN_Field_API_Name__c = 'FirstName',
            PJN_Active__c = true,
            PJN_Required_for_DCR_Transmission__c = true,
            PJN_DCR_Transmission__c = true,
            PJN_Sync_Transmission__c = true,
            Id = PREFIX + '000000000001'
        );

        currentNetworkFieldMappings.PJN_Network_Value_Mappings__r.addAll(
            new List<PJN_Network_Value_Mapping__mdt> {
                new PJN_Network_Value_Mapping__mdt (
                    PJN_External_Value__c = 'VNTest',
                    PJN_Inbound__c = true,
                    PJN_Outbound__c = true,
                    PJN_Value__c = 'Test'
                ),
                new PJN_Network_Value_Mapping__mdt (
                    PJN_External_Value__c = 'VNNoTest',
                    PJN_Inbound__c = true,
                    PJN_Outbound__c = true,
                    PJN_Value__c = 'NoTest'
                )
            }
        );
        networkFieldMappings.add(currentNetworkFieldMappings);

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = Account.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'PJN_Physician',
                PJN_External_Field_Name__c = 'last_name__v',
                PJN_Field_API_Name__c = 'LastName',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '000000000002'
            )
        );

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = Account.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'PJN_Physician',
                PJN_External_Field_Name__c = 'phone__v',
                PJN_Field_API_Name__c = 'PersonMobilePhone',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = false,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '000000000003'
            )
        );

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = Account.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'PJN_Organization',
                PJN_External_Field_Name__c = 'name__v',
                PJN_Field_API_Name__c = 'Name',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '000000000004'
            )
        );

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = Account.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'PJN_Organization',
                PJN_External_Field_Name__c = 'name__v',
                PJN_Field_API_Name__c = 'Name',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '000000000005'
            )
        );

        return networkFieldMappings;
    }

    private static List<PJN_Network_Field_Mapping__mdt> getAddressNetworkFieldMappings() {
        List<PJN_Network_Field_Mapping__mdt> networkFieldMappings = new List<PJN_Network_Field_Mapping__mdt>();

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = PJN_Contact_Information__c.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'All',
                PJN_External_Field_Name__c = 'address_line_1__v',
                PJN_Field_API_Name__c = 'PJN_Address_Line_1__c',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '100000000001'
            )
        );

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = PJN_Contact_Information__c.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'All',
                PJN_External_Field_Name__c = 'address_line_2__v',
                PJN_Field_API_Name__c = 'PJN_Address_Line_2__c',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = false,
                Id = PREFIX + '100000000002'
            )
        );

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = PJN_Contact_Information__c.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'All',
                PJN_External_Field_Name__c = 'locality__v',
                PJN_Field_API_Name__c = 'PJN_City__c',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = false,
                Id = PREFIX + '100000000003'
            )
        );

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = PJN_Contact_Information__c.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'All',
                PJN_External_Field_Name__c = 'administrative_area__v',
                PJN_Field_API_Name__c = 'PJN_State__c',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = false,
                Id = PREFIX + '100000000004'
            )
        );

        return networkFieldMappings;
    }

    private static List<PJN_Network_Field_Mapping__mdt> getLicenseNetworkFieldMappings() {
        List<PJN_Network_Field_Mapping__mdt> networkFieldMappings = new List<PJN_Network_Field_Mapping__mdt>();

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = PJN_License__c.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'All',
                PJN_External_Field_Name__c = 'license_number__v',
                PJN_Field_API_Name__c = 'Name',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = true,
                PJN_DCR_Transmission__c = true,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '200000000001'
            )
        );

        return networkFieldMappings;
    }

    private static List<PJN_Network_Field_Mapping__mdt> getAffiliationNetworkFieldMappings() {
        List<PJN_Network_Field_Mapping__mdt> networkFieldMappings = new List<PJN_Network_Field_Mapping__mdt>();

        networkFieldMappings.add(
            new PJN_Network_Field_Mapping__mdt (
                PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                    PJN_SObject_Name__c = PJN_Affiliation__c.getSObjectType().getDescribe().getName()
                ),
                PJN_SObject_Record_Type__c = 'All',
                PJN_External_Field_Name__c = 'parent_hco_vid__v',
                PJN_Field_API_Name__c = 'PJN_Parent_Account__c',
                PJN_Active__c = true,
                PJN_Required_for_DCR_Transmission__c = false,
                PJN_DCR_Transmission__c = false,
                PJN_Sync_Transmission__c = true,
                Id = PREFIX + '300000000001'
            )
        );

        PJN_Network_Field_Mapping__mdt currentNetworkFieldMapping = new PJN_Network_Field_Mapping__mdt (
            PJN_Network_Object__r = new PJN_Network_Object_Setting__mdt (
                PJN_SObject_Name__c = PJN_Affiliation__c.getSObjectType().getDescribe().getName()
            ),
            PJN_SObject_Record_Type__c = 'All',
            PJN_External_Field_Name__c = 'parent_hco_status__v',
            PJN_Field_API_Name__c = 'PJN_Status__c',
            PJN_Active__c = true,
            PJN_Required_for_DCR_Transmission__c = false,
            PJN_DCR_Transmission__c = false,
            PJN_Sync_Transmission__c = true,
            Id = PREFIX + '300000000002'
        );

        currentNetworkFieldMapping.PJN_Network_Value_Mappings__r.addAll(
            new List<PJN_Network_Value_Mapping__mdt> {
                new PJN_Network_Value_Mapping__mdt (
                    PJN_External_Value__c = 'A',
                    PJN_Inbound__c = true,
                    PJN_Outbound__c = true,
                    PJN_Value__c = 'Active'
                ),
                new PJN_Network_Value_Mapping__mdt (
                    PJN_External_Value__c = 'I',
                    PJN_Inbound__c = true,
                    PJN_Outbound__c = true,
                    PJN_Value__c = 'Inactive'
                )
            }
        );
        networkFieldMappings.add(currentNetworkFieldMapping);

        return networkFieldMappings;
    }
}