force-app/main/default/src/objects/Account/fields/PJN_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Address record type.</description>
    <label>Primary Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Address</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/MVN_RBM_User__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RBM User assigned to this Care Plan.</description>
    <label>RBM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Enrollment_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Region__c.field-meta.xml
<CustomField>
    <fullName>PJN_Region__c</fullName>
    <description>The region that this case is assigned to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The region that this case is assigned to.</inlineHelpText>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Run_ZTT_Against_Enrollment_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Run_ZTT_Against_Enrollment_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set to TRUE the code will use the enrollment address of the Physician on Physician update in order to apply the Zip To Team mapping.</description>
    <label>Run ZTT Against Enrollment Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Territory__c.field-meta.xml
<CustomField>
    <fullName>PJN_Territory__c</fullName>
    <description>The territory the case is assigned to.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The territory the case is assigned to.</inlineHelpText>
    <label>MS Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Zip_To_Team__c.field-meta.xml
<CustomField>
    <fullName>PJN_Zip_To_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The record used to align this case to a care team - Created July 11, 2019</description>
    <label>Zip To Team</label>
    <referenceTo>PJN_Zip_To_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>PJN_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Set_as_Primary__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates this record should be set as primary. A trigger will manage this update.</description>
    <inlineHelpText>Indicates this record should be set as primary.</inlineHelpText>
    <label>Set as Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/PJN_Zip_To_Team__c.object-meta.xml
<CustomObject>
    <description>Zip to Team is used to record mapping between zip codes and Case Managers, Therapeutic Specialists, regions and territories.</description>
    <label>Zip To Team</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip To Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip To Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/MVN_RBM_User__c.field-meta.xml
<CustomField>
    <fullName>MVN_RBM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for RBM User, the RBM user assigned to care plans linked to this Zip To Team record.</description>
    <label>RBM User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zip_To_Team_RBM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for ZTT, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The program this ZTT is related to. Created July 11, 2019</description>
    <inlineHelpText>The program this ZTT is related to</inlineHelpText>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Zip To Team</relationshipLabel>
    <relationshipName>PJN_Zip_To_Teams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Region__c.field-meta.xml
<CustomField>
    <fullName>PJN_Region__c</fullName>
    <description>The region any case tied to this ZTT is assigned to. Created July 12, 2019</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The region any case tied to this ZTT is assigned to.</inlineHelpText>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Territory__c.field-meta.xml
<CustomField>
    <fullName>PJN_Territory__c</fullName>
    <description>The territory any case tied to this ZTT is assigned to. Created July 12, 2019</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The territory any case tied to this ZTT is assigned to.</inlineHelpText>
    <label>Territory</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Zip_To_Team__c/fields/PJN_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Zip_Code__c</fullName>
    <description>Text (5) Zip code field.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/MVN_ZipToTeamAssignmentBatchSchTest.cls
@IsTest
private class MVN_ZipToTeamAssignmentBatchSchTest {
    static String REGION = 'Northeast';
    static String REGION2 = 'Southwest';
    static String TERRITORY = 'Boston';
    /**
    * @description setups data for all unit tests
    */
    @testSetup
    private static void setup() {
        CareProgram program = new CareProgram(
            Name = 'Test Program',
            PJN_Program_DeveloperName__c = 'PJN_Test_Program',
            StartDate = Date.today()
        );
        insert program;

        PJN_TestFactoryAccount accountFactory = new PJN_TestFactoryAccount();
        Account physician = accountFactory.create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
                'LastName' => 'Physician Test'
            }
        );
        PJN_TestFactoryContactInformation contactInformationFactory = new PJN_TestFactoryContactInformation();
        PJN_Contact_Information__c contactInfoPhysician = contactInformationFactory.createAddress(new Map<String,Object>{
            'PJN_Address_Line_1__c' => 'Physician Address Line 1',
            'PJN_Address_Line_2__c' => 'Physician Address Line 2',
            'PJN_Set_as_Primary__c' => true,
            'PJN_City__c' => 'Physician City',
            'PJN_Postal_Code__c' => '11111',
            'PJN_Country__c' => 'United States',
            'PJN_Account__c' => Physician.Id
        });

        Account physicianUpdated = accountFactory.create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
                'LastName' => 'Physician Updated Test'
            }
        );
        Account IndustriesIndividualUpdated = accountFactory.create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesIndividual').getRecordTypeId(),
                'Name' => 'IndustriesIndividual Updated Test'
            }
        );

        PJN_Contact_Information__c contactInfoPhysicianUpdated = contactInformationFactory.createAddress(new Map<String,Object>{
            'PJN_Address_Line_1__c' => 'Physician Address Line 1',
            'PJN_Address_Line_2__c' => 'Physician Address Line 2',
            'PJN_Set_as_Primary__c' => true,
            'PJN_City__c' => 'Physician City',
            'PJN_Postal_Code__c' => '22222',
            'PJN_Country__c' => 'United States',
            'PJN_Account__c' => physicianUpdated.Id
        });
        physicianUpdated.PJN_Primary_Address__c = contactInfoPhysicianUpdated.Id;
        update physicianUpdated;

        Account patient = accountFactory.create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId(),
                'LastName' => 'Patient Test'
            }
        );
        PJN_Contact_Information__c contactInfoPatient = contactInformationFactory.createAddress(new Map<String,Object>{
            'PJN_Address_Line_1__c' => 'Patient Address Line 1',
            'PJN_Address_Line_2__c' => 'Patient Address Line 2',
            'PJN_Set_as_Primary__c' => true,
            'PJN_City__c' => 'Patient City',
            'PJN_Postal_Code__c' => '11111',
            'PJN_Country__c' => 'United States',
            'PJN_Account__c' => Patient.Id
        });
        patient.PJN_Primary_Address__c = contactInfoPatient.Id;
        update patient;
        Account patientUpdated = accountFactory.create(
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId(),
                'LastName' => 'Patient Updated Test'
            }
        );
        PJN_Contact_Information__c contactInfoPatientUpdated = contactInformationFactory.createAddress(new Map<String,Object>{
            'PJN_Address_Line_1__c' => 'Patient Address Line 1',
            'PJN_Address_Line_2__c' => 'Patient Address Line 2',
            'PJN_Set_as_Primary__c' => true,
            'PJN_City__c' => 'Patient City',
            'PJN_Postal_Code__c' => '22222',
            'PJN_Country__c' => 'United States',
            'PJN_Account__c' => PatientUpdated.Id
        });
        patientUpdated.PJN_Primary_Address__c = contactInfoPatientUpdated.Id;
        update PatientUpdated;

        String country =  PJN_Contact_Information__c.PJN_Country__c.getDescribe().getPicklistValues().get(0).getValue();
        List<User> userList = [SELECT Id FROM User WHERE Name!='Automated Process' AND Name!='System' AND IsActive=true LIMIT 2];
        List<PJN_Zip_To_Team__c> zipToTeamList = new List<PJN_Zip_To_Team__c>();
        zipToTeamList.add(
            new PJN_Zip_To_Team__c(
                Name = 'Zip To Team Test 1',
                MVN_RBM_User__c = userList.get(0).Id,
                PJN_Zip_Code__c = '11111',
                PJN_Program__c = program.Id,
                PJN_Country__c = 'United States',
                PJN_Region__c = REGION,
                PJN_Territory__c = TERRITORY
            )
        );
         zipToTeamList.add(
            new PJN_Zip_To_Team__c(
                Name = 'Zip To Team Test 2',
                MVN_RBM_User__c = userList.get(1).Id,
                PJN_Zip_Code__c = '22222',
                PJN_Program__c = program.Id,
                PJN_Country__c = 'United States',
                PJN_Region__c = REGION2,
                PJN_Territory__c = TERRITORY
            )
        );
        insert zipToTeamList;
        Test.startTest();
        PJN_TestFactoryCase caseFactory = new PJN_TestFactoryCase();
        List<Case> carePlans = caseFactory.constructMany(100,
            new Map<String, Object> {
                'RecordTypeId' => SObjectType.Case.getRecordTypeInfosByName().get('CarePlan').getRecordTypeId(),
                'PJN_Program_DeveloperName__c' => 'PJN_Test_Program',
                'Status' => 'Test',
                'Subject' => 'Care Plan Case',
                'PJN_Physician__c' => physician.Id,
                'PJN_Enrollment_Address__c' => contactInfoPhysician.Id
            }
        );
        carePlans.addAll(
            caseFactory.constructMany(100,
                new Map<String, Object> {
                    'RecordTypeId' => SObjectType.Case.getRecordTypeInfosByName().get('CarePlan').getRecordTypeId(),
                    'PJN_Program_DeveloperName__c' => 'PJN_Test_Program',
                    'Status' => 'Test',
                    'Subject' => 'Care Plan Case',
                    'PJN_Physician__c' => physicianUpdated.Id,
                    'PJN_Enrollment_Address__c' => contactInfoPhysicianUpdated.Id
                }
            )
        );
        carePlans.addAll(
            caseFactory.constructMany(1,
                new Map<String, Object> {
                    'RecordTypeId' => SObjectType.Case.getRecordTypeInfosByName().get('CarePlan').getRecordTypeId(),
                    'PJN_Program_DeveloperName__c' => 'PJN_Test_Program',
                    'Status' => 'Test',
                    'Subject' => 'Care Plan Case',
                    'AccountId' => IndustriesIndividualUpdated.Id
                }
            )
        );
        insert carePlans;
        Test.stopTest();
    }

    @isTest
    private static void testInsertCarePlanAndUpdatePhysician() {
        List<Case> carePlans = [SELECT Id FROM Case WHERE RecordType.DeveloperName = 'CarePlan'];
        for (Case carePlan : carePlans) {
            carePlan.PJN_Zip_To_Team__c = null;
            carePlan.PJN_Run_ZTT_Against_Enrollment_Address__c = false;
            carePlan.PJN_Region__c = null;
            carePlan.PJN_Territory__c = null;
            carePlan.MVN_RBM_User__c = null;
        }
        update carePlans;
        Test.startTest();
        MVN_ZipToTeamAssignmentBatchSch zttAssignmentBatch = new MVN_ZipToTeamAssignmentBatchSch();
        ID batchprocessid = Database.executeBatch(zttAssignmentBatch, 2000);
        Test.stopTest();
        carePlans = [
            SELECT
                OwnerId,
                PJN_Zip_To_Team__c,
                PJN_Run_ZTT_Against_Enrollment_Address__c,
                PJN_Region__c,
                PJN_Territory__c,
                MVN_RBM_User__c,
                PJN_Physician__r.LastName
            FROM
                Case
            WHERE
                Id IN :carePlans
        ];
        /*
        System.assertEquals(200, carePlans.size(), 'CarePlans were not created or retrieved correctly.');
        for (Case carePlan : carePlans) {
            System.assertEquals(TERRITORY, carePlan.PJN_Territory__c);
            if (carePlan.PJN_Physician__r.LastName == 'Physician Test') {
                System.assertEquals(REGION, carePlan.PJN_Region__c);
            } else {
                System.assertEquals(REGION2, carePlan.PJN_Region__c);
            }
        }
        */
    }
}