force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Account/recordTypes/PJN_Organization.recordType-meta.xml
<RecordType>
    <fullName>PJN_Organization</fullName>
    <active>true</active>
    <description>Defines a healthcare organization where physicians and staff work</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/src/objects/PJN_Affiliation__c/PJN_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Stores the hierarchical relationship between people and organizations.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFFL-{0000000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Child_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Child_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup(Account) where account is affiliated with.</description>
    <label>Child Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Staff,PJN_Physician,PJN_Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliated To</relationshipLabel>
    <relationshipName>Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Parent_Account__c</fullName>
    <description>Master-Detail (Account) with Affiliation Members as children accounts.</description>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Members</relationshipLabel>
    <relationshipName>Affiliation1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Affiliation__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <description>External ID, unique Network ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Picklist: Correspondence label or type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>PO Box</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The address this license applies to</description>
    <label>Contact Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The address must be an address of the Account&apos;s</errorMessage>
        <filterItems>
            <field>$Source.PJN_Account__c</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>The type of license</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STATE</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>CDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/recordTypes/PJN_DEA_License.recordType-meta.xml
<RecordType>
    <fullName>PJN_DEA_License</fullName>
    <active>true</active>
    <description>A Drug Enforcement Administration license</description>
    <label>DEA License</label>
</RecordType>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>NY</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_NetworkSyncTest.cls
/**
 * Test for PJN_NetworkSync
 * @author  Mavens
 * @group   Network
 */
@IsTest
public class PJN_NetworkSyncTest {

    static {
        PJN_NetworkObjectSetting.NetworkObjectSettingsQuery = (PJN_NetworkObjectSettingsQuery) Test.createStub(PJN_NetworkObjectSettingsQuery.class, new PJN_NetworkObjectSettingsMock());
        PJN_NetworkObjectSetting.NetworkRecordTypeMappingsQuery = (PJN_NetworkRecordTypeMappingsQuery) Test.createStub(PJN_NetworkRecordTypeMappingsQuery.class, new PJN_NetworkRecordTypeMappingsMock());
        PJN_NetworkObjectSetting.NetworkFieldMappingsQuery = (PJN_NetworkFieldMappingsQuery) Test.createStub(PJN_NetworkFieldMappingsQuery.class, new PJN_NetworkFieldMappingsMock());

        PJN_NetworkStatusMapping.networkStatusMappingQuery = (PJN_NetworkStatusMappingQuery) Test.createStub(PJN_NetworkStatusMappingQuery.class, new PJN_NetworkStatusMappingMock());
    }

    @TestSetup
    static void makeData(){
        PJN_TestFactoryGlobalSetting.setMock();

        Test.startTest();
        List<Account> accounts = new List<Account>();

        accounts.add(
            new Account (
                FirstName = 'whatever',
                LastName = 'whatever',
                PJN_Veeva_Network_Id__c = '933580259012116000',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId()
            )
        );

        accounts.add(
            new Account (
                Name = 'Hospital',
                PJN_Veeva_Network_Id__c = '27112020000000001',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Organization').getRecordTypeId()
            )
        );

        insert accounts;
        Test.stopTest();
    }

    @IsTest
    static void testAccountCreatingAddressAndLicense() {
        Test.setMock(HttpCalloutMock.class, new PJN_NetworkSyncMock.RetrieveHCPSuccessMock());
        PJN_TestFactoryGlobalSetting.setMock();
        Account acc = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'PJN_Physician' LIMIT 1];

        Boolean isUpdated = false;

        Test.startTest();
        PJN_NetworkCallout.noRunInTest = false;
        PJN_NetworkSync networkSync = new PJN_NetworkSync(acc.Id);
        isUpdated = networkSync.sync();
        Test.stopTest();

        System.assert(isUpdated, 'Sync process did not updated the records');

        acc = getAccount(acc.Id);
        System.assertEquals('Daniel', acc.FirstName, 'Sync process did not update first name');
        System.assertEquals('Carter', acc.LastName, 'Sync process did not update last name');

        System.assert(!acc.PJN_Contact_Information__r.isEmpty(), 'Sync process did not create address');
        System.assertEquals('200 Park Blvd.', acc.PJN_Contact_Information__r[0].PJN_Address_Line_1__c, 'Sync process did not create address line 1');

        System.assert(!acc.PJN_Licenses__r.isEmpty(), 'Sync process did not create license');
        System.assertEquals('1256987', acc.PJN_Licenses__r[0].Name, 'Sync process did not create license number');

        System.assert(!acc.Affiliation__r.isEmpty(), 'Sync process did not create affiliation');
        System.assertEquals(1, acc.Affiliation__r.size(), 'Sync process must not create affiliations for non-existing HCOs');
        System.assertEquals('27112020000000001', acc.Affiliation__r[0].PJN_Parent_Account__r.PJN_Veeva_Network_Id__c, 'Sync process did not create affiliation');
    }

    @IsTest
    static void testAccountUpdatingAddressAndLicense() {
        Test.setMock(HttpCalloutMock.class, new PJN_NetworkSyncMock.RetrieveHCPSuccessMock());
        PJN_TestFactoryGlobalSetting.setMock();
        Account acc = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'PJN_Physician' LIMIT 1];

        createAddress(acc.Id);
        createLicense(acc.Id);

        Boolean isUpdated = false;

        Test.startTest();
        PJN_NetworkCallout.noRunInTest = false;
        PJN_NetworkSync networkSync = new PJN_NetworkSync(acc.Id);
        isUpdated = networkSync.sync();
        Test.stopTest();

        System.assert(isUpdated, 'Sync process did not updated the records');

        acc = getAccount(acc.Id);
        System.assertEquals('Daniel', acc.FirstName, 'Sync process did not update first name');
        System.assertEquals('Carter', acc.LastName, 'Sync process did not update last name');

        System.assert(!acc.PJN_Contact_Information__r.isEmpty(), 'Sync process did not create address');
        System.assertEquals('200 Park Blvd.', acc.PJN_Contact_Information__r[0].PJN_Address_Line_1__c, 'Sync process did not create address line 1');

        System.assert(!acc.PJN_Licenses__r.isEmpty(), 'Sync process did not create license');
        System.assertEquals('1256987', acc.PJN_Licenses__r[0].Name, 'Sync process did not create license number');

        System.assert(!acc.Affiliation__r.isEmpty(), 'Sync process did not create affiliation');
        System.assertEquals(1, acc.Affiliation__r.size(), 'Sync process must not create affiliations for non-existing HCOs');
        System.assertEquals('27112020000000001', acc.Affiliation__r[0].PJN_Parent_Account__r.PJN_Veeva_Network_Id__c, 'Sync process did not create affiliation');
    }

    private static Account getAccount(Id accountId) {
        return [
            SELECT
                Id,
                FirstName,
                LastName,
                (
                    SELECT
                        Id,
                        PJN_Address_Line_1__c,
                        PJN_Address_Line_2__c,
                        PJN_City__c,
                        PJN_State__c
                    FROM
                        PJN_Contact_Information__r
                ),
                (
                    SELECT
                        Id,
                        Name,
                        PJN_Type__c
                    FROM
                        PJN_Licenses__r
                ),
                (
                    SELECT
                        Id,
                        PJN_Parent_Account__c,
                        PJN_Parent_Account__r.PJN_Veeva_Network_Id__c
                    FROM
                        Affiliation__r
                )
            FROM
                Account
            WHERE
                Id = :accountId
        ];
    }

    private static void createAddress(Id accountId) {
        insert new PJN_Contact_Information__c (
            RecordTypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId(),
            PJN_Account__c = accountId,
            PJN_Address_Line_1__c = 'whatever',
            PJN_City__c = 'New York',
            PJN_State__c = 'NY',
            PJN_Country__c = 'United States',
            PJN_Veeva_Network_Id__c = '933580259012006000'
        );
    }

    private static  void createLicense(Id accountId) {
        insert new PJN_License__c (
            RecordTypeId = SObjectType.PJN_License__c.getRecordTypeInfosByDeveloperName().get('PJN_DEA_License').getRecordTypeId(),
            PJN_Account__c = accountId,
            Name = 'whatever',
            PJN_Veeva_Network_Id__c = '932910724244966000'
        );
    }
}