force-app/main/default/src/objects/Account/fields/PJN_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Address record type.</description>
    <label>Primary Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Address</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Missing_Information_Config__mdt/PJN_Missing_Information_Config__mdt.object-meta.xml
<CustomObject>
    <description>Missing Information Configuration to identify the fields with missing information in the Care Plan related.
All these configurations are applied to the Care Plan with a specific Program.</description>
    <label>Missing Information Config</label>
    <pluralLabel>Missing Information Configs</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Missing_Information_Config__mdt/fields/PJN_Field_Path__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_Path__c</fullName>
    <description>Field API name path to verify the missing information. Eg: Account.FirstName or CaseNumber</description>
    <inlineHelpText>Field API name path to verify the missing information. Eg: Account.FirstName or CaseNumber</inlineHelpText>
    <label>Field Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Missing_Information_Config__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <description>Care Plan program which applies this configuration. Eg: Evkeeza</description>
    <inlineHelpText>Care Plan program which applies this configuration. Eg: Evkeeza</inlineHelpText>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Missing Information Configs</relationshipLabel>
    <relationshipName>PJN_Missing_Information_Configs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_MissingInformationConfigMock.cls
/**
 * @author      Mavens
 * @group       MissingInformation
 * @description Mock Missing Information Config metadatas for testing
 */
@isTest(isParallel=true)
public with sharing class PJN_MissingInformationConfigMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                    String stubbedMethodName,
                                    Type returnType,
                                    List<Type> listOfParamTypes,
                                    List<String> listOfParamNames,
                                    List<Object> listOfArgs) {
        if(stubbedMethodName == 'queryMissingInfoConfigsByProgramName') {
            return this.queryMissingInfoConfigsByProgramName((String) listOfArgs[0]);
        } else if(stubbedMethodName == 'queryAllMissingInfoConfigs') {
            return this.queryAllMissingInfoConfigs();
        } else {
            return null;
        }
    }

    private Object queryMissingInfoConfigsByProgramName(String programCaseDeveloperName) {
        List<PJN_Missing_Information_Config__mdt> missingInfoConfigs = getAllMissingInfoConfigs(programCaseDeveloperName);
        return missingInfoConfigs;
    }

    private Object queryAllMissingInfoConfigs() {
        List<PJN_Missing_Information_Config__mdt> missingInfoConfigs = getAllMissingInfoConfigs('PJN_CLP');
        return missingInfoConfigs;
    }

    private static List<PJN_Missing_Information_Config__mdt> getAllMissingInfoConfigs(String programCaseDeveloperName) {
        List<PJN_Missing_Information_Config__mdt> missingInfoConfigs = new List<PJN_Missing_Information_Config__mdt>();
        missingInfoConfigs.add(
            new PJN_Missing_Information_Config__mdt(
                MasterLabel = 'Patient Name',
                DeveloperName = 'PJN_Patient_Name',
                PJN_Program__r = new PJN_Program__mdt(
                    MasterLabel = 'Mocked Program',
                    DeveloperName = programCaseDeveloperName
                ),
                PJN_Field_Path__c = 'PJN_Patient_Name__c'
            )
        );
        missingInfoConfigs.add(
            new PJN_Missing_Information_Config__mdt(
                MasterLabel = 'Patient: Address',
                DeveloperName = 'PJN_Patient_Address',
                PJN_Program__r = new PJN_Program__mdt(
                    MasterLabel = 'Mocked Program',
                    DeveloperName = programCaseDeveloperName
                ),
                PJN_Field_Path__c = 'Account.PJN_Primary_Address__c'
            )
        );
        missingInfoConfigs.add(
            new PJN_Missing_Information_Config__mdt(
                MasterLabel = 'Patient: Gender',
                DeveloperName = 'PJN_Patient_Gender',
                PJN_Program__r = new PJN_Program__mdt(
                    MasterLabel = 'Mocked Program',
                    DeveloperName = programCaseDeveloperName
                ),
                PJN_Field_Path__c = 'Account.HealthCloudGA__Gender__pc'
            )
        );
        return missingInfoConfigs;
    }
}