force-app/main/default/src/objects/Account/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Undetermined</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dead</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Rejected By Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Account/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Error__c.field-meta.xml
<CustomField>
    <fullName>PJN_Error__c</fullName>
    <description>Part of the Patient Service accelerator: Details of any errors that occurred during outbound DCR requests to Veeva Network, or inbound DCR updates from Veeva Network. Errors are cleared after DCR is successfully processed.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Details of any errors that occurred during outbound DCR requests to Veeva Network, or inbound DCR updates from Veeva Network. Errors are cleared after DCR is successfully processed.</inlineHelpText>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Data Change Request ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>External Data Change Request ID</inlineHelpText>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Sent_Datetime__c.field-meta.xml
<CustomField>
    <fullName>PJN_Sent_Datetime__c</fullName>
    <description>Part of the Patient Service accelerator: Time the record has been sent to the MDM system for approval.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Time the record has been sent to the MDM system for approval.</inlineHelpText>
    <label>Sent Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>Part of the Patient Service accelerator: local data change request status which defines what happens next with the data change request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/PJN_Data_Change_Request_Line__c.object-meta.xml
<CustomObject>
    <description>Lists all of the specific data changes that are being requested in a data change request.</description>
    <label>Data Change Request Line</label>
    <nameField>
        <displayFormat>DCRL - {000000000}</displayFormat>
        <label>DCR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Change_Request__c</fullName>
    <description>Part of the Patient Service accelerator: Parent data change request.</description>
    <label>Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/classes/PJN_DCRAccountHdlr.cls
/**
 * DCR Account create trigger handler to create DCR and Lines when an account is inserted or updated
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_DCRAccountHdlr implements PJN_TriggerDispatcher.HandlerInterface {

    private static Boolean hasRun = false;

    /**
     * handler
     */
    public void handle() {
        Boolean isAllowed = Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate) && !PJN_DCR.updateFromNetwork;

        if(!isAllowed || hasRun) {
            return;
        }

        List<PJN_Data_Change_Request__c> dcrs = new List<PJN_Data_Change_Request__c>();
        List<PJN_Data_Change_Request_Line__c> dcrLines = new List<PJN_Data_Change_Request_Line__c>();

        List<Account> accountsToUpdate = new List<Account>();

        for(Account thisAccount : (List<Account>) Trigger.new) {
            if(Trigger.isInsert && String.isNotBlank(thisAccount.PJN_Veeva_Network_Id__c)) {
                continue;
            }

            PJN_DCR dcrWrapper = new PJN_DCR(
                (Trigger.isInsert ? null : (Account) Trigger.oldMap.get(thisAccount.Id)),
                thisAccount
            );

            Boolean isAllowedToSend = dcrWrapper.dcr != null && !dcrWrapper.dcrLines.isEmpty();

            if (!isAllowedToSend) {
                continue;
            }

            dcrs.add(dcrWrapper.dcr);
            dcrLines.addAll(dcrWrapper.dcrLines);

            if (Trigger.isUpdate && dcrWrapper.revertValueByFieldName != null && !dcrWrapper.revertValueByFieldName.isEmpty()) {
                Account accountToUpdate = new Account (
                    Id = thisAccount.Id
                );
                for (String fieldName : dcrWrapper.revertValueByFieldName.keySet()) {
                    accountToUpdate.put(fieldName, dcrWrapper.revertValueByFieldName.get(fieldName));
                }

                accountsToUpdate.add(accountToUpdate);
            }
        }

        if(!dcrs.isEmpty() && !dcrLines.isEmpty()) {
            upsert dcrs PJN_External_Id__c;
            PJN_DCRCreateHelper.upsertDCRLines(dcrLines);

            Map<Id, String> errorMessageByDCRId = PJN_NetworkEventHelper.publishDCRs(dcrs);
            updateDCRsWithError(dcrs, errorMessageByDCRId);
        }

        if (!accountsToUpdate.isEmpty()) {
            hasRun = true;
            update accountsToUpdate;
        }
    }

    /**
     * Handles DCRs with error to update them to Cancelled
     * @param dcrs                  List of DCRs
     * @param errorMessageByDCRId   Map of error messages by DCR id
     */
    @testVisible
    private void updateDCRsWithError(List<PJN_Data_Change_Request__c> dcrs, Map<Id, String> errorMessageByDCRId) {
        if (errorMessageByDCRId == null || errorMessageByDCRId.isEmpty()) {
            return;
        }

        List<PJN_Data_Change_Request__c> updateDCRs = new List<PJN_Data_Change_Request__c>();

        for(PJN_Data_Change_Request__c dcr : dcrs) {
            if (!errorMessageByDCRId.containsKey(dcr.Id)) {
                continue;
            }

            dcr.PJN_Error__c = errorMessageByDCRId.get(dcr.Id);
            dcr.PJN_Status__c = PJN_NetworkConstants.DCR_STATUS_CANCELLED;
            dcr.PJN_Sent_Datetime__c = System.now();

            updateDCRs.add(dcr);
        }

        if (updateDCRs != null && !updateDCRs.isEmpty()) {
            update updateDCRs;
        }
    }
}