force-app/main/default/src/objects/Account/fields/PJN_Relay_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Relay_Phone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The phone number used for Relay Network SMS communications.</description>
    <inlineHelpText>The phone number used for Relay Network SMS communications.</inlineHelpText>
    <label>Relay Phone</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts (Relay Phone)</relationshipLabel>
    <relationshipName>PJN_Relay_Phone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Is_Relay_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Relay_Phone__c</fullName>
    <description>Indicates this record has been selected as the phone number to be used for Relay Network SMS communications.</description>
    <formula>PJN_Account__r.PJN_Relay_Phone__c == Id</formula>
    <inlineHelpText>Indicates this record has been selected as the phone number to be used for Relay Network SMS communications.</inlineHelpText>
    <label>Relay Phone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Set_as_Relay_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Relay_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true, sets this phone number as the Relay Phone on the parent Account.</description>
    <inlineHelpText>When true, sets this phone number as the Relay Phone on the parent Account.</inlineHelpText>
    <label>Set as Relay Phone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Email.recordType-meta.xml
<RecordType>
    <fullName>PJN_Email</fullName>
    <active>true</active>
    <description>Defines email contact information</description>
    <label>Email</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Phone.recordType-meta.xml
<RecordType>
    <fullName>PJN_Phone</fullName>
    <active>true</active>
    <description>Defines phone contact information</description>
    <label>Phone</label>
</RecordType>

force-app/main/default/src/objects/Relay_Network__mdt/Relay_Network__mdt.object-meta.xml
<CustomObject>
    <label>Relay Network Setting</label>
    <pluralLabel>Relay Network Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Relay_Network__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>The API key used to access the Relay APIs</description>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayApiUrl__c.field-meta.xml
<CustomField>
    <fullName>RelayApiUrl__c</fullName>
    <description>The Relay REST API endpoint URL. Relay has different endpoints for our Staging and Production environments</description>
    <label>Relay API URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/src/classes/PJN_SetRelayPhoneContactInfoTest.cls
/*
 * Unit tests for PJN_SetRelayPhoneContactInfo
 * @author  Mavens
 * @date    Oct 2021 
 * @group   Relay Network
 */
@isTest(isParallel=false)
public class PJN_SetRelayPhoneContactInfoTest {

    @TestSetup
    static void makeData(){
        List<Account> accounts = new List<Account>();
        for (Integer i=0; i<200; i++) {
            accounts.add(new Account(LastName = 'LastName' + i));
        }
        insert accounts;
    }

    static {
        Relay.testMetaData = new Relay_Network__mdt(
                Client_ID__c='sf-unit=test', 
                API_Key__c='111-222-333', 
                RelayApiUrl__c='https://sf-unit-test.relayit.com');
    }
    
    @isTest
    private static void itShouldSetRelayPhoneOnInsert() {
        List<Account> accounts = [SELECT Id FROM Account];
        List<PJN_Contact_Information__c> phones = new List<PJN_Contact_Information__c>();

        for (Account acct : accounts) {
            phones.add(
                new PJN_Contact_Information__c(
                    RecordTypeId = SObjectType.PJN_Contact_Information__c
                        .getRecordTypeInfosByDeveloperName()
                        .get('PJN_Phone')
                        .getRecordTypeId(),
                    PJN_Account__c = acct.Id,
                    PJN_Set_As_Relay_Phone__c = true
                )
            );
        }

        Test.startTest();
        insert phones;
        Test.stopTest();

        System.assertEquals(200, [SELECT COUNT() FROM Account WHERE PJN_Relay_Phone__c IN :phones]);
        System.assertEquals(200,
            [SELECT COUNT()
            FROM PJN_Contact_Information__c
            WHERE PJN_Set_as_Relay_Phone__c = false
            AND PJN_Is_Relay_Phone__c = true
        ]);
    }

    @isTest
    private static void itShouldSetRelayPhoneOnUpdate() {
        List<Account> accounts = [SELECT Id FROM Account];
        List<PJN_Contact_Information__c> phones = new List<PJN_Contact_Information__c>();

        for (Account acct : accounts) {
            phones.add(
                new PJN_Contact_Information__c(
                    RecordTypeId = SObjectType.PJN_Contact_Information__c
                        .getRecordTypeInfosByDeveloperName()
                        .get('PJN_Phone')
                        .getRecordTypeId(),
                    PJN_Account__c = acct.Id,
                    PJN_Set_As_Relay_Phone__c = false
                )
            );
        }
        insert phones;

        for (PJN_Contact_Information__c phone : phones) {
            phone.PJN_Set_As_Relay_Phone__c = true;
        }

        Test.startTest();
        update phones;
        Test.stopTest();

        System.assertEquals(200, [SELECT COUNT() FROM Account WHERE PJN_Relay_Phone__c IN :phones]);
        System.assertEquals(200,
            [SELECT COUNT()
            FROM PJN_Contact_Information__c
            WHERE PJN_Set_as_Relay_Phone__c = false
            AND PJN_Is_Relay_Phone__c = true
        ]);
    }

    @isTest
    private static void itShouldErrorIfNotPhone() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        PJN_Contact_Information__c contactInfo = new PJN_Contact_Information__c(
                    RecordTypeId = SObjectType.PJN_Contact_Information__c
                        .getRecordTypeInfosByDeveloperName()
                        .get('PJN_Email')
                        .getRecordTypeId(),
                    PJN_Account__c = account.Id,
                    PJN_Set_As_Relay_Phone__c = true
                );

        Exception caughtException;
        Test.startTest();
            try {
                insert contactInfo;
            } catch(Exception ex) {
                caughtException = ex;
            }
        Test.stopTest();

        System.assertNotEquals(null, caughtException, 'No error caught');
        System.assert(caughtException.getMessage().contains(PJN_SetRelayPhoneContactInfo.notPhoneRelayError), 'Incorrect error message');
        
    }
}