force-app/main/default/src/objects/Account/fields/PJN_Primary_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup (Contact Information) filtered on the Address record type.</description>
    <label>Primary Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Contact_Information__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Address</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>PJN_Contact_Information__c.PJN_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/CareProgramProduct/fields/PJN_NDC__c.field-meta.xml
<CustomField>
    <fullName>PJN_NDC__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>NDC code of the therapeutic product.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NDC</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/CareProgramProduct/fields/PJN_Program_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Developer_Name__c</fullName>
    <description>Program Developer Name that this product is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Enrollment_Completed__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enrollment Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Physician__c.field-meta.xml
<CustomField>
    <fullName>PJN_Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s care plan physician account.</description>
    <label>Physician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PJN_Physician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Physician)</relationshipLabel>
    <relationshipName>CasesPhysician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/MVN_Missing_Information.recordType-meta.xml
<RecordType>
    <fullName>MVN_Missing_Information</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines missing enrollment information activities related to a patient&apos;s care plan</description>
    <label>Missing Information</label>
</RecordType>

force-app/main/default/src/objects/HealthCloudGA__ReciprocalRole__c/HealthCloudGA__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Case_Field_Configuration__mdt/PJN_Case_Field_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search (Select Account); Case Team Member assignation
Purpose: For the Account Search on a Case, when selecting a related Account, depending on the account record type that relationship must be stored in a specific field on the Case, which this CMT record defines. For the Case Team Member assignation, this CMT also defines the case team role given to that Account on the Case Team and the reciprocal and inverse roles if required.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Case Field Configuration</label>
    <pluralLabel>Case Field Configurations</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Case_Field_Configuration__mdt/fields/PJN_Case_Team_Role_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Case_Team_Role_Mapping__c</fullName>
    <description>The case team role this field maps to. Used by CaseCareTeamManager.cls trigger handler</description>
    <label>Case Team Role Mapping</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_CaseMissingInformationCtrlTest.cls
/**
 * @author      Mavens
 * @group       MissingInformation
 * @description Test for PJN_CaseMissingInformationCtrl
 */
@IsTest
private class PJN_CaseMissingInformationCtrlTest {

    static {
        PJN_CarePlanMissingInformationHdlr.missingInformationQuery = (PJN_MissingInformationConfigQuery) Test.createStub(PJN_MissingInformationConfigQuery.class, new PJN_MissingInformationConfigMock());
        PJN_CarePlanMissingInformationHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_MappingEngine.mappingJobQuery = (PJN_MappingJobQuery) Test.createStub(PJN_MappingJobQuery.class, new PJN_MappingJobMock());
        PJN_CarePlanProblemHdlr.programProblemQuery = (PJN_ProgramProblemQuery) Test.createStub(PJN_ProgramProblemQuery.class, new PJN_ProgramProblemMock());
        PJN_ProgramCase.programCaseQuery = (PJN_ProgramCaseQuery) Test.createStub(PJN_ProgramCaseQuery.class, new PJN_ProgramCaseMock());
        PJN_CaseMissingInformationCtrl.missingInformationConfigQuery = (PJN_MissingInformationConfigQuery) Test.createStub(PJN_MissingInformationConfigQuery.class, new PJN_MissingInformationConfigMock());
    }

    @TestSetup
    static void makeData(){
        Test.startTest();
        CareProgram program = new CareProgram(
            Name = 'Test Program',
            PJN_Program_DeveloperName__c = 'PJN_CLP',
            StartDate = Date.today()
        );
        insert program;
        CareProgramProduct product = new CareProgramProduct(
            CareProgramId = program.Id,
            PJN_Program_Developer_Name__c = 'PJN_CLP',
            PJN_NDC__c = '1234567890',
            Name = 'Test Product'
        );
        insert product;
        Account patient = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId(),
            LastName = 'Test Patient'
        );
        Account physician = new Account(
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId(),
            LastName = 'Test Physician'
        );
        insert new List<Account> {patient, physician};
        Case carePlan = new Case (
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            Status = 'Test',
            Subject = 'Care Plan',
            AccountId = patient.Id,
            PJN_Physician__c = physician.Id,
            PJN_Program_DeveloperName__c = 'PJN_CLP',
            PJN_Program__c = program.Id
        );
        insert carePlan;

        insert new Case (
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('MVN_Missing_Information').getRecordTypeId(),
            ParentId = carePlan.Id,
            PJN_Program__c = program.Id
        );

        List<PJN_Case_Field_Configuration__mdt> configList = new PJN_TestFactoryCaseFieldConfiguration().createCaseFieldsConfigurationDefaulted();
        List<CaseTeamRole> caseTeamRoleList = new List<CaseTeamRole>();
        for (PJN_Case_Field_Configuration__mdt config : configList) {
            caseTeamRoleList.add(
                new CaseTeamRole(
                    Name = config.PJN_Case_Team_Role_Mapping__c,
                    AccessLevel = 'Read'
                )
            );
        }
        Database.insert(caseTeamRoleList, false);

        HealthCloudGA__ReciprocalRole__c healthCloudRole = new HealthCloudGA__ReciprocalRole__c(
            Name='Patient',
            HealthCloudGA__InverseRole__c='Caregiver',
            RecordTypeId=SObjectType.HealthCloudGA__ReciprocalRole__c.getRecordTypeInfosByName().get('Contact Role').getRecordTypeId()
        );
        insert healthCloudRole;
        Test.stopTest();
    }

    @IsTest
    static void testIfGetMissingInfoFields() {
        Case missingInfoActivity = getMissingInfoActivity();
        List<String> missingInfoFields;
        Test.startTest();
        missingInfoFields = PJN_CaseMissingInformationCtrl.getMissingInformationFields(missingInfoActivity.Id);
        Test.stopTest();
        System.assertNotEquals(null, missingInfoFields, 'Care Plan Id is null for the method.');
        System.assert(!missingInfoFields.isEmpty(), 'No missing info fields found.');
        System.assertEquals(2, missingInfoFields.size(), 'Missing info fields must include patient address and gender only.');
    }

    @IsTest
    static void testIfGetMissingInfoFieldsNoResults() {
        Account patient = getPatient();
        patient.HealthCloudGA__Gender__pc = 'Female';
        patient.PJN_Primary_Address__c = createAddress(patient.Id);
        update patient;
        Case missingInfoActivity = getMissingInfoActivity();
        List<String> missingInfoFields;
        Test.startTest();
        missingInfoFields = PJN_CaseMissingInformationCtrl.getMissingInformationFields(missingInfoActivity.Id);
        Test.stopTest();
        System.assertNotEquals(null, missingInfoFields, 'Care Plan Id is null for the method.');
        System.assert(missingInfoFields.isEmpty(), 'There should not be any missing info field.');
    }

    private static Account getPatient() {
        return [
            SELECT
                Id,
                HealthCloudGA__Gender__pc,
                PJN_Primary_Address__c
            FROM
                Account
            WHERE
                RecordType.DeveloperName = 'PJN_Patient'
            LIMIT 1
        ];
    }

    private static Id createAddress(Id patientId) {
        PJN_Contact_Information__c ci = new PJN_Contact_Information__c(
            PJN_Account__c = patientId,
            PJN_Address_Line_1__c = 'Main Street 123',
            PJN_City__c = 'Chicago',
            PJN_Postal_Code__c = '60606',
            PJN_State__c = 'IL',
            PJN_Country__c = 'United States'
        );
        insert ci;
        return ci.Id;
    }

    private static List<Case> getCarePlans() {
        return [
            SELECT
                Id,
                Status,
                Subject,
                AccountId,
                PJN_Physician__c,
                PJN_Program_DeveloperName__c,
                PJN_Program__c,
                PJN_Enrollment_Completed__c
            FROM
                Case
            WHERE
                RecordType.DeveloperName = 'CarePlan'
        ];
    }

    private static Case getMissingInfoActivity() {
        return [
            SELECT
                Id,
                ParentId,
                PJN_Program_DeveloperName__c,
                PJN_Program__c
            FROM
                Case
            WHERE
                RecordType.DeveloperName = 'MVN_Missing_Information'
            LIMIT 1
        ];
    }
}