force-app/main/default/src/objects/Account/fields/RelayCCID__c.field-meta.xml
<CustomField>
    <fullName>RelayCCID__c</fullName>
    <description>The Relay CCID uniquely identifies a single Customer (end user) within the Relay platform. Every Relay Customer must have a unique CCID value. The Relay CCID value should never change for the life of the Customer.</description>
    <formula>CASESAFEID( Id )</formula>
    <inlineHelpText>The Relay CCID uniquely identifies a single Customer (end user) within the Relay platform.</inlineHelpText>
    <label>Relay CCID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/Relay_Network__mdt.object-meta.xml
<CustomObject>
    <label>Relay Network Setting</label>
    <pluralLabel>Relay Network Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableAccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableAccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable all Account trigger logic from running</description>
    <inlineHelpText>If checked (disabled), all Relay Account trigger logic will be disabled.</inlineHelpText>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableEventConsentTrigger__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableEventConsentTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Relay Event Trigger from updating Accounts when a Consent change event is received</description>
    <inlineHelpText>If checked (disabled), this trigger will not update TCPA consent data on Account or Contact objects.</inlineHelpText>
    <label>Disable TCPA Consent Processing Logic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayDisableTaskEventing__c.field-meta.xml
<CustomField>
    <fullName>RelayDisableTaskEventing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable events from being emitted when a call task is created.</description>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsAccountCCIDFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsAccountCCIDFieldName__c</fullName>
    <description>The filed name in the Account object that contains the Relay CCID</description>
    <inlineHelpText>The filed name in the Account object that contains the Relay CCID</inlineHelpText>
    <label>Account CCID Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsContactCCIDFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsContactCCIDFieldName__c</fullName>
    <description>The field name in the Contact object that contains the Relay CCID.</description>
    <inlineHelpText>The field name in the Contact object that contains the Relay CCID. If the Conact object does not need to contain the Relay CCID, then this can be left blank</inlineHelpText>
    <label>Contact CCID Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsDisableAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsDisableAccountLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the lookup of the Account reference object</description>
    <label>Disable Account Ref Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayEventsDisableContactLookup__c.field-meta.xml
<CustomField>
    <fullName>RelayEventsDisableContactLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the lookup of the Contact reference object</description>
    <label>Disable Contact Ref Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Relay_Network__mdt/fields/RelayMobilePhoneFieldName__c.field-meta.xml
<CustomField>
    <fullName>RelayMobilePhoneFieldName__c</fullName>
    <description>The Account field name that contains the mobile phone number</description>
    <inlineHelpText>The filed name in the Account object that contains the mobile number. If left blank, it defaults to MobilePhone</inlineHelpText>
    <label>Account Mobile Phone Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/RelayEvents__c.object-meta.xml
<CustomObject>
    <label>Relay Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relay Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/RelayEvents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relay Events</relationshipLabel>
    <relationshipName>Relay_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/ChannelAddr__c.field-meta.xml
<CustomField>
    <fullName>ChannelAddr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Channel Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/ClientMessageTag__c.field-meta.xml
<CustomField>
    <fullName>ClientMessageTag__c</fullName>
    <description>An optional, Client, value that was initially provided during a Messaging API call.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Message Tag</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relay Events</relationshipLabel>
    <relationshipName>Relay_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventSubType__c.field-meta.xml
<CustomField>
    <fullName>EventSubType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventTimestamp__c.field-meta.xml
<CustomField>
    <fullName>EventTimestamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/RelayEvents__c/fields/TriggerID__c.field-meta.xml
<CustomField>
    <fullName>TriggerID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trigger ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/TestRelayEventTrigger.cls
@isTest
public class TestRelayEventTrigger {

    static testMethod void TestPopulatingContactRef() {

        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c='Id',
                RelayEventsContactCCIDFieldName__c='Id',
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

        Contact newContact = new Contact(FirstName='Test', LastName='Coverage',  MobilePhone='1005551212');
        insert newContact;
        RelayEvents__c event = new RelayEvents__c(Name='notification_delivered', RelayCCID__c=newContact.Id);        
        insert event;        
        RelayEvents__c event2 = [SELECT Contact__c from RelayEvents__c where Id = :event.Id];

        System.assert(event2.Contact__c == newContact.Id); // Ensure the Contact__c ref was properly updated
    }

    static testMethod void TestPopulatingBatchContactRef() {

        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c='Id',
                RelayEventsContactCCIDFieldName__c='Id',
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

        List<Contact> contacts = new List<Contact>();
        contacts.add( new Contact(FirstName='Test1', LastName='Coverage',  MobilePhone='1-100-555-1111'));
        contacts.add( new Contact(FirstName='Test2', LastName='Coverage',  MobilePhone='100-555-2222'));
        insert contacts;
        List<RelayEvents__c> events = new List<RelayEvents__c>();
        events.add( new RelayEvents__c(Name='notification_delivered', RelayCCID__c=contacts[0].Id));
        events.add( new RelayEvents__c(Name='notification_delivered', RelayCCID__c=contacts[1].Id));
        insert events;
        List<RelayEvents__c> eventsPost = [SELECT Contact__c from RelayEvents__c where Id in (:events[0].Id, :events[1].Id)];

        System.assert(eventsPost.size() == 2);
        System.assert(eventsPost[0].Contact__c != null); // Ensure the Contact__c ref was properly updated
        System.assert(eventsPost[1].Contact__c != null); // Ensure the Contact__c ref was properly updated
    }

    static testMethod void TestNotPopulatingContactRef() {

        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c=null,
                RelayEventsContactCCIDFieldName__c=null,
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

        Contact newContact = new Contact(FirstName='Test', LastName='Coverage',  MobilePhone='1005551212');
        insert newContact;
        RelayEvents__c event = new RelayEvents__c(Name='notification_delivered', RelayCCID__c=newContact.Id);        
        insert event;        
        RelayEvents__c event2 = [SELECT Contact__c from RelayEvents__c where Id = :event.Id];

        System.assert(event2.Contact__c == null); // Ensure the Contact__c ref was properly updated
    }

    static testMethod void TestPopulatingAccountRef() {

        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c='Id',
                RelayEventsContactCCIDFieldName__c='Id',
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

        Account account = new Account(Name='Unit Test', AccountNumber='unit-test');
        insert account;
        RelayEvents__c event = new RelayEvents__c(Name='notification_delivered', RelayCCID__c=account.Id);        
        insert event;
        RelayEvents__c event2 = [SELECT Account__c from RelayEvents__c where Id = :event.Id];
        
        System.assert(event2.Account__c == account.Id);
    }

    static testMethod void TestPopulatingBatchAccountRef() {

        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c='Id',
                RelayEventsContactCCIDFieldName__c='Id',
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

        List<Account> accounts = new List<Account>();
        accounts.add( new Account(Name='Unit Test 2', AccountNumber='unit-test-1') );
        accounts.add( new Account(Name='Unit Test 2', AccountNumber='unit-test-2') );
        insert accounts;

        List<RelayEvents__c> events = new List<RelayEvents__c>();
        events.add( new RelayEvents__c(Name='notification_delivered', RelayCCID__c=accounts[0].Id));
        events.add( new RelayEvents__c(Name='notification_delivered', RelayCCID__c=accounts[1].Id));
        insert events;

        // let's see if they RelayEvents__c trigger updated the Account references
        List<RelayEvents__c> eventsPost = [SELECT Account__c from RelayEvents__c where Id in (:events[0].Id, :events[1].Id)];
        
        System.assert(eventsPost.size() == 2);
        System.assert(eventsPost[0].Account__c != null);
        System.assert(eventsPost[1].Account__c != null);
    }

    static testMethod void TestNotPopulatingAccountRef() {

        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c=null,
                RelayEventsContactCCIDFieldName__c=null,
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

        Account account = new Account(Name='Unit Test', AccountNumber='unit-test');
        insert account;
        RelayEvents__c event = new RelayEvents__c(Name='notification_delivered', RelayCCID__c=account.Id);        
        insert event;
        RelayEvents__c event2 = [SELECT Account__c from RelayEvents__c where Id = :event.Id];
        
        System.assert(event2.Account__c == null);
    }

    static testMethod void TestConsentUpdates() {
        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c='Id',
                RelayEventsContactCCIDFieldName__c='Id',
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);

          RelayEvents__c event = new RelayEvents__c(Name='channel_consent', EventType__c='channel_consent', EventSubType__c='update', ChannelAddr__c='11005551212', RelayCCID__c='1001');
          insert event;
    }

    static testMethod void TestRelayEventTrigger_Bulkified() {
        Relay.testMetaData = new Relay_Network__mdt(
                RelayDisableEventConsentTrigger__c=false,
                RelayEventsAccountCCIDFieldName__c='Id',
                RelayEventsContactCCIDFieldName__c='Id',
                RelayEventsDisableContactLookup__c=false, 
                RelayEventsDisableAccountLookup__c=false, 
                RelayMobilePhoneFieldName__c='Phone', 
                RelayDisableAccountTrigger__c=false, 
                RelayDisableTaskEventing__c=false);
                
        Datetime dt = Datetime.now();
        List<RelayEvents__c> evts = new List<RelayEvents__c>();
        RelayEvents__c re = new RelayEvents__c(
            Name='Test Trigger 1',
            RelayCCID__c = '3445',
            EventType__c = 'journey_trigger',
            EventTimestamp__c = dt,
            ClientMessageTag__c = '5003j00001rxqH4AAI',
            TriggerID__c = '00000000-0000-0000-0000-000000000000',
            TriggerNickname__c = 'n/a'
        );
        evts.add(re);
        re = new RelayEvents__c(
            Name='Test Trigger 2',        
            RelayCCID__c = '3445',
            EventType__c = 'journey_trigger',
            EventSubtype__c = 'action_test-trigger',
            EventTimestamp__c = dt,
            ClientMessageTag__c = '5003j00001dplmCAAQ',	// case id
            TriggerID__c = '00000000-0000-0000-0000-000000000000',
            TriggerNickname__c = 'n/a'
        );
        evts.add(re);
        insert evts;
    }
}