force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Parent Account which this License belongs to</description>
    <inlineHelpText>Parent Account which this License belongs to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>PJN_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/classes/PJN_TestFactoryLicense.cls
@isTest(isParallel=true) public class PJN_TestFactoryLicense {
    private class PJN_LicenseException extends Exception {}
    private PJN_TestFactorySObject objectFactory;

    public PJN_TestFactoryLicense() {
        objectFactory = new PJN_TestFactorySObject('PJN_License__c', new Map<String, Object>());
    }

    public PJN_License__c constructLicense(Map<String,Object> valuesByField) {
        return (PJN_License__c) objectFactory.constructSObject(valuesByField);
    }

    public List<PJN_License__c> constructManyLicense(Map<String,Object> valuesByField, Integer numberOfRecords, List<Id> accountIds) {
        List<PJN_License__c> addresses = new List<PJN_License__c>();
        if(!accountIds.isEmpty() && accountIds.size() != 1 && numberOfRecords != accountIds.size()) {
            throw new PJN_LicenseException('Number of Licenses does not match number of account ids passed.');
        }

        for (Integer index = 0; index < numberOfRecords; index++) {

            Map<String,Object> newValuesByField = valuesByField;
            if(!accountIds.isEmpty() && accountIds.size() == 1) {
                newValuesByField.put('PJN_Account__c', accountIds[0]);
            } else if(!accountIds.isEmpty() && accountIds.size() > 1) {
                newValuesByField.put('PJN_Account__c', accountIds[index]);
            }

            addresses.add(constructLicense(newValuesByField));
        }

        return addresses;
    }

    public PJN_License__c createLicense(Map<String,Object> valuesByField) {
        return (PJN_License__c) objectFactory.createSObject(valuesByField);
    }
}