force-app/main/default/src/objects/PJN_License__c/PJN_License__c.object-meta.xml
<CustomObject>
    <description>License for Physicians which includes DEA, SLN, etc. This Object allows connection with Veeva Network Licenses.</description>
    <label>License</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Expiration_Date__c</fullName>
    <description>The license&apos;s expiration date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The license&apos;s expiration date</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Licensing_Authority__c.field-meta.xml
<CustomField>
    <fullName>PJN_Licensing_Authority__c</fullName>
    <description>The licensing authority for this license. For DEA license, this is DEA. For a State license, this is the specific state.</description>
    <label>Licensing Authority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEA</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Status__c</fullName>
    <description>The status of the license</description>
    <inlineHelpText>The status of the license</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>The type of license</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STATE</fullName>
            </value>
            <value>
                <fullName>ADDRESS</fullName>
            </value>
            <value>
                <fullName>CDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_License__c/recordTypes/PJN_State_License_Number.recordType-meta.xml
<RecordType>
    <fullName>PJN_State_License_Number</fullName>
    <active>true</active>
    <description>An Physicians State License Number</description>
    <label>State License Number</label>
</RecordType>

force-app/main/default/src/classes/MVN_DataLakeCMLicense.cls
/**
 * @author      Mavens
 * @group       DataLake
 * @description Wrapper for the MVN_DataLakeCMLicense License DataLake Object
 */
public with sharing class MVN_DataLakeCMLicense {

    /**
     * Datalake HCP License objects
     */
    public String hcp_license_id;
    public String hcp_license_state_license_num;
    public Date hcp_license_expiration_date;
    public String hcp_license_state_cd;
    public String hcp_license_status;
    public String hcp_license_hcp_id;

    /**
     * Get SFDC Record using the wrapper parameters obtained from the search
     * @return  `PJN_License__c`
     */
    public PJN_License__c getSFDCRecord() {
        return new PJN_License__c(
            RecordTypeId = Schema.SObjectType.PJN_License__c.getRecordTypeInfosByDeveloperName().get('PJN_State_License_Number').getRecordTypeId(),
            MVN_External_Id__c = this.hcp_license_id,
            Name = this.hcp_license_state_license_num,
            PJN_Expiration_Date__c = this.hcp_license_expiration_date,
            PJN_Licensing_Authority__c = this.hcp_license_state_cd,
            PJN_Type__c = 'STATE',
            PJN_Status__c = MVN_DataLakeCMSearchUtil.getStatusFromMapped(this.hcp_license_status)
        );
    }
}