force-app/main/default/src/objects/PJN_Enrollment_Wizard_Record_Form__mdt/PJN_Enrollment_Wizard_Record_Form__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Enrollment Wizard
Purpose: Define the object to be presented on the Enrollment Wizard Form component. This is step 4 in setting up the Enrollment Wizard.
Metadata Relationship(s): Enrollment Wizard Component
Created by Mavens: Yes</description>
    <label>Enrollment Wizard Record Form</label>
    <pluralLabel>Enrollment Wizard Record Forms</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Record_Form__mdt/fields/PJN_Care_Plan_Lookup_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan_Lookup_Field_API_Name__c</fullName>
    <label>Care Plan Lookup Field API Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Record_Form__mdt/fields/PJN_Edit_Care_Plan_Record_Form__c.field-meta.xml
<CustomField>
    <fullName>PJN_Edit_Care_Plan_Record_Form__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tells if the form is defined to edit current care plan record</description>
    <inlineHelpText>Tells if the form is defined to edit current care plan record</inlineHelpText>
    <label>Edit Care Plan Record Form</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Record_Form__mdt/fields/PJN_Enrollment_Wizard_Component__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Wizard_Component__c</fullName>
    <label>Enrollment Wizard Component</label>
    <referenceTo>PJN_Enrollment_Wizard_Component__mdt</referenceTo>
    <relationshipLabel>Enrollment Wizard Record Forms</relationshipLabel>
    <relationshipName>PJN_Enrollment_Wizard_Record_Forms</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Record_Form__mdt/fields/PJN_RecordType_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_RecordType_DeveloperName__c</fullName>
    <label>RecordType DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_EnrollmentWizardRecordFormQuery.cls
/**
 * @author Mavens
 * @date Mar 2019
 * @description Class to query custom metadata types for PJN_Enrollment_Wizard_Record_Form__mdt
 * @group EnrollmentWizard
 */
public with sharing class PJN_EnrollmentWizardRecordFormQuery {
    /**
     * Query enrollment wizard record form by enrollment wizard component id
     * @param   componentSettingId   enrollment wizard component id
     * @returns                       PJN_Enrollment_Wizard_Record_Form__mdt
     */
    public PJN_Enrollment_Wizard_Record_Form__mdt getEnrollmentWizardRecordForm(Id componentSettingId) {
        return [
            SELECT
                Id,
                Label,
                DeveloperName,
                PJN_SObject_API_Name__c,
                PJN_RecordType_DeveloperName__c,
                PJN_Care_Plan_Lookup_Field_API_Name__c,
                PJN_Edit_Care_Plan_Record_Form__c
            FROM
                PJN_Enrollment_Wizard_Record_Form__mdt
            WHERE
                PJN_Enrollment_Wizard_Component__c = :componentSettingId
            LIMIT 1
        ];
    }
}