force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/classes/PJN_TriggerHandlerSettingQuery.cls
/**
 * @author      Mavens
 * @group       PJN_TriggerDispatcher
 * @description class to query trigger handler settings
 */
public with sharing class PJN_TriggerHandlerSettingQuery {
    /**
     * trigger handler settings map by sObject type
     */
    @TestVisible
    private static Map<SObjectType, List<PJN_Trigger_Handler_Setting__mdt>> triggerHandlerSettingBySObjectType = new Map<SObjectType, List<PJN_Trigger_Handler_Setting__mdt>>();

    /**
     * query trigger handler setting by sObject type
     * @param   SObjectType         thisSObjectType
     * @returns  List<PJN_Trigger_Handler_Setting__mdt>
     */
    public List<PJN_Trigger_Handler_Setting__mdt> queryBySObjectType(SObjectType thisSObjectType) {
        if(!triggerHandlerSettingBySObjectType.containsKey(thisSObjectType)) {
            triggerHandlerSettingBySObjectType.put(
                thisSObjectType,
                [
                    SELECT
                        Id,
                        DeveloperName,
                        PJN_Class__c,
                        PJN_Event__c,
                        PJN_Order__c
                    FROM
                        PJN_Trigger_Handler_Setting__mdt
                    WHERE
                        PJN_SObject_API_Name__c = :thisSObjectType.getDescribe().getName()
                    AND
                        PJN_Active__c = true
                    ORDER BY
                        PJN_Order__c ASC
                ]
            );
        }
        return triggerHandlerSettingBySObjectType.get(thisSObjectType);
    }
}