force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Milestone__c.field-meta.xml
<CustomField>
    <fullName>MVN_Milestone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Milestone_Active__c.field-meta.xml
<CustomField>
    <fullName>MVN_Milestone_Active__c</fullName>
    <description>Patient journey milestone for Status = Active</description>
    <formula>CASE(PJN_New_Therapy_Status__c, &quot;Active&quot;,
CASE(PJN_New_Therapy_Sub_Status__c,
&quot;Treatment Confirmed&quot;, &quot;OB&quot;,
&quot;Patient Support&quot;, &quot;OB&quot;,
&quot;Prescriber Support&quot;, &quot;OB&quot;,
&quot;Transfer to SP IAP&quot;, &quot;OB&quot;,
&quot;Transfer to SP PAP&quot;, &quot;OB&quot;,
&quot;Prior Authorization Support Start&quot;, &quot;OB&quot;,
&quot;Prior Authorization Approved&quot;, &quot;OB&quot;,
&quot;Prior Authorization Denied&quot;, &quot;OB&quot;,
&quot;Appeal Support (1st Level)&quot;, &quot;OB&quot;,
&quot;Appeal Support (2nd Level)&quot;, &quot;OB&quot;,
&quot;Appeal Support (3rd Level)&quot;, &quot;OB&quot;,
&quot;Appeal Support (Peer-to-Peer)&quot;, &quot;OB&quot;,
&quot;Appeal Approved&quot;, &quot;OB&quot;,
&quot;Appeal Denied&quot;, &quot;OB&quot;,
&quot;PA/Appeal Support Max Attempts&quot;, &quot;OB&quot;,
&quot;Claims Support&quot;, &quot;OB&quot;,
&quot;Copay Support&quot;, &quot;OB&quot;,
null),
null)</formula>
    <label>Milestone - Active</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status_Code__c</fullName>
    <description>Patient status codes</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status_Description__c</fullName>
    <description>Regeneron Status Description</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Status_Description_Active__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status_Description_Active__c</fullName>
    <description>Status Description for Status = Active</description>
    <formula>CASE(PJN_New_Therapy_Status__c, &quot;Active&quot;,
CASE(PJN_New_Therapy_Sub_Status__c,
&quot;Treatment Confirmed&quot;, &quot;MyRare has confirmed that patient received treatment&quot;,
&quot;Patient Support&quot;, &quot;Hub provided support to patient&quot;,
&quot;Prescriber Support&quot;, &quot;Hub provided support to prescriber&quot;, 
&quot;Transfer to SP IAP&quot;, &quot;Hub triaged IAP dispense to SP&quot;,
&quot;Transfer to SP PAP&quot;, &quot;Hub triaged PAP dispense to SP&quot;, 
&quot;Prior Authorization Support Start&quot;, &quot;PA support by Hub&quot;, 
&quot;Prior Authorization Approved&quot;, &quot;PA was approved by payor&quot;, 
&quot;Prior Authorization Denied&quot;, &quot;PA was denied by payor&quot;, 
&quot;Appeal Support (1st Level)&quot;, &quot;PA was denied, Hub providing 1st Level support&quot;,
&quot;Appeal Support (2nd Level)&quot;, &quot;PA was denied, Hub providing 2nd Level support&quot;,
&quot;Appeal Support (3rd Level)&quot;, &quot;PA was denied, Hub providing 3rd Level support&quot;,
&quot;Appeal Support (Peer-to-Peer)&quot;, &quot;PA was denied, Peer-to-Peer review&quot;,
&quot;Appeal Approved&quot;, &quot;PA Appeal approved by payor&quot;,
&quot;Appeal Denied&quot;, &quot;PA Appeal denied by payor&quot;, 
&quot;PA/Appeal Support Max Attempts&quot;, &quot;PA/Appeal support has exhausted the maximum number of attempts&quot;,
&quot;Claims Support&quot;, &quot;HCP Claims Support&quot;, 
&quot;Copay Support&quot;, &quot;Patient Copay Support&quot;,
null),
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Description - Active</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Status_Description_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status_Description_Cancelled__c</fullName>
    <description>Status Description for Status = Cancelled</description>
    <formula>CASE(PJN_New_Therapy_Status__c, &quot;Cancelled&quot;,
CASE(PJN_New_Therapy_Sub_Status__c,
&quot;Missing Information, Max Attempts&quot;,&quot;Missing information required to complete enrollment, max attempts to patient, prescriber and/or RBM&quot;,
&quot;Indication Criteria Not Met&quot;,&quot;ICD Code, Indication Confirmation or Underaged  - not eligible to start&quot;, 
&quot;Requirement Not Met - Patient Residency&quot;,&quot;Patient does not reside in the United States or territories&quot;,
&quot;Requirement Not Met - Prescriber License&quot;,&quot;Prescriber is not licensed to prescribe medication in the United States or territories&quot;,
&quot;Unable to reach Patient on required contact, Max Attempts&quot;,&quot;Maximum attempts exhausted for contacting patient&quot;,
&quot;Unable to reach Prescriber on required contact, Max Attempts&quot;,&quot;Maximum attempts exhausted for contacting prescriber&quot;,
&quot;Patient Decision - Alternate Therapy&quot;,&quot;Patient on alternate treatment therapy&quot;,
&quot;Patient Decision - Financial&quot;,&quot;Patient unable to afford out of pocket expense&quot;,
&quot;Patient Decision - Other&quot;,&quot;Patient unwilling to started treatment, other&quot;,
&quot;Prescriber Decision - Alternate Therapy&quot;,&quot;Patient on alternate treatment therapy&quot;,
&quot;Prescriber Decision - Financial&quot;	,&quot;Patient unable to afford out of pocket expense&quot;,
&quot;Prescriber Decision - Coverage Effort&quot;,&quot;Prescriber not willing to purse treatment due to payor hurdles&quot;,
&quot;Prescriber Decision - Other&quot;,&quot;Patient unwilling to started treatment, other&quot;,
&quot;Patient Medical Delay, Max Delay&quot;,&quot;Hospitalization, LTC, and other medical reason a patient could not start treatment&quot;,
&quot;No Route of Access&quot;,&quot;Appeal options exhausted and over criteria for PAP&quot;,
&quot;Patient Deceased&quot;,&quot;Patient deceased&quot;,
&quot;Other&quot;,&quot;Other&quot;,
&quot;Clinical Trial&quot;,&quot;Patient is entering a clinical trial for a different medication&quot;,
&quot;No coverage: Appeals exhausted and PAP ineligible&quot;,&quot;Replaces No Route of Access sub status - Appeal options exhausted and over income criteria for PAP&quot;,
&quot;Patient does not want infusion&quot;,&quot;Patient does not want infusion&quot;,
&quot;Administration Barrier&quot;,&quot;Could not locate vein access to infuse patient&quot;,
null),
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Description - Cancelled</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Status_Description_Discontinued__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status_Description_Discontinued__c</fullName>
    <description>Status Description for Status = Discontinued</description>
    <formula>CASE(PJN_New_Therapy_Status__c, &quot;Discontinued&quot;,
CASE(PJN_New_Therapy_Sub_Status__c,
&quot;Requirement Not Met - Patient Residency&quot;,&quot;Patient does not reside in the United States or territories&quot;,
&quot;Unable to reach Patient on required contact, Max Attempts&quot;,&quot;Maximum attempts exhausted for contacting patient&quot;,
&quot;Unable to reach Prescriber on required contact, Max Attempts&quot;,&quot;Maximum attempts exhausted for contacting prescriber&quot;,
&quot;Patient Decision - Alternate Therapy&quot;,&quot;Patient on alternate treatment therapy&quot;,
&quot;Patient Decision - Financial&quot;,&quot;Patient unable to afford out of pocket expense&quot;,
&quot;Patient Decision - MyRare Only&quot;,&quot;Patient has opted out of patient support services, but still on treatment&quot;,
&quot;Patient Decision - Other&quot;,&quot;Patient unwilling to started treatment, other&quot;,
&quot;Prescriber Decision - Alternate Therapy&quot;,&quot;Patient on alternate treatment therapy&quot;,
&quot;Prescriber Decision - Financial&quot;,&quot;Patient unable to afford out of pocket expense&quot;,
&quot;Prescriber Decision - Coverage Effort&quot;,&quot;&quot;,
&quot;Prescriber Decision - Other&quot;,&quot;Patient unwilling to started treatment, other&quot;,
&quot;Patient Medical Delay, Max Delay&quot;,&quot;Hospitalization, LTC, and other medical reason a patient could not start treatment&quot;,
&quot;No Route of Access&quot;,&quot;Appeal options exhausted and over criteria for PAP&quot;,
&quot;Patient Deceased&quot;,&quot;Patient deceased&quot;,
&quot;Patient Off Therapy&quot;,&quot;Patient no longer in therapy&quot;,
&quot;Other&quot;,&quot;Other&quot;,
&quot;Reported Reaction&quot;,&quot;Patient Stopped therapy due to reported  Reaction&quot;,
&quot;Clinical Trial&quot;,&quot;Patient is entering a clinical trial for a different medication&quot;,
&quot;Administration Barrier&quot;,&quot;Patient refused treatment, could not locate vein access to infuse patient&quot;,
&quot;No coverage: Appeals exhausted and PAP ineligible&quot;,&quot;Replaces No Route of Access sub status - Appeal options exhausted and over income criteria for PAP&quot;,
null),
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Description - Discontinued</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/MVN_Status_Description_Pending__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status_Description_Pending__c</fullName>
    <description>Status Description for Status = Pending</description>
    <formula>CASE(PJN_New_Therapy_Status__c, &quot;Pending&quot;,
CASE(PJN_New_Therapy_Sub_Status__c,
&quot;New Referral&quot;,	&quot;Enrollment received via PSF, CCTP Form, or verbal patient outreach&quot;,
&quot;Missing Information, Patient Outreach&quot;,&quot;Required data field missing to enroll patient, outreach to patient&quot;,
&quot;Missing Information, HCP Outreach&quot;,&quot;Required data field missing to enroll patient, outreach to HCP&quot;,
&quot;Missing Information, RBM Outreach&quot;,&quot;Required data field missing to enroll patient, outreach to RBM&quot;,
&quot;Prescriber Welcome Call Attempted&quot;,&quot;Welcome call attempt to prescriber&quot;,
&quot;Prescriber Welcome Call Completed&quot;,&quot;Welcome call completed to prescriber&quot;,
&quot;Patient Welcome Call Attempted&quot;,&quot;Welcome call attempt to patient&quot;,
&quot;Patient Welcome Call Completed&quot;,&quot;Welcome call completed to patient&quot;,
&quot;Copay Card Enrolled&quot;,&quot;Patient was  enrolled in the Copay Program&quot;,
&quot;Copay Card Not Eligible&quot;,&quot;Patient was not eligible for enrollment&apos; in the Copay Program&quot;,
&quot;Transfer to SP CTTP&quot;,&quot;Hub has transferred patient to SP for CTTP dispense&quot;,
&quot;Benefits Investigation Start&quot;,&quot;Benefits investigation started at Hub&quot;,
&quot;Benefits Investigation Completed&quot;,&quot;Benefits investigation completed at Hub&quot;,
&quot;Access Plan Pending Confirmation&quot;,&quot;Hub is reviewing access plan options&quot;, 
&quot;Access Plan Confirmed&quot;,&quot;Hub has confirmed access plan options&quot;,
&quot;Transfer to HCP B&amp;B&quot;,&quot;Hub has transferred patient to HCP for commercial dispense under Buy &amp; Bill&quot;,
&quot;Transfer to SP Commercial&quot;,&quot;Hub has transferred patient to SP for commercial dispense under AOB&quot;,
&quot;Transfer to SP PAP&quot;,&quot;Hub has transferred patient to SP for PAP dispense&quot;,
&quot;Prior Authorization Support Start&quot;,&quot;PA support by Hub&quot;,
&quot;Prior Authorization Approved&quot;,&quot;PA was approved by payor&quot;,
&quot;Prior Authorization Denied&quot;,&quot;PA was denied by payor&quot;,
&quot;Appeal Support (1st Level)&quot;,&quot;PA was denied, Hub providing 1st Level support&quot;,
&quot;Appeal Support (2nd Level)&quot;,&quot;PA was denied, Hub providing 2nd Level support&quot;,
&quot;Appeal Support (3rd Level)&quot;,&quot;PA was denied, Hub providing 3rd Level support&quot;,
&quot;Appeal Support (Peer-to-Peer)&quot;,&quot;PA was denied, Peer-to-Peer review&quot;,
&quot;Appeal Approved&quot;,&quot;PA Appeal approved by payor&quot;,
&quot;Appeal Denied&quot;,&quot;PA Appeal denied by payor&quot;,
&quot;PA/Appeal Support Max Attempts&quot;,&quot;PA/Appeal support has exhausted the maximum number of attempts&quot;,
&quot;SD Order Confirmed (verbal)&quot;,&quot;Hub has confirmed that HCP has ordered product via verbal&quot;,
&quot;SD Order Confirmed (data)&quot;,&quot;Hub has confirmed that HCP has ordered product via 861 data&quot;,
&quot;SP Shipment Confirmed&quot;,&quot;Hub has confirmed first shipment for existing PSF&quot;,
&quot;Site of Care Delayed&quot;,&quot;Site of Care Not Ready to Receive Product&quot;,
&quot;Site of Care Changed&quot;,&quot;Site of Care has changed to a new location&quot;,
&quot;Site of Care Cancelled&quot;,&quot;Site of Care has been cancelled with no new site identified&quot;,
&quot;Site of Care Ready&quot;,&quot;Site of Care is ready to access shipments and perform treatment&quot;,
&quot;Benefit Investigation COB&quot;,&quot;Benefit Investigation detailed pharmacy/medical review and coordination of benefits&quot;,
&quot;Prior Authorization Support Queued&quot;,&quot;HUB Prior Authorization support queued for HCP support&quot;,
&quot;Prior Authorization Support Unnecessary&quot;,&quot;HUB Prior Authorization support unnecessary - not requested by HCP or SP Channel&quot;,
&quot;Pending Onboarding&quot;,&quot;Pending Confirmation of first treatment or Site of Care delay&quot;,
&quot;Hospital Pharmacy Review&quot;,&quot;Hospital System Completing Formulary Review&quot;,
&quot;On Hold Medical Delay&quot;, &quot;On Hold Medical Delay&quot;,
&quot;On Hold Step Therapy Required&quot;, &quot;On Hold Step Therapy Required&quot;,
&quot;On Hold Patient Travel&quot;, &quot;On Hold Patient Travel&quot;,
&quot;On Hold Genetic Testing&quot;, &quot;On Hold Genetic Testing&quot;,
&quot;On Hold Prescriber Change&quot;, &quot;On Hold Prescriber Change&quot;,
&quot;On Hold Hospital formulary/EMR build&quot;, &quot;Hospital formulary delay or EMR configuration-Build delay.&quot;,
null),
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Description - Pending</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/MVN_Therapy_Status_Restatement.recordType-meta.xml
<RecordType>
    <fullName>MVN_Therapy_Status_Restatement</fullName>
    <active>true</active>
    <description>Defines a restatement to an event representing a known update in the patient&apos;s therapy status and/or sub-status</description>
    <label>Therapy Status Restatement</label>
</RecordType>

force-app/main/default/src/objects/PJN_Event__c/recordTypes/PJN_Therapy_Status_Update.recordType-meta.xml
<RecordType>
    <fullName>PJN_Therapy_Status_Update</fullName>
    <active>true</active>
    <description>Defines an event representing a known update in the patient&apos;s therapy status and/or sub-status</description>
    <label>Therapy Status Update</label>
</RecordType>

force-app/main/default/src/classes/MVN_HubStatusExportHdlr.cls
/**
 * @author Mavens
 * @description On therapy status update event creation, set fields below following IntegriChain pattern
 *                  - MVN_Status_Description__c
 *                  - MVN_Milestone__c
 *                  - MVN_Status_Code__c
 * @group hub-status-export
 */
public with sharing class MVN_HubStatusExportHdlr implements PJN_TriggerDispatcher.HandlerInterface {

    /**
     * Handle the trigger call BEFORE INSERT
     */
    public void handle() {
        Id therapyStatusUpdateRT = SObjectType.PJN_Event__c.getRecordTypeInfosByDeveloperName()
                                    .get('PJN_Therapy_Status_Update').getRecordTypeId();
        Id therapyStatusRT = SObjectType.PJN_Event__c.getRecordTypeInfosByDeveloperName()
                                    .get('MVN_Therapy_Status_Restatement').getRecordTypeId();
                                    
        Map<PJN_Event__c, PJN_Event__c> eventsCloned = new Map<PJN_Event__c,PJN_Event__c>();
        for (PJN_Event__c event : (List<PJN_Event__c>)Trigger.new) {
            if (event.RecordTypeId == therapyStatusUpdateRT || event.RecordTypeId == therapyStatusRT) {
                eventsCloned.put(event, event.clone());
            }
        }
        Formula.recalculateFormulas(eventsCloned.values());
        for (PJN_Event__c event : (List<PJN_Event__c>)Trigger.new) {
            if (event.RecordTypeId == therapyStatusUpdateRT || event.RecordTypeId == therapyStatusRT) {
                PJN_Event__c eventCloned = eventsCloned.get(event);
                event.MVN_Status_Description__c =
                    (eventCloned.MVN_Status_Description_Active__c != null ? eventCloned.MVN_Status_Description_Active__c :
                    (eventCloned.MVN_Status_Description_Pending__c != null ? eventCloned.MVN_Status_Description_Pending__c :
                    (eventCloned.MVN_Status_Description_Cancelled__c != null ? eventCloned.MVN_Status_Description_Cancelled__c :
                    (eventCloned.MVN_Status_Description_Discontinued__c != null ? eventCloned.MVN_Status_Description_Discontinued__c :
                    ''))));
                event.MVN_Milestone__c =
                    (eventCloned.MVN_Milestone_Active__c != null ? eventCloned.MVN_Milestone_Active__c :
                    (eventCloned.MVN_Milestone_Pending__c != null ? eventCloned.MVN_Milestone_Pending__c :
                    (eventCloned.MVN_Milestone_Cancelled__c != null ? eventCloned.MVN_Milestone_Cancelled__c :
                    (eventCloned.MVN_Milestone_Discontinued__c != null ? eventCloned.MVN_Milestone_Discontinued__c :
                    ''))));
                event.MVN_Status_Code__c =
                    (eventCloned.MVN_Status_Code_Active__c != null ? eventCloned.MVN_Status_Code_Active__c :
                    (eventCloned.MVN_Status_Code_Pending__c != null ? eventCloned.MVN_Status_Code_Pending__c :
                    (eventCloned.MVN_Status_Code_Cancelled__c != null ? eventCloned.MVN_Status_Code_Cancelled__c :
                    (eventCloned.MVN_Status_Code_Discontinued__c != null ? eventCloned.MVN_Status_Code_Discontinued__c :
                    ''))));
            }
        }
    }
}