force-app/main/default/src/objects/PJN_CarePlan_Path_Coaching_Setting__mdt/PJN_CarePlan_Path_Coaching_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder; Care Plan Path Coaching
Purpose: Define the guidance and key fields for each program problem/stage.
Metadata Relationship(s): Program Problem; CarePlan Path Keys Setting
Created by Mavens: Yes</description>
    <label>CarePlan Path Coaching Setting</label>
    <pluralLabel>CarePlan Path Coaching Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CarePlan_Path_Coaching_Setting__mdt/fields/PJN_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Component_Name__c</fullName>
    <defaultValue>&apos;PJN_CarePlanPathKeys&apos;</defaultValue>
    <label>Component Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_CarePlan_Path_Coaching_Setting__mdt/fields/PJN_Mode__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>left</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>right</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>flexible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_CarePlan_Path_Coaching_Setting__mdt/fields/PJN_Program_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem__c</fullName>
    <label>Program Problem</label>
    <referenceTo>PJN_Program_Problem__mdt</referenceTo>
    <relationshipName>PJN_CarePlan_Path_Keys_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/PJN_Program_Problem__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Define the attributes of the problems/stages that comprise a Program. Program Problems are distinct stages in the patient’s journey that are (typically) completed before moving on to the next stage.
Metadata Relationship(s): Program; Program Case
Created by Mavens: Yes</description>
    <label>Program Problem</label>
    <pluralLabel>Program Problems</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_CarePlanPathCoachSettingMock.cls
@isTest(isParallel=true) public with sharing class PJN_CarePlanPathCoachSettingMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'queryByProgramProblemDeveloperName') {
            return this.queryByProgramProblemDeveloperName((String) listOfArgs[0]);
        } else {
            return null;
        }
    }

    private Object queryByProgramProblemDeveloperName(String programProblemDeveloperName) {
        List<PJN_CarePlan_Path_Coaching_Setting__mdt> carePlanPathCoachingSettings = new List<PJN_CarePlan_Path_Coaching_Setting__mdt>();
        carePlanPathCoachingSettings.add(
            new PJN_CarePlan_Path_Coaching_Setting__mdt(
                MasterLabel = 'Mocked Care Plan Path Coaching Setting',
                DeveloperName = 'PJN_Mocked_Care_Plan_Path_Coaching_Setting',
                PJN_Program_Problem__r = new PJN_Program_Problem__mdt(
                    MasterLabel = 'Mocked Program Problem',
                    DeveloperName = programProblemDeveloperName
                ),
                PJN_Component_Name__c = 'PJN_TestComponent',
                PJN_Mode__c = 'A'
            )
        );
        return carePlanPathCoachingSettings;
    }
}