force-app/main/default/src/objects/PJN_CarePlan_Path_Coaching_Setting__mdt/PJN_CarePlan_Path_Coaching_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder; Care Plan Path Coaching
Purpose: Define the guidance and key fields for each program problem/stage.
Metadata Relationship(s): Program Problem; CarePlan Path Keys Setting
Created by Mavens: Yes</description>
    <label>CarePlan Path Coaching Setting</label>
    <pluralLabel>CarePlan Path Coaching Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CarePlan_Path_Keys_Setting__mdt/PJN_CarePlan_Path_Keys_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder; Care Plan Path
Purpose: Define the key fields to be displayed on the Care Plan for each program problem/stage.
Metadata Relationship(s): CarePlan Path Coaching Setting
Created by Mavens: Yes</description>
    <label>CarePlan Path Keys Setting</label>
    <pluralLabel>CarePlan Path Keys Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_CarePlan_Path_Keys_Setting__mdt/fields/PJN_CarePlan_Path_Coaching_Setting__c.field-meta.xml
<CustomField>
    <fullName>PJN_CarePlan_Path_Coaching_Setting__c</fullName>
    <label>CarePlan Path Coaching Setting</label>
    <referenceTo>PJN_CarePlan_Path_Coaching_Setting__mdt</referenceTo>
    <relationshipLabel>CarePlan Path Keys Settings</relationshipLabel>
    <relationshipName>PJN_CarePlan_Path_Keys_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_CarePlan_Path_Keys_Setting__mdt/fields/PJN_Columns__c.field-meta.xml
<CustomField>
    <fullName>PJN_Columns__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Columns</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_CarePlan_Path_Keys_Setting__mdt/fields/PJN_Fields__c.field-meta.xml
<CustomField>
    <fullName>PJN_Fields__c</fullName>
    <label>Fields</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/classes/PJN_CarePlanPathKeySettingMock.cls
@isTest(isParallel=true) public with sharing class PJN_CarePlanPathKeySettingMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'queryByCarePlanCoachSettingDeveloperName') {
            return this.queryByCarePlanCoachSettingDeveloperName((String) listOfArgs[0]);
        } else {
            return null;
        }
    }

    private Object queryByCarePlanCoachSettingDeveloperName(String carePlanPathCoachingSettingDeveloperName) {
        return new PJN_CarePlan_Path_Keys_Setting__mdt(
            MasterLabel = 'Mocked Care Plan Path Key Setting',
            DeveloperName = 'PJN_Mocked_Care_Plan_Path_Key_Setting',
            PJN_CarePlan_Path_Coaching_Setting__r = new PJN_CarePlan_Path_Coaching_Setting__mdt(
                MasterLabel = 'Mocked Coaching',
                DeveloperName = carePlanPathCoachingSettingDeveloperName
            ),
            PJN_Fields__c = 'Subject,Status',
            PJN_Columns__c = 2
        );
    }
}