force-app/main/default/src/objects/Email_Quick_Send_MVN__c/Email_Quick_Send_MVN__c.object-meta.xml
<CustomObject>
    <description>Allows a user to send an email easily from Salesforce while on a mobile device.</description>
    <label>Email Quick Send</label>
    <nameField>
        <displayFormat>EQS-{00000}</displayFormat>
        <label>Email Quick Send Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Quick Sends</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/Email_Quick_Send_MVN__c/fields/Account_MVN__c.field-meta.xml
<CustomField>
    <fullName>Account_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account this email belongs to. This may be set by sending an email to an account or, by trigger, when the account is created through a lead conversion.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Email Quick Sends</relationshipLabel>
    <relationshipName>Email_Quick_Sends_MVN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Email_Quick_Send_MVN__c/fields/Care_Plan_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the care plan from which this email quick send was sent.</description>
    <label>Care Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CarePlan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Email Quick Sends</relationshipLabel>
    <relationshipName>Email_Quick_Sends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Email_Quick_Send_MVN__c/fields/Consumer_MVN__c.field-meta.xml
<CustomField>
    <fullName>Consumer_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Interaction from which the email quick send was requested.</description>
    <label>Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Email Quick Sends</relationshipLabel>
    <relationshipName>Email_Quick_Sends_MVN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Email_Quick_Send_MVN__c/fields/Email_Template_MVN__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_MVN__c</fullName>
    <description>Existing email template for the email to be sent using.</description>
    <label>Email Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointment_Reminder_MVN</fullName>
                <label>Appointment Reminder</label>
            </value>
            <value>
                <fullName>Diabetic_Retinopathy_and_You_MVN</fullName>
                <label>Diabetic Retinopathy &amp; You</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Email_Quick_Send_MVN__c/fields/From_Address_MVN__c.field-meta.xml
<CustomField>
    <fullName>From_Address_MVN__c</fullName>
    <description>The org-wide email address from which this email will be sent. Maps to the Display Name of the org-wide address.</description>
    <label>From Address</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEDSI Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/Email_Quick_Send_MVN__c/fields/To_Address_MVN__c.field-meta.xml
<CustomField>
    <fullName>To_Address_MVN__c</fullName>
    <description>Email address to which the message should be sent.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>To Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/Lead/fields/Event_MVN__c.field-meta.xml
<CustomField>
    <fullName>Event_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Event at which the interaction occurred.</description>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Consumers</relationshipLabel>
    <relationshipName>Consumers_MVN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/classes/LeadConvertReparentChildrenTestMVN.cls
/**
 * @author      Mavens
 * @group       LeadMVN
 * @description Unit tests for LeadConvertReparentChildrenMVN
 *              assumes configuration is correct for metadata 
 */
@isTest
public class LeadConvertReparentChildrenTestMVN {
    
    private static final Integer DATA_SIZE = 200;

    static {
        // don't need to actually end emails in the test
        EmailQuickSendHdlrMVN.sendEmails = false;
    }
    
    @TestSetup
    static void makeData() {
        String firstTemplateValue = SObjectType.Email_Quick_Send_MVN__c
            .fields.getMap()
            .get('Email_Template_MVN__c')
            .getDescribe()
            .getPicklistValues()[0]
            .getValue();

        if ([SELECT Id FROM EmailTemplate WHERE DeveloperName = :firstTemplateValue].isEmpty()) {
            System.runAs(new User(Id= UserInfo.getUserId())) {
                EmailTemplate testTemplate = new EmailTemplate(
                    DeveloperName = 'TestTemplate_MVN',
                    HtmlValue = '<html><body>test</body></html>',
                    Description = 'Test Template',
                    Encoding = 'ISO-8859-1',
                    Name = 'Test Template',
                    Subject = 'Test Template',
                    IsActive = true,
                    TemplateType = 'Custom',
                    FolderId = userInfo.getUserId()
                );
        
                insert testTemplate;
            }
        }

        Campaign event = new Campaign(Name='Test');
        insert event;

        List<Lead> leads = new List<Lead>();

        for (Integer i=0; i < DATA_SIZE; i++) {
            leads.add(
                new Lead(
                    Event_MVN__c=event.Id,
                    LastName='Test'+i,
                    Phone = '5555555555',
                    Status = 'Consented'
                )
            );    
        }
        insert leads;
        
        List<Email_Quick_Send_MVN__c> emails = new List<Email_Quick_Send_MVN__c>();               

        for (Lead ld : leads) {
            emails.add(
                new Email_Quick_Send_MVN__c (
                    Consumer_MVN__c = ld.Id,
                    To_Address_MVN__c = 'test@consumer.com', 
                    From_Address_MVN__c = 'DEDSI Program',
                    Email_Template_MVN__c = firstTemplateValue
                )
            );
        }
        insert emails;

        List<Database.LeadConvert> converts = new List<Database.LeadConvert>();
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];

        for (Lead ld : leads) {
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(ld.id);
            lc.setConvertedStatus(convertStatus.MasterLabel);
            converts.add(lc);
        }
        Database.convertLead(converts);
    }

    @isTest
    private static void itShouldReparentRecordsFromConvertedLeadToAccountAndCarePlan() {
        List<Lead> leads = [SELECT Id, ConvertedAccountId FROM Lead];
        List<Case> carePlans = new List<Case>(); 
        for (Lead ld : leads) {
            carePlans.add(
                new Case (
                    AccountId = ld.ConvertedAccountId,
                    RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId()
                )
            );
        }

        insert carePlans;

        Test.startTest();
        LeadConvertReparentChildrenMVN.reparentLeadChidren(new List<Id>(new Map<Id, Case>(carePlans).keySet()));
        Test.stopTest();

        System.assertEquals(DATA_SIZE, [
            SELECT COUNT()
            FROM Email_Quick_Send_MVN__c
            WHERE Account_MVN__c != null
            AND Care_Plan_MVN__c != null
        ]);
                
    }

}