force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/PJN_Program_Problem__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Define the attributes of the problems/stages that comprise a Program. Program Problems are distinct stages in the patient’s journey that are (typically) completed before moving on to the next stage.
Metadata Relationship(s): Program; Program Case
Created by Mavens: Yes</description>
    <label>Program Problem</label>
    <pluralLabel>Program Problems</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Is_Library__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Library__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Library</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Is_Removable__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Removable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Removable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Is_Skippable__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Skippable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Skippable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Is_Standard__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Standard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Standard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Is_Startable__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Startable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Startable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Program Problems</relationshipLabel>
    <relationshipName>PJN_Program_Problems</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_ProgramProblemQuery.cls
/**
 * @author      Mavens
 * @group       Program
 * @description Program Problem Queries
 */
public with sharing class PJN_ProgramProblemQuery {
    /**
     * fields to query
     */
    public Set<String> fields = new Set<String>{
        'Id',
        'Label',
        'MasterLabel',
        'DeveloperName',
        'PJN_Order__c',
        'PJN_Is_Standard__c',
        'PJN_Is_Startable__c',
        'PJN_Is_Skippable__c',
        'PJN_Is_Removable__c'
    };

    /* CACHE programProblemsByDevName */
    static Map<String, PJN_Program_Problem__mdt> programProblemsByDevName;
    /**
     * query Program Problem by Developer Name
     * @param   String      programProblemDeveloperName
     * @returns  PJN_Program_Problem__mdt
     */
    public PJN_Program_Problem__mdt queryByDeveloperName(String programProblemDeveloperName) {
        if (programProblemsByDevName == null) {
            programProblemsByDevName = new Map<String, PJN_Program_Problem__mdt>();
        }

        if (!programProblemsByDevName.containsKey(programProblemDeveloperName)) {
            programProblemsByDevName.put(programProblemDeveloperName,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Problem__mdt ' +
                    'WHERE ' +
                        'DeveloperName = :programProblemDeveloperName ' +
                    'ORDER BY ' +
                        'PJN_Order__c ASC'
                )
            );
        }

        return programProblemsByDevName.get(programProblemDeveloperName);
    }



    /* CACHE programProblemsByDevNameAndIsStandardFilter */
    static Map<String, List<PJN_Program_Problem__mdt>> programProblemsByDevNameAndIsStandardFilter;
    /**
     * query Program Problem by Developer Name
     * @param   String      programProblemDeveloperName
     * @returns  PJN_Program_Problem__mdt
     */
    public List<PJN_Program_Problem__mdt> queryByProgramDeveloperName(String programProblemDeveloperName, Boolean isStandard) {
        if (programProblemsByDevNameAndIsStandardFilter == null) {
            programProblemsByDevNameAndIsStandardFilter = new Map<String, List<PJN_Program_Problem__mdt>>();
        }

        String key = programProblemDeveloperName + String.valueOf(isStandard);

        if (!programProblemsByDevNameAndIsStandardFilter.containsKey(key)) {
            programProblemsByDevNameAndIsStandardFilter.put(key,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Problem__mdt ' +
                    'WHERE ' +
                        'PJN_Program__r.DeveloperName = :key ' +
                    (isStandard ? ' AND PJN_Is_Standard__c = true ' : '') +
                    'ORDER BY ' +
                        'PJN_Order__c ASC'
                )
            );
        }

        return programProblemsByDevNameAndIsStandardFilter.get(key);
    }



    /* CACHE programProblemsByDevName */
    static Map<String, List<PJN_Program_Problem__mdt>> problemsByProgramDevNameAndLibrary;
    /**
     * query Program Problem by Program Developer Name
     * @param   String      programDeveloperName
     * @returns  List<PJN_Program_Problem__mdt>
     */
    public List<PJN_Program_Problem__mdt> queryByProgramDeveloperNameAndLibrary(String programDeveloperName) {
        if (problemsByProgramDevNameAndLibrary == null) {
            problemsByProgramDevNameAndLibrary = new Map<String, List<PJN_Program_Problem__mdt>>();
        }

        if (!problemsByProgramDevNameAndLibrary.containsKey(programDeveloperName)) {
            problemsByProgramDevNameAndLibrary.put(programDeveloperName,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Problem__mdt ' +
                    'WHERE ' +
                        'PJN_Program__r.DeveloperName = :programDeveloperName ' +
                    'AND ' +
                        'PJN_Is_Library__c = true ' +
                    'ORDER BY ' +
                        'Label'
                )
            );
        }

        return problemsByProgramDevNameAndLibrary.get(programDeveloperName);
    }

    public List<PJN_Program_Problem__mdt> getProblemsForProgramInReverseOrder(Id programId) {
        return Database.query(
            'SELECT ' + String.join(new List<String>(fields), ', ') + ' ' +
            'FROM PJN_Program_Problem__mdt ' +
            'WHERE PJN_Program__c = \'' + programId + '\' ' +
            'ORDER BY PJN_Order__c DESC'
        );
    }
}