force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/PJN_Program_Problem__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Define the attributes of the problems/stages that comprise a Program. Program Problems are distinct stages in the patient’s journey that are (typically) completed before moving on to the next stage.
Metadata Relationship(s): Program; Program Case
Created by Mavens: Yes</description>
    <label>Program Problem</label>
    <pluralLabel>Program Problems</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Is_Standard__c.field-meta.xml
<CustomField>
    <fullName>PJN_Is_Standard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Standard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>Program Problems</relationshipLabel>
    <relationshipName>PJN_Program_Problems</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_ProgramQuery.cls
/**
 * @author      Mavens
 * @group       Program
 * @description Program Queries
 */
public with sharing class PJN_ProgramQuery {
    /**
     * fields to query
     */
    public static Set<String> fields = new Set<String>{
        'Id',
        'Label',
        'MasterLabel',
        'DeveloperName'
    };

    /**
     * query for all programs*
     * @returns  List<PJN_Program__mdt>
     */
    public List<PJN_Program__mdt> getAllPrograms() {
        return Database.query(
            'SELECT ' + String.join(new List<String>(fields), ', ') + ' ' +
            'FROM PJN_Program__mdt ' +
            'ORDER BY MasterLabel'
        );
    }

    /**
     * query Program by Developer Name
     * @param   String      programDeveloperName
     * @returns  PJN_Program__mdt
     */
    public PJN_Program__mdt queryByDeveloperName(String programDeveloperName) {
        return Database.query(
            'SELECT ' +
                String.join(new List<String>(fields), ', ') + ', ' +
                '( ' +
                    'SELECT ' +
                        String.join(new List<String>((new PJN_ProgramProblemQuery()).fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Problems__r ' +
                    'WHERE ' +
                        'PJN_Is_Standard__c = true ' +
                ') '+
            'FROM ' +
                'PJN_Program__mdt ' +
            'WHERE ' +
                'DeveloperName = :programDeveloperName'
        );
    }
}