force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information to be modified.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_License_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information (Address) related to License which is updated.</description>
    <label>License Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests (License Address)</relationshipLabel>
    <relationshipName>PJN_License_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_License_Address_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_License_Address_Network_Id__c</fullName>
    <description>Contact Information (Address) Network Id related to License which is updated.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>License Address Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Veeva_Network_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Veeva Network Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_SetDCRLicenseAddressHdlr.cls
/**
 * Data Change Request Trigger handler to replace License Address related when it's needed
 * @author  Mavens
 * @group   DCR
 */
public with sharing class PJN_SetDCRLicenseAddressHdlr implements PJN_TriggerDispatcher.HandlerInterface {
    /**
     * handler
     */
    public void handle() {
        Boolean isAllowed = Trigger.IsBefore && Trigger.isUpdate;

        if (!isAllowed) {
            return;
        }

        Set<String> licenseAddressNetworkIds = new Set<String>();

        for(PJN_Data_Change_Request__c dcr : (List<PJN_Data_Change_Request__c>) Trigger.new) {
            PJN_Data_Change_Request__c oldDCR = (PJN_Data_Change_Request__c) Trigger.oldMap.get(dcr.Id);

            Boolean hasLicenseAddressChanged = oldDCR.PJN_License_Address_Network_Id__c != dcr.PJN_License_Address_Network_Id__c;

            if(!hasLicenseAddressChanged) {
                continue;
            }

            if (String.IsBlank(dcr.PJN_License_Address_Network_Id__c)) {
                dcr.PJN_License_Address__c = null;
            } else {
                licenseAddressNetworkIds.add(dcr.PJN_License_Address_Network_Id__c);
            }
        }

        Map<String, Id> addressIdByNetworkIds = getAddressIdByNetworkIds(licenseAddressNetworkIds);

        if (addressIdByNetworkIds.isEmpty()) {
            return;
        }

        for (PJN_Data_Change_Request__c dcr : (List<PJN_Data_Change_Request__c>) Trigger.new) {
            if (addressIdByNetworkIds.containsKey(dcr.PJN_License_Address_Network_Id__c)) {
                dcr.PJN_License_Address__c = addressIdByNetworkIds.get(dcr.PJN_License_Address_Network_Id__c);
            }
        }
    }

    private static Map<String, Id> getAddressIdByNetworkIds(Set<String> licenseAddressNetworkIds) {
        Map<String, Id> addressIdByNetworkIds = new Map<String, Id>();

        if (licenseAddressNetworkIds.isEmpty()) {
            return addressIdByNetworkIds;
        }

        List<PJN_Contact_Information__c> addresses = [
            SELECT
                Id,
                PJN_Veeva_Network_Id__c
            FROM
                PJN_Contact_Information__c
            WHERE
                PJN_Veeva_Network_Id__c IN :licenseAddressNetworkIds
        ];

        for (PJN_Contact_Information__c address : addresses) {
            addressIdByNetworkIds.put(address.PJN_Veeva_Network_Id__c, address.Id);
        }

        return addressIdByNetworkIds;
    }
}