force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (50): Contact Information External ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information to be modified.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Requests</relationshipLabel>
    <relationshipName>PJN_Data_Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_External_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Data Change Request ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>External Data Change Request ID</inlineHelpText>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/PJN_Data_Change_Request_Line__c.object-meta.xml
<CustomObject>
    <description>Lists all of the specific data changes that are being requested in a data change request.</description>
    <label>Data Change Request Line</label>
    <nameField>
        <displayFormat>DCRL - {000000000}</displayFormat>
        <label>DCR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to be modified, or parent Account of other records being modified.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Contact_Information__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Information record related to the DCR Line.</description>
    <label>Contact Information</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Data_Change_Request_Line__c/fields/PJN_Data_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>PJN_Data_Change_Request__c</fullName>
    <description>Part of the Patient Service accelerator: Parent data change request.</description>
    <label>Data Change Request</label>
    <referenceTo>PJN_Data_Change_Request__c</referenceTo>
    <relationshipLabel>Data Change Request Lines</relationshipLabel>
    <relationshipName>PJN_Data_Change_Request_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/classes/PJN_DCRAddressHdlr.cls
/**
 * DCR Address create trigger handler to create DCR and Lines when an address is inserted or updated
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_DCRAddressHdlr implements PJN_TriggerDispatcher.HandlerInterface {


    private Map<String, PJN_Data_Change_Request__c> parentDcrsByExtId = new Map<String, PJN_Data_Change_Request__c>();
    private Map<String, List<PJN_Data_Change_Request_Line__c>> parentDcrLinesByExtId = new Map<String, List<PJN_Data_Change_Request_Line__c>>();
    private List<PJN_Data_Change_Request__c> dcrs = new List<PJN_Data_Change_Request__c>();
    private List<PJN_Data_Change_Request_Line__c> dcrLines = new List<PJN_Data_Change_Request_Line__c>();

    /**
     * Handler
     */
    public void handle() {
        Boolean isAllowed = Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate) && !PJN_DCR.updateFromNetwork;

        if(!isAllowed) {
            return;
        }

        Map<Id, Account> accountsMap = PJN_DCRCreateHelper.getAccountsRelatedMap(Trigger.new);

        buildDCRs(accountsMap);

        if(!parentDcrsByExtId.isEmpty() && !dcrs.isEmpty() && !dcrLines.isEmpty() && !parentDcrLinesByExtId.isEmpty()) {
            upsert parentDcrsByExtId.values() PJN_External_Id__c;
            upsert dcrs PJN_External_Id__c;

            for (List<PJN_Data_Change_Request_Line__c> parentDcrLines : parentDcrLinesByExtId.values()) {
                dcrLines.addAll(parentDcrLines);
            }
            PJN_DCRCreateHelper.upsertDCRLines(dcrLines);

            Map<Id, String> errorMessageByDCRId = PJN_NetworkEventHelper.publishDCRs(parentDcrsByExtId.values());
            List<PJN_Data_Change_Request__c> allDCRs = dcrs;
            allDCRs.addAll(parentDcrsByExtId.values());
            PJN_DCRCreateHelper.updateDCRsWithError(allDCRs, errorMessageByDCRId);
        }
    }

    /**
     * Builds Address and Parent Account DCRs
     * @param accountsMap   Retrieve Account record related to Address using this map
     */
    private void buildDCRs(Map<Id, Account> accountsMap) {
        for(PJN_Contact_Information__c thisAddress : (List<PJN_Contact_Information__c>) Trigger.new) {
            Account parentAccount = accountsMap.get(thisAddress.PJN_Account__c);

            if (parentAccount == null) {
                continue;
            }

            PJN_DCR dcrWrapper = new PJN_DCR(
                parentAccount,
                (Trigger.isInsert ? null : (PJN_Contact_Information__c) Trigger.oldMap.get(thisAddress.Id)),
                thisAddress
            );

            Boolean isAllowedToSend = dcrWrapper.parentDcr != null && dcrWrapper.dcr != null
                && !dcrWrapper.dcrLines.isEmpty();

            if (!isAllowedToSend) {
                continue;
            }

            parentDcrsByExtId.put(dcrWrapper.parentDcr.PJN_External_Id__c, dcrWrapper.parentDcr);
            dcrs.add(dcrWrapper.dcr);
            parentDcrLinesByExtId.put(dcrWrapper.parentDcr.PJN_External_Id__c, dcrWrapper.parentDcrLines);
            dcrLines.addAll(dcrWrapper.dcrLines);
        }
    }
}