force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Email__c</fullName>
    <description>Email: Correspondence email address.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Email.recordType-meta.xml
<RecordType>
    <fullName>PJN_Email</fullName>
    <active>true</active>
    <description>Defines email contact information</description>
    <label>Email</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Phone.recordType-meta.xml
<RecordType>
    <fullName>PJN_Phone</fullName>
    <active>true</active>
    <description>Defines phone contact information</description>
    <label>Phone</label>
</RecordType>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_TestFactoryContactInformation.cls
/**
* @author Mavens
* @date Jan 2019
* @description Class to provide factory methods to create test data for Contact Information object
* @group TestFactory
*/
@isTest(isParallel=true) public class PJN_TestFactoryContactInformation {
    private class PJN_ContactInformationException extends Exception {}
    private PJN_TestFactorySObject objectFactory;

    public static Map<String, Schema.RecordTypeInfo> ciRecordTypesByName {
        get {
            if (ciRecordTypesByName == null) {
                ciRecordTypesByName = PJN_SObjectUtil.getRecordTypesByDevNameForObject('PJN_Contact_Information__c');
            }
            return ciRecordTypesByName;
        }
        private set;
    }

    public PJN_TestFactoryContactInformation() {
        objectFactory = new PJN_TestFactorySObject('PJN_Contact_Information__c', new Map<String, Object>());
    }

    public PJN_Contact_Information__c constructAddress(Map<String,Object> valuesByField) {
        valuesByField.put('RecordTypeId', ciRecordTypesByName.get('PJN_Address').getRecordTypeId());
        return (PJN_Contact_Information__c) objectFactory.constructSObject(valuesByField);
    }

    public List<PJN_Contact_Information__c> constructManyAddress(Map<String,Object> valuesByField, Integer numberOfAddresses, List<Id> accountIds) {
        List<PJN_Contact_Information__c> addresses = new List<PJN_Contact_Information__c>();
        if(!accountIds.isEmpty() && accountIds.size() > 1 && numberOfAddresses != accountIds.size()) {
            throw new PJN_ContactInformationException('Number of Addresses does not match number of account ids passed.');
        }

        for (Integer index = 0; index < numberOfAddresses; index++) {

            Map<String,Object> newValuesByField = valuesByField;
            if(!accountIds.isEmpty() && accountIds.size() == 1) {
                newValuesByField.put('PJN_Account__c', accountIds[0]);
            } else if(!accountIds.isEmpty() && accountIds.size() > 1) {
                newValuesByField.put('PJN_Account__c', accountIds[index]);
            }

            addresses.add(constructAddress(newValuesByField));
        }

        return addresses;
    }

    public PJN_Contact_Information__c createAddress(Map<String,Object> valuesByField) {
        valuesByField.put('RecordTypeId', ciRecordTypesByName.get('PJN_Address').getRecordTypeId());
        return (PJN_Contact_Information__c) objectFactory.createSObject(valuesByField);
    }

    public PJN_Contact_Information__c constructAddress(
        Id     accountId,
        String line1,
        String line2,
        String city,
        String state,
        String country,
        String postalCode
    ) {
        return new PJN_Contact_Information__c(
            RecordTypeId          = ciRecordTypesByName.get('PJN_Address').getRecordTypeId(),
            PJN_Account__c        = accountId,
            PJN_Address_Line_1__c = line1,
            PJN_Address_Line_2__c = line2,
            PJN_City__c           = city,
            PJN_State__c          = state,
            PJN_Country__c        = country,
            PJN_Postal_Code__c    = postalCode
        );
    }

    public PJN_Contact_Information__c constructEmail(Account parentAccount) {
        PJN_Contact_Information__c email = new PJN_Contact_Information__c(
            PJN_Account__c = parentAccount.Id,
            PJN_Email__c = parentAccount.FirstName + 'email@' + parentAccount.LastName + '.com',
            RecordTypeId = ciRecordTypesByName.get('PJN_Email').getRecordTypeId()
        );

        return email;
    }

    public PJN_Contact_Information__c constructPhone(Account parentAccount) {
        PJN_Contact_Information__c phone = new PJN_Contact_Information__c(
            PJN_Account__c = parentAccount.Id,
            PJN_Phone__c = '5555555555',
            RecordTypeId = ciRecordTypesByName.get('PJN_Phone').getRecordTypeId()
        );

        return phone;
    }


}