force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Email__c</fullName>
    <description>Email: Correspondence email address.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/classes/PJN_AccountSearchRqstTest.cls
@isTest(isParallel=true) private  class PJN_AccountSearchRqstTest {

    @isTest private static void itShouldReturnPopulatedInfoByObject() {
        PJN_AccountSearchRqst req = new PJN_AccountSearchRqst();
        req.account = new Account(FirstName='Test', LastName='TestLast', PersonEmail=null);
        req.contactInfo = new PJN_Contact_Information__c(PJN_Phone__c='5555555555', PJN_Email__c=null);
        req.isPersonSearch = true;
        req.maxResults = 200;

        Map<String, Object> populatedAccountFields = req.populatedInfoByObject.get('Account');
        System.assert(populatedAccountFields.containsKey('FirstName'));
        System.assert(populatedAccountFields.containsKey('LastName'));
        System.assert(!populatedAccountFields.containsKey('PersonEmail'));

        Map<String, Object> populatedCiFields = req.populatedInfoByObject.get('PJN_Contact_Information__c');
        System.assert(populatedCiFields.containsKey('PJN_Phone__c'));
        System.assert(!populatedCiFields.containsKey('PJN_Email__c'));

    }
}