force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Created_From_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Created_From_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact information address record a phone or fax was generated from.</description>
    <label>Created From Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Generated Records</relationshipLabel>
    <relationshipName>Contact_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/classes/PJN_AddressContactInfoSyncHdlr.cls
/**
 *  Trigger handler used to keep contact information in sync with
 *  address data. Metadata configuration will allow for mapping
 *  of address fields to proper contact info record types.
 *  Should be called after insert/update/undelete.
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_AddressContactInfoSyncHdlr implements PJN_TriggerDispatcher.HandlerInterface {

    public void handle() {
        Boolean isAllowed = Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate || Trigger.isUndelete);

        if (!isAllowed) {
            return;
        }

        PJN_ObjectFieldContactInfoSync objectFieldContactInfoSync = new PJN_ObjectFieldContactInfoSync();
        objectFieldContactInfoSync.oldRecordsMap = !Trigger.isInsert ? Trigger.oldMap : null;
        objectFieldContactInfoSync.accountFieldName = 'PJN_Account__c';
        objectFieldContactInfoSync.relatedRecordFieldName = 'PJN_Created_From_Address__c';

        List<PJN_Contact_Information__c> contactInfos = new List<PJN_Contact_Information__c>();
        Id addressRecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId();

        for (PJN_Contact_Information__c contactInfo : (List<PJN_Contact_Information__c>) Trigger.new) {
            if (contactInfo.RecordTypeId == addressRecordTypeId) {
                contactInfos.add(contactInfo);
            }
        }

        objectFieldContactInfoSync.syncContactInfoFromObject(contactInfos);
    }
}