force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Created_From_Address__c.field-meta.xml
<CustomField>
    <fullName>PJN_Created_From_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contact information address record a phone or fax was generated from.</description>
    <label>Created From Address</label>
    <referenceTo>PJN_Contact_Information__c</referenceTo>
    <relationshipLabel>Generated Records</relationshipLabel>
    <relationshipName>Contact_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Email__c</fullName>
    <description>Email: Correspondence email address.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_External_ID__c.field-meta.xml
<CustomField>
    <fullName>PJN_External_ID__c</fullName>
    <description>Text (50): Contact Information External ID.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Email.recordType-meta.xml
<RecordType>
    <fullName>PJN_Email</fullName>
    <active>true</active>
    <description>Defines email contact information</description>
    <label>Email</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Phone.recordType-meta.xml
<RecordType>
    <fullName>PJN_Phone</fullName>
    <active>true</active>
    <description>Defines phone contact information</description>
    <label>Phone</label>
</RecordType>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_ObjectFieldContactInfoSyncTest.cls
@IsTest
public class PJN_ObjectFieldContactInfoSyncTest {

    private static final Integer DATA_SIZE = 10;

    static {
        PJN_ObjectFieldContactInfoMappings.objectFieldContactInfoMappingsQuery = (PJN_ObjectFieldContactInfoMappingsQuery) Test.createStub(PJN_ObjectFieldContactInfoMappingsQuery.class, new PJN_ObjectFieldContactInfoMappingsMock());
        PJN_TestFactoryGlobalSetting.setMock();
    }

    @TestSetup
    static void makeData(){
        List<Account> accounts = buildAccounts(DATA_SIZE);
        insert accounts;

        List<PJN_Contact_Information__c> contactInfos = buildAddresses(accounts);
        insert contactInfos;
    }

    private static List<Account> buildAccounts(Integer numOfAccounts) {
        PJN_TestFactoryGlobalSetting.setMock();
        List<Account> accounts = new List<Account>();

        for (Integer accIndex = 0; accIndex < numOfAccounts; accIndex++) {
            accounts.add(
                new Account(
                    FirstName = 'First' + accIndex,
                    LastName = 'Test' + accIndex,
                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Physician').getRecordTypeId()
                )
            );
        }

        return accounts;
    }

    private static List<PJN_Contact_Information__c> buildAddresses(List<Account> accounts) {
        List<PJN_Contact_Information__c> contactInfos = new List<PJN_Contact_Information__c>();

        for (Account account : accounts) {
            contactInfos.add(
                new PJN_Contact_Information__c(
                    PJN_Account__c = account.Id,
                    PJN_Address_Line_1__c = 'Main Street 123',
                    PJN_City__c = 'Chicago',
                    PJN_State__c = 'IL',
                    PJN_Country__c = 'United States',
                    RecordTypeId = Schema.SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId()
                )
            );
        }

        return contactInfos;
    }

    @IsTest
    static void testIfAccountInsertCreatesContactInfos() {
        List<Account> accounts = buildAccounts(DATA_SIZE);

        for (Account account : accounts) {
            account.PersonEmail = 'test@test.com';
            account.Phone = '1111111111';
        }

        Test.startTest();
        insert accounts;
        Test.stopTest();

        accounts = getAccountsQueried(accounts);
        System.assert(!accounts.isEmpty(), 'Something went wrong getting accounts queried.');

        /*
        for (Account account : accounts) {
            System.assert(!account.PJN_Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : account.PJN_Contact_Information__r) {
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(account.PersonEmail, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(account.Phone, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }
        */
    }

    @IsTest
    static void testIfAccountUpdateCreatesContactInfos() {
        List<Account> accounts = getAccountsQueried();

        for (Account account : accounts) {
            account.PersonEmail = 'test@test.com';
            account.Phone = '1111111111';
        }

        Test.startTest();
        update accounts;
        Test.stopTest();

        accounts = getAccountsQueried(accounts);
        System.assert(!accounts.isEmpty(), 'Something went wrong getting accounts queried.');

        for (Account account : accounts) {
            System.assert(!account.PJN_Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : account.PJN_Contact_Information__r) {
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(account.PersonEmail, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(account.Phone, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }
    }

    @IsTest
    static void testIfAccountUpdateGetsContactInfosUpdated() {
        List<Account> accounts = getAccountsQueried();

        for (Account account : accounts) {
            account.PersonEmail = 'test@test.com';
            account.Phone = '1111111111';
        }

        update accounts;

        for (Account account : accounts) {
            account.PersonEmail = 'test2@test.com';
            account.Phone = '222222222';
        }

        Test.startTest();
        update accounts;
        Test.stopTest();

        accounts = getAccountsQueried(accounts);
        System.assert(!accounts.isEmpty(), 'Something went wrong getting accounts queried.');

        for (Account account : accounts) {
            Integer emailCount = 0;
            Integer phoneCount = 0;
            System.assert(!account.PJN_Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : account.PJN_Contact_Information__r) {
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(account.PersonEmail, contactInfo.PJN_Email__c, 'Email must be the same');
                    emailCount++;
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(account.Phone, contactInfo.PJN_Phone__c, 'Phone must be the same');
                    phoneCount++;
                }
            }
            System.assertEquals(1, emailCount, 'Email Contact Info must be updated not recreated');
            System.assertEquals(1, phoneCount, 'Phone Contact Info must be updated not recreated');
        }
    }

    @IsTest
    static void testIfAddressInsertCreatesContactInfos() {
        List<Account> accounts = getAccountsQueried();

        List<PJN_Contact_Information__c> addresses = buildAddresses(accounts);

        for (PJN_Contact_Information__c address : addresses) {
            address.PJN_Email__c = 'test@test.com';
            address.PJN_Phone__c = '1111111111';
        }

        Test.startTest();
        insert addresses;
        Test.stopTest();

        addresses = getAddressesQueried(addresses);
        System.assert(!addresses.isEmpty(), 'Something went wrong getting address contact info queried.');

        for (PJN_Contact_Information__c address : addresses) {
            System.assert(!address.Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : address.Contact_Information__r) {
                System.assertEquals(address.PJN_Account__c, contactInfo.PJN_Account__c, 'Address Account and Contact Info Account must be the same.');
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(address.PJN_Email__c, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(address.PJN_Phone__c, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }
    }

    @IsTest
    static void testIfAddressUpdateCreatesContactInfos() {
        List<PJN_Contact_Information__c> contactInfos = getAddressesQueried();

        for (PJN_Contact_Information__c contactInfo : contactInfos) {
            contactInfo.PJN_Email__c = 'test@test.com';
            contactInfo.PJN_Phone__c = '1111111111';
        }

        Test.startTest();
        update contactInfos;
        Test.stopTest();

        contactInfos = getAddressesQueried(contactInfos);
        System.assert(!contactInfos.isEmpty(), 'Something went wrong getting address contact info queried.');

        for (PJN_Contact_Information__c address : contactInfos) {
            System.assert(!address.Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : address.Contact_Information__r) {
                System.assertEquals(address.PJN_Account__c, contactInfo.PJN_Account__c, 'Address Account and Contact Info Account must be the same.');
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(address.PJN_Email__c, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(address.PJN_Phone__c, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }
    }

    @IsTest
    static void testIfAddressUpdateGetsContactInfosUpdated() {
        List<PJN_Contact_Information__c> contactInfos = getAddressesQueried();

        for (PJN_Contact_Information__c contactInfo : contactInfos) {
            contactInfo.PJN_Email__c = 'test@test.com';
            contactInfo.PJN_Phone__c = '1111111111';
        }
        update contactInfos;

        for (PJN_Contact_Information__c contactInfo : contactInfos) {
            contactInfo.PJN_Email__c = 'test2@test.com';
            contactInfo.PJN_Phone__c = '22222222222';
        }

        Test.startTest();
        update contactInfos;
        Test.stopTest();

        contactInfos = getAddressesQueried(contactInfos);
        System.assert(!contactInfos.isEmpty(), 'Something went wrong getting address contact info queried.');

        for (PJN_Contact_Information__c address : contactInfos) {
            Integer emailCount = 0;
            Integer phoneCount = 0;
            System.assert(!address.Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : address.Contact_Information__r) {
                System.assertEquals(address.PJN_Account__c, contactInfo.PJN_Account__c, 'Address Account and Contact Info Account must be the same.');
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(address.PJN_Email__c, contactInfo.PJN_Email__c, 'Email must be the same');
                    emailCount++;
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(address.PJN_Phone__c, contactInfo.PJN_Phone__c, 'Phone must be the same');
                    phoneCount++;
                }
            }
            System.assertEquals(1, emailCount, 'Email Contact Info must be updated not recreated');
            System.assertEquals(1, phoneCount, 'Phone Contact Info must be updated not recreated');
        }
    }

    /*
    @IsTest
    static void testIfContactInfosUpdateGetAccountUpdated() {
        List<Account> accounts = buildAccounts(DATA_SIZE);

        for (Account account : accounts) {
            account.PersonEmail = 'test@test.com';
            account.Phone = '1111111111';
        }

        insert accounts;

        accounts = getAccountsQueried(accounts);
        System.assert(!accounts.isEmpty(), 'Something went wrong getting accounts queried.');

        for (Account account : accounts) {
            System.assert(!account.PJN_Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : account.PJN_Contact_Information__r) {
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(account.PersonEmail, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(account.Phone, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }

        List<PJN_Contact_Information__c> contactInfos = getContactInfosQueried();
        System.assert(!contactInfos.isEmpty(), 'No Contact Info created from Account found');

        for (PJN_Contact_Information__c contactInfo : contactInfos) {
            if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                contactInfo.PJN_Email__c = 'test2@test.com';
            } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                contactInfo.PJN_Phone__c = '2222222222';
            }
        }

        Test.startTest();
        update contactInfos;
        Test.stopTest();

        accounts = getAccountsQueried(accounts);
        System.assert(!accounts.isEmpty(), 'Something went wrong getting accounts queried.');

        for (Account account : accounts) {
            System.assert(!account.PJN_Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : account.PJN_Contact_Information__r) {
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals('test2@test.com', contactInfo.PJN_Email__c, 'Email has not changed');
                    System.assertEquals(account.PersonEmail, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals('2222222222', contactInfo.PJN_Phone__c, 'Phone has not changed');
                    System.assertEquals(account.Phone, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }
    }
    */

    @IsTest
    static void testIfContactInfosUpdateGetsAddressUpdated() {
        List<Account> accounts = getAccountsQueried();

        List<PJN_Contact_Information__c> addresses = buildAddresses(accounts);

        for (PJN_Contact_Information__c address : addresses) {
            address.PJN_Email__c = 'test@test.com';
            address.PJN_Phone__c = '1111111111';
        }

        insert addresses;

        addresses = getAddressesQueried(addresses);
        System.assert(!addresses.isEmpty(), 'Something went wrong getting address contact info queried.');

        for (PJN_Contact_Information__c address : addresses) {
            System.assert(!address.Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : address.Contact_Information__r) {
                System.assertEquals(address.PJN_Account__c, contactInfo.PJN_Account__c, 'Address Account and Contact Info Account must be the same.');
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals(address.PJN_Email__c, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals(address.PJN_Phone__c, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }

        List<PJN_Contact_Information__c> contactInfos = getContactInfosQueried();
        System.assert(!contactInfos.isEmpty(), 'No Contact Info created from Account found');

        for (PJN_Contact_Information__c contactInfo : contactInfos) {
            if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                contactInfo.PJN_Email__c = 'test2@test.com';
            } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                contactInfo.PJN_Phone__c = '2222222222';
            }
        }

        Test.startTest();
        update contactInfos;
        Test.stopTest();

        addresses = getAddressesQueried(addresses);
        System.assert(!addresses.isEmpty(), 'Something went wrong getting address contact info queried.');

        for (PJN_Contact_Information__c address : addresses) {
            System.assert(!address.Contact_Information__r.isEmpty(), 'Contact Information records must be created and related to accounts.');
            for (PJN_Contact_Information__c contactInfo : address.Contact_Information__r) {
                System.assertEquals(address.PJN_Account__c, contactInfo.PJN_Account__c, 'Address Account and Contact Info Account must be the same.');
                if (contactInfo.RecordType.DeveloperName == 'PJN_Email') {
                    System.assertEquals('test2@test.com', contactInfo.PJN_Email__c, 'Email has not changed');
                    System.assertEquals(address.PJN_Email__c, contactInfo.PJN_Email__c, 'Email must be the same');
                } else if (contactInfo.RecordType.DeveloperName == 'PJN_Phone') {
                    System.assertEquals('2222222222', contactInfo.PJN_Phone__c, 'Phone has not changed');
                    System.assertEquals(address.PJN_Phone__c, contactInfo.PJN_Phone__c, 'Phone must be the same');
                }
            }
        }
    }

    private static List<Account> getAccountsQueried(List<Account> accounts) {
        return [
            SELECT
                Id,
                PersonEmail,
                Phone,
                (
                    SELECT
                        Id,
                        PJN_Email__c,
                        PJN_Phone__c,
                        RecordType.DeveloperName
                    FROM
                        PJN_Contact_Information__r
                    WHERE
                        RecordType.DeveloperName IN ('PJN_Email', 'PJN_Phone')
                )
            FROM
                Account
            WHERE
                Id IN :accounts
        ];
    }

    private static List<Account> getAccountsQueried() {
        return [
            SELECT
                Id,
                PersonEmail,
                Phone
            FROM
                Account
            LIMIT :DATA_SIZE
        ];
    }

    private static List<PJN_Contact_Information__c> getAddressesQueried(List<PJN_Contact_Information__c> addresses) {
        return [
            SELECT
                Id,
                PJN_Account__c,
                PJN_Email__c,
                PJN_Phone__c,
                (
                    SELECT
                        Id,
                        PJN_Account__c,
                        PJN_Email__c,
                        PJN_Phone__c,
                        RecordType.DeveloperName
                    FROM
                        Contact_Information__r
                    WHERE
                        RecordType.DeveloperName IN ('PJN_Email', 'PJN_Phone')
                )
            FROM
                PJN_Contact_Information__c
            WHERE
                Id IN :addresses
        ];
    }

    private static List<PJN_Contact_Information__c> getAddressesQueried() {
        return [
            SELECT
                Id,
                PJN_Account__c,
                PJN_Email__c,
                PJN_Phone__c
            FROM
                PJN_Contact_Information__c
            WHERE
                RecordType.DeveloperName = 'PJN_Address'
            LIMIT :DATA_SIZE
        ];
    }

    private static List<PJN_Contact_Information__c> getContactInfosQueried() {
        return [
            SELECT
                Id,
                PJN_Account__c,
                PJN_Email__c,
                PJN_Phone__c,
                RecordType.DeveloperName,
                PJN_Created_From_Address__c
            FROM
                PJN_Contact_Information__c
            WHERE
                PJN_External_Id__c != null
        ];
    }
}