force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_1__c</fullName>
    <description>Text(100) for address line 1.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>PJN_Address_Line_2__c</fullName>
    <description>Text(100) for address line 2.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_City__c.field-meta.xml
<CustomField>
    <fullName>PJN_City__c</fullName>
    <description>City field for Contact Information.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Country__c.field-meta.xml
<CustomField>
    <fullName>PJN_Country__c</fullName>
    <description>Country field for Contact Information, utilizing HealthCloudGA country global field set.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Email__c.field-meta.xml
<CustomField>
    <fullName>PJN_Email__c</fullName>
    <description>Email: Correspondence email address.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Fax__c.field-meta.xml
<CustomField>
    <fullName>PJN_Fax__c</fullName>
    <description>Fax: Correspondence fax number.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Phone__c.field-meta.xml
<CustomField>
    <fullName>PJN_Phone__c</fullName>
    <description>Phone: Correspondence phone number.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>PJN_Postal_Code__c</fullName>
    <description>Text(10) Zip/postal code.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Set_as_Primary__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates this record should be set as primary. A trigger will manage this update.</description>
    <inlineHelpText>Indicates this record should be set as primary.</inlineHelpText>
    <label>Set as Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_State__c.field-meta.xml
<CustomField>
    <fullName>PJN_State__c</fullName>
    <description>Global Value picklist for States, dependent on country.</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PJN_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PJN_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Address.recordType-meta.xml
<RecordType>
    <fullName>PJN_Address</fullName>
    <active>true</active>
    <description>Defines address contact information</description>
    <label>Address</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Email.recordType-meta.xml
<RecordType>
    <fullName>PJN_Email</fullName>
    <active>true</active>
    <description>Defines email contact information</description>
    <label>Email</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Fax.recordType-meta.xml
<RecordType>
    <fullName>PJN_Fax</fullName>
    <active>true</active>
    <description>Defines fax contact information</description>
    <label>Fax</label>
</RecordType>

force-app/main/default/src/objects/PJN_Contact_Information__c/recordTypes/PJN_Phone.recordType-meta.xml
<RecordType>
    <fullName>PJN_Phone</fullName>
    <active>true</active>
    <description>Defines phone contact information</description>
    <label>Phone</label>
</RecordType>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>NY</fullName>
    </customValue>
    <description>List of states using the 5 character iso code format: &lt;country code&gt;_&lt;state code&gt;</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PrimaryCIChangeHdlrTestMVN.cls
/**
 * @author      Mavens
 * @group       PrimaryCIChangeHdlrMVN
 * @description Unit tests for PrimaryCIChangeHdlrMVN
 */
@isTest(isParallel=true)
public with sharing class PrimaryCIChangeHdlrTestMVN {
    
    private static final Integer DATA_SIZE = 200;

    @TestSetup
    static void makeData(){
        Id progParticipantRecTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Program_Participant_MVN').getRecordTypeId();
        Id businessRecTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesBusiness').getRecordTypeId();

        List<Account> newAccounts = new List<Account>();
        for (Integer i=0; i<DATA_SIZE; i++) {
            newAccounts.add(
                new Account(
                    LastName = 'Test'+i,
                    RecordTypeId = progParticipantRecTypeId
                )
            );
            newAccounts.add(
                new Account(
                    Name = 'Test Business ' + i,
                    RecordTypeId = businessRecTypeId
                )
            );
        }
        insert newAccounts;
    }

    static {
        PJN_TriggerHandlerSettingQuery.triggerHandlerSettingBySObjectType = new Map<SObjectType, List<PJN_Trigger_Handler_Setting__mdt>> {
            SObjectType.Account.getSObjectType() => new List<PJN_Trigger_Handler_Setting__mdt> {
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'PrimaryCIChangeHdlrMVN',
                    PJN_Event__c = 'BEFORE_INSERT',
                    PJN_SObject_API_Name__c = 'Account'
                ),
                new PJN_Trigger_Handler_Setting__mdt(
                    PJN_Class__c = 'PrimaryCIChangeHdlrMVN',
                    PJN_Event__c = 'BEFORE_UPDATE',
                    PJN_SObject_API_Name__c = 'Account'
                )
            }
        };
    }

    /*** EMAIL TESTS ***/
    @isTest
    private static void itShouldCopyPrimaryEmailToAccountOnInsert() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> emails = createEmailsFor(progParticipants);
        
        Test.startTest();
        insert emails;
        Test.stopTest();

        progParticipants = [SELECT PersonEmail FROM Account WHERE Id IN :progParticipants];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assertEquals('testemail@regneron.test', participant.PersonEmail);
        }
    }

    @isTest
    private static void itShouldCopyPrimaryEmailToAccountOnUpdate() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> emails = createEmailsFor(progParticipants);
        
        insert emails;
        for (PJN_Contact_Information__c email : emails) {
            if (email.PJN_Email__c == 'testemail-1@regneron.test') {
                email.PJN_Set_as_Primary__c = true;
            }
        }
        Test.startTest();
        update emails;
        Test.stopTest();

        progParticipants = [SELECT PersonEmail FROM Account WHERE Id IN :progParticipants];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assertEquals('testemail-1@regneron.test', participant.PersonEmail);
        }
    }

    private static List<PJN_Contact_Information__c> createEmailsFor(List<Account> accounts) {
        Id emailRecTypeIid = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Email').getRecordTypeId();
        List<PJN_Contact_Information__c> emails = new List<PJN_Contact_Information__c>();
        for (Account acct : accounts) {
            emails.add(
                new PJN_Contact_Information__c(
                    PJN_Account__c = acct.Id,
                    PJN_Set_as_Primary__c = true,
                    PJN_Email__c = 'testemail@regneron.test',
                    RecordTypeId = emailRecTypeIid
                ) 
            );
            emails.add(
                new PJN_Contact_Information__c(
                    PJN_Account__c = acct.Id,
                    PJN_Set_as_Primary__c = false,
                    PJN_Email__c = 'testemail-1@regneron.test',
                    RecordTypeId = emailRecTypeIid
                )
            );
        }
        return emails;
    }

    /*** Phone/Fax Tests ***/
    @isTest
    private static void itShouldCopyPrimaryPhoneToAccountOnInsert() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> phones = createPhonesFor(progParticipants, 'PJN_Phone');
        
        Test.startTest();
        insert phones;
        Test.stopTest();

        progParticipants = [SELECT Phone FROM Account WHERE Id IN :progParticipants];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assertEquals('5555555555', participant.Phone);
        }
    }

    @isTest
    private static void itShouldCopyPrimaryPhoneToAccountOnUpdate() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> phones = createPhonesFor(progParticipants, 'PJN_Phone');
        
        insert phones;
        for (PJN_Contact_Information__c phone : phones) {
            if (phone.PJN_Phone__c == '6666666666') {
                phone.PJN_Set_as_Primary__c = true;
            }
        }
        Test.startTest();
        update phones;
        Test.stopTest();

        progParticipants = [SELECT Phone FROM Account WHERE Id IN :progParticipants];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assertEquals('6666666666', participant.Phone);
        }
    }

    @isTest
    private static void itShouldCopyPrimaryFaxToAccountOnInsert() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> faxes = createPhonesFor(progParticipants, 'PJN_Fax');
        
        Test.startTest();
        insert faxes;
        Test.stopTest();

        progParticipants = [SELECT Fax FROM Account WHERE Id IN :progParticipants];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assertEquals('5555555555', participant.Fax);
        }
    }

    @isTest
    private static void itShouldCopyPrimaryFaxToAccountOnUpdate() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> faxes = createPhonesFor(progParticipants, 'PJN_Fax');
        
        insert faxes;
        for (PJN_Contact_Information__c fax : faxes) {
            if (fax.PJN_Fax__c == '6666666666') {
                fax.PJN_Set_as_Primary__c = true;
            }
        }
        Test.startTest();
        update faxes;
        Test.stopTest();

        progParticipants = [SELECT Fax FROM Account WHERE Id IN :progParticipants];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assertEquals('6666666666', participant.Fax);
        }
    }

    private static List<PJN_Contact_Information__c> createPhonesFor(List<Account> accounts, String recTypeDevName) {
        Id phoneRecTypeIid = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get(recTypeDevName).getRecordTypeId();
        List<PJN_Contact_Information__c> phones = new List<PJN_Contact_Information__c>();
        for (Account acct : accounts) {
            phones.add(
                new PJN_Contact_Information__c(
                    PJN_Account__c = acct.Id,
                    PJN_Set_as_Primary__c = true,
                    PJN_Phone__c = '5555555555',
                    PJN_Fax__c = '5555555555',
                    RecordTypeId = phoneRecTypeIid
                ) 
            );
            phones.add(
                new PJN_Contact_Information__c(
                    PJN_Account__c = acct.Id,
                    PJN_Set_as_Primary__c = false,
                    PJN_Phone__c = '6666666666',
                    PJN_Fax__c = '6666666666',
                    RecordTypeId = phoneRecTypeIid
                )
            );
        }
        return phones;
    }

    /*** Address Tests ***/
    @isTest
    private static void itShouldCopyPrimaryAddressToPersonAccount() {
        List<Account> progParticipants = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Program_Participant_MVN'];
        List<PJN_Contact_Information__c> addresses = createAddressesFor(progParticipants);
        
        Test.startTest();
        insert addresses;
        Test.stopTest();

        progParticipants = [
            SELECT PersonMailingStreet, PersonMailingCity, PersonMailingState, PersonMailingPostalCode, PersonMailingCountry 
            FROM Account 
            WHERE Id IN :progParticipants            
        ];
        System.assertEquals(DATA_SIZE, progParticipants.size());
        for (Account participant : progParticipants) {
            System.assert(participant.PersonMailingStreet.contains('123 Main St.'));
            System.assert(participant.PersonMailingStreet.contains('Suite 1'));
            System.assertEquals('Tarrytown', participant.PersonMailingCity);
            System.assertEquals('NY', participant.PersonMailingState);
            System.assertEquals('22222', participant.PersonMailingPostalCode);
            System.assertEquals('United States', participant.PersonMailingCountry);
        }
    }

    @isTest
    private static void itShouldCopyPrimaryAddressToBusinessAccount() {
        List<Account> businesses = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'IndustriesBusiness'];
        List<PJN_Contact_Information__c> addresses = createAddressesFor(businesses);
        
        Test.startTest();
        insert addresses;
        Test.stopTest();

        businesses = [
            SELECT BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry
            FROM Account 
            WHERE Id IN :businesses
        ];
        System.assertEquals(DATA_SIZE, businesses.size());
        for (Account business : businesses) {
            System.assert(business.BillingStreet.contains('123 Main St.'));
            System.assert(business.BillingStreet.contains('Suite 1'));
            System.assertEquals('Tarrytown', business.BillingCity);
            System.assertEquals('NY', business.BillingState);
            System.assertEquals('22222', business.BillingPostalCode);
            System.assertEquals('United States', business.BillingCountry);
        }
    }


    private static List<PJN_Contact_Information__c> createAddressesFor(List<Account> accounts) {
        Id addrRecordtypeId = SObjectType.PJN_Contact_Information__c.getRecordTypeInfosByDeveloperName().get('PJN_Address').getRecordTypeId();
        List<PJN_Contact_Information__c> addresses = new List<PJN_Contact_Information__c>();
        for (Account acct : accounts) {
            addresses.add(
                new PJN_Contact_Information__c(
                    PJN_Account__c = acct.Id,
                    PJN_Set_as_Primary__c = true,
                    PJN_Address_Line_1__c = '123 Main St.',
                    PJN_Address_Line_2__c = 'Suite 1.',
                    PJN_City__c = 'Tarrytown',
                    PJN_State__c = 'NY',
                    PJN_Postal_Code__c = '22222',
                    PJN_Country__c = 'United States',
                    RecordTypeId = addrRecordtypeId
                ) 
            );
        }
        return addresses;
    }
}