force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/MVN_RBM_Sharing_Setting__mdt.object-meta.xml
<CustomObject>
    <description>A record represents the number of days that a Case with a given Therapy Status/Sub-Status combination or Pharmacy Status is visible to the RBM group.</description>
    <label>RBM Sharing Setting</label>
    <pluralLabel>RBM Sharing Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Days_Visible__c.field-meta.xml
<CustomField>
    <fullName>MVN_Days_Visible__c</fullName>
    <description>Amount of time, in days, that records with either a Therapy Status/Sub-Status or a Pharmacy Status should be visible to RBMs.</description>
    <label>Days Visible</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>MVN_Program_Name__c</fullName>
    <description>DeveloperName of the Program custom metadata that the sharing setting applies to.</description>
    <label>Program Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Status__c</fullName>
    <description>Therapy Status or Pharmacy Status value that the setting applies to.</description>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Sub_Status__c</fullName>
    <description>Therapy Sub-Status that the setting applies to.</description>
    <label>Sub-Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/MVN_RBM_Sharing_Setting__mdt/fields/MVN_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Type__c</fullName>
    <description>The Status field that the setting applies to.  &apos;Therapy&apos; for Therapy Status, &apos;Pharmacy&apos; for Pharmacy Status.</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Therapy</fullName>
                <default>true</default>
                <label>Therapy</label>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/MVN_RBMSharingSettingsQueryTest.cls
/**
* @author Mavens
* @description Unit tests for MVN_RBMSharingSettingsQuery
* @group RBM
*/
@isTest
public class MVN_RBMSharingSettingsQueryTest {


    @isTest 
    private static void itShouldQueryForProgramTherapyStatusMap() {

        List<MVN_RBM_Sharing_Setting__mdt> settings = new List<MVN_RBM_Sharing_Setting__mdt>();
        settings.add(
            new MVN_RBM_Sharing_Setting__mdt(
                DeveloperName = 'Therapy_Cancelled_Patient_Deceased',
                MVN_Days_Visible__c = 180,
                MVN_Status__c = 'Cancelled',
                MVN_Sub_Status__c = 'Patient Deceased',
                MVN_Type__c = 'Therapy',
                MVN_Program_Name__c = 'MVN_EVK'
            )
        );

        Map<String,List<String>> therapyStatusMap = new Map<String,List<String>>();
        therapyStatusMap.put('Cancelled', new List<String> { 'Patient Deceased' });

        Map<String,Map<String,List<String>>> programTherapyStatusMap = new Map<String,Map<String,List<String>>>();
        programTherapyStatusMap.put('MVN_EVK', therapyStatusMap);
        
        Test.startTest();

        MVN_RBMSharingSettingsQuery query = new MVN_RBMSharingSettingsQuery();
        query.settings = settings;

        List<MVN_RBM_Sharing_Setting__mdt> returned = query.forProgramTherapyStatusMap(programTherapyStatusMap);
        
        Test.stopTest();

        System.assertNotEquals(null, returned);
    }

    @isTest 
    private static void itShouldQueryForProgramPharmacyStatusMap() {

        List<MVN_RBM_Sharing_Setting__mdt> settings = new List<MVN_RBM_Sharing_Setting__mdt>();
        settings.add(
            new MVN_RBM_Sharing_Setting__mdt(
                DeveloperName = 'Unknown',
                MVN_Days_Visible__c = 180,
                MVN_Status__c = 'Unknown',
                MVN_Sub_Status__c = '',
                MVN_Type__c = 'Pharmacy',
                MVN_Program_Name__c = 'MVN_EVK'
            )
        );

        Set<String> pharmacyStatusSet = new Set<String> { 'Unknown' }; 

        Map<String,Set<String>> programPharmacyStatusMap = new Map<String,Set<String>>();
        programPharmacyStatusMap.put('MVN_EVK', pharmacyStatusSet);
        
        Test.startTest();
        
        MVN_RBMSharingSettingsQuery query = new MVN_RBMSharingSettingsQuery();
        query.settings = settings;

        List<MVN_RBM_Sharing_Setting__mdt> returned = query.forProgramPharmacyStatusMap(programPharmacyStatusMap);
        
        Test.stopTest();

        System.assertNotEquals(null, returned);
    }
}