force-app/main/default/src/objects/PJN_Enrollment_Wizard_Component__mdt/PJN_Enrollment_Wizard_Component__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Enrollment Wizard
Purpose: Define section title, type of component and its order within the Enrollment Wizard Step. This is step 3 in setting up the Enrollment Wizard.
Metadata Relationship(s): Enrollment Wizard Step; Enrollment Wizard Record Form; Enrollment Wizard Record List
Created by Mavens: Yes</description>
    <label>Enrollment Wizard Component</label>
    <pluralLabel>Enrollment Wizard Components</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Component__mdt/fields/PJN_Component_To_Load__c.field-meta.xml
<CustomField>
    <fullName>PJN_Component_To_Load__c</fullName>
    <label>Component To Load</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Component__mdt/fields/PJN_Enrollment_Wizard_Step__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Wizard_Step__c</fullName>
    <label>Enrollment Wizard Step</label>
    <referenceTo>PJN_Enrollment_Wizard_Step__mdt</referenceTo>
    <relationshipLabel>Enrollment Wizard Components</relationshipLabel>
    <relationshipName>PJN_Enrollment_Wizard_Components</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Component__mdt/fields/PJN_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Component__mdt/fields/PJN_Section_Title__c.field-meta.xml
<CustomField>
    <fullName>PJN_Section_Title__c</fullName>
    <description>The title for the section that this component creates.</description>
    <label>Section Title</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_EnrollmentWizardComponentQuery.cls
/**
 * @author Mavens
 * @date Mar 2019
 * @description Class to query custom metadata types for PJN_Enrollment_Wizard_Component__mdt
 * @group EnrollmentWizard
 */
public with sharing class PJN_EnrollmentWizardComponentQuery {

    /**
     * Query enrollment wizard components by enrollment wizard step id
     * @param   stepId   enrollment wizard step id
     * @returns           List<PJN_Enrollment_Wizard_Component__mdt>
     */
    public List<PJN_Enrollment_Wizard_Component__mdt> getEnrollmentComponentsByStep(Id stepId) {
        return [
            SELECT
                Id,
                Label,
                PJN_Order__c,
                PJN_Component_To_Load__c,
                PJN_Section_Title__c
            FROM
                PJN_Enrollment_Wizard_Component__mdt
            WHERE
                PJN_Enrollment_Wizard_Step__c = :stepId
            ORDER BY
                PJN_Order__c ASC
        ];
    }
}