force-app/main/default/src/objects/PJN_Enrollment_Wizard_Step__mdt/PJN_Enrollment_Wizard_Step__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Enrollment Wizard
Purpose: Define enrollment wizard screen and its order for a specific enrollment wizard setting. This is step 2 in setting up the Enrollment Wizard.
Metadata Relationship(s): Enrollment Wizard Setting; Enrollment Wizard Component
Created by Mavens: Yes</description>
    <label>Enrollment Wizard Step</label>
    <pluralLabel>Enrollment Wizard Steps</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Step__mdt/fields/PJN_Enrollment_Wizard_Setting__c.field-meta.xml
<CustomField>
    <fullName>PJN_Enrollment_Wizard_Setting__c</fullName>
    <label>Enrollment Wizard Setting</label>
    <referenceTo>PJN_Enrollment_Wizard_Setting__mdt</referenceTo>
    <relationshipLabel>Enrollment Wizard Steps</relationshipLabel>
    <relationshipName>PJN_Enrollment_Wizard_Steps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Step__mdt/fields/PJN_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/classes/PJN_EnrollmentWizardStepQuery.cls
/**
 * @author Mavens
 * @date Mar 2019
 * @description Class to query custom metadata types for PJN_Enrollment_Wizard_Step__mdt
 * @group EnrollmentWizard
 */
public with sharing class PJN_EnrollmentWizardStepQuery {

    /**
     * Query enrollment wizard steps bry program
     * @param  programDevName   program developer name
     * @returns                  List<PJN_Enrollment_Wizard_Step__mdt>
     */
    public List<PJN_Enrollment_Wizard_Step__mdt> getEnrollmentStepsByProgram(String programDevName) {
        PJN_EnrollmentWizardSettingQuery enrollmentSettingQuery = new PJN_EnrollmentWizardSettingQuery();
        return [
            SELECT
                Id,
                Label,
                PJN_Order__c
            FROM
                PJN_Enrollment_Wizard_Step__mdt
            WHERE
                PJN_Enrollment_Wizard_Setting__c = :enrollmentSettingQuery.getAllSettingsByProgram().get(programDevName).Id
            ORDER BY
                PJN_Order__c ASC
        ];
    }
}