force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Exception_JSON__c.field-meta.xml
<CustomField>
    <fullName>PJN_Exception_JSON__c</fullName>
    <label>Exception JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Message__c.field-meta.xml
<CustomField>
    <fullName>PJN_Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_SObject_JSON__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_JSON__c</fullName>
    <label>SObject JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_SObject_Type__c</fullName>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Log_Event__e/fields/PJN_Source__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source__c</fullName>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_LogEventHdlr.cls
/**
 * @author      Mavens
 * @group       Log
 * @description publish log event
 */
public inherited sharing class PJN_LogEventHdlr {
    /**
     * publish log event
     * @param   String      source
     * @param   String      message
     * @param   Object      thisException
     * @param   SObject      thisSObject
     * @returns  Database.SaveResult
     */
    public static Database.SaveResult publishLogEvent(String source, String message, Object thisException, SObject thisSObject) {
        String exceptionType;
        String exceptionJson;

        if (thisException instanceof Database.SaveResult) {
            exceptionType = 'Database.SaveResult';
            exceptionJson = JSON.serializePretty(thisException, true);
        } else if (thisException instanceof Database.UpsertResult) {
            exceptionType = 'Database.UpsertResult';
            exceptionJson = JSON.serializePretty(thisException, true);
        } else {
            exceptionType = 'Exception';
            exceptionJson = ((Exception)thisException).getStackTraceString();
        }

        return EventBus.publish(
            new PJN_Log_Event__e(
                PJN_Source__c = source,
                PJN_Message__c = message,
                PJN_Exception_Type__c = exceptionType,
                PJN_Exception_JSON__c = exceptionJson,
                PJN_SObject_Type__c = thisSObject.getSObjectType().getDescribe().getName(),
                PJN_SObject_JSON__c = JSON.serializePretty(thisSObject, true)
            )
        );
    }
}