force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Coverage Investigation where the Therapy Access event is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Therapy Access</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/PJN_Trigger_Handler_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Triggers
Purpose: Define the order of execution of triggers. This is a global setting for all Programs and should not need to be changed.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Class__c.field-meta.xml
<CustomField>
    <fullName>PJN_Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Trigger_Handler_Setting__mdt/fields/PJN_Event__c.field-meta.xml
<CustomField>
    <fullName>PJN_Event__c</fullName>
    <label>Event</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_DELETE</fullName>
                <default>true</default>
                <label>AFTER_DELETE</label>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_TriggerTestMockHelper.cls
@isTest
public class PJN_TriggerTestMockHelper {

    public static void mock(SObjectType objectType) {
        String objectName = objectType.getDescribe().getName();
        switch on (objectName) {
            when 'PJN_Coverage_Investigation__c' {
                handleCoverageInvestigation();
            }
        }
    }

    private static void handleCoverageInvestigation() {
        List<PJN_Trigger_Handler_Setting__mdt> settings = new List<PJN_Trigger_Handler_Setting__mdt>{
            new PJN_Trigger_Handler_Setting__mdt(
                DeveloperName='PJN_Before_Update_Active_Investigation',
                PJN_Class__c='PJN_ActiveCoverageInvestigationHdlr',
                PJN_Event__c='BEFORE_UPDATE'
            ),
            new PJN_Trigger_Handler_Setting__mdt(
                DeveloperName='PJN_Before_Insert_Active_Investigation',
                PJN_Class__c='PJN_ActiveCoverageInvestigationHdlr',
                PJN_Event__c='BEFORE_INSERT'
            ),
            new PJN_Trigger_Handler_Setting__mdt(
                DeveloperName='PJN_After_Insert_Active_Investigation',
                PJN_Class__c='PJN_ActiveCoverageInvestigationHdlr',
                PJN_Event__c='AFTER_INSERT'
            ),
            new PJN_Trigger_Handler_Setting__mdt(
                DeveloperName='PJN_After_Update_Active_Investigation',
                PJN_Class__c='PJN_ActiveCoverageInvestigationHdlr',
                PJN_Event__c='AFTER_UPDATE'
            )
        };

        PJN_TriggerHandlerSettingQuery.triggerHandlerSettingBySObjectType.put(
            PJN_Coverage_Investigation__c.SObjectType,
            settings
        );
    }
}