force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Access_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Access_Type__c</fullName>
    <description>The type of Access the patient has following the Coverage Investigation.</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Coverage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/PJN_Event__c.object-meta.xml
<CustomObject>
    <description>Object to track Events for patients, referrals, and shipments. It goes together with Event Values and Event Automation objects.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Access_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Access_Type__c</fullName>
    <description>The patient&apos;s method of obtaining funding and access to therapy during the duration of the Event.</description>
    <label>Access Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PJN_Coverage_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Coverage Investigation where the Therapy Access event is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Therapy Access</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Event__c/fields/PJN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Start_Date__c</fullName>
    <description>Start date of the Event.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/globalValueSets/PJN_Coverage_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Medicaid</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare</fullName>
    </customValue>
    <customValue>
        <fullName>Tricare</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Assistance Program</fullName>
    </customValue>
    <customValue>
        <fullName>Interim Access Program</fullName>
    </customValue>
    <customValue>
        <fullName>Clinical Trial Transition Program</fullName>
    </customValue>
    <customValue>
        <fullName>Bridge Program</fullName>
        <isActive>false</isActive>
        <label>Bridge Program</label>
    </customValue>
    <customValue>
        <fullName>Quick Start</fullName>
        <isActive>false</isActive>
        <label>Quick Start</label>
    </customValue>
    <masterLabel>Coverage Types</masterLabel>
</GlobalValueSet>

force-app/main/default/src/classes/PJN_CoverageInvestigationEventHdlr.cls
/**
 * @author      Mavens
 * @date       05/2021
 * @description Coverage Investigation Event handler to process logic based on event values
 * @group       CoverageInvestigation
 */
public with sharing class PJN_CoverageInvestigationEventHdlr implements PJN_TriggerDispatcher.HandlerInterface {

    public void handle() {
        Set<Id> coverageInvestigationIds = new Set<Id>();
        List<PJN_Event__c> scope;
        if (Trigger.isDelete) {
            scope = (List<PJN_Event__c>) Trigger.old;
        } else {
            scope = (List<PJN_Event__c>) Trigger.new;
        }

        for (PJN_Event__c event : scope) {
            if (event.PJN_Coverage_Investigation__c != null && String.isNotBlank(event.PJN_Access_Type__c)) {
                // if there are more than one event for the coverage investigation the last in
                // will be the winner. This is the desired outcome.
                coverageInvestigationIds.add(event.PJN_Coverage_Investigation__c);
            }
        }

        if (coverageInvestigationIds.isEmpty()) {
            return; // nothing to process
        }

        List<PJN_Coverage_Investigation__c> investigations = [
            SELECT
                Id,
                PJN_Access_Type__c,
                (
                    SELECT PJN_Access_Type__c
                    FROM Events__r
                    WHERE PJN_Access_Type__c != null
                    ORDER BY PJN_Start_Date__c DESC NULLS LAST
                )
            FROM PJN_Coverage_Investigation__c
            WHERE Id IN :coverageInvestigationIds
        ];

        for (PJN_Coverage_Investigation__c investigation : investigations) {
            if (!investigation.Events__r.isEmpty()) {
                PJN_Event__c event = investigation.Events__r[0];
                investigation.PJN_Access_Type__c = event.PJN_Access_Type__c;
            } else {
                investigation.PJN_Access_Type__c = null;
            }
        }

        update investigations;
    }
}