force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <description>Indicates whether  the Assistance Program is currently Active</description>
    <formula>TODAY() &gt;=  PJN_Effective_Date__c &amp;&amp; 
TODAY() &lt;=  PJN_Expiration_Date__c &amp;&amp;
 TEXT( PJN_Outcome__c ) == &apos;Eligible&apos;</formula>
    <inlineHelpText>Indicates whether  the Assistance Program is currently Active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Coverage Investigation where the Assistance Program was generated from.</description>
    <label>Coverage Investigation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.PJN_Care_Plan__c</field>
            <operation>equals</operation>
            <valueField>PJN_Coverage_Investigation__c.PJN_Care_Plan__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Member Plan which a Copay Assistance Program is linked to.</description>
    <label>Member Plan</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a Member Plan from the same Care Plan.</errorMessage>
        <filterItems>
            <field>PJN_Member_Plan__c.PJN_Care_Plan__c</field>
            <operation>equals</operation>
            <valueField>$Source.PJN_Care_Plan__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Copay Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/PJN_Coverage_Investigation__c.object-meta.xml
<CustomObject>
    <description>The Coverage Investigation object is used to store information related to a patient&apos;s therapy coverage options and the outcome of the investigation.</description>
    <label>Coverage Investigation</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Coverage Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>The parent Care Plan where the Coverage Investigation is run from.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Coverage Investigations</relationshipLabel>
    <relationshipName>Coverage_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <defaultValue>&apos;Standard&apos;</defaultValue>
    <description>Indicates the type of investigation being performed</description>
    <label>Investigation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PJN_Initial_Investigation</fullName>
                <default>true</default>
                <label>Initial Investigation</label>
            </value>
            <value>
                <fullName>PJN_Re-Authorization</fullName>
                <label>Re-Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/PJN_Coverage_Investigation_Item__c.object-meta.xml
<CustomObject>
    <description>Patient Journey Navigator custom object which stores the join between a Coverage Investigation and the items involved such as Member Plans.</description>
    <label>Coverage Investigation Item</label>
    <nameField>
        <displayFormat>CII-{000000}</displayFormat>
        <label>Coverage Investigation Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Investigation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Assistance_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Assistance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Assistance Programs being assessed in the Coverage Investigation.</description>
    <label>Assistance Program</label>
    <referenceTo>PJN_Assistance_Program__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <description>The parent Coverage Investigation which the items are related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/fields/PJN_Prior_Authorization__c.field-meta.xml
<CustomField>
    <fullName>PJN_Prior_Authorization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The patient&apos;s Member Plan being assessed in the Coverage Investigation.</description>
    <label>Prior Authorization</label>
    <referenceTo>PJN_Prior_Authorization__c</referenceTo>
    <relationshipLabel>Coverage Investigation Items</relationshipLabel>
    <relationshipName>Coverage_Investigation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Coverage_Investigation_Item__c/recordTypes/PJN_Member_Plan.recordType-meta.xml
<RecordType>
    <fullName>PJN_Member_Plan</fullName>
    <active>true</active>
    <description>A Member Plan benefit investigation item.</description>
    <label>Member Plan</label>
</RecordType>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <description>Formula checkbox to indicate whether or not a patient&apos;s member plan record matches either the PJN_Primary_Member_Plan__c, PJN_Secondary_Member_Plan__c, or PJN_Tertiary_Member_Plan__c case field value. If so, value is set to TRUE which means the record is currently an active primary, secondary or tertiary member plan for a patient.</description>
    <formula>IF(ISPICKVAL(PJN_Coverage_Order__c, &quot;Primary&quot;),
Id = PJN_Care_Plan__r.PJN_Primary_Member_Plan__c,
IF(ISPICKVAL(PJN_Coverage_Order__c, &quot;Secondary&quot;),
Id = PJN_Care_Plan__r.PJN_Secondary_Member_Plan__c,
IF(ISPICKVAL(PJN_Coverage_Order__c, &quot;Tertiary&quot;),
Id = PJN_Care_Plan__r.PJN_Tertiary_Member_Plan__c,
False
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/PJN_Prior_Authorization__c.object-meta.xml
<CustomObject>
    <description>Custom object to track prior authorizations related to member plans.</description>
    <label>Prior Authorization</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Prior Authorization Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prior Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <description>Indicates whether the Prior Authorization is currently Active</description>
    <formula>TODAY() &gt;= PJN_Effective_Date__c &amp;&amp;
TODAY() &lt;= PJN_Expiration_Date__c &amp;&amp;
ISPICKVAL( PJN_Outcome__c, &apos;Approved&apos;)</formula>
    <inlineHelpText>Indicates whether the Prior Authorization is currently Active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care plan the parent member plan belongs to.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Coverage_Investigation__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Coverage Investigation which the Prior Authorization is related to.</description>
    <label>Coverage Investigation</label>
    <referenceTo>PJN_Coverage_Investigation__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>Prior_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Member_Plan__c</fullName>
    <description>Master detail relationship with Member Plan.</description>
    <label>Member Plan</label>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Prior Authorizations</relationshipLabel>
    <relationshipName>PJN_Prior_Authorizations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Prior_Authorization__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Type of prior authorization.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Appeal - 1st Level</fullName>
            </value>
            <value>
                <fullName>Appeal - 2nd Level</fullName>
            </value>
            <value>
                <fullName>Appeal - 3rd Level</fullName>
            </value>
            <value>
                <fullName>Appeal - Peer-to-Peer</fullName>
            </value>
            <value>
                <fullName>Appeal - External Review</fullName>
            </value>
            <value>
                <fullName>Appeal - Formal Grievance</fullName>
            </value>
            <value>
                <fullName>Reauthorization</fullName>
            </value>
            <value>
                <fullName>Appeal</fullName>
                <isActive>false</isActive>
                <label>Appeal</label>
            </value>
            <value>
                <fullName>External Review</fullName>
                <isActive>false</isActive>
                <label>External Review</label>
            </value>
            <value>
                <fullName>Formal Grievance</fullName>
                <isActive>false</isActive>
                <label>Formal Grievance</label>
            </value>
            <value>
                <fullName>Peer-to-Peer</fullName>
                <isActive>false</isActive>
                <label>Peer-to-Peer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_CoverageInvestigationHelper.cls
/**
 * @author      Mavens
 * @date        11/2020
 * @description Handles new coverage investigation trigger logic and provdes aura methods for the
 *              coverage investigation quick actions
 * @group       CoverageInvestigation
 */
public with sharing class PJN_CoverageInvestigationHelper {

    @AuraEnabled
    public static string getInvestigationCarePlanId(String investigationId){
        try {
            return [
                SELECT PJN_Care_Plan__c
                FROM PJN_Coverage_Investigation__c
                WHERE Id = :investigationId
            ].PJN_Care_Plan__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<PJN_Member_Plan__c> retrieveMemberPlans(Id carePlanId){
        try {
            Map<Id, List<PJN_Member_Plan__c>> activeMemberPlans
                = retrieveMemberPlans(new Set<Id>{carePlanId});

            if (activeMemberPlans.containsKey(carePlanId)){
                return activeMemberPlans.get(carePlanId);
            }

            return new List<PJN_Member_Plan__c>();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<PJN_FieldWrapper> getFieldSet(){
        try {
            Schema.FieldSet mpFieldSet = PJN_Member_Plan__c.sObjectType
                .getDescribe()
                .fieldSets.getMap()
                .get('PJN_Coverage_Investigation_Add_Screen');
            List<PJN_FieldWrapper> mpFieldWrappers = new List<PJN_FieldWrapper>();
            for (Schema.FieldSetMember fsm: mpFieldSet.getFields()) {
                mpFieldWrappers.add(
                    new PJN_FieldWrapper('PJN_Member_Plan__c', fsm.getSObjectField().getDescribe())
                );
            }

            return mpFieldWrappers;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Query for active member plans given a set of care plan ids
     * @param carePlanIds
     * @returns `Map<Id, List<PJN_Member_Plan__c>>`
     */
    public static Map<Id, List<PJN_Member_Plan__c>> retrieveMemberPlans(Set<Id> carePlanIds) {
        Set<String> memberPlanFields = new Set<String> { 'Id', 'PJN_Care_Plan__c', 'PJN_Active__c'};
        for (PJN_FieldWrapper fieldWrapper : getFieldSet())  {
            memberPlanFields.add(fieldWrapper.fieldName);
        }

        // gather and sort member plans
        List<PJN_Member_Plan__c> memberPlans = Database.query(
            'SELECT ' + String.join(new List<String>(memberPlanFields), ', ') + ' ' +
            'FROM PJN_Member_Plan__c ' +
            'WHERE PJN_Care_Plan__c IN :carePlanIds'
        );

        Map<Id, List<PJN_Member_Plan__c>> activeMemberPlansByCarePlan = new Map<Id, List<PJN_Member_Plan__c>>();
        for (PJN_Member_Plan__c memberPlan : memberPlans) {
            if (!activeMemberPlansByCarePlan.containsKey(memberPlan.PJN_Care_Plan__c)) {
                activeMemberPlansByCarePlan.put(
                    memberPlan.PJN_Care_Plan__c,
                    new List<PJN_Member_Plan__c>()
                );
            }
            activeMemberPlansByCarePlan.get(memberPlan.PJN_Care_Plan__c)
                .add(memberPlan);
        }
        return activeMemberPlansByCarePlan;
    }

    @AuraEnabled
    public static List<PJN_Coverage_Investigation_Item__c> retrieveCoverageInvestigationItems(Id investigationId){
        return [
            SELECT Id, PJN_Assistance_Program__c, PJN_Member_Plan__c, PJN_Prior_Authorization__c
            FROM PJN_Coverage_Investigation_Item__c
            WHERE PJN_Coverage_Investigation__c =  :investigationId
        ];
    }

    /**
     * Query for Prior Authorizaions for given member plans
     * @param carePlanIds
     * @returns `Map<Id, List<PJN_Prior_Authorization__c>>`
     */
    @AuraEnabled
    public static Id createCoverageInvestigationItems(
        PJN_Coverage_Investigation__c coverageInvestigation,
        List<String> memberPlanIds
    ) {
        try {
            if (coverageInvestigation.Id == null) {
                insert coverageInvestigation;

                // When inserting non-standard investigations a trigger will create new records
                if (coverageInvestigation.PJN_Type__c != 'PJN_Initial_Investigation') {
                    return coverageInvestigation.Id;
                }
            }

            List<PJN_Coverage_Investigation_Item__c> items = new List<PJN_Coverage_Investigation_Item__c>();
            Id ciiRecTypeId = SObjectType.PJN_Coverage_Investigation_Item__c
                .getRecordTypeInfosByDeveloperName()
                .get('PJN_Member_Plan')
                .getRecordTypeId();


            for (String id : memberPlanIds) {
                PJN_Coverage_Investigation_Item__c item = new PJN_Coverage_Investigation_Item__c (
                    PJN_Coverage_Investigation__c = coverageInvestigation.Id,
                    RecordTypeId = ciiRecTypeId
                );
                item.PJN_Member_Plan__c = id;
                items.add(item);
            }

            insert items;

            return coverageInvestigation.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}