force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/classes/PJN_AssistanceProgramQueryMock.cls
/**
 * @author      Mavens
 * @date        11/2020
 * @description Mock response for PJN_AssistanceProgramQuery
 * @group       CoverageInvestigation
 */
@isTest
public with sharing class PJN_AssistanceProgramQueryMock implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'activeByCarePlanId') {
            return this.activeByCarePlanId((Set<String>)listOfArgs[0], (Set<Id>)listOfArgs[1]);
        } else {
            return null;
        }
    }

    private List<PJN_Assistance_Program__c> activeByCarePlanId(Set<String> fields, Set<Id> carePlanIds) {
        List<PJN_Assistance_Program__c> assistancePrograms = new List<PJN_Assistance_Program__c>();
        for (Id carePlanId : carePlanIds) {
            assistancePrograms.add(new PJN_Assistance_Program__c(PJN_Care_Plan__c=carePlanId));
            assistancePrograms.add(new PJN_Assistance_Program__c(PJN_Care_Plan__c=carePlanId));
        }
        return assistancePrograms;
    }
}