force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Active__c</fullName>
    <description>Indicates whether  the Assistance Program is currently Active</description>
    <formula>TODAY() &gt;=  PJN_Effective_Date__c &amp;&amp; 
TODAY() &lt;=  PJN_Expiration_Date__c &amp;&amp;
 TEXT( PJN_Outcome__c ) == &apos;Eligible&apos;</formula>
    <inlineHelpText>Indicates whether  the Assistance Program is currently Active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Assistance Programs</relationshipLabel>
    <relationshipName>Assistance_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/classes/PJN_AssistanceProgramQuery.cls
/**
 * @author      Mavens
 * @date        11/2020
 * @description Wrapper for PJN_Assistance_Program__c queries. Allows for mocking of responses
 *              since customers can configure the PJN_Active__c field
 * @group       CoverageInvestigation
 */
public with sharing class PJN_AssistanceProgramQuery {

    public List<PJN_Assistance_Program__c> activeByCarePlanId(Set<String> fields, Set<Id> carePlanIds) {
        return Database.query(
            'SELECT ' + String.join(new List<String>(fields), ', ') + ' ' +
            'FROM PJN_Assistance_Program__c ' +
            'WHERE PJN_Active__c = true ' +
            'AND PJN_Care_Plan__c IN :carePlanIds'
        );
    }
}