force-app/main/default/src/objects/PJN_Assistance_Program__c/PJN_Assistance_Program__c.object-meta.xml
<CustomObject>
    <description>Stores the application details and approval status of enrollments to various Assistance Programs</description>
    <label>Assistance Program</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Assistance Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistance Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Activated_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Activated_Date__c</fullName>
    <description>Date and time when the membership was activated.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Activated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_BIN__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_BIN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay BIN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Caregiver_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Caregiver_Id__c</fullName>
    <description>The unique identifier for the Caregiver.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Copay Caregiver Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Effective_Date__c</fullName>
    <description>Date and time when the membership becomes active.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Enrollment_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Enrollment_Id__c</fullName>
    <description>The unique identifier for the enrollment.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Copay Enrollment Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Enrollment_Success__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Enrollment_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copay Enrollment Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Issued_Date__c</fullName>
    <description>Date and time when the membership was issued in ISO 8601 Notation.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Issued Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Member_Id__c</fullName>
    <description>The unique number a plan assigns to a member.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Member Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Patient_Id__c</fullName>
    <description>The unique identifier for the Patient.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Copay Patient Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Total_Uses__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Total_Uses__c</fullName>
    <description>Maximum times the membership benefit can be used.</description>
    <label>Copay Total Uses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Assistance_Program__c/fields/MVN_Copay_Usage_Period_Unit__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Usage_Period_Unit__c</fullName>
    <description>The unit for the relative time period that the membership benefit.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Usage Period Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/PJN_Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <description>This is the object which will allow us to send requests to third-parties like Specialty Pharmacies and Clinical Trainers.</description>
    <label>Fulfillment Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Fulfillment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Caregiver_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Caregiver_Id__c</fullName>
    <description>The unique identifier for the Caregiver.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Caregiver Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Deactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Deactivated_Date__c</fullName>
    <description>Date and time when the membership was deactivated.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Deactivated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Eligibility_Check_Type__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Eligibility_Check_Type__c</fullName>
    <description>The type of eligibility check performed.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Eligibility Check Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Enrollment_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Enrollment_Id__c</fullName>
    <description>The unique identifieer for the enrollment.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Enrollment Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Enrollment_Result_Details__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Enrollment_Result_Details__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Enrollment Result Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Expiration_Date__c</fullName>
    <description>Date and time when the membership expires.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Group_Number__c</fullName>
    <description>The plan&apos;s pharmacy group number or the unique number a plan assigns to an employer group or another entity purchasing health coverage on behalf of its employees/members.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Group Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Is_Activated__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Is_Activated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Membership has been activated.</description>
    <label>Copay Is Activated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Membership is active.</description>
    <label>Copay Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Is_Reenrollment__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Is_Reenrollment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copay Is Reenrollment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Member_Id__c</fullName>
    <description>The unique number a plan assigns to a member.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Copay Member Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Patient_Id__c</fullName>
    <description>The unique identifier for the Patient.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Patient Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_PCN__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_PCN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay PCN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Program_Cap__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Program_Cap__c</fullName>
    <description>Maximum benefit amount.</description>
    <label>Copay Program Cap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Status__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Copay Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/MVN_Copay_Usage_Period__c.field-meta.xml
<CustomField>
    <fullName>MVN_Copay_Usage_Period__c</fullName>
    <description>The value for the relative time period that the membership benefit can be used.</description>
    <label>Copay Usage Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/fields/PJN_Fulfillment_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>PJN_Fulfillment_Request_Status__c</fullName>
    <description>Status of the fulfillment request.</description>
    <label>Fulfillment Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/recordTypes/MVN_Copay_Enrollment.recordType-meta.xml
<RecordType>
    <fullName>MVN_Copay_Enrollment</fullName>
    <active>true</active>
    <description>Defines a request to enroll a patient in commercial copay</description>
    <label>Copay Enrollment</label>
</RecordType>

force-app/main/default/src/objects/PJN_Fulfillment_Request__c/recordTypes/MVN_Copay_Submitted.recordType-meta.xml
<RecordType>
    <fullName>MVN_Copay_Submitted</fullName>
    <active>true</active>
    <description>Defines a submitted request to enroll a patient in commercial copay</description>
    <label>Copay - Submitted</label>
</RecordType>

force-app/main/default/src/classes/MVN_ConnectiveRxEnrollResult.cls
/**
 * @author      Mavens
 * @group       ConnectiveRx
 * @description Wrapper for Result enrollment
 */
public with sharing class MVN_ConnectiveRxEnrollResult {

    /**
     * JSON Parameters from ConnectiveRx Result
     */
    public String id;
    public String brand;
    public String brandId;
    public String programId;
    public List<String> benefitTypes;
    public Boolean isActive;
    public String status;
    public Boolean isReenrollment;
    public MVN_ConnectiveRxEnrollPersonAccount patient;
    public MVN_ConnectiveRxEnrollPersonAccount prescribingPhysician;
    public MVN_ConnectiveRxEnrollAccount referralPractice;
    public List<MVN_ConnectiveRxEnrollOutcome> outcomes;
    public List<MVN_ConnectiveRxEnrollAssociation> associations;
    public List<MVN_ConnectiveRxEnrollMetadata> metaInfo;

    /**
     * Get Assistance Program record updated with the ConnectiveRx Result
     * @param assistanceProgram     Assistance Program record
     * @return  `PJN_Assistance_Program__c`
     */
    public PJN_Assistance_Program__c getAssistanceProgram(PJN_Assistance_Program__c assistanceProgram) {
        assistanceProgram.MVN_Copay_Enrollment_Id__c = this.id;
        assistanceProgram.MVN_Copay_Status__c = this.status;
        assistanceProgram.MVN_Copay_Is_Reenrollment__c = this.isReenrollment;
        if (this.patient != null) {
            assistanceProgram.MVN_Copay_Patient_Id__c = this.patient.id;
        }
        if (this.patient != null && this.patient.caregiver != null) {
            assistanceProgram.MVN_Copay_Caregiver_Id__c = this.patient.caregiver.id;
        }
        if (this.patient != null && this.patient.membership != null) {
            assistanceProgram.MVN_Copay_Group_Number__c = this.patient.membership.groupNumber;
            assistanceProgram.MVN_Copay_Member_Id__c = this.patient.membership.memberId;
            assistanceProgram.MVN_Copay_BIN__c = this.patient.membership.bin;
            assistanceProgram.MVN_Copay_PCN__c = this.patient.membership.pcn;
            assistanceProgram.MVN_Copay_Is_Activated__c = this.patient.membership.isActivated;
            assistanceProgram.MVN_Copay_Issued_Date__c = this.patient.membership.issuedDate;
            assistanceProgram.MVN_Copay_Effective_Date__c = this.patient.membership.effectiveDate;
            assistanceProgram.MVN_Copay_Activated_Date__c = this.patient.membership.activatedDate;
            assistanceProgram.MVN_Copay_Expiration_Date__c = this.patient.membership.expirationDate;
            assistanceProgram.MVN_Copay_Deactivated_Date__c = this.patient.membership.deactivatedDate;
            assistanceProgram.MVN_Copay_Program_Cap__c = this.patient.membership.programCap;
            assistanceProgram.MVN_Copay_Total_Uses__c = this.patient.membership.totalUses;
            assistanceProgram.MVN_Copay_Usage_Period__c = this.patient.membership.usagePeriodValue;
            assistanceProgram.MVN_Copay_Usage_Period_Unit__c = this.patient.membership.usagePeriodUnit;
            assistanceProgram.MVN_Copay_Is_Active__c = this.patient.membership.isActive;
        }
        if (this.outcomes != null && !this.outcomes.isEmpty()) {
            assistanceProgram.MVN_Copay_Eligibility_Check_Type__c = this.outcomes[0].type;
            assistanceProgram.MVN_Copay_Enrollment_Success__c = this.outcomes[0].success;
            assistanceProgram.MVN_Copay_Enrollment_Result_Details__c = this.outcomes[0].message;
        }
        return assistanceProgram;
    }

    /**
     * Get Fulfillment Request record updated with the ConnectiveRx Result
     * @param fulfillment   Fulfillment Request record
     * @return  `PJN_Fulfillment_Request__c`
     */
    public PJN_Fulfillment_Request__c getFulfillmentUpdated(PJN_Fulfillment_Request__c fulfillment) {
        Map<String, Schema.RecordTypeInfo> fulfillmentRecordTypes = Schema.SObjectType.PJN_Fulfillment_Request__c.getRecordTypeInfosByDeveloperName();
        Boolean hasCopayRecordType = fulfillment.RecordTypeId == fulfillmentRecordTypes.get('MVN_Copay_Enrollment').getRecordTypeId()
            && fulfillmentRecordTypes.containsKey('MVN_Copay_Submitted');
        PJN_Fulfillment_Request__c fulfillmentToUpdate = new PJN_Fulfillment_Request__c(
            Id = fulfillment.Id,
            MVN_Copay_Enrollment_Id__c = this.id,
            MVN_Copay_Status__c = this.status,
            MVN_Copay_Is_Reenrollment__c = this.isReenrollment,
            PJN_Fulfillment_Request_Status__c = 'Processed',
            RecordTypeId = hasCopayRecordType ? fulfillmentRecordTypes.get('MVN_Copay_Submitted').getRecordTypeId() : fulfillment.RecordTypeId
        );
        if (this.patient != null) {
            fulfillmentToUpdate.MVN_Copay_Patient_Id__c = this.patient.id;
        }
        if (this.patient != null && this.patient.caregiver != null) {
            fulfillmentToUpdate.MVN_Copay_Caregiver_Id__c = this.patient.caregiver.id;
        }
        if (this.patient != null && this.patient.membership != null) {
            fulfillmentToUpdate.MVN_Copay_Group_Number__c = this.patient.membership.groupNumber;
            fulfillmentToUpdate.MVN_Copay_Member_Id__c = this.patient.membership.memberId;
            fulfillmentToUpdate.MVN_Copay_BIN__c = this.patient.membership.bin;
            fulfillmentToUpdate.MVN_Copay_PCN__c = this.patient.membership.pcn;
            fulfillmentToUpdate.MVN_Copay_Is_Activated__c = this.patient.membership.isActivated;
            fulfillmentToUpdate.MVN_Copay_Issued_Date__c = this.patient.membership.issuedDate;
            fulfillmentToUpdate.MVN_Copay_Effective_Date__c = this.patient.membership.effectiveDate;
            fulfillmentToUpdate.MVN_Copay_Activated_Date__c = this.patient.membership.activatedDate;
            fulfillmentToUpdate.MVN_Copay_Expiration_Date__c = this.patient.membership.expirationDate;
            fulfillmentToUpdate.MVN_Copay_Deactivated_Date__c = this.patient.membership.deactivatedDate;
            fulfillmentToUpdate.MVN_Copay_Program_Cap__c = this.patient.membership.programCap;
            fulfillmentToUpdate.MVN_Copay_Total_Uses__c = this.patient.membership.totalUses;
            fulfillmentToUpdate.MVN_Copay_Usage_Period__c = this.patient.membership.usagePeriodValue;
            fulfillmentToUpdate.MVN_Copay_Usage_Period_Unit__c = this.patient.membership.usagePeriodUnit;
            fulfillmentToUpdate.MVN_Copay_Is_Active__c = this.patient.membership.isActive;
        }
        if (this.outcomes != null && !this.outcomes.isEmpty()) {
            fulfillmentToUpdate.MVN_Copay_Eligibility_Check_Type__c = this.outcomes[0].type;
            fulfillmentToUpdate.MVN_Copay_Enrollment_Success__c = this.outcomes[0].success;
            fulfillmentToUpdate.MVN_Copay_Enrollment_Result_Details__c = this.outcomes[0].message;
        }
        return fulfillmentToUpdate;
    }
}