force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/echosign_dev1__Agreement_Template__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <description>Agreement Templates allow you to predefine default settings and options for your agreements which can save you time and help minimize errors.</description>
    <label>Agreement Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/fields/echosign_dev1__Data_Mapping__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Data_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the data mapping to map Adobe Sign field inputs from the signed agreement back into Salesforce.</description>
    <inlineHelpText>Select the data mapping to map Adobe Sign field inputs from the signed agreement back into Salesforce.</inlineHelpText>
    <label>Data Mapping</label>
    <referenceTo>echosign_dev1__SIGN_Data_Mapping__c</referenceTo>
    <relationshipLabel>Agreement Templates</relationshipLabel>
    <relationshipName>Agreement_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/fields/echosign_dev1__Merge_Mapping__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Merge_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the merge mapping to merge Salesforce fields into the Adobe Sign agreement before it is sent for signature.</description>
    <inlineHelpText>Select the merge mapping to merge Salesforce fields into the Adobe Sign agreement before it is sent for signature.</inlineHelpText>
    <label>Merge Mapping</label>
    <referenceTo>echosign_dev1__SIGN_Merge_Mapping__c</referenceTo>
    <relationshipLabel>Agreement Templates</relationshipLabel>
    <relationshipName>Agreement_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/fields/echosign_dev1__Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Name__c</fullName>
    <defaultValue>&quot;Adobe Sign Agreement&quot;</defaultValue>
    <description>Enter a name for the agreement.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter a name for the agreement.</inlineHelpText>
    <label>Agreement Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/CustomConsumer__c.field-meta.xml
<CustomField>
    <fullName>CustomConsumer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field created by Adobe to allow re-labeled Lead records to be used as recipients.</description>
    <label>Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agreements (Consumer)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Document_Key__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Document_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Name__c</fullName>
    <description>Agreement name can have up to 255 characters.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agreement name can have up to 255 characters.</inlineHelpText>
    <label>Agreement Name(Long Version))</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Post_Sign_Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Post_Sign_Redirect_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Sign Redirect URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Recipient_Addresses__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Recipient_Addresses__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Recipient Addresses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Status__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Status__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping__c/echosign_dev1__SIGN_Form_Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Form Field Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Target Field</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping__c/fields/echosign_dev1__Data_Mapping__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Data_Mapping__c</fullName>
    <label>Salesforce to Adobe Sign Data Mapping</label>
    <referenceTo>echosign_dev1__SIGN_Merge_Mapping__c</referenceTo>
    <relationshipLabel>Adobe Sign Form Field Mappings</relationshipLabel>
    <relationshipName>Form_Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping__c/fields/echosign_dev1__Form_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Form_Field_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target Document Field</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c.object-meta.xml
<CustomObject>
    <label>Form Field Mapping Entry</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Form Field Mapping Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Field Mapping Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c/fields/echosign_dev1__Field_Reference_Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Field_Reference_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c/fields/echosign_dev1__Object_Reference_Path__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Object_Reference_Path__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/Regeneron_Adobe_Sign_Settings_MVN__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the config for the Regeneron custom API connection to Adobe Sign</description>
    <label>Regeneron Adobe Sign Settings</label>
</CustomObject>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Authentication_Endpoint_MVN__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Endpoint_MVN__c</fullName>
    <description>The endpoint to call for authentication actions such as obtaining an access token</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The endpoint to call for authentication actions such as obtaining an access token</inlineHelpText>
    <label>Authentication Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Client_Id_MVN__c.field-meta.xml
<CustomField>
    <fullName>Client_Id_MVN__c</fullName>
    <description>The client id for the Adobe Sign App</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The client id for the Adobe Sign App</inlineHelpText>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Client_Secret_MVN__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret_MVN__c</fullName>
    <description>The client secret for the Adobe Sign App</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The client secret for the Adobe Sign App</inlineHelpText>
    <label>Client Secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Refresh_Token_MVN__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token_MVN__c</fullName>
    <description>The refresh token for the Adobe Sign App</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <inlineHelpText>The refresh token for the Adobe Sign App</inlineHelpText>
    <label>Refresh Token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/REST_API_Endpoint_MVN__c.field-meta.xml
<CustomField>
    <fullName>REST_API_Endpoint_MVN__c</fullName>
    <description>The base endpoint to send all rest API calls to</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The base endpoint to send all rest API calls to</inlineHelpText>
    <label>REST API Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/Regeneron_Adobe_Sign_Settings_MVN__c/fields/Webhook_Public_Site_MVN__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Public_Site_MVN__c</fullName>
    <description>The url of the public site that the Adobe webhook can call</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The url of the public site that the Adobe webhook can call</inlineHelpText>
    <label>Webhook Public Site</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/src/classes/AdobeSignAPITestMVN.cls
@isTest
public class AdobeSignAPITestMVN {
    
    @TestSetup
    static void makeData(){
        insert new Regeneron_Adobe_Sign_Settings_MVN__c(
            Authentication_Endpoint_MVN__c  = 'https://auth.endpoint.adobe.com',
            Client_Id_MVN__c = 'A-client-id',
            Client_Secret_MVN__c = 'A-client-secret',
            Refresh_Token_MVN__c = 'A-refresh-token',
            REST_API_Endpoint_MVN__c = 'https://rest.endpoint.adobe.com',
            Webhook_Public_Site_MVN__c = 'https://public-site-regeneron.salesforce.com'
        );
    }

    @isTest
    private static void itShouldGetAnAccessToken() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        Test.startTest();
        System.assertEquals('1234567890Access', AdobeSignAPIMVN.getAccessToken());
        Test.stopTest();
    }

    @isTest
    private static void itShouldSendAgreementForSigning() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        AdobeSignAgreementMVN agreement = new AdobeSignAgreementMVN('name', 'sigType', 'state', 'externalId');

        Test.startTest();
        System.assertEquals('1234567890Id', AdobeSignAPIMVN.sendForSigning(agreement));
        Test.stopTest();
    }

    @isTest
    private static void itShouldCreateWebhook() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        Test.startTest();
        AdobeSignAPIMVN.createWebhook();
        System.assert(true); // just exercising he code, assertions made in the mock callout
        Test.stopTest();
    }

    @isTest
    private static void itShouldHandleWebHookVerification() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/adobe/';
        req.httpMethod = 'GET';
        req.headers.put(
            'X-AdobeSign-ClientId',
            Regeneron_Adobe_Sign_Settings_MVN__c.getOrgDefaults().Client_Id_MVN__c
        );

        Test.startTest();
        RestContext.request = req;
        RestContext.response = res;
        AdobeSignAPIMVN.handleInitialization();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals(
            Regeneron_Adobe_Sign_Settings_MVN__c.getOrgDefaults().Client_Id_MVN__c, 
            RestContext.response.headers.get('X-AdobeSign-ClientId')
        );
    }

    @isTest
    private static void itShouldHandleWebHookRejection() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/api/adobe/';
        req.httpMethod = 'GET';
        req.headers.put('X-AdobeSign-ClientId', 'A Bad Client Id');

        Test.startTest();
        RestContext.request = req;
        RestContext.response = res;
        AdobeSignAPIMVN.handleInitialization();
        Test.stopTest();

        System.assertEquals(401, RestContext.response.statusCode);
    }

    @isTest
    private static void itShouldHandleWebHookNotification() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        echosign_dev1__Agreement_Template__c template = createAdobeSignTemplate();
        Lead consumer  = new Lead(
            FirstName = 'Dean',
            LastName = 'Martin',
            Email = 'dean.martin@dedsi.com'
        );
        insert consumer;

        echosign_dev1__SIGN_Agreement__c agreementObject =  new echosign_dev1__SIGN_Agreement__c(
            Name = template.echosign_dev1__Name__c,
            echosign_dev1__Recipient_Lead__c = consumer.Id,
            echosign_dev1__Process_Template__c = template.echosign_dev1__Data_Mapping__c,
            echosign_dev1__Merge_Mapping__c = template.echosign_dev1__Merge_Mapping__c,
            echosign_dev1__Agreement_Type__c = template.echosign_dev1__Agreement_Type__c,
            CustomConsumer__c = consumer.Id,
            echosign_dev1__Document_Key__c = 'AgreementIdFromAdobe',
            echosign_dev1__Post_Sign_Redirect_URL__c = template.echosign_dev1__Post_Sign_Redirect_URL__c,
            echosign_dev1__Post_Sign_Redirect_Delay__c = template.echosign_dev1__Post_Sign_Redirect_Delay__c,
            echosign_dev1__Recipient_Addresses__c = consumer.Email,
            echosign_dev1__SignatureOrder__c = 'Recipient signs, then I sign',
            echosign_dev1__SignatureType__c = 'e-Signature',
            echosign_dev1__Status__c = 'Out for Signature',
            echosign_dev1__Enable_Hosted_Signing__c = true
        );
        insert agreementObject;

        RestContext.request = new RestRequest();
        RestContext.request.headers.put(
            'X-AdobeSign-ClientId', 
            Regeneron_Adobe_Sign_Settings_MVN__c.getOrgDefaults().Client_Id_MVN__c
        );

        AdobeSignAPIMVN.WebhookNotification webhook = new AdobeSignAPIMVN.WebhookNotification();
        AdobeSignAPIMVN.Agreement agreement = new AdobeSignAPIMVN.Agreement();
        agreement.Id = 'AgreementIdFromAdobe';
        agreement.Name = 'Test Agreement';
        agreement.status = 'SIGNED';
        webhook.agreement = agreement;

        RestContext.request.requestBody = Blob.valueOf(JSON.serialize(webhook));
        RestContext.response = new RestResponse();

        Test.startTest();
        AdobeSignAPIMVN.handleWebhookEvent();
        Test.stopTest();

        List<Lead> leads = [SELECT FirstName FROM Lead]; 
        System.assertEquals(1, leads.size());
        System.assertEquals('DeanUpdated', leads[0].FirstName); // mock updates first name
        System.assertEquals(1, [SELECT COUNT() FROM Attachment WHERE Name = 'Test Agreement' and ParentId = :agreementObject.Id]);
        System.assertEquals(1, [SELECT COUNT() FROM echosign_dev1__SIGN_Agreement__c WHERE Id = :agreementObject.Id AND echosign_dev1__Status__c = 'Signed']);
    }

    @isTest
    private static void itShouldGetSigningUrls() {
        Test.setMock(HttpCalloutMock.class, new AdobeSignAPIMockMVN());

        Test.startTest();
        AdobeSignAPIMVN.SigningUrlResponse signingUrls = AdobeSignAPIMVN.getSigningUrl('AdobeSignAgreementId');
        Test.stopTest();

        System.assertEquals(1, signingUrls.signingUrlSetInfos.size());
        System.assertEquals(1, signingUrls.signingUrlSetInfos[0].signingUrls.size());
        System.assertEquals('https://signingurl.adobesign.com', signingUrls.signingUrlSetInfos[0].signingUrls[0].esignUrl);
    }


    /******************* HELPER METHODS *******************/
    public static echosign_dev1__Agreement_Template__c createAdobeSignTemplate() {
        echosign_dev1__Agreement_Template__c template = new echosign_dev1__Agreement_Template__c(
            Name = 'DEDSI Consent',
            echosign_dev1__Name__c = 'Regeneron Consent & Release Form',
            echosign_dev1__Post_Sign_Redirect_URL__c = 'https://www.looktoyourfuture.com/',
            echosign_dev1__Post_Sign_Redirect_Delay__c = 3,
            echosign_dev1__Merge_Mapping__c = buildMergeMapping().Id,
            echosign_dev1__Data_Mapping__c = buildDataMapping().Id
        );
        insert template;
        return template;
    }

    private static echosign_dev1__SIGN_Merge_Mapping__c buildMergeMapping() {
        echosign_dev1__SIGN_Merge_Mapping__c mergeMapping = new echosign_dev1__SIGN_Merge_Mapping__c(
            Name = 'DEDSI Program Merge Mapping'
        );

        insert mergeMapping;

        List<echosign_dev1__SIGN_Form_Field_Mapping__c> formFieldMappings = new List<echosign_dev1__SIGN_Form_Field_Mapping__c>{
            new echosign_dev1__SIGN_Form_Field_Mapping__c(
                echosign_dev1__Data_Mapping__c = mergeMapping.Id,
                echosign_dev1__Form_Field_Name__c = '"First Name"',
                echosign_dev1__Index__c = 1               
            ),
            new echosign_dev1__SIGN_Form_Field_Mapping__c(
                echosign_dev1__Data_Mapping__c = mergeMapping.Id,                
                echosign_dev1__Form_Field_Name__c = '"Last Name"', 
                echosign_dev1__Index__c = 2               
            )
        };
        insert formFieldMappings;

        List<echosign_dev1__SIGN_Form_Field_Mapping_Entry__c> formFieldMappingEntries = new List<echosign_dev1__SIGN_Form_Field_Mapping_Entry__c> {
            new echosign_dev1__SIGN_Form_Field_Mapping_Entry__c(
                echosign_dev1__Form_Field_Mapping__c = formFieldMappings[0].Id,
                echosign_dev1__Type__c = 'Salesforce Object Field',
                echosign_dev1__Field_Reference_Name__c = 'FirstName',
                echosign_dev1__Object_Reference_Path__c = 'echosign_dev1__Recipient_Lead__r',
                echosign_dev1__Index__c = 1
            ),
            new echosign_dev1__SIGN_Form_Field_Mapping_Entry__c(
                echosign_dev1__Form_Field_Mapping__c = formFieldMappings[1].Id,
                echosign_dev1__Type__c = 'Salesforce Object Field',
                echosign_dev1__Field_Reference_Name__c = 'LastName',
                echosign_dev1__Object_Reference_Path__c = 'echosign_dev1__Recipient_Lead__r',
                echosign_dev1__Index__c = 2
            )
        };
        insert formFieldMappingEntries;

        return mergeMapping;
    }

    private static echosign_dev1__SIGN_Data_Mapping__c buildDataMapping() {
        echosign_dev1__SIGN_Data_Mapping__c dataMapping = new echosign_dev1__SIGN_Data_Mapping__c(
            Name = 'DEDSI Program Consent Mapping'
        );
        insert dataMapping;

        echosign_dev1__SIGN_Object_Mapping__c objectMapping = new echosign_dev1__SIGN_Object_Mapping__c(
            echosign_dev1__Field_API_Name__c = 'CustomConsumer__c',
            echosign_dev1__Fully_Qualified_API__c = 'CustomConsumer__r',
            echosign_dev1__SIGN_Data_Mapping__c = dataMapping.Id,
            Name = 'Lead'
        );
        insert objectMapping;

        List<echosign_dev1__SIGN_Field_Mapping__c> fieldMappings = new List<echosign_dev1__SIGN_Field_Mapping__c> {
            new echosign_dev1__SIGN_Field_Mapping__c(
                Name = 'FirstName',
                echosign_dev1__SIGN_Object_Mapping__c = objectMapping.Id,
                echosign_dev1__Source__c = '"first"',
                echosign_dev1__Type__c = 'EchoSign Form Field',
                echosign_dev1__Index__c = 1
            ),
            new echosign_dev1__SIGN_Field_Mapping__c(
                Name = 'LastName',
                echosign_dev1__SIGN_Object_Mapping__c = objectMapping.Id,
                echosign_dev1__Source__c = '"last"',
                echosign_dev1__Type__c = 'EchoSign Form Field',
                echosign_dev1__Index__c = 2
            )
        };
        insert fieldMappings;

        return dataMapping;
    }
}