force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/echosign_dev1__Agreement_Template__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <description>Agreement Templates allow you to predefine default settings and options for your agreements which can save you time and help minimize errors.</description>
    <label>Agreement Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/fields/echosign_dev1__Data_Mapping__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Data_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the data mapping to map Adobe Sign field inputs from the signed agreement back into Salesforce.</description>
    <inlineHelpText>Select the data mapping to map Adobe Sign field inputs from the signed agreement back into Salesforce.</inlineHelpText>
    <label>Data Mapping</label>
    <referenceTo>echosign_dev1__SIGN_Data_Mapping__c</referenceTo>
    <relationshipLabel>Agreement Templates</relationshipLabel>
    <relationshipName>Agreement_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/fields/echosign_dev1__Merge_Mapping__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Merge_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the merge mapping to merge Salesforce fields into the Adobe Sign agreement before it is sent for signature.</description>
    <inlineHelpText>Select the merge mapping to merge Salesforce fields into the Adobe Sign agreement before it is sent for signature.</inlineHelpText>
    <label>Merge Mapping</label>
    <referenceTo>echosign_dev1__SIGN_Merge_Mapping__c</referenceTo>
    <relationshipLabel>Agreement Templates</relationshipLabel>
    <relationshipName>Agreement_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__Agreement_Template__c/fields/echosign_dev1__Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Name__c</fullName>
    <defaultValue>&quot;Adobe Sign Agreement&quot;</defaultValue>
    <description>Enter a name for the agreement.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter a name for the agreement.</inlineHelpText>
    <label>Agreement Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__Agreement_Type__c/echosign_dev1__Agreement_Type__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__Attachment_Template__c/echosign_dev1__Attachment_Template__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Add File Attachment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Attachment Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Add File Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__Attachment_Template__c/fields/echosign_dev1__Attachment_Document__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Attachment_Document__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Attachment Document ID&apos;s</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__Attachment_Template__c/fields/echosign_dev1__Type__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Document from Content</fullName>
            </value>
            <value>
                <fullName>Document from EchoSign Library</fullName>
            </value>
            <value>
                <fullName>Document from Library</fullName>
                <default>true</default>
                <label>Document from Library</label>
            </value>
            <value>
                <fullName>Document from Master Object</fullName>
            </value>
            <value>
                <fullName>Quote Document from Master Quote</fullName>
            </value>
            <value>
                <fullName>Quote Document from Opportunity Quote</fullName>
            </value>
            <value>
                <fullName>Runtime Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/CustomConsumer__c.field-meta.xml
<CustomField>
    <fullName>CustomConsumer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field created by Adobe to allow re-labeled Lead records to be used as recipients.</description>
    <label>Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Agreements (Consumer)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Document_Key__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Document_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Name__c</fullName>
    <description>Agreement name can have up to 255 characters.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Agreement name can have up to 255 characters.</inlineHelpText>
    <label>Agreement Name(Long Version))</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Post_Sign_Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Post_Sign_Redirect_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Post Sign Redirect URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Recipient_Addresses__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Recipient_Addresses__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Recipient Addresses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Status__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Status__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping__c/echosign_dev1__SIGN_Form_Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Form Field Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Target Field</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping__c/fields/echosign_dev1__Data_Mapping__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Data_Mapping__c</fullName>
    <label>Salesforce to Adobe Sign Data Mapping</label>
    <referenceTo>echosign_dev1__SIGN_Merge_Mapping__c</referenceTo>
    <relationshipLabel>Adobe Sign Form Field Mappings</relationshipLabel>
    <relationshipName>Form_Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping__c/fields/echosign_dev1__Form_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Form_Field_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Target Document Field</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c.object-meta.xml
<CustomObject>
    <label>Form Field Mapping Entry</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Form Field Mapping Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Field Mapping Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c/fields/echosign_dev1__Field_Reference_Name__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Field_Reference_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Form_Field_Mapping_Entry__c/fields/echosign_dev1__Object_Reference_Path__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Object_Reference_Path__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/src/classes/LeadConsentCtrlMVN.cls
/**
 * @author      Mavens
 * @group       AdobeSign
 * @description Controller for the Lead Consent quick action
 *     - Handles creation of agreement object and api wrapper plus callout to Adobe to send and inserting new record
 *     - Handles obtaining signing url for an agreement
 */
public with sharing class LeadConsentCtrlMVN {
    
    /**
     * Create an agreement and send it out for signature. insert agreeement record into Database and attach to lead
     * @param leadId - Id
     * @param templateName - String
     * @param signInPerson - Boolean
     * @return String
     */
    @AuraEnabled
    public static String createAndSendAgreement(Id leadId, String templateName, Boolean signInPerson) {
        // Get Template
        echosign_dev1__Agreement_Template__c template = [
            SELECT 
                Id,
                echosign_dev1__Agreement_Type__c,
                echosign_dev1__Name__c,                
                echosign_dev1__Data_Mapping__c,
                echosign_dev1__Merge_Mapping__c,
                echosign_dev1__Post_Sign_Redirect_Delay__c,
                echosign_dev1__Post_Sign_Redirect_URL__c,
                (
                    SELECT
                        Id,
                        echosign_dev1__Attachment_Document__c,
                        echosign_dev1__Type__c
                    FROM 
                        echosign_dev1__Attachment_Templates__r
                )
            FROM echosign_dev1__Agreement_Template__c
            WHERE Name = :templateName
            LIMIT 1
        ];

        Set<String> leadFields = new Set<String>{ 'Id', 'Email' };
        Map<String, String> formFieldToLeadField = new Map<String, String>();

        // get lead and designated fields from the template merge Mapping
        if (template.echosign_dev1__Merge_Mapping__c != null) {
            List<echosign_dev1__SIGN_Form_Field_Mapping__c> formFieldMappings = [
                SELECT
                    Id,
                    echosign_dev1__Form_Field_Name__c,
                    (
                        SELECT echosign_dev1__Field_Reference_Name__c
                        FROM echosign_dev1__Object_Field_Mappings__r
                        WHERE echosign_dev1__Object_Reference_Path__c = 'echosign_dev1__Recipient_Lead__r'
                        AND echosign_dev1__Type__c = 'Salesforce Object Field'
                    )
                FROM
                    echosign_dev1__SIGN_Form_Field_Mapping__c
                WHERE 
                    echosign_dev1__Data_Mapping__c = :template.echosign_dev1__Merge_Mapping__c
            ];
            
            for (echosign_dev1__SIGN_Form_Field_Mapping__c formFieldMapping : formFieldMappings) {
                for (echosign_dev1__SIGN_Form_Field_Mapping_Entry__c entry : formFieldMapping.echosign_dev1__Object_Field_Mappings__r) {
                    leadFields.add(entry.echosign_dev1__Field_Reference_Name__c);
                    if (!formFieldToLeadField.containsKey(formFieldMapping.echosign_dev1__Form_Field_Name__c)) {
                        // for DEDSI Leads assumptoin is there is only one mapping and take the first one from the children
                        formFieldToLeadField.put(
                            formFieldMapping.echosign_dev1__Form_Field_Name__c, 
                            entry.echosign_dev1__Field_Reference_Name__c
                        );
                    }
                }
            }
        }

        // query for the consumer
        Lead consumer = Database.query(
            'SELECT ' +
            String.join(new List<String>(leadFields), ', ') + ' ' +
            'FROM Lead ' +
            'WHERE Id = :leadId'
        );

        // create agreement API wrapper and populate
        String signatureType = 'ESIGN';
        String state = 'IN_PROCESS';
        String externalId = leadId;

        AdobeSignAgreementMVN agreement = new AdobeSignAgreementMVN(template.echosign_dev1__Name__c, signatureType, state, externalId)
            .addSigners(new List<String> {consumer.Email})
            .addEmailOption('ALL', 'ALL', signInPerson ? 'NONE' : 'ALL');
        
        if (!signInPerson) {
            agreement.addPostSignOption(
                template.echosign_dev1__Post_Sign_Redirect_URL__c, 
                template.echosign_dev1__Post_Sign_Redirect_Delay__c
            );
        }
        
        for (echosign_dev1__Attachment_Template__c document : template.echosign_dev1__Attachment_Templates__r) {
            if (document.echosign_dev1__Type__c == 'Document from EchoSign Library') {
                agreement.addLibraryFileInfo(document.echosign_dev1__Attachment_Document__c);
            }
        }

        for (String formField : formFieldToLeadField.keySet()) {
            String leadField = formFieldToLeadField.get(formField);
            Object fieldValue = consumer.get(leadField);
            DisplayType dt = Lead.sObjectType.getDescribe().fields.getMap().get(leadField).getDescribe().getType();
            String stringValue;
            if (dt == DisplayType.DATE && consumer.get(leadField) != null ) {
                Date dateValue = (Date) consumer.get(leadField);
                stringValue = dateValue.month() + '/' + dateValue.day() + '/' + dateValue.year();
            } else {
               stringValue = (String) consumer.get(leadField); 
            }
            agreement.addMergeField(formField, stringValue);
        }

        String agreementId = AdobeSignAPIMVN.sendForSigning(agreement);
        
        // create the new agreement object
        echosign_dev1__SIGN_Agreement__c agreementObject = new echosign_dev1__SIGN_Agreement__c(
            Name = template.echosign_dev1__Name__c,
            echosign_dev1__Recipient_Lead__c = leadId,
            echosign_dev1__Process_Template__c = template.echosign_dev1__Data_Mapping__c,
            echosign_dev1__Merge_Mapping__c = template.echosign_dev1__Merge_Mapping__c,
            echosign_dev1__Agreement_Type__c = template.echosign_dev1__Agreement_Type__c,
            CustomConsumer__c = leadId,
            echosign_dev1__Document_Key__c = agreementId,
            echosign_dev1__Post_Sign_Redirect_URL__c = template.echosign_dev1__Post_Sign_Redirect_URL__c,
            echosign_dev1__Post_Sign_Redirect_Delay__c = template.echosign_dev1__Post_Sign_Redirect_Delay__c,
            echosign_dev1__Recipient_Addresses__c = consumer.Email,
            echosign_dev1__SignatureOrder__c = 'Recipient signs, then I sign',
            echosign_dev1__SignatureType__c = 'e-Signature',
            echosign_dev1__Status__c = 'Out for Signature',
            echosign_dev1__Enable_Hosted_Signing__c = signInPerson
        );

        insert agreementObject;

        return agreementId;
    }

    /**
     * Retrieves signing urls and returns the first one.
     * @param agreementId - String
     * @return String
     */
    @AuraEnabled
    public static string getSigningUrl(String agreementId) {
        AdobeSignAPIMVN.SigningUrlResponse signingUrlResp = AdobeSignAPIMVN.getSigningUrl(agreementId);
        System.debug(JSON.serialize(signingUrlResp));
        if (!signingUrlResp.signingUrlSetInfos.isEmpty() && !signingUrlResp.signingUrlSetInfos[0].signingUrls.isEmpty()) {
            return signingUrlResp.signingUrlSetInfos[0].signingUrls[0].esignUrl;
        }
        return null;
    }

    @AuraEnabled
    public static string getAgreementDocId(Id agreementId) {
        return [
            SELECT echosign_dev1__Document_Key__c
            FROM echosign_dev1__SIGN_Agreement__c
            WHERE Id = :agreementId
        ].echosign_dev1__Document_Key__c;
    }
}