force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Field__mdt/PJN_Mapping_Field__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define source field and target field for a Field Mapping type. This is step 3 in setting up the mapping engine for object-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Field__mdt/fields/PJN_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping__c</fullName>
    <label>Mapping</label>
    <referenceTo>PJN_Mapping__mdt</referenceTo>
    <relationshipLabel>Mapping Fields</relationshipLabel>
    <relationshipName>PJN_Mapping_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Field__mdt/fields/PJN_Source_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Field_API_Name__c</fullName>
    <description>Source Field API Name</description>
    <label>Source Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Field__mdt/fields/PJN_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Target_Field_API_Name__c</fullName>
    <description>Target Field API Name</description>
    <label>Target Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingFieldMock.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping Field mock provider
 */
@isTest(isParallel=true) public with sharing class PJN_MappingFieldMock implements System.StubProvider {
    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'queryByMapping') {
            return this.queryByMapping((PJN_Mapping__mdt) listOfArgs[0]);
        } else {
            return null;
        }
    }

    private Object queryByMapping(PJN_Mapping__mdt mapping) {
        if(mapping.DeveloperName == 'PJN_DOES_NOT_EXIST') {
            throw new System.QueryException('TEST');
        } else {
            return new List<PJN_Mapping_Field__mdt> {
                new PJN_Mapping_Field__mdt(
                    MasterLabel = 'Mocked Mapping Field',
                    DeveloperName = 'PJN_Mocked_Mapping_Field',
                    PJN_Source_Field_API_Name__c = 'Parent.Name',
                    PJN_Target_Field_API_Name__c = 'Name',
                    PJN_Mapping__r = mapping
                ),
                new PJN_Mapping_Field__mdt(
                    MasterLabel = 'Mocked Mapping Field Boolean',
                    DeveloperName = 'PJN_Mocked_Mapping_Field_Boolean',
                    PJN_Source_Field_API_Name__c = 'HealthCloudGA__Disabled__c',
                    PJN_Target_Field_API_Name__c = 'HealthCloudGA__Disabled__c',
                    PJN_Mapping__r = mapping
                )
            };
        }
    }
}