force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/PJN_Mapping_Date_Formula__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define date field value and target field for a Date Formula Mapping type. This is step 4 in setting up the mapping engine for case-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Date Formula</label>
    <pluralLabel>Mapping Date Formulas</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/fields/PJN_Days_To_Add__c.field-meta.xml
<CustomField>
    <fullName>PJN_Days_To_Add__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days To Add</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/fields/PJN_Formula__c.field-meta.xml
<CustomField>
    <fullName>PJN_Formula__c</fullName>
    <label>Formula</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOW</fullName>
                <default>true</default>
                <label>NOW</label>
            </value>
            <value>
                <fullName>TODAY</fullName>
            </value>
            <value>
                <fullName>FIELD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/fields/PJN_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping__c</fullName>
    <label>Mapping</label>
    <referenceTo>PJN_Mapping__mdt</referenceTo>
    <relationshipLabel>Mapping Date Formulas</relationshipLabel>
    <relationshipName>PJN_Mapping_Date_Formulas</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingDateFormulaMock.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping Date Formula mock provider
 */
@isTest(isParallel=false) public with sharing class PJN_MappingDateFormulaMock implements System.StubProvider {
    public Object handleMethodCall(Object stubbedObject,
                                   String stubbedMethodName,
                                   Type returnType,
                                   List<Type> listOfParamTypes,
                                   List<String> listOfParamNames,
                                   List<Object> listOfArgs) {
        if (stubbedMethodName == 'queryByMapping') {
            return this.queryByMapping((PJN_Mapping__mdt) listOfArgs[0]);
        } else {
            return null;
        }
    }

    private Object queryByMapping(PJN_Mapping__mdt mapping) {
        if(mapping.DeveloperName == 'PJN_DOES_NOT_EXIST') {
            throw new System.QueryException('TEST');
        } else {
            return new List<PJN_Mapping_Date_Formula__mdt> {
                new PJN_Mapping_Date_Formula__mdt(
                    MasterLabel = 'Mocked Mapping Date Formula NOW',
                    DeveloperName = 'PJN_Mocked_Mapping_Date_Formula_NOW',
                    PJN_Target_Field_API_Name__c = 'HealthCloudGA__SourceSystemModified__c',
                    PJN_Formula__c = 'NOW',
                    PJN_Days_To_Add__c = 0,
                    PJN_Mapping__r = mapping
                ),
                new PJN_Mapping_Date_Formula__mdt(
                    MasterLabel = 'Mocked Mapping Date Formula TODAY',
                    DeveloperName = 'PJN_Mocked_Mapping_Date_Formula_TODAY',
                    PJN_Target_Field_API_Name__c = 'PJN_Override_Next_Activity__c',
                    PJN_Formula__c = 'TODAY',
                    PJN_Days_To_Add__c = 1,
                    PJN_Mapping__r = mapping
                ),
                new PJN_Mapping_Date_Formula__mdt(
                    MasterLabel = 'Mocked Mapping Date Formula FIELD',
                    DeveloperName = 'PJN_Mocked_Mapping_Date_Formula_FIELD',
                    PJN_Source_Field_API_Name__c = 'HealthCloudGA__DueDate__c',
                    PJN_Target_Field_API_Name__c = 'HealthCloudGA__DueDate__c',
                    PJN_Formula__c = 'FIELD',
                    PJN_Days_To_Add__c = -1,
                    PJN_Mapping__r = mapping
                )
            };
        }
    }
}