force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Queue__mdt/PJN_Mapping_Queue__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define queue value and target field for a Queue Mapping type. This is step 5 in setting up the mapping engine for case-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Queue</label>
    <pluralLabel>Mapping Queues</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Queue__mdt/fields/PJN_Queue_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Queue_API_Name__c</fullName>
    <description>Queue API Name</description>
    <label>Queue API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingEngineQueueHdlr.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping record types
 */
public with sharing class PJN_MappingEngineQueueHdlr extends PJN_MappingEngineHdlr {
    /**
     * queue mapping query
     */
    @testVisible private PJN_MappingQueueQuery mappingQueueQuery = new PJN_MappingQueueQuery();

    /**
     * queue query
     */
    @testVisible private PJN_QueueQuery queueQuery = new PJN_QueueQuery();

    /**
     * record type mapping
     */
    private PJN_Mapping_Queue__mdt queueMapping;

    /**
     * use mapping implementation
     * @param PJN_Mapping__mdt       mapping
     */
    public override void useMapping(PJN_Mapping__mdt mapping) {
        try {
            this.queueMapping = this.mappingQueueQuery.queryByMapping(mapping);
        } catch(System.QueryException qE) {
            throw new PJN_MappingEngineException('No specific Mapping for ' + mapping.Label + '(' + mapping.DeveloperName + ') found.');
        }
    }

    /**
     * map record
     * @param SObject       sourceObject
     * @param SObject       targetObject
     * @returns SObject
     */
     @testVisible protected override SObject mapRecord(SObject sourceObject, SObject targetObject) {
        targetObject.put(this.queueMapping.PJN_Target_Field_API_Name__c, this.getQueue());
        return targetObject;
    }

    /**
     * get queue by developer name
     * @param SObject       targetObject
     * @returns Id
     */
    private Id getQueue() {
        return this.queueQuery.queryByDeveloperName(this.queueMapping.PJN_Queue_API_Name__c).Id;
    }
}