force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Always_Runs__c.field-meta.xml
<CustomField>
    <fullName>PJN_Always_Runs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Always Runs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Mapping_Job__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping_Job__c</fullName>
    <label>Mapping Job</label>
    <referenceTo>PJN_Mapping_Job__mdt</referenceTo>
    <relationshipLabel>Mapping</relationshipLabel>
    <relationshipName>PJN_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Mapping_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping_Type__c</fullName>
    <label>Mapping Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PJN_Field</fullName>
                <default>true</default>
                <label>Field</label>
            </value>
            <value>
                <fullName>PJN_Label</fullName>
                <label>Label</label>
            </value>
            <value>
                <fullName>PJN_Queue</fullName>
                <label>Queue</label>
            </value>
            <value>
                <fullName>PJN_Record_Type</fullName>
                <label>Record Type</label>
            </value>
            <value>
                <fullName>PJN_Date_Formula</fullName>
                <label>Date Formula</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Source_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Object_API_Name__c</fullName>
    <description>Source Object API Name</description>
    <label>Source Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Source_Object_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Object_Type_Name__c</fullName>
    <description>Source Object Type Name</description>
    <label>Source Object Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Field__mdt/PJN_Mapping_Field__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define source field and target field for a Field Mapping type. This is step 3 in setting up the mapping engine for object-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Field</label>
    <pluralLabel>Mapping Fields</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Job__mdt/PJN_Mapping_Job__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the object against which the mapping is executed. This is the first step in setting up the mapping engine.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Job</label>
    <pluralLabel>Mapping Jobs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_MappingQuery.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping query
 */
public with sharing class PJN_MappingQuery {
    static Map<String, List<PJN_Mapping__mdt>> mappingsByJobName;
    static Map<Id, List<PJN_Mapping_Field__mdt>> fieldMappingsByMappingId;

    /**
     * query mapping by mapping job name
     * @param String       jobName
     * @returns List<PJN_Mapping__mdt>
     */
    public List<PJN_Mapping__mdt> queryMappingsByJobName(String jobName) {
        if (mappingsByJobName == null) {
            mappingsByJobName = new Map<String, List<PJN_Mapping__mdt>>();
        }

        if (!mappingsByJobName.containsKey(jobName)) {
            List<PJN_Mapping__mdt> mappingsForJob = [
                SELECT
                    Id,
                    Label,
                    DeveloperName,
                    PJN_Mapping_Type__c,
                    PJN_Always_Runs__c,
                    PJN_Source_Object_Type_Name__c,
                    PJN_Source_Object_API_Name__c
                FROM
                    PJN_Mapping__mdt
                WHERE
                    PJN_Mapping_Job__r.DeveloperName = :jobName
            ];
            mappingsByJobName.put(jobName, mappingsForJob);
        }

        return mappingsByJobName.get(jobName);
    }
}