force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Label__mdt/PJN_Mapping_Label__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define label value and target field for a Label Mapping type. This is step 3 in setting up the mapping engine for case-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Label</label>
    <pluralLabel>Mapping Labels</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Label__mdt/fields/PJN_Label_Text_Area__c.field-meta.xml
<CustomField>
    <fullName>PJN_Label_Text_Area__c</fullName>
    <label>Label Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Label__mdt/fields/PJN_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping__c</fullName>
    <label>Mapping</label>
    <referenceTo>PJN_Mapping__mdt</referenceTo>
    <relationshipLabel>Mapping Labels</relationshipLabel>
    <relationshipName>PJN_Mapping_Labels</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingLabelQuery.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping Label query
 */
public with sharing class PJN_MappingLabelQuery {

    private static Map<Id, PJN_Mapping__mdt> mappingsWithMappingLabels {
        get {
            if (mappingsWithMappingLabels == null) {
                mappingsWithMappingLabels = new Map<Id, PJN_Mapping__mdt> (
                    [
                        SELECT
                            Id,
                            (
                                SELECT
                                    Id,
                                    PJN_Source_Field_API_Name__c,
                                    PJN_Target_Field_API_Name__c,
                                    PJN_Label_Text_Area__c
                                FROM
                                    PJN_Mapping_Labels__r
                            )
                        FROM
                            PJN_Mapping__mdt
                    ]
                );
            }
            return mappingsWithMappingLabels;
        }
        set;
    }
    /**
     * query record type mapping by mapping
     * @param PJN_Mapping__mdt       mapping
     */
    public List<PJN_Mapping_Label__mdt> queryByMapping(PJN_Mapping__mdt mapping) {
        if (mappingsWithMappingLabels.containsKey(mapping.Id)) {
            return mappingsWithMappingLabels.get(mapping.Id).PJN_Mapping_Labels__r;
        }

        return new List<PJN_Mapping_Label__mdt>();
    }
}