force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Queue__mdt/PJN_Mapping_Queue__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define queue value and target field for a Queue Mapping type. This is step 5 in setting up the mapping engine for case-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Queue</label>
    <pluralLabel>Mapping Queues</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Queue__mdt/fields/PJN_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping__c</fullName>
    <label>Mapping</label>
    <referenceTo>PJN_Mapping__mdt</referenceTo>
    <relationshipLabel>Mapping Queues</relationshipLabel>
    <relationshipName>PJN_Mapping_Queues</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Queue__mdt/fields/PJN_Queue_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Queue_API_Name__c</fullName>
    <description>Queue API Name</description>
    <label>Queue API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingQueueQuery.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping queue query
 */
public with sharing class PJN_MappingQueueQuery {
    /**
     * query record type mapping by mapping
     * @param PJN_Mapping__mdt       mapping
     */
    public PJN_Mapping_Queue__mdt queryByMapping(PJN_Mapping__mdt mapping) {
        return [
            SELECT
                Id,
                PJN_Queue_API_Name__c,
                PJN_Target_Field_API_Name__c
            FROM
                PJN_Mapping_Queue__mdt
            WHERE
                PJN_Mapping__c = :mapping.Id
        ];
    }
}