force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/PJN_Mapping_Date_Formula__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Define date field value and target field for a Date Formula Mapping type. This is step 4 in setting up the mapping engine for case-related mapping.
Metadata Relationship(s): Mapping
Created by Mavens: Yes</description>
    <label>Mapping Date Formula</label>
    <pluralLabel>Mapping Date Formulas</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/fields/PJN_Days_To_Add__c.field-meta.xml
<CustomField>
    <fullName>PJN_Days_To_Add__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days To Add</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/fields/PJN_Formula__c.field-meta.xml
<CustomField>
    <fullName>PJN_Formula__c</fullName>
    <label>Formula</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOW</fullName>
                <default>true</default>
                <label>NOW</label>
            </value>
            <value>
                <fullName>TODAY</fullName>
            </value>
            <value>
                <fullName>FIELD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping_Date_Formula__mdt/fields/PJN_Mapping__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping__c</fullName>
    <label>Mapping</label>
    <referenceTo>PJN_Mapping__mdt</referenceTo>
    <relationshipLabel>Mapping Date Formulas</relationshipLabel>
    <relationshipName>PJN_Mapping_Date_Formulas</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingDateFormulaQuery.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description mapping date formula query
 */
public with sharing class PJN_MappingDateFormulaQuery {

    static Map<Id, List<PJN_Mapping_Date_Formula__mdt>> mappingDateFormulasById;
    /**
     * query date formula mapping by mapping
     * @param PJN_Mapping__mdt       mapping
     */
    public List<PJN_Mapping_Date_Formula__mdt> queryByMapping(PJN_Mapping__mdt mapping) {
        if (mappingDateFormulasById == null) {
            mappingDateFormulasById = new Map<Id, List<PJN_Mapping_Date_Formula__mdt>>();
        }

        if (!mappingDateFormulasById.containsKey(mapping.Id)) {
            mappingDateFormulasById.put(mapping.Id,
                [
                    SELECT
                        Id,
                        PJN_Formula__c,
                        PJN_Days_To_Add__c,
                        PJN_Source_Field_API_Name__c,
                        PJN_Target_Field_API_Name__c
                    FROM
                        PJN_Mapping_Date_Formula__mdt
                    WHERE
                        PJN_Mapping__c = :mapping.Id
                ]
            );
        }
        return mappingDateFormulasById.get(mapping.Id);
    }
}