force-app/main/default/src/objects/PJN_Mapping__mdt/PJN_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Mapping Engine
Purpose: Definition of the mapping type. This is step 2 in setting up the mapping engine.
Metadata Relationship(s): Mapping Job; Mapping Field; Mapping Label; Mapping Date Formula; Mapping Queue; Mapping Record Type
Created by Mavens: Yes</description>
    <label>Mapping</label>
    <pluralLabel>Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Mapping_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Mapping_Type__c</fullName>
    <label>Mapping Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PJN_Field</fullName>
                <default>true</default>
                <label>Field</label>
            </value>
            <value>
                <fullName>PJN_Label</fullName>
                <label>Label</label>
            </value>
            <value>
                <fullName>PJN_Queue</fullName>
                <label>Queue</label>
            </value>
            <value>
                <fullName>PJN_Record_Type</fullName>
                <label>Record Type</label>
            </value>
            <value>
                <fullName>PJN_Date_Formula</fullName>
                <label>Date Formula</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Source_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Object_API_Name__c</fullName>
    <description>Source Object API Name</description>
    <label>Source Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Mapping__mdt/fields/PJN_Source_Object_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Source_Object_Type_Name__c</fullName>
    <description>Source Object Type Name</description>
    <label>Source Object Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_MappingEngineHdlrTest.cls
/**
 * @author      Mavens
 * @group       MappingEngine
 * @description Unit tests for PJN_MappingEngineHdlr & PJN_MappingEngineMockHdlr
 */
@isTest(isParallel=true) private with sharing class PJN_MappingEngineHdlrTest {
    @isTest private static void useMapping() {
        PJN_Mapping__mdt mapping = new PJN_Mapping__mdt(
            MasterLabel = 'Mocked Mapping',
            DeveloperName = 'PJN_DOES_NOT_EXIST',
            PJN_Source_Object_Type_Name__c = 'Case',
            PJN_Source_Object_API_Name__c = 'Case',
            PJN_Mapping_Type__c = 'PJN_Field'
        );
        PJN_MappingEngineMockHdlr mappingEngineHdlr = new PJN_MappingEngineMockHdlr();

        Test.startTest();
            mappingEngineHdlr.useMapping(mapping);
        Test.stopTest();

        System.assertEquals(mapping.DeveloperName, mappingEngineHdlr.mapping.DeveloperName);
    }

    @isTest private static void mapRecord() {
        Case sourceCase = new Case(
            Subject = 'Test Source Case'
        );
        insert sourceCase;
        Case targetCase = new Case(
            Subject = 'Test Target Case'
        );
        insert targetCase;
        PJN_MappingEngineMockHdlr mappingEngineHdlr = new PJN_MappingEngineMockHdlr();

        Test.startTest();
            Case actualCase = (Case) mappingEngineHdlr.mapRecord(sourceCase.Id, targetCase);
        Test.stopTest();

        System.assertEquals(targetCase.Id, actualCase.Id);
        System.assertNotEquals(sourceCase.Subject, actualCase.Subject);
    }

    @isTest private static void mapRecordMultiple() {
        Case sourceCase = new Case(
            Subject = 'Test Source Case'
        );
        insert sourceCase;
        Case targetCase = new Case(
            Subject = 'Test Target Case'
        );
        insert targetCase;
        PJN_MappingEngineMockHdlr mappingEngineHdlr = new PJN_MappingEngineMockHdlr();

        Test.startTest();
            List<SObject> actualCases = mappingEngineHdlr.maprecord(new List<Id> { sourceCase.Id }, new List<SObject> { targetCase });
        Test.stopTest();

        System.assertEquals(1, actualCases.size());
        Case actualCase = (Case) actualCases.get(0);
        System.assertEquals(targetCase.Id, actualCase.Id);
        System.assertNotEquals(sourceCase.Subject, actualCase.Subject);
    }
}