force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Primary_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Primary_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s primary active member plan.</description>
    <label>Primary Member Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Member_Plan__c.PJN_Coverage_Order__c</field>
            <operation>equals</operation>
            <value>Primary</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>PJN_Member_Plan__c.PJN_Patient__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>CarePlansPrimary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Secondary_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Secondary_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s secondary active member plan.</description>
    <label>Secondary Member Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Member_Plan__c.PJN_Coverage_Order__c</field>
            <operation>equals</operation>
            <value>Secondary</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>PJN_Member_Plan__c.PJN_Patient__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Cases (Secondary Member Plan)</relationshipLabel>
    <relationshipName>CarePlansSecondary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Tertiary_Member_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Tertiary_Member_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a patient&apos;s tertiary active member plan.</description>
    <label>Tertiary Member Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PJN_Member_Plan__c.PJN_Coverage_Order__c</field>
            <operation>equals</operation>
            <value>Tertiary</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>PJN_Member_Plan__c.PJN_Patient__r.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PJN_Member_Plan__c</referenceTo>
    <relationshipLabel>Cases (Tertiary Member Plan)</relationshipLabel>
    <relationshipName>CarePlansTertiary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/PJN_Member_Plan__c.object-meta.xml
<CustomObject>
    <description>Mavens custom object for Member Plans.</description>
    <label>Member Plan</label>
    <nameField>
        <displayFormat>MP-{00000}</displayFormat>
        <label>Member Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Care_Plan__c.field-meta.xml
<CustomField>
    <fullName>PJN_Care_Plan__c</fullName>
    <description>Patient care plan for which the member plan was captured.</description>
    <label>Care Plan</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>PJN_Member_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Coverage_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Coverage_Order__c</fullName>
    <description>Picklist for the plan&apos;s coverage order number as part of the coordination of benefits rules.</description>
    <label>Coverage Order</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>PJN_Expiration_Date__c</fullName>
    <description>Date insurance plan effective to.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/src/objects/PJN_Member_Plan__c/fields/PJN_Set_as_Active__c.field-meta.xml
<CustomField>
    <fullName>PJN_Set_as_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to indicate that a patient&apos;s member plan should be set to active. Triggers the member plan to be stamped into the PJN_Primary_Member_Plan__c, PJN_Secondary_Member_Plan__c, or PJN_Tertiary_Member_Plan__c case fields (depending on member plan&apos;s PJN_Coverage_Order__c value) and sets the PJN_Active__c checkbox on the member plan to TRUE.</description>
    <label>Set as Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/classes/PJN_ClearMemberPlanFieldsTest.cls
/**
* @author Mavens
* @description Test class for PJN_ClearMemberPlanFields
* @group       CarePlan Fields Mapping
*/
@isTest
private class PJN_ClearMemberPlanFieldsTest {

    @TestSetup
    static void makeData(){
        CareProgram program = new CareProgram(
            Name = 'Test Program',
            PJN_Program_DeveloperName__c = 'PJN_CLP',
            StartDate = Date.today()
        );
        insert program;

        Account patient = new Account (
            LastName = 'Patient',
            RecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PJN_Patient').getRecordTypeId()
        );
        insert patient;

        Case carePlan = new Case(
            RecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId(),
            AccountId = patient.Id,
            PJN_Program__c = program.Id
        );
        insert carePlan;

        List<PJN_Member_Plan__c> memberPlanList = new List<PJN_Member_Plan__c>();
        memberPlanList.add(new PJN_Member_Plan__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Expiration_Date__c = Date.today(),
            PJN_Coverage_Order__c = 'Primary'
        ));
        memberPlanList.add(new PJN_Member_Plan__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Expiration_Date__c = Date.today(),
            PJN_Coverage_Order__c = 'Secondary'
        ));
        memberPlanList.add(new PJN_Member_Plan__c(
            PJN_Care_Plan__c = carePlan.Id,
            PJN_Expiration_Date__c = Date.today(),
            PJN_Coverage_Order__c = 'Tertiary'
        ));
        insert memberPlanList;
    }

    @isTest
    private static void testUpdatePrimaryMemberPlan() {
        PJN_Member_Plan__c memberPlan = [
            SELECT Id FROM PJN_Member_Plan__c WHERE PJN_Coverage_Order__c = 'Primary'
        ];
        Test.startTest();
            memberPlan.PJN_Coverage_Order__c = 'Secondary';
            memberPlan.PJN_Set_as_Active__c = true;
            update memberPlan;
        Test.stopTest();

        Id carePlanRecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId();
        Case carePlan = [
            SELECT PJN_Primary_Member_Plan__c FROM Case WHERE RecordTypeId = :carePlanRecordTypeId
        ];
        System.assertEquals(null, carePlan.PJN_Primary_Member_Plan__c, 'Primary Member Plan Lookup has not been cleared up');
    }

    @isTest
    private static void testUpdateSecondaryMemberPlan() {
        PJN_Member_Plan__c memberPlan = [
            SELECT Id FROM PJN_Member_Plan__c WHERE PJN_Coverage_Order__c = 'Secondary'
        ];
        Test.startTest();
            memberPlan.PJN_Coverage_Order__c = 'Primary';
            memberPlan.PJN_Set_as_Active__c = true;
            update memberPlan;
        Test.stopTest();

        Id carePlanRecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId();
        Case carePlan = [
            SELECT PJN_Secondary_Member_Plan__c FROM Case WHERE RecordTypeId = :carePlanRecordTypeId
        ];
        System.assertEquals(null, carePlan.PJN_Secondary_Member_Plan__c, 'Secondary Member Plan Lookup has not been cleared up');
    }

    @isTest
    private static void testUpdateTertiaryMemberPlan() {
        PJN_Member_Plan__c memberPlan = [
            SELECT Id FROM PJN_Member_Plan__c WHERE PJN_Coverage_Order__c = 'Tertiary'
        ];
        Test.startTest();
            memberPlan.PJN_Coverage_Order__c = 'Secondary';
            memberPlan.PJN_Set_as_Active__c = true;
            update memberPlan;
        Test.stopTest();

        Id carePlanRecordTypeId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CarePlan').getRecordTypeId();
        Case carePlan = [
            SELECT PJN_Tertiary_Member_Plan__c FROM Case WHERE RecordTypeId = :carePlanRecordTypeId
        ];
        System.assertEquals(null, carePlan.PJN_Tertiary_Member_Plan__c, 'Tertiary Member Plan Lookup has not been cleared up');
    }
}