force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting__mdt/PJN_All_Care_Plan_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: All Care Plans tab
Purpose: Define information to be displayed on the All Care Plans tab.
Metadata Relationship(s): Program, All Care Plan Setting Fields
Created by Mavens: Yes</description>
    <label>All Care Plan Setting</label>
    <pluralLabel>All Care Plan Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting__mdt/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <label>Program</label>
    <referenceTo>PJN_Program__mdt</referenceTo>
    <relationshipLabel>All Care Plan Settings</relationshipLabel>
    <relationshipName>PJN_All_Care_Plan_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting__mdt/fields/PJN_Subtitle_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Subtitle_Field_API_Name__c</fullName>
    <label>Subtitle Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting__mdt/fields/PJN_Title_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Title_Field_API_Name__c</fullName>
    <label>Title Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting_Field__mdt/PJN_All_Care_Plan_Setting_Field__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: All Care Plans tab
Purpose: Define the field and its order to be displayed on the All Care Plans tab.
Metadata Relationship(s): All Care Plan Setting
Created by Mavens: Yes</description>
    <label>All Care Plan Setting Field</label>
    <pluralLabel>All Care Plan Setting Fields</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting_Field__mdt/fields/PJN_All_Care_Plan_Setting__c.field-meta.xml
<CustomField>
    <fullName>PJN_All_Care_Plan_Setting__c</fullName>
    <label>All Care Plan Setting</label>
    <referenceTo>PJN_All_Care_Plan_Setting__mdt</referenceTo>
    <relationshipLabel>All Care Plan Setting Fields</relationshipLabel>
    <relationshipName>PJN_All_Care_Plan_Setting_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting_Field__mdt/fields/PJN_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_All_Care_Plan_Setting_Field__mdt/fields/PJN_Link_Record_Id_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Link_Record_Id_Field_API_Name__c</fullName>
    <label>Link Record Id Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program__mdt/PJN_Program__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the program developer name for a given program. This is the first step in the Program Builder.
Metadata Relationship(s): Program Problem; Care Plan Timeline Case; Care Plan Field
Created by Mavens: Yes</description>
    <label>Program</label>
    <pluralLabel>Programs</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_CarePlanPathListCtrl.cls
/**
 * @author      Mavens
 * @group       CarePlan-UI
 * @description get all care plan problems for one care plan
 */
public with sharing class PJN_CarePlanPathListCtrl {
    /**
     *
     */
    @testVisible private static PJN_AllCarePlanSettingQuery allCarePlanSettingQuery = new PJN_AllCarePlanSettingQuery();

    /**
     *
     */
    @testVisible private static PJN_AllCarePlanFieldSettingQuery allCarePlanFieldSettingQuery = new PJN_AllCarePlanFieldSettingQuery();

    /**
     *
     * @param   Id        patientId
     * @returns  List<Case>
     */
	@auraEnabled public static List<Case> getCareplans(Id patientId) {
        try {
            Set<String> fieldsToQuery = new Set<String> { 'PJN_Program_DeveloperName__c', 'Subject' };
            Map<String, PJN_All_Care_Plan_Setting__mdt> allCarePlanSettingsByProgramDeveloperName = getAllCarePlanSettingsByProgramDeveloperName();
            Set<String> allCarePlanSettingDeveloperNames = new Set<String>();
            for(PJN_All_Care_Plan_Setting__mdt thisAllCarePlanSetting : allCarePlanSettingsByProgramDeveloperName.values()) {
                allCarePlanSettingDeveloperNames.add(thisAllCarePlanSetting.DeveloperName);
                fieldsToQuery.add(thisAllCarePlanSetting.PJN_Title_Field_API_Name__c);
                fieldsToQuery.add(thisAllCarePlanSetting.PJN_Subtitle_Field_API_Name__c);
            }

            for(List<PJN_All_Care_Plan_Setting_Field__mdt> thisAllCarePlanSettingFields : getAllCarePlanSettingFieldsBySettingDeveloperName(new List<String>(allCarePlanSettingDeveloperNames)).values()) {
                for(PJN_All_Care_Plan_Setting_Field__mdt thisAllCarePlanSettingField : thisAllCarePlanSettingFields) {
                    fieldsToQuery.add(thisAllCarePlanSettingField.PJN_Field_API_Name__c);
                    if(thisAllCarePlanSettingField.PJN_Link_Record_Id_Field_API_Name__c != null) {
                        fieldsToQuery.add(thisAllCarePlanSettingField.PJN_Link_Record_Id_Field_API_Name__c);
                    }
                }
            }

            return Database.query(
                'SELECT ' +
                    String.join(new List<String>(fieldsToQuery), ', ') + ' ' +
                'FROM ' +
                    'Case ' +
                'WHERE ' +
                    'AccountId = :patientId ' +
                'AND ' +
                    'RecordType.DeveloperName = \'Careplan\' ' +
                'ORDER BY ' +
                    'LastModifiedDate DESC'
            );
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }

    /**
     *
     * @returns  Map<String, PJN_All_Care_Plan_Setting__mdt>
     */
    @AuraEnabled public static Map<String, PJN_All_Care_Plan_Setting__mdt> getAllCarePlanSettingsByProgramDeveloperName() {
        try {
            Map<String, PJN_All_Care_Plan_Setting__mdt> allCarePlanSettingsByProgramDeveloperName = new Map<String, PJN_All_Care_Plan_Setting__mdt>();
            for(PJN_All_Care_Plan_Setting__mdt thisAllCarePlanSetting : allCarePlanSettingQuery.queryAll()) {
                allCarePlanSettingsByProgramDeveloperName.put(
                    thisAllCarePlanSetting.PJN_Program__r.DeveloperName,
                    thisAllCarePlanSetting
                );
            }
            return allCarePlanSettingsByProgramDeveloperName;
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }

    /**
     *
     * @param   List<String>        allCarePlanSettingDeveloperNames
     * @returns  Map<String, List<PJN_All_Care_Plan_Setting_Field__mdt>>
     */
    @AuraEnabled public static Map<String, List<PJN_All_Care_Plan_Setting_Field__mdt>> getAllCarePlanSettingFieldsBySettingDeveloperName(List<String> allCarePlanSettingDeveloperNames) {
        try {
            Set<String> allCarePlanSettingDeveloperNamesSet = new Set<String>(allCarePlanSettingDeveloperNames);
            Map<String, List<PJN_All_Care_Plan_Setting_Field__mdt>> allCarePlanSettingFieldsBySettingDeveloperName = new Map<String, List<PJN_All_Care_Plan_Setting_Field__mdt>>();
            for(PJN_All_Care_Plan_Setting_Field__mdt thisAllCarePlanSettingField : allCarePlanFieldSettingQuery.queryBySettingDeveloperNames(allCarePlanSettingDeveloperNamesSet)) {
                List<PJN_All_Care_Plan_Setting_Field__mdt> allCarePlanSettingFields = new List<PJN_All_Care_Plan_Setting_Field__mdt>();
                if(allCarePlanSettingFieldsBySettingDeveloperName.containsKey(thisAllCarePlanSettingField.PJN_All_Care_Plan_Setting__r.DeveloperName)) {
                    allCarePlanSettingFields = allCarePlanSettingFieldsBySettingDeveloperName.get(thisAllCarePlanSettingField.PJN_All_Care_Plan_Setting__r.DeveloperName);
                }
                allCarePlanSettingFields.add(thisAllCarePlanSettingField);
                allCarePlanSettingFieldsBySettingDeveloperName.put(
                    thisAllCarePlanSettingField.PJN_All_Care_Plan_Setting__r.DeveloperName,
                    allCarePlanSettingFields
                );
            }
            return allCarePlanSettingFieldsBySettingDeveloperName;
        } catch(Exception ex) {
            throw PJN_AuraHandledExceptionUtil.handleException(ex);
        }
    }
}