force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/recordTypes/PJN_Request.recordType-meta.xml
<RecordType>
    <fullName>PJN_Request</fullName>
    <active>true</active>
    <businessProcess>PJN_Care Plan Activity</businessProcess>
    <description>Defines activities outside of a patient&apos;s care plan like enrollments, and inbound inquiries</description>
    <label>Request</label>
</RecordType>

force-app/main/default/src/classes/PJN_CaseSetProgramDevNameHdlr.cls
/**
 * @author      Mavens
 * @description Sets Program Developer Name on Requests.
 */
public with sharing class PJN_CaseSetProgramDevNameHdlr implements PJN_TriggerDispatcher.HandlerInterface {
    /**
     * handle before trigger context
     */
    public void handle() {
        Set<Id> parentCaseIds = new Set<Id>();
        for(Case currentCase : (List<Case>) trigger.new) {
            if(newOrUpdatedParentCase(currentCase)) {
                parentCaseIds.add(currentCase.ParentId);
            }
        }

        Map<Id, Case> parentCaseMap = queryParentCases(parentCaseIds);

        for(Case currentCase : (List<Case>) trigger.new) {
            if(newOrUpdatedParentCase(currentCase) && mapHasParentCaseData(parentCaseMap, currentCase.ParentId)) {
                Case parentCase = parentCaseMap.get(currentCase.ParentId);
                if (parentCase.PJN_Program__c != NULL && parentCase.PJN_Program__r.PJN_Program_DeveloperName__c != NULL) {
                    currentCase.PJN_Program_DeveloperName__c = parentCase.PJN_Program__r.PJN_Program_DeveloperName__c;
                } else {
                    currentCase.PJN_Program_DeveloperName__c = parentCase.PJN_Program_DeveloperName__c;
                }
            }
        }
    }

    private Boolean newOrUpdatedParentCase(Case newCase) {
        if (newCase.RecordTypeId == SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PJN_Request').getRecordTypeId()) {
            if (Trigger.isInsert) {
                return String.isNotBlank(newCase.ParentId);
            } else if (Trigger.isUpdate) {
                Case oldCase = (Case) Trigger.oldMap.get(newCase.Id);
                return String.isNotBlank(newCase.ParentId) && newCase.ParentId != oldCase.ParentId;
            }
        }

        return false;
    }

    private Boolean mapHasParentCaseData(Map<Id, Case> parentCaseMap, Id parentId) {
        if (parentCaseMap.containsKey(parentId)) {
            Case parentCase = parentCaseMap.get(parentId);
            return (parentCase.PJN_Program_DeveloperName__c != NULL || (parentCase.PJN_Program__c != NULL && parentCase.PJN_Program__r.PJN_Program_DeveloperName__c != NULL));
        }

        return false;
    }

    private Map<Id, Case> queryParentCases(Set<Id> parentCaseIds) {
        return new Map<Id, Case>([SELECT Id, PJN_Program_DeveloperName__c, PJN_Program__r.PJN_Program_DeveloperName__c FROM Case WHERE Id IN :parentCaseIds]);
    }
}