force-app/main/default/src/objects/CareProgram/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Case/fields/Care_Plan_Template_External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Template_External_ID_MVN__c</fullName>
    <description>The external ID of the care plan template which should be assigned automatically by code.</description>
    <formula>IF( NOT( ISBLANK( Care_Plan_Template_Ext_ID_Override_MVN__c ) ),
    Care_Plan_Template_Ext_ID_Override_MVN__c, /* return the override */
    CASE( RecordType.DeveloperName,

        /* DEDSI logic */
        &quot;CarePlan&quot;,
        CASE( Account.Screening_Results_on_Conversion_MVN__c,
            &quot;Signs of DR&quot;, 
            IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot; &amp;&amp; 
                Account.Specialists_Shared_on_Conversion_MVN__c = &quot;Yes&quot;,
                &quot;CPT-a0956000002t50X&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot; &amp;&amp; 
                    Account.Specialists_Shared_on_Conversion_MVN__c = &quot;No&quot;,
                    &quot;CPT-a0956000002t50N&quot;,
                    IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;No&quot; &amp;&amp; 
                        Account.Specialists_Shared_on_Conversion_MVN__c = &quot;Yes&quot;,
                        &quot;CPT-a0956000002t50S&quot;, 
                        IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;No&quot; &amp;&amp; 
                            Account.Specialists_Shared_on_Conversion_MVN__c = &quot;No&quot;,
                            &quot;CPT-a0956000002WMTv&quot;, 
                            &quot;&quot;
                        )
                    )
                )
            ),
            &quot;No Signs of DR&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot;,
                    &quot;CPT-a09S000000DEWHkIAP&quot;,
                    &quot;CPT-a0956000002nKd9&quot;
                ), 
                    &quot;Not Yet Screened&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot;,
                    &quot;CPT-a09S000000DEWHpIAP&quot;,
                    &quot;CPT-a0956000002nFSg&quot;
                ), 
                    &quot;Unknown&quot;,
                IF( Account.Ed_Materials_Sent_on_Conversion_MVN__c = &quot;Yes&quot;,
                    &quot;CPT-a09S000000DEWHpIAP&quot;,
                    &quot;CPT-a0956000002nFSg&quot;
                ),
            &quot;&quot;
        ),

        /* Libtayo logic */
        &quot;Libtayo_Marketing_Care_Plan_MVN&quot;,

            CASE( TEXT( Qualification_Status_MVN__c ),

                    /* Qualified */
                    &quot;Qualified&quot;,
                    CASE( TEXT( Type ),
                    &quot;Patient&quot;,
                        IF( ISPICKVAL( Origin, &quot;Libtayo Surround&quot; ),
                            &quot;CPT-libtayo-marketing-qualified-surround-patient&quot;,
                            IF( ISPICKVAL( Email_Opt_In_MVN__c, &quot;Yes&quot; ),
                                &quot;CPT-libtayo-marketing-qualified-website-patient&quot;,
                            &quot;CPT-libtayo-marketing-qualified-web-patient-mail&quot;
                               )
                           ),
                    &quot;Caregiver&quot;, &quot;CPT-libtayo-marketing-qualified-caregiver&quot;,
                    &quot;&quot;
                ),

                /* Unqualified */
                &quot;Unqualified&quot;, &quot;CPT-libtayo-marketing-unqualified&quot;,

            /* Default Qualification_Status__c */
            &quot;&quot;
        ),

    /* Default RecordType.DeveloperName */
    &quot;&quot;
    )
)</formula>
    <label>Care Plan Template External ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/Converted_Lead_MVN__c.field-meta.xml
<CustomField>
    <fullName>Converted_Lead_MVN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Original consumer record whose conversion created this case.</description>
    <label>Converted Consumer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CareProgram</referenceTo>
    <relationshipLabel>Care Plans</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <description>Program DeveloperName that this Case/CarePlan is used for</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Case/fields/Record_Type_Key_MVN__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Key_MVN__c</fullName>
    <description>Namespace + RecordType DeveloperName</description>
    <formula>RecordType.NamespacePrefix + RecordType.DeveloperName</formula>
    <label>Record Type Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Effective_Months__c.field-meta.xml
<CustomField>
    <fullName>PJN_Effective_Months__c</fullName>
    <description>Number of months for which written opt-in consent of this type is valid.</description>
    <label>Effective Months (Written)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/DataUsePurpose/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program Consent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/HealthCloudGA__CarePlanTemplate__c.object-meta.xml
<CustomObject>
    <label>Care Plan Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/HealthCloudGA__CarePlanTemplate__c/fields/External_ID_MVN__c.field-meta.xml
<CustomField>
    <fullName>External_ID_MVN__c</fullName>
    <description>External ID of the care plan template. Used in mapping the correct template upon creation of a care plan.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt.object-meta.xml
<CustomObject>
    <description>Maps lead fields to care plan fields based on care plan record type</description>
    <label>Lead Convert Care Plan Field Mapping</label>
    <pluralLabel>Lead Convert Care Plan Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Care_Plan_Field_Name_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Field_Name_MVN__c</fullName>
    <description>Care plan field name to map value to</description>
    <inlineHelpText>Care plan field name to map value to</inlineHelpText>
    <label>Care Plan Field Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Care_Plan_Record_Type_DeveloperName_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Record_Type_DeveloperName_MVN__c</fullName>
    <description>Care plan record type developer name to which this mapping belongs
Used with care plan record type namespace</description>
    <inlineHelpText>Care plan record type developer name to which this mapping belongs</inlineHelpText>
    <label>Care Plan Record Type Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Care_Plan_Record_Type_Namespace_Pref_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Record_Type_Namespace_Pref_MVN__c</fullName>
    <description>Care plan record type namespace prefix to which this mapping belongs
Used with care plan record type developer name</description>
    <inlineHelpText>Care plan record type namespace prefix to which this mapping belongs</inlineHelpText>
    <label>Care Plan Record Type Namespace Prefix</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Is_Active_MVN__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_MVN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Only map the value if the checkbox is checked</description>
    <inlineHelpText>Only map the value if the checkbox is checked</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Lead_Field_Name_MVN__c.field-meta.xml
<CustomField>
    <fullName>Lead_Field_Name_MVN__c</fullName>
    <description>Lead field name to map value from</description>
    <inlineHelpText>Lead field name to map value from</inlineHelpText>
    <label>Lead Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt/fields/Text_Value_MVN__c.field-meta.xml
<CustomField>
    <fullName>Text_Value_MVN__c</fullName>
    <description>Text value to populate to the target care plan field.</description>
    <inlineHelpText>Text value to populate to the target care plan field.</inlineHelpText>
    <label>Text Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt.object-meta.xml
<CustomObject>
    <description>Maps lead record types to the types of care plan record types that should be created on conversion</description>
    <label>Lead Convert Care Plan RT Mapping</label>
    <pluralLabel>Lead Convert Care Plan RT Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/Care_Plan_Record_Type_DeveloperName_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Plan_Record_Type_DeveloperName_MVN__c</fullName>
    <description>Care plan record type developer name to use when converting lead</description>
    <inlineHelpText>Developer name of the case record type</inlineHelpText>
    <label>Care Plan Record Type Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/Care_Program_DeveloperName_MVN__c.field-meta.xml
<CustomField>
    <fullName>Care_Program_DeveloperName_MVN__c</fullName>
    <description>Developer name corresponding to the field CareProgram.PJN_Program_DeveloperName__c.  Used to determine the care program to associate to the care plan being created on conversion.</description>
    <inlineHelpText>Developer name of the care program to associate to the care plan.</inlineHelpText>
    <label>Care Program DeveloperName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt/fields/CarePlan_RecordType_Namespace_Prefix_MVN__c.field-meta.xml
<CustomField>
    <fullName>CarePlan_RecordType_Namespace_Prefix_MVN__c</fullName>
    <description>Namespace of the care plan record type to use when converting lead</description>
    <label>Care Plan Record Type Namespace Prefix</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/PJN_Contact_Information__c.object-meta.xml
<CustomObject>
    <description>Part of the Patient Services Accelerator, the contact information object is used to store address, phone and email information related to an account.</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Account__c.field-meta.xml
<CustomField>
    <fullName>PJN_Account__c</fullName>
    <description>Master-Detail: Relationship to the Account object that links the Contact Information record to an Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>PJN_Contact_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Record_Type_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Contact_Information__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Picklist: Correspondence label or type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>PO Box</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/LeadConversionUtilityMVN.cls
/**
 * @author      Mavens
 * @group       LeadMVN
 * @description Collection of queries and shared methods used by PopulateCarePlanHdlr and CareConsentsHdlrMVN
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class LeadConversionUtilityMVN {


    public static Map<Id, List<PJN_Contact_Information__c>> queryContactInformationMap(Set<Id> accountIds) { //, Map<String, Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt> recordTypeSettingMap) {
        Map<Id, List<PJN_Contact_Information__c>> result = new Map<Id, List<PJN_Contact_Information__c>>();

        for (PJN_Contact_Information__c contactInfo : [SELECT PJN_Account__c, PJN_Record_Type_Name__c FROM PJN_Contact_Information__c WHERE PJN_Account__c IN :accountIds]) {
            if (result.containsKey(contactInfo.PJN_Account__c)) {
                List<PJN_Contact_Information__c> currentList = result.get(contactInfo.PJN_Account__c);
                currentList.add(contactInfo);
                result.put(contactInfo.PJN_Account__c, currentList);
            } else {
                result.put(contactInfo.PJN_Account__c, new List<PJN_Contact_Information__c>{contactInfo});
            }
        }

        return result;
    }

    public static List<Case> queryCarePlans(List<Id> carePlanIds) {
        return [SELECT AccountId, Care_Plan_Template_External_ID_MVN__c, Converted_Lead_MVN__c, PJN_Program__c, Record_Type_Key_MVN__c FROM Case WHERE Id IN :carePlanIds];
    }

    public static Map<String, CareProgram> queryCareProgramMap(List<Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt> recordTypeSettings) {
        Set<String> programDevNames = new Set<String>();
        for (Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt recordTypeSetting : recordTypeSettings) {
            programDevNames.add(recordTypeSetting.Care_Program_DeveloperName_MVN__c);
        }
        System.debug('#### programDevNames: ' + programDevNames);

        Map<String, CareProgram> result = new Map<String, CareProgram>();
        for (CareProgram program : [SELECT PJN_Program_DeveloperName__c FROM CareProgram WHERE PJN_Program_DeveloperName__c IN :programDevNames]) {
            result.put(program.PJN_Program_DeveloperName__c, program);
        }

        System.debug('#### programMap: ' + result);
        return result;
    }

    public static Map<Id, Lead> queryLeadMap(String soqlString, Set<String> leadIds) {
        Map<Id, Lead> result = new Map<Id, Lead>();

        System.debug('#### querying leads');
        for (Lead consumer : Database.query(soqlString)) {
            System.debug('#### lead found: ' + consumer);
            result.put(consumer.Id, consumer);
        }

        return result;
    }

    public static Map<String, Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt> queryRecordTypeSettingMap() {
        Map<String, Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt> result = new Map<String, Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt>();
        for (Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt rtMapping : [SELECT Care_Program_DeveloperName_MVN__c, Care_Plan_Record_Type_DeveloperName_MVN__c, CarePlan_RecordType_Namespace_Prefix_MVN__c FROM Lead_Convert_Care_Plan_RT_Mapping_MVN__mdt]) {
            result.put((rtMapping.CarePlan_RecordType_Namespace_Prefix_MVN__c == NULL ? '' : rtMapping.CarePlan_RecordType_Namespace_Prefix_MVN__c) + rtMapping.Care_Plan_Record_Type_DeveloperName_MVN__c, rtMapping);
        }
        return result;
    }

    public static List<Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt> queryFieldMappingSettings() {
        return [SELECT Care_Plan_Field_Name_MVN__c, Care_Plan_Record_Type_DeveloperName_MVN__c, Care_Plan_Record_Type_Namespace_Pref_MVN__c, Is_Active_MVN__c, Lead_Field_Name_MVN__c, Text_Value_MVN__c FROM Lead_Convert_Care_Plan_Field_Mapping_MVN__mdt WHERE Is_Active_MVN__c = TRUE];
    }

    public static Map<Id, DataUsePurpose> queryDataUsePurposeMap(Set<Id> dataUsePurposeIds) {
        return new Map<Id, DataUsePurpose>([SELECT PJN_Effective_Months__c FROM DataUsePurpose WHERE Id IN :dataUsePurposeIds]);
    }

    public static Map<Id, DataUsePurpose> queryDataUsePurposeMapByPurpose(Set<Id> purposes) {
        Map<Id, DataUsePurpose> result = new Map<Id, DataUsePurpose>();
        for (DataUsePurpose purpose : [SELECT PJN_Effective_Months__c, PurposeId FROM DataUsePurpose WHERE PJN_Type__c = 'Program Consent' AND PurposeId IN :purposes]) {
            result.put(purpose.PurposeId, purpose);
        }
        return result;
    }

    public static Map<String, HealthCloudGA__CarePlanTemplate__c> queryTemplateMap(Set<String> templateIds) {
        Map<String, HealthCloudGA__CarePlanTemplate__c> templateMap = new Map<String, HealthCloudGA__CarePlanTemplate__c>();
        for (HealthCloudGA__CarePlanTemplate__c template : [SELECT Address_Channel_Consent_Status_MVN__c, Email_Channel_Consent_Status_MVN__c, External_ID_MVN__c, HIPAA_Consent_Data_Use_Purpose_MVN__c, Marketing_Consent_Data_Use_Purpose_MVN__c, Phone_Channel_Consent_Status_MVN__c, Program_Consent_Data_Use_Purpose_MVN__c FROM HealthCloudGA__CarePlanTemplate__c WHERE External_ID_MVN__c IN :templateIds]) {
            templateMap.put(template.External_ID_MVN__c, template);
        }
        return templateMap;
    }
}