force-app/main/default/src/objects/Agreement_Update_MVN__e/Agreement_Update_MVN__e.object-meta.xml
<CustomObject>
    <label>Agreement Update</label>
    <pluralLabel>Agreement Updates</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/Agreement_Update_MVN__e/fields/Agreement_MVN__c.field-meta.xml
<CustomField>
    <fullName>Agreement_MVN__c</fullName>
    <label>Agreement</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/Agreement_Update_MVN__e/fields/Status_MVN__c.field-meta.xml
<CustomField>
    <fullName>Status_MVN__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/src/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__Status__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__Status__c</fullName>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pre-Send</fullName>
            </value>
            <value>
                <fullName>Send in Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled / Declined</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Signature</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Out for Approval</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Out for Form-Filling</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Form-Filling</fullName>
            </value>
            <value>
                <fullName>Form-Filled</fullName>
            </value>
            <value>
                <fullName>Out for Acceptance</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Waiting for Counter-Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Waiting for my Delegation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/AdobeSignAgreementUpdateHdlrMVN.cls
/**
 * @author      Mavens
 * @group       AdobeSign
 * @description On insertion of an Agreement_Update_MVN__e, it will update the corresponding Adobe Sign Agreement as a workaround for Site Guest privilege restrictions.
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class AdobeSignAgreementUpdateHdlrMVN implements PJN_TriggerDispatcher.HandlerInterface {
    public void handle() {
        List<echosign_dev1__SIGN_Agreement__c> agreements = new List<echosign_dev1__SIGN_Agreement__c>();

        for (Agreement_Update_MVN__e agreementUpdate : (List<Agreement_Update_MVN__e>) trigger.new) {
            if (agreementUpdate.Status_MVN__c != NULL) {
                agreements.add(new echosign_dev1__SIGN_Agreement__c(
                    Id = agreementUpdate.Agreement_MVN__c,
                    echosign_dev1__Status__c = agreementUpdate.Status_MVN__c
                ));
            }
        }

        System.debug('#### updating agreements: ' + agreements);
        update agreements;
    }
}