force-app/main/default/src/objects/PJN_Program_Case__mdt/PJN_Program_Case__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Case activities that are specific to a Program Problem, and are created automatically on a Care Plan when the patient enters that Program Problem/Stage.
Metadata Relationship(s): Program Problem; Program Case Dependency
Created by Mavens: Yes</description>
    <label>Program Case</label>
    <pluralLabel>Program Cases</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Case_Dependency__mdt/PJN_Program_Case_Dependency__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Defines the relationship/dependency between different Cases within a single Program Problem/Stage.
Metadata Relationship(s): Program Case
Created by Mavens: Yes</description>
    <label>Program Case Dependency</label>
    <pluralLabel>Program Case Dependencies</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Case_Dependency__mdt/fields/PJN_Dependent__c.field-meta.xml
<CustomField>
    <fullName>PJN_Dependent__c</fullName>
    <label>Dependent</label>
    <referenceTo>PJN_Program_Case__mdt</referenceTo>
    <relationshipLabel>Program Case Dependencies (Dependent)</relationshipLabel>
    <relationshipName>PJN_Dependent</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Case_Dependency__mdt/fields/PJN_Dependent_On__c.field-meta.xml
<CustomField>
    <fullName>PJN_Dependent_On__c</fullName>
    <label>Dependent On</label>
    <referenceTo>PJN_Program_Case__mdt</referenceTo>
    <relationshipLabel>Program Case Dependencies (Dependent On)</relationshipLabel>
    <relationshipName>PJN_Dependent_On</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/classes/PJN_ProgramCaseDependencyQuery.cls
/**
 * @author      Mavens
 * @group       Program
 * @description Program Case Queries
 */
public with sharing class PJN_ProgramCaseDependencyQuery {
    /**
     * fields to query
     */
    public Set<String> fields = new Set<String>{
        'Id',
        'Label',
        'DeveloperName',
        'PJN_Dependent_On__c',
        'PJN_Dependent_On__r.DeveloperName',
        'PJN_Dependent_On__r.MasterLabel',
        'PJN_Dependent__c',
        'PJN_Dependent__r.DeveloperName',
        'PJN_Dependent__r.MasterLabel'
    };

    /* CACHE dependentsByProgramCaseDevName */
    static Map<String, List<PJN_Program_Case_Dependency__mdt>> dependentsByProgramCaseDevName;
    /**
     * query Program Case Dependencies by Program Case Developer Name
     * @param   String      programCaseDeveloperName
     * @returns  List<PJN_Program_Case__mdt>
     */
    public List<PJN_Program_Case_Dependency__mdt> queryDependentsByProgramCaseDeveloperName(String programCaseDeveloperName) {
        if (dependentsByProgramCaseDevName == null) {
            dependentsByProgramCaseDevName = new Map<String, List<PJN_Program_Case_Dependency__mdt>>();
        }

        if (!dependentsByProgramCaseDevName.containsKey(programCaseDeveloperName)) {
            dependentsByProgramCaseDevName.put(programCaseDeveloperName,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(this.fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Case_Dependency__mdt ' +
                    'WHERE ' +
                        'PJN_Dependent_On__r.DeveloperName = :programCaseDeveloperName '
                )
            );
        }

        return dependentsByProgramCaseDevName.containsKey(programCaseDeveloperName) ?
            dependentsByProgramCaseDevName.get(programCaseDeveloperName) :
            new List<PJN_Program_Case_Dependency__mdt>();
    }

    /* CACHE dependentsByProgramCaseDevName */
    static Map<String, List<PJN_Program_Case_Dependency__mdt>> dependentOnsByProgramCaseDevName;
    /**
     * query Program Case Dependencies by Program Case Developer Name
     * @param   String      programCaseDeveloperName
     * @returns  List<PJN_Program_Case__mdt>
     */
    public List<PJN_Program_Case_Dependency__mdt> queryDependentOnsByProgramCaseDeveloperName(String programCaseDeveloperName) {
        if (dependentOnsByProgramCaseDevName == null) {
            dependentOnsByProgramCaseDevName = new  Map<String, List<PJN_Program_Case_Dependency__mdt>>();
        }

        if (!dependentOnsByProgramCaseDevName.containsKey(programCaseDeveloperName)) {
            dependentOnsByProgramCaseDevName.put(programCaseDeveloperName,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(this.fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Case_Dependency__mdt ' +
                    'WHERE ' +
                        'PJN_Dependent__r.DeveloperName = :programCaseDeveloperName '
                )
            );
        }

        return dependentOnsByProgramCaseDevName.get(programCaseDeveloperName);
    }

    /**
     * query for dependencies belongnig to the program cases and group them together
     * @param programCases
     * @returns `Map<Id, List<PJN_Program_Case_Dependency__mdt>>`
     */
    public Map<Id, List<PJN_Program_Case_Dependency__mdt>> queryDependenciesByProgramCase(List<PJN_Program_Case__mdt> programCases) {

        String query = 'SELECT ' + String.join(new List<String>(this.fields), ', ') + ' ' +
        'FROM PJN_Program_Case_Dependency__mdt ' +
        'WHERE PJN_Dependent_On__c IN :programCases';

        List<PJN_Program_Case_Dependency__mdt> dependencies = Database.query(query);

        Map<Id, List<PJN_Program_Case_Dependency__mdt>> dependenciesByProgramCase = new Map<Id, List<PJN_Program_Case_Dependency__mdt>>();
        for (PJN_Program_Case_Dependency__mdt dependency : dependencies) {
            if (!dependenciesByProgramCase.containsKey(dependency.PJN_Dependent_On__c)) {
                dependenciesByProgramCase.put(
                    dependency.PJN_Dependent_On__c,
                    new List<PJN_Program_Case_Dependency__mdt>()
                );
            }
            dependenciesByProgramCase.get(dependency.PJN_Dependent_On__c).add(dependency);
        }

        return dependenciesByProgramCase;
    }
}