force-app/main/default/src/objects/PJN_Program_Case__mdt/PJN_Program_Case__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Case activities that are specific to a Program Problem, and are created automatically on a Care Plan when the patient enters that Program Problem/Stage.
Metadata Relationship(s): Program Problem; Program Case Dependency
Created by Mavens: Yes</description>
    <label>Program Case</label>
    <pluralLabel>Program Cases</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Program_Case__mdt/fields/PJN_Order__c.field-meta.xml
<CustomField>
    <fullName>PJN_Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Case__mdt/fields/PJN_Program_Problem__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_Problem__c</fullName>
    <label>Program Problem</label>
    <referenceTo>PJN_Program_Problem__mdt</referenceTo>
    <relationshipLabel>Program Cases</relationshipLabel>
    <relationshipName>PJN_Program_Cases</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/src/objects/PJN_Program_Problem__mdt/PJN_Program_Problem__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Program Builder
Purpose: Define the attributes of the problems/stages that comprise a Program. Program Problems are distinct stages in the patient’s journey that are (typically) completed before moving on to the next stage.
Metadata Relationship(s): Program; Program Case
Created by Mavens: Yes</description>
    <label>Program Problem</label>
    <pluralLabel>Program Problems</pluralLabel>
</CustomObject>

force-app/main/default/src/classes/PJN_ProgramCaseQuery.cls
/**
 * @author      Mavens
 * @group       Program
 * @description Program Case Queries
 */
public with sharing class PJN_ProgramCaseQuery {
    /**
     * fields to query
     */
    public Set<String> fields = new Set<String>{
        'Id',
        'Label',
        'MasterLabel',
        'DeveloperName',
        'PJN_Order__c',
        'PJN_Program_Problem__c'
    };



    /* CACHE programCasesByDeveloperName */
    static Map<String, PJN_Program_Case__mdt> programCasesByDeveloperName;
    /**
     * query Program Case by Developer Name
     * @param   String      programCaseDeveloperName
     * @returns  PJN_Program_Case__mdt
     */
    public PJN_Program_Case__mdt queryByDeveloperName(String programCaseDeveloperName) {
        if (programCasesByDeveloperName == null) {
            programCasesByDeveloperName = new Map<String, PJN_Program_Case__mdt>();
        }

        if (!programCasesByDeveloperName.containsKey(programCaseDeveloperName)) {
            programCasesByDeveloperName.put( programCaseDeveloperName,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(this.fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Case__mdt ' +
                    'WHERE ' +
                        'DeveloperName = :programCaseDeveloperName'
                )
            );
        }

        return programCasesByDeveloperName.get(programCaseDeveloperName);
    }

    /* CACHE programCasesByProblemDevName */
    static Map<String, List<PJN_Program_Case__mdt>> programCasesByProblemDevName;
    /**
     * query Program Cases by Program Problem Developer Name
     * @param   String      programProblemDeveloperName
     * @returns  List<PJN_Program_Case__mdt>
     */
    public List<PJN_Program_Case__mdt> queryByProgramProblemDeveloperName(String programProblemDeveloperName) {
        if (programCasesByProblemDevName == null) {
            programCasesByProblemDevName = new Map<String, List<PJN_Program_Case__mdt>>();
        }

        if (!programCasesByProblemDevName.containsKey(programProblemDeveloperName)) {
            programCasesByProblemDevName.put(programProblemDeveloperName,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(this.fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Case__mdt ' +
                    'WHERE ' +
                        'PJN_Program_Problem__r.DeveloperName = :programProblemDeveloperName ' +
                    'ORDER BY ' +
                        'PJN_Order__c ASC NULLS LAST'
                )
            );
        }

        return programCasesByProblemDevName.get(programProblemDeveloperName);
    }

    static Map<Set<String>,List<PJN_Program_Case__mdt>> programCasesByDeveloperNames;
    /**
     * query Program Cases by Program Problem Developer Name
     * @param   String      programProblemDeveloperName
     * @returns  List<PJN_Program_Case__mdt>
     */
    public List<PJN_Program_Case__mdt> queryByProgramCaseDeveloperNames(Set<String> programCaseDeveloperNames) {
        if (programCasesByDeveloperNames == null) {
            programCasesByDeveloperNames = new Map<Set<String>,List<PJN_Program_Case__mdt>>();
        }

        if (!programCasesByDeveloperNames.containsKey(programCaseDeveloperNames)) {
            programCasesByDeveloperNames.put(programCaseDeveloperNames,
                Database.query(
                    'SELECT ' +
                        String.join(new List<String>(this.fields), ', ') + ' ' +
                    'FROM ' +
                        'PJN_Program_Case__mdt ' +
                    'WHERE ' +
                        'DeveloperName IN :programCaseDeveloperNames ' +
                    'ORDER BY ' +
                        'PJN_Order__c ASC NULLS LAST'
                )
            );
        }
        return programCasesByDeveloperNames.get(programCaseDeveloperNames);
    }

    public List<PJN_Program_Case__mdt> queryProgramCasesByProblemIds(Set<Id> problemIds) {
        PJN_ProgramCaseDependencyQuery caseDependencyQuery = new PJN_ProgramCaseDependencyQuery();
        return Database.query(
            'SELECT ' + String.join(new List<String>(this.fields), ', ') + ' ' +
            'FROM PJN_Program_Case__mdt ' +
            'WHERE PJN_Program_Problem__c IN :problemIds ' +
            'ORDER BY PJN_Order__c'
        );
    }
}