force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Data_Change_Request__c/fields/PJN_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Type__c</fullName>
    <description>Part of the Patient Service accelerator: data change request type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/src/classes/PJN_SetDCRTypeHdlr.cls
/**
 * Data Change Request Trigger handler to replace dcr type when it's needed
 * @author  Mavens
 * @group   DCR
 */
public with sharing class PJN_SetDCRTypeHdlr implements PJN_TriggerDispatcher.HandlerInterface {
    /**
     * handler
     */
    public void handle() {
        Boolean isAllowed = Trigger.IsBefore && Trigger.isUpdate;

        if (!isAllowed) {
            return;
        }

        List<SObject> recordsToUpdate = new List<SObject>();

        for(PJN_Data_Change_Request__c dcr : (List<PJN_Data_Change_Request__c>) Trigger.new) {
            PJN_Data_Change_Request__c oldDCR = (PJN_Data_Change_Request__c) Trigger.oldMap.get(dcr.Id);

            Boolean isDCRTypeChanged = String.IsNotBlank(oldDCR.PJN_Type__c) && oldDCR.PJN_Type__c != dcr.PJN_Type__c;

            if(!isDCRTypeChanged) {
                continue;
            }

            dcr.PJN_Type__c = oldDCR.PJN_Type__c;
        }
    }
}