force-app/main/default/src/objects/PJN_Data_Change_Request__c/PJN_Data_Change_Request__c.object-meta.xml
<CustomObject>
    <description>Data change request header</description>
    <label>Data Change Request</label>
    <nameField>
        <displayFormat>DCR - {000000000}</displayFormat>
        <label>Data Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/PJN_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Account Search
Purpose: Definition of handler class used for the Account Search and the number max of results to be displayed. Global setting for all Programs; change only the max results field.
Metadata Relationship(s): --
Created by Mavens: Yes</description>
    <label>Global Setting</label>
    <pluralLabel>Global Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Global_Setting__mdt/fields/PJN_Veeva_Network__c.field-meta.xml
<CustomField>
    <fullName>PJN_Veeva_Network__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows Veeva Network connection (Send/Retrieve DCRs, Sync, Search...)</description>
    <inlineHelpText>Allows Veeva Network connection</inlineHelpText>
    <label>Veeva Network</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/src/objects/PJN_Veeva_Network__e/PJN_Veeva_Network__e.object-meta.xml
<CustomObject>
    <label>Veeva Network</label>
    <pluralLabel>Veeva Network</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Veeva_Network__e/fields/PJN_DCR_Id__c.field-meta.xml
<CustomField>
    <fullName>PJN_DCR_Id__c</fullName>
    <description>Data Change Request Id</description>
    <label>DCR Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_NetworkEventHelper.cls
/**
 * Helper to create and publish events for Network
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_NetworkEventHelper {

    /**
     * Max Publish tries
     */
    private static final Integer PUBLISH_MAX_LIMIT = 10;

    /**
     * Publish DCR Count tries
     */
    private static Integer publishDCRCount = 0;

    /**
     * Publish CCS events with DCR Ids to be sent into CCS
     * @param dcrs  List of Data change requests
     * @returns `Map<Id, String>`
     */
    public static Map<Id, String> publishDCRs(List<PJN_Data_Change_Request__c> dcrs) {
        PJN_Global_Setting__mdt pjnSetting = PJN_Utilities.globalSetting;
        Boolean isNetworkAllowed = pjnSetting != null ? pjnSetting.PJN_Veeva_Network__c : false;

        if (!isNetworkAllowed) {
            return null;
        }

        Map<Id, String> errorMessageByDCRId = new Map<Id, String>();
        List<PJN_Data_Change_Request__c> republishDCRs = new List<PJN_Data_Change_Request__c>();

        List<PJN_Veeva_Network__e> networkEvents = new List<PJN_Veeva_Network__e>();

        for(PJN_Data_Change_Request__c parentDCR : dcrs) {
            networkEvents.add(
                new PJN_Veeva_Network__e(
                    PJN_DCR_Id__c = parentDCR.Id
                )
            );
        }

        publishDCRCount++;
        List<Database.SaveResult> networkEventResults = EventBus.publish(networkEvents);

        for (Integer networkEventResultIndex = 0; networkEventResultIndex < networkEventResults.size(); networkEventResultIndex++) {
            Database.SaveResult networkEventResult = networkEventResults[networkEventResultIndex];
            PJN_Veeva_Network__e networkEvent = networkEvents[networkEventResultIndex];

            if (!networkEventResult.isSuccess() && publishDCRCount <= PUBLISH_MAX_LIMIT) {
                republishDCRs.add(new PJN_Data_Change_Request__c(Id = networkEvent.PJN_DCR_Id__c));
            } else if (!networkEventResult.isSuccess()) {
                for (Database.Error error : networkEventResult.getErrors()) {
                    errorMessageByDCRId.put(networkEvent.PJN_DCR_Id__c, error.getMessage());
                    System.debug(LoggingLevel.ERROR, PJN_NetworkConstants.NETWORK_DEBUG + '::Error: ' + error.getMessage());
                }
            }
        }

        if (publishDCRCount <= PUBLISH_MAX_LIMIT && !republishDCRs.isEmpty()) {
            errorMessageByDCRId.putAll(publishDCRs(republishDCRs));
        }

        publishDCRCount = 0;

        return errorMessageByDCRId;
    }
}