force-app/main/default/src/objects/PJN_Object_Field_Contact_Info_Mapping__mdt/PJN_Object_Field_Contact_Info_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Object Field Contact Info Mapping</label>
    <pluralLabel>Object Field Contact Info Mappings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Object_Field_Contact_Info_Mapping__mdt/fields/PJN_Contact_Info_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Field_Name__c</fullName>
    <description>Field API Name from Contact Information</description>
    <label>Contact Info Field Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Object_Field_Contact_Info_Mapping__mdt/fields/PJN_Contact_Info_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Record_Type__c</fullName>
    <description>Contact Information Record Type Developer Name.</description>
    <label>Contact Info Record Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Object_Field_Contact_Info_Mapping__mdt/fields/PJN_Contact_Info_Type__c.field-meta.xml
<CustomField>
    <fullName>PJN_Contact_Info_Type__c</fullName>
    <description>Contact Information Field Type.</description>
    <label>Contact Info Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Object_Field_Contact_Info_Mapping__mdt/fields/PJN_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Field_Name__c</fullName>
    <description>Field API name from Object Name field.</description>
    <label>Field Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/objects/PJN_Object_Field_Contact_Info_Mapping__mdt/fields/PJN_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>PJN_Object_Name__c</fullName>
    <description>Object API name used to map from/to Contact Information.</description>
    <label>Object Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_ObjectFieldContactInfoMappingsQuery.cls
/**
 * Query PJN_Object_Field_Contact_Info_Mapping__mdt custom metadatas
 * @author  Mavens
 * @group   Network
 */
public with sharing class PJN_ObjectFieldContactInfoMappingsQuery {
    /**
     * Query all Object Field Contact Info mappings
     * @returns `List<PJN_Object_Field_Contact_Info_Mapping__mdt>`
     */
    public List<PJN_Object_Field_Contact_Info_Mapping__mdt> queryAll() {
        return [
            SELECT
                Id,
                DeveloperName,
                MasterLabel,
                PJN_Contact_Info_Field_Name__c,
                PJN_Contact_Info_Record_Type__c,
                PJN_Contact_Info_Type__c,
                PJN_Field_Name__c,
                PJN_Object_Name__c
            FROM
                PJN_Object_Field_Contact_Info_Mapping__mdt
        ];
    }
}