force-app/main/default/src/objects/PJN_Enrollment_Wizard_Setting__mdt/PJN_Enrollment_Wizard_Setting__mdt.object-meta.xml
<CustomObject>
    <description>App: Patient Journey Navigator
Impacted Functionality: Enrollment Wizard
Purpose: Define enrollment wizard settings by program developer name. This is the first step in setting up the Enrollment Wizard.
Metadata Relationship(s): Enrollment Wizard Step
Created by Mavens: Yes</description>
    <label>Enrollment Wizard Setting</label>
    <pluralLabel>Enrollment Wizard Settings</pluralLabel>
</CustomObject>

force-app/main/default/src/objects/PJN_Enrollment_Wizard_Setting__mdt/fields/PJN_Program_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>PJN_Program_DeveloperName__c</fullName>
    <label>Program DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/src/classes/PJN_EnrollmentWizardSettingQuery.cls
/**
 * @author Mavens
 * @date Mar 2019
 * @description Class to query custom metadata types for PJN_Enrollment_Wizard_Setting__mdt
 * @group EnrollmentWizard
 */
public with sharing class PJN_EnrollmentWizardSettingQuery {

    /**
     * Query enrollment wizard settings and return a map of settings by program
     * @returns   Map<String, PJN_Enrollment_Wizard_Setting__mdt>
     */
    public Map<String, PJN_Enrollment_Wizard_Setting__mdt> getAllSettingsByProgram() {
        Map<String, PJN_Enrollment_Wizard_Setting__mdt> allSettingsByProgram = new Map<String, PJN_Enrollment_Wizard_Setting__mdt>();
        for (PJN_Enrollment_Wizard_Setting__mdt setting : getAllSettings()) {
            allSettingsByProgram.put(setting.PJN_Program_DeveloperName__c, setting);
        }
        return allSettingsByProgram;
    }

    /**
     * Query all enrollment wizard settings
     * @returns   List<PJN_Enrollment_Wizard_Setting__mdt>
     */
    private List<PJN_Enrollment_Wizard_Setting__mdt> getAllSettings() {
        return [
            SELECT
                Id,
                PJN_Program_DeveloperName__c
            FROM
                PJN_Enrollment_Wizard_Setting__mdt
        ];
    }

}